### PR TITLE
Revert heading, pitch, roll changes

### LINKED ISSUE #5868: Sandcastle examples have deprecation warnings
After #5848 was merged, there are now a bunch of deprecation warnings in Sandcastle examples.  We should probably fix them before today's release. (It's probably easiest to go through each example and fix them as you go.

CC @ggetz

### PR DESCRIPTION
**Pull request by bagnell**
Reverts #5848 to fix #5868.

I'll add the changes to another branch when this is merged.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@bagnell, thanks for the pull request! Maintainers, we have a signed CLA from @bagnell, so you can review this at any time.



__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by hpinkos** [comment]
Looks good @bagnell, thanks!

**Comment by hpinkos** [comment]
@kaktus40 sorry, but we decided to revert the heading/pitch/roll counter clockwise changes you made.  It was hard to justify making such a big breaking change that would effect the vast majority of our user base.  See the discussion in #5868.

We may decide to make this change eventually, but we need to discuss it more so we understand the benefit of using CCW compared to the cost of forcing everyone to switch.  We'll continue discussion in #5666

**Comment by kaktus40** [comment]
It's OK for me, I just hope that the community make a choice after thinking about it.

**Pull request merged**
