### PR TITLE
Fix OIT on machines where it was broken.

### PR DESCRIPTION
**Pull request by mramato**
As pointed out by one of the Chromium developers, we were using an undefined variable in `czm_alphaWeight` due to a double declaration of the `z` variable resulting in scoping issues.  This change then lead to another issue where textures were too dark, which was fixed by flipping `q.w`

We also discovered that #2327 is related to `czm_alphaWeight` and may be an issue with the weighting function. @bagnell is going to look into it separately.

This makes OIT work everywhere and disabling it should no longer be necessary.

### CODE REVIEW

**Comment by mramato** [comment]
Here's the Chrome issue: https://code.google.com/p/chromium/issues/detail?id=414280

Fixes #2129

**Comment by pjcozzi** [comment]
I will test this on Mac / Intel tomorrow.

**Comment by chris-cooper** [comment]
Nice!  This fixes the issue in Ubuntu 14.04 on a Dell XPS 14 for me.  The "Geometry and Appearances" Sandcastle example shows pixel flickering in master but not in the fix-oit branch.

**Comment by gberaudo** [comment]
It also fixes the issue on my machine. Thank you guys.

**Comment by pjcozzi** [comment]
Code looks good.  Works on my my MacBook Pro forced to Intel.

@bagnell can you please verify this in scenes with high depth complexity like we did before http://cesiumjs.org/2014/03/14/Weighted-Blended-Order-Independent-Transparency/

@bagnell can you also followup in the [Chrome issue](https://code.google.com/p/chromium/issues/detail?id=414280) to confirm that this is not a GLSL compiler issue that they need to test for (assuming that is the case)?

When we merge this, please post this to the forum and also followup on the few threads where this was discussed.

CC @kenrussell

**Comment by mramato** [comment]
I also tested this on OS X with an Radeon HD6630M and Linux Mint with an Intel HD 4000.  Both showed the problem before and both are now fixed.

**Comment by kenrussell** [comment]
Please do take a little time and see if you can reduce this into a small test case. It looks like there may be bugs in many GLSL compilers related to shadowing of variables, and it's critically important that we expose these issues so browsers can provide uniform behavior, and so that the underlying bugs may eventually be fixed. Thanks.

**Comment by bagnell** [comment]
The weighting function still needs to be investigated, but this fixes the issue and still matches master so I'm merging.

**Comment by pjcozzi** [comment]
@kenrussell we'll see if we can put together a trimmed down test to see if this was 100% our issue or a potential GLSL shadowing issue.

**Pull request merged**
