### PR TITLE
Flyto options

### PR DESCRIPTION
**Pull request by kiselev-dv**
Forum discussion http://cesiumjs.org/forum.html#!topic/cesium-dev/naHiF2_0F5M/discussion

I've added 2 new mechanics to camera flyto.

First one is pitchAdjusAltitude

When you fly for a big distance and with high altitude and start pitch and end pitch are quite close to zero, Earth goes out of sight.
That happens because pitch interpolated linear between start and end points, and with high altitude camera looks straight and Earth goes out of viewport.

What I want, is to point camera down during the high altitude flights.
So camera pitch interpolates following way:

(startPitch) ----- ( straight down ) ----- (endPitch)

Pitch interpolated accordingly to camera altitude distance between start/end altitude and middle point.

But for small altitude I wan to leave default behavior. I've implemented flyTo options parameter pitchAdjusAltitude. If camera goes higher than this altitude, camera pitch interpolated as mentioned above.

If this option is omitted, or camera goes lower, pitch interpolated as it was.

Second item is flyOverLon and flyOverLonWeight options.

Lets say you want to fly camera from Los Angeles to Tokyo. There are two ways on globe to do that:

a) over Pacific ocean (shortest path which is used now)
b) over Atlantic and Europe - which some times may be preferable, because it's populated and the rest of your data might be located there.

So to be able to specify which way you want camera to fly, you can add flyOverLon. For example above you can set it to 0 (Greenwich meridian).

flyOverLonWeight sets treshold for this option, camera will fly over flyOverLon only if this way is shorten than default way * flyOverLonWeight. In a nut shell we'll fly over flyOverLon until it's not too far away.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Cool, thanks for this, @kiselev-dv!

@bagnell can you please review this once you wrap up #5021?

@kiselev-dv a few quick comments:
* Can you please remove the example app, and instead update the [Camera Sandcastle example](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/gallery/Camera.html)?  Sandcastle is where we keep all the code examples.
* Update [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) with a concise description of the new features.
* Avoid using abbreviations when naming public identifiers, e.g., `flyOverLon` would be something like `flyOverLongitude`.  Also use "height", e.g., `pitchAdjustAltitude` would be `pitchAdjustHeight`.  See the [Coding Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/CodingGuide/README.md) for more info.
* Add [unit tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide#testing-guide).

For more general info on contributing, see the [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

**Comment by kiselev-dv** [comment]
@pjcozzi what would be better to use for `flyOverLongitude` radians or degrees? 

Now I'm using radians because angular properties in Cesium is used to be in radians, but I always forget that it's in radians, so I'm afraid others will be confused as well.

So what will be more Cesiumish? 

* use `flyOverLongitudeRadians` parameter name
* set `flyOverLongitude` in degrees and convert to radians
* set `flyOverLongitude` in radians (leave it as it is)

**Comment by pjcozzi** [comment]
Use the last option:

> set flyOverLongitude in radians (leave it as it is)

Everything in Cesium is radians; see the [Units Section of the Coding Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#units).

**Comment by kiselev-dv** [comment]
* [x] Fix options naming
* [x] Update CHANGES.md
* [x] Unit tests
* [x] Sandcastle demo

**Comment by pjcozzi** [comment]
Great, thanks so much @kiselev-dv!  @bagnell please review when you're available.

**Comment by bagnell** [comment]
@kiselev-dv I made some minor code style tweaks in 29f351b. This looks great! Thanks!

**Comment by bagnell** [comment]
Also, can you add yourself to CONTRIBUTORS.md if you aren't already listed.

**Comment by kiselev-dv** [comment]
https://github.com/AnalyticalGraphicsInc/cesium/pull/5102

Sorry for separate PR just for Contributors.

**Pull request merged**
