### PR TITLE
Fix ScreenSpaceCameraController docs

### PR DESCRIPTION
**Pull request by nmschulte-aviture**
```javascript
10000.0 !== 15000.0
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @nmschulte-aviture! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Aviture/cesium/blob/min-collision-terrain-height-doc/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/min-collision-terrain-height-doc/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks for the fix @nmschulte-aviture ! The missing contributors entry is OK because @nmschulte-aviture is already listed as his other account @nmschulte.

**Comment by nmschulte** [comment]
@OmarShehata I just submitted an individual CLA for @nmschulte.
Should I submit a request to change `CONTRIBUTORS.md`; update `Aviture`/`Nathan Schulte` as `nmschulte-aviture` (@nmschulte-aviture), and add individual `Nathan Schulte` as `nmschulte` (@nmschulte)?

**Comment by OmarShehata** [comment]
If you've contributed both as an individual and under Aviture, then yes you should put your name as an individual as well under contributors. 

Thanks again for all these recent fixes @nmschulte !

**Pull request merged**
