### PR TITLE
Move WebGLConstants from Renderer to Core

### PR DESCRIPTION
**Pull request by lasalvavida**
Justification:

Currently we use` WebGLConstants` in Core (`ComponentDataType`, `IndexDataType`, `PixelFormat`, `PrimitiveType`, ...), but `WebGLConstants` lives in Renderer. Moving `WebGLConstants` to Core makes Core completely self contained with no dependencies on the rest of Cesium.

This PR also makes `WebGLConstants` public and updates the reference doc for it. We use `WebGLConstants` as part of the Cesium API in `gltf-pipeline`, so this seemed appropriate.

There were also a few members missing `@memberof` declarations in other modules which were being added to `global` in the doc, so this corrects those as well.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@lasalvavida this is perfect, just one request: for maintenance and conciseness, it is perfectly OK to not document each individual enum vale in this case; instead, the reference doc for `WebGLConstants` can say that these match the WebGL spec constants and provide a link to the WebGL 1 and WebGL 2 specs.

**Comment by lasalvavida** [comment]
> @lasalvavida this is perfect, just one request: for maintenance and conciseness, it is perfectly OK to not document each individual enum vale in this case; instead, the reference doc for WebGLConstants can say that these match the WebGL spec constants and provide a link to the WebGL 1 and WebGL 2 specs.

Okay. I need to see if I can make jsdoc hide the description column here for this. I added the comment because having a completely empty column looked a bit odd.

**Comment by lasalvavida** [comment]
This is updated removing the per entry comments and I've added links to the WebGL 1.0 and 2.0 specifications. I can't find a good way to hide the description column, so it is still there currently. Let me know if there are any other changes you would like to see, otherwise this is good to go.

**Comment by pjcozzi** [comment]
Thanks @lasalvavida!

**Pull request merged**
