### PR TITLE
Fix merging of composite availability

### LINKED ISSUE #7717: Merged Entity availability
Here's some code from where two Entities are merged into one:

https://github.com/AnalyticalGraphicsInc/cesium/blob/502f34abebb4ffb06dfc1671db0983c52fdffe70/Source/DataSources/Entity.js#L568-L569

The order of parameters on the merged `name` property is the same order as all of the other merged properties in this merge function.

But `availability` is backwards.  It actually prefers the lower-priority Entity over the higher-priority one, when all the other properties go the other way.

This has some strange consequences for `entity.path` for example, as it takes the `position` data from one side of the merge and clamps it to the `availability` from the other side of the merge.  As a quick test, flipping these two parameters on line 569 here fixed the problem in an app with a CompositeEntityCollection made from different time intervals.  But is that the right answer in all cases?  Why were they placed backwards here?

/cc @shunter @mramato

### PR DESCRIPTION
**Pull request by emackey**
Fixes #7717

The `name` and `availability` weren't being cleaned by the CompositeEntityCollection's clean helper, so re-merging them wasn't taking place by order of composed collections, instead it was whatever the order that the underlying collections were being populated by the server, which was a race condition.

At some point, the merge for `availability` had intentionally been installed backwards, possibly as a workaround for this race condition in a particular app.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/merge-availability/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by emackey** [comment]
I need to fix the merge tests, they test for the bad behavior.

**Comment by emackey** [comment]
I added a new test to ensure that `availability` cleans & merges correctly like the other properties.  The new test succeeds here and fails in master (with master showing the lowest-priority collection's availability is the winner in that case).

I also modified one other test in a way I'm less certain of.  This test specifically tested for `merge` to treat availability the opposite way from everything else, and here I've modified the test to treat it as a normal merge, so `availability` aligns with the other merged properties.  I strongly suspect that this intentional backwards-ness was placed there as a workaround for the bug where `clean` didn't clean the availability.

Ultimately, in `master`, the chosen `availability` for any one entity doesn't come from the ordering of collections in the composite at all.  Due to the lack of cleaning, it comes from the order in which the collections happened to be first populated in the composite.  On this branch, the availability gets cleaned and merged in the same order as all the other entity properties, so it will come from the same source that provided the time-dynamic properties, which seems like a good thing.

It would be great for this to sit in master for a while, to get some testing.  I've done my own testing where I intentionally defer loading one collection or the other, and it's clear that master has a race condition there that is fixed here.

**Comment by emackey** [comment]
The Travis fail is unrelated to tests on this branch.  This is ready.

**Comment by emackey** [comment]
@mramato Any chance you can take a look at this?

**Comment by mramato** [comment]
Sorry for the slow roll here @emackey.  This looks like a straightforward fix and I'm sure if there was a good reason it was flipped (spoiler alert, probably not) we'll be reminded of this soon enough.  Thanks again!

**Pull request merged**
