### PR TITLE
Add list of ESLint rules to CodingGuide

### PR DESCRIPTION
**Pull request by omh1280**
A continuation of #5472. 

I've added a list of the main ESLint rules we enable that are not enabled by the [eslint recommended](http://eslint.org/docs/rules/) config. This is to make the CodingGuide more clear for new submitters so that they don't have to search through the code to find what rules are enabled.

### CODE REVIEW

**Comment by mramato** [comment]
@pjcozzi can correct me if I'm wrong, but I think he wanted a list of the recommend config rules as well, that way it's completely obvious to readers.

**Comment by omh1280** [comment]
There are about 40 of them. I can add them, it will just be a huge list!

**Comment by pjcozzi** [comment]
Yes, I wanted all of them, but you could also add a link to the recommonded config list.

@omh1280 see the big picture here: the Coding Guide - for the most part - covers all our best practices.  With eslint, we just added a bunch more and didn't document them.  Just make it clear - however you see fit - so that a new person reading the Coding Guide would truly walk away with an understanding of the best practices, and not just skip over a link that contains most of them hidden in eslint.

**Comment by omh1280** [comment]
Unfortunately, there is no list of "recommended rules"--just http://eslint.org/docs/rules/, where every recommended rule has a ✔️ next to it. I'll add a link to this page.

**Comment by omh1280** [comment]
Ready for another look! Sorry I took so long.

**Comment by omh1280** [comment]
Bump!

**Comment by hpinkos** [comment]
@pjcozzi do we want to merge this?

**Comment by pjcozzi** [comment]
Yeap, thanks @omh1280 @hpinkos!

**Pull request merged**
