### PR TITLE
added Zhihang Yao (from virtualcitySYSTEMS GmbH) to CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by yaozhihang**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @yaozhihang!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/patch-2/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Added this change to #7589

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @yaozhihang! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Comment by hpinkos** [comment]
@OmarShehata why did concierge comment when I closed this instead of merging it?

**Comment by OmarShehata** [comment]
@hpinkos the GitHub API marks a PR "closed" if it was merged or closed, so it's always been posting in either case (like here https://github.com/AnalyticalGraphicsInc/cesium/pull/7428#issuecomment-456102936).

I've got a fix for this same issue for the Slack bot here https://github.com/AnalyticalGraphicsInc/cesium-concierge/pull/137. I've added a note to do the same check on a PR close/merge to check that it has actually been merged before posting.

**Pull request closed without merging**
