### PR TITLE
Fix point cloud test failures on Linux

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/7070

For anyone on Linux, try:
http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/point-cloud-test-fix/Specs/SpecRunner.html?spec=Scene%2FPointCloud3DTileContent

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/point-cloud-test-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
I can confirm the tests fail for me in master but pass in this branch; but I'm not the right person to review this.  @likangning93 or @loshjawrence can one of you review?

@lilleyse Maybe it's obvious to someone that knows this code, but can you explain what this change is actually doing any why it might have been failing on Linux only to begin with?

**Comment by likangning93** [comment]
Can confirm the fix as well, but the problem is more that the underlying spec is fragile, which is  my fault from when these were written... the "reference" `noAttenuationPixelCount` value is hardcoded when it should probably be computed before any specs are run instead.

Maybe then we won't have to tune parameters to get this to pass both on Linux and Windows?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
@lilleyse @likangning93 should we take this as-is since it's a short term win, or do you want to see a change to `noAttenuationPixelCount` as you mentioned?  I'm fine with merging as-is and writing up a second issue for `noAttenuationPixelCount`

**Comment by lilleyse** [comment]
Opened that issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/7407

**Comment by mramato** [comment]
Can confirm once again that these still pass on my machine.  Thanks @lilleyse

**Pull request merged**
