### PR TITLE
Fix oit/picking bug

### LINKED ISSUE #6817: Rendering stops when: picking after adding non-pickable primitive and before render is called
##### What I'm trying to do
In an application I'm developing, `scene.pick` gets called _a lot_, eg. on mouse move.
Additionally, primitives are added to the `scene` at a similar frequency.
These primitves should _not_ be picked (`allowPicking: false`)

##### What happens
Some times, rendering stops, due to an error arising during rendering:
```
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'translucentCommand' of undefined
TypeError: Cannot read property 'translucentCommand' of undefined
    at executeTranslucentCommandsSortedMRT (https://cesiumjs.org/Cesium/Source/Scene/OIT.js:605:160)
    at OIT.executeCommands (https://cesiumjs.org/Cesium/Source/Scene/OIT.js:621:13)
    at scene._executeOITFunction (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2230:32)
    at executeCommands (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2461:13)
    at executeCommandsInViewport (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2853:9)
    at updateAndExecuteCommands (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:2701:13)
    at render (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:3265:9)
    at tryAndCatchError (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:3285:13)
    at Scene.render (https://cesiumjs.org/Cesium/Source/Scene/Scene.js:3329:13)
```

##### What causes this to happen
As stated above, picking and adding primitives happens a lot. In some seldom cases,
primitives are added (async), their ready promise resolves, but _before_ they are rendered
the first time, they are drawn in a _pick_ pass. Since they do not have a `pickId`,
this line is executed in [Scene.js:1527](https://github.com/AnalyticalGraphicsInc/cesium/blob/40ba971f4f01493c27b0f44c737c7c89bdbc1242/Source/Scene/Scene.js#L1527)
```javascript
if (scene.frameState.passes.pick && !defined(command.pickId)) {
    return;
}
```
So now the draw command of the primitve is no longer dirty, _but_ it was never
fully created.

##### What could solve the issue
So I hacked in a working solution for my case:
```javascript
var oit = scene._oit;
if (scene.frameState.passes.pick && !defined(command.pickId)) {
    if (defined(oit) && oit.isSupported() && !defined(derivedCommands.oit)) {
        command.dirty = true;
    }
    return;
}
```
But I'm not sure if this is a) the right place to fix the issue or b) the right approach.
If this _is_ a working solution, I'm more then happy to open a PR.

##### How to reproduce
I've create a small Sandcastle: https://gist.github.com/bkuster/498b83a2bad638e5ed43f24110cdf89d

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #6817

@lilleyse suggested this fix.

@bagnell can you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-oit-picking/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by bagnell** [comment]
This would break picking for polygons and lines on terrain. Try the picking in this example:
http://localhost:8080/Apps/Sandcastle/index.html?src=development%2FGround%20Primitive.html&label=Development

If the command doesn't have a derived pick command, it executes the derived depth command. Classification primitives can't use the derived commands for reasons, so they have custom pick commands that are executed.

Can you try moving that if block to right before the line `derivedCommands.depth = //...`? I can't reproduce the issue this fixes.

**Comment by lilleyse** [comment]
> Can you try moving that if block to right before the line derivedCommands.depth = //...? I can't reproduce the issue this fixes.

That worked for me for #6817.
@hpinkos does this also fix your use case?

**Comment by hpinkos** [comment]
@bagnell yep, that seems to have worked

**Comment by bagnell** [comment]
:+1:

**Pull request merged**
