### PR TITLE
Remove all double quote usage from JS code

### PR DESCRIPTION
**Pull request by mramato**
99% of this PR was automatically fixed with eslint, I simply removed the `"quotes": "off"` from Sandcastle and Specs which was ignoring the standard rule of using single quotes.

Also added some Sandcastle generated files to .eslintignore.

We should get this in ASAP because it will get out of date quickly

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/no-double-quote/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by ggetz** [comment]
Changes looks fine, tests pass, and Sandcastle examples still work. :+1: 

Thanks @mramato !

**Comment by emackey** [comment]
I'm fine with this, but, did all the pasted JSON code get converted to single quotes too?  We have a number of CZML samples hard-coded into Sandcastle code snippets.

**Comment by hpinkos** [comment]
@emackey good catch, it looks like they did

**Comment by ggetz** [comment]
If they are JS objects and not JSON files, shouldn't they still be single quotes?

**Comment by hpinkos** [comment]
Since they're inline it's a tough call.  Maybe we should change them to be a string and call `JSON.parse`?

**Comment by emackey** [comment]
The idea is that users can copy-and-paste them into actual CZML files.  JSON, and therefore CZML, require double quotes to parse correctly.

I think they should be in the most copy-and-paste-ready format possible for the users looking at them.

**Pull request merged**
