### PR TITLE
Port Sandcastle examples to entity layer

### PR DESCRIPTION
**Pull request by mramato**
__NOTE: This is a pull request into the `implicit-properties` branch.__ 

@pjcozzi, I'm assume you'll be the one to hit merge on this, but for anyone curious, it's worth checking out the "new" Sandcastle examples.

As discussed in #2315 and offline, this PR updates practically every Sandcastle examples that was using primitives (especially Geometry) to use the new entity system.

Most modified examples were "backed up" to the gallery/development subdirectory.  This new directory can be used for storing dev-only sandcastle examples. The build process has been modified so that these files are not shipped as part of the release.  We'll probably actually want to delete a bunch of these sooner rather than later, but I'm sure some of them will be useful for debugging. Since git has no explicit rename functionality, it thinks a lot of the files under `Sandcastle/gallery/development` are new.  You can ignore every file in this directory for review purposes.  They are a carbon copy of what's in master (except they are now under the `Development` label.

As for the examples I ported, most of them are much easier to read and understand now.  Especially the geometry examples.  I also merged the outline and non-outline versions and made various tweaks.

For the sake of making Cesium more approachable to beginners (and since our goal is to make the Entity API the main thing people use) I moved some examples to the dev-only gallery without porting them.  For example, Volumes and some of the polyline and appearance examples (we had way too many polyline examples).  I plan on filtering some of the functionality these demos back into the main geometry examples.

There were 5 or so issues I uncovered during the port that require features to be added to the entity layer in order to finish up. It's up to you guys if I should work on these in this branch first, or I can do it after we merge this into implicit-properties. Here they are:

__TODO Features needed for specific Sandcastle examples__
* [x] 3D Models: Way to get bounding sphere for a primtiive (or primitives for a given entity)?
* [x] Resnap sandcsatle examples.
* [x] ~~Picking: Make temporarily overriding a property easy (plus material).~~ __Punted for now__
* [x] Billboards: Support for `Billboard.imageSubRegion` at entity layer.

Check out this branch and browse all of the examples and let me know what you think.  Short of build.xml and createGalleryTask.js, all code changes are reviewable by just browsing Sandcastle.  I would recommend that over trying to look at the crazy diff below.  Ultimately, I think this is the tip of the iceberg, with some additional Sandcastle work (most likely post merge to master), Cesium approachability and usability is going to increase 10-fold hopefully).

### CODE REVIEW

**Comment by pjcozzi** [comment]
We'll want to change some of the wording for the [Geometry and Appearances tutorial](http://cesiumjs.org/2013/11/04/Geometry-and-Appearances/) (e.g., entities, not primitives, are built on geometries) and we'll have to figure out the links to the Sandcastle example.  This should remain a low-level tutorial (as is always has been).  We'll introduce a higher-level tutorial each geometry later.

**Comment by pjcozzi** [comment]
I have not looked at the code yet, but my gut is:

> 3D Models: Way to get bounding sphere for a primtiive (or primitives for a given entity)?

No need for the entity to return the bounding sphere, but we do want to be able to zoom to entities in general.  For 3D models, this is a major benefit of the entity API, since this is pretty painful with the primitive.

> Picking: Make temporarily overriding a property easy (plus material).

Probably important for mouse over, etc.  I always envisioned the highest-level API to make this really easy like:
```
entity.material = Color.Blue;
entity.rollOverMaterial = Color.White;
```
It wouldn't be quite that simple and this is probably a bigger discussion for another day.

> Geometry Showcase: Support for per-segment or per-vertex polyline color.

Could punt it for now.

> Billboards/Labels: Define entity position in another reference frame.

Could punt it for now.

**Comment by pjcozzi** [comment]
Can we remove the commented out code in `Entity Geometry and Appearances.html`?

**Comment by mramato** [comment]
> No need for the entity to return the bounding sphere, but we do want to be able to zoom to entities in general. For 3D models, this is a major benefit of the entity API, since this is pretty painful with the primitive.

Yeah, I agree that zooming to is the main goal, not necessarily exposing the bounding sphere. It can be a little tricky because of the asynchronous nature of loading models and the fact that the data (Entity) and visualization (Primitives) are completely decoupled (on purpose).  I think I have a workable solution tough that I'll look into coding up soon.

> entity.material = Color.Blue;
> entity.rollOverMaterial = Color.White;

I have some ideas here, not that different than yours.  We might add something like `entity.pickStyle`, which would allow you to temporarily override any property. So to override `entity.polygon.material`, you set `entity.pickStyle.polygon.material`.  When you want to go back to the original, you just set `entity.pickStyle.polygon.material` to `undefined`.  I don't like the name `pickStyle`, it could even be something more generic like `overrides`.  KML takes a similar approach (though it's directly tied to hovering).

I'm fine with punting on the other two things, I'll update the roadmap issue so we don't forget about them.

**Comment by mramato** [comment]
> We'll want to change some of the wording for the Geometry and Appearances tutorial

I'll add a to-do on the `implicit-properties` PR to remember to do a full review/scrub of the tutorials before we release.  I'll do the 1.6 release as well, just to keep things simple.

**Comment by mramato** [comment]
I did another pass on cleaning up Sandcastle demos and made some other tweaks. I still need to work on those other 2 issues, but for sake of review, I'll do that in another branch. This PR can be merged into `implicit-properties` at any time (assuming you are happy).  We can continue to work stuff there before going into master.

**Comment by pjcozzi** [comment]
> I have some ideas here, not that different than yours...

They sound good.

**Comment by pjcozzi** [comment]
The new 3D model example zooms out to a global view when I select the ground vehicle.

**Comment by pjcozzi** [comment]
Can we make `development` not show up under `All`?

**Comment by pjcozzi** [comment]
The picking example has the GUIDs show up in the info box.  We probably don't want that.

**Comment by pjcozzi** [comment]
For the polygon example, the initial zoom is right up on the ground and we can't see any polygons.

**Comment by pjcozzi** [comment]
Same for the `PolylineVolume` example.

**Comment by pjcozzi** [comment]
And, to a lesser extent, the `Rectangle` example.

**Comment by pjcozzi** [comment]
Overall looks very good.

**Comment by pjcozzi** [comment]
For 1.6, we might also want to make a pass over the 3D Model tutorial and any other tutorial that uses primitives to see if we should port them to entities.

**Comment by mramato** [comment]
I'm going to branch off this PR and implement `viewer.zoomTo`, I'll fix the examples in that branch and then PR into this one.

**Comment by pjcozzi** [comment]
Do we want to add a Sandcastle example that shows some common heterogeneous objects like area targets (polygon, polyline, point, label)?

**Comment by mramato** [comment]
> Do we want to add a Sandcastle example that shows some common heterogeneous objects like area targets (polygon, polyline, point, label)?

I've got all kinds of plans for that, but I didn't want to start writing new Sandcastle examples or messing with things too much until everything else is in master.  The `implicit-properties` PR is already going to be huge.

**Comment by pjcozzi** [comment]
Yeap.

**Comment by mramato** [comment]
This is ready to be merged (into `implicit-properties`).

**Comment by mramato** [comment]
FYI, all of the comments above should also be taken care of already.  If you find anything in the examples, let me know.  I'm doing a pass on them now.

**Comment by pjcozzi** [comment]
I won't be able to look at this until Saturday.  If that holds you up, just merge it, and I will still comment in this PR to keep the diff clean.

**Comment by pjcozzi** [comment]
I think we can remove all geometry/appearance examples except the massive "Geometry and Appearances" from the `Development` examples.

**Comment by pjcozzi** [comment]
Do any of the example show how to add metadata for the infobox?

**Comment by pjcozzi** [comment]
My comments can be addressed in 1.6 or later.

**Comment by mramato** [comment]
> Do any of the example show how to add metadata for the infobox?

Not really, but the new Entity tutorial will.  I plan on doing another round of Sandcastle updates shortly after 1.6,so I'll be sure we include one there.

I'll open a PR for for deleting other examples for post 1.6 as well.

Thanks.

**Pull request merged**
