### PR TITLE
fix for issue #6612: Missing tiles in VR mode (regression w.r.t. Cesium 1.44)

### PR DESCRIPTION
**Pull request by glathoud**
Two small commits to better support VR, in particular to avoid having missing tiles. See also https://github.com/AnalyticalGraphicsInc/cesium/issues/6612

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @glathoud!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Thanks again @glathoud, we also received your CLA.

**Comment by hpinkos** [comment]
Thanks @glathoud!  @bagnell could you review?

**Comment by bagnell** [comment]
Thanks for looking into this @glathoud. The problem was deeper in the engine where we change the frustum aspect ratios for the two eyes. Closing this in favor of #6798.

**Comment by glathoud** [comment]
@bagnell Thanks!

**Pull request closed without merging**
