### PR TITLE
Tile coloring

### PR DESCRIPTION
**Pull request by lilleyse**
This lets the 3D Tiles inspector do hover-over coloring for tiles that don't have features, like a lot of photogrammetery tilesets and point clouds.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@hpinkos do you want to look at this and merge?

**Comment by hpinkos** [comment]
Picking isn't working correctly for the composite example in the 3dtiles sandcastle demo.  The highlight color doesn't unselect.  It might not happen the first mouseout, but if you keep hovering over different features it gets into a weird state fairly quickly

**Comment by hpinkos** [comment]
Everything else works though, thanks @lilleyse!

**Comment by lilleyse** [comment]
Thanks for noticing that, should be fixed now.

I also had a small fix to jsep that I didn't catch before. We took that code out of the prior version too.

**Comment by hpinkos** [comment]
@lilleyse that's a prime example for why we shouldn't ever edit a third party library like that.  It makes updating to a new version a nightmare because you lose track of custom changes you made.  Why do we need to remove that section of code from jsep?  Is there a bug?

**Comment by pjcozzi** [comment]
Please contribute back to jsep if it is a change they would be interested in.

**Comment by lilleyse** [comment]
I'm not sure why the changes were originally made, but I'm guessing it has to do with working with AMD.

**Comment by hpinkos** [comment]
If it's a problem with AMD, we should try to figure out what the issue is instead of hacking things out of the source file.  Ask @mramato if you need help figuring it out.

**Comment by lilleyse** [comment]
Took the jsep changes out of here and moved to https://github.com/AnalyticalGraphicsInc/cesium/pull/5365.

**Comment by hpinkos** [comment]
Thanks @lilleyse!

**Pull request merged**
