### PR TITLE
Add the new outline to the Cesium logo.

### LINKED ISSUE #4582: Update Cesium logo
We've been using a new logo with a border around the Cesium icon which can be found on our logos page: https://github.com/AnalyticalGraphicsInc/cesium/wiki/Cesium-Logos

We should update the Cesium credit in the footer and the favicon to use this new logo

### PR DESCRIPTION
**Pull request by emackey**
Fixes #4582.

### CODE REVIEW

**Comment by emackey** [comment]
Oh, I didn't do the favicon yet, hold on...

**Comment by emackey** [comment]
I don't think I have the right tooling to regenerate `Apps/Sandcastle/images/cesium_maptiler`, but it's opaque anyway, just missing the &reg; symbol.

This is ready.

**Comment by emackey** [comment]
OK I'm really putting this one down now... walking away...

**Comment by hpinkos** [comment]
Looks great @emackey, thanks!  I think you got everything

**Comment by hpinkos** [comment]
Wait! found one more https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/Images/Cesium_Logo_overlay.png

I'll update that real quick

**Comment by hpinkos** [comment]
Though, I can't find anything that's actually using that image.  Maybe we can just delete it?

**Comment by emackey** [comment]
There's also a `logo.png` in the root folder that was not updated.  I can't find any references to that either, is it not needed?

**Comment by hpinkos** [comment]
@emackey I couldn't find anywhere that was using that either.  Maybe it was used by `README.md` once upon a time?  I went ahead and deleted that too

**Comment by hpinkos** [comment]
I think this is good to go.  Did anyone else want to look at this?

**Comment by pjcozzi** [comment]
No need from me, ship it!

**Pull request merged**
