### PR TITLE
Enable GroundPrimitives to render without the fragment depth extension.

### LINKED ISSUE #4899: Enable glitchy ground primitives on IE 11
I was talking with @bagnell on Friday and learned that we could actually enable ground primitives on machines without `frag_depth` but it would lead to artifacts when inside of the shadow volume.  I  had no idea this was an option and personally feel like it's a much better solution than having ground primitives not work at all.

Can we open a PR with making this behavior the default and ask our users to experiment with it and let us know what they think?  For many cases where you are nowhere near the shadow volume, this solution is ideal.

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #4899.

### CODE REVIEW

**Comment by bagnell** [comment]
Because we can't write depth to clamp fragments to the far plane, there is an artifact when any of the far planes of the multi-frustum intersect terrain and the volume.

**Comment by pjcozzi** [comment]
Update CHANGES.md (for 1.31, not 1.30) and the reference doc.

**Comment by bagnell** [comment]
@pjcozzi Updated.

**Comment by mramato** [comment]
This is awesome!  Extremely preferable to what we had before.  Hopefully users will think so too. While there are definitely some artifacts, they are way less common than I thought and I think will not even be a problem in most casas.

@pjcozzi approved this for merge offline and it will have a whole month to stew in master if there are unforeseen problems

**Pull request merged**
