### PR TITLE
Fix Spelling Error

### PR DESCRIPTION
**Pull request by TJKoury**
_removeDefaultDataSoureListener - > _removeDefaultDataSourceListener

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @TJKoury! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/TJKoury/cesium/blob/patch-1/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/patch-1/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks @TJKoury!  If you search for `Soure`, the same spelling mistake is in a few other places in that file.  Can you fix that too please?

**Comment by TJKoury** [comment]
@hpinkos Good catch!  Done.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @TJKoury! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
whoops, sorry for the delay on this @TJKoury!  I'll get this merged as soon as CI passes

**Comment by TJKoury** [comment]
You are doing me the favor, @hpinkos!  Thanks for the update.

**Pull request merged**
