### PR TITLE
Clipping planes invert distance sign

### PR DESCRIPTION
**Pull request by ggetz**
Adjust `Plane.transform` function and adjusted distance sign accordingly.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@ggetz, thanks for the pull request! Maintainers, we have a signed CLA from @ggetz, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
@lilleyse just a reminder that this is a not a breaking change; `transform` was added this release.

**Comment by hpinkos** [comment]
@ggetz  this all looks fine to me.  Are we sure we have it right this time?  Is there an equation we followed to write the `Plane.transform` function?  I just don't want to merge this without understanding why we had to make this change.

**Comment by ggetz** [comment]
I was using the definition of plane.distance opposite of what was previously defined:

> The shortest distance from the origin to the plane. The sign of distance determines which side of the plane the origin is on. If distance is positive, the origin is in the half-space in the direction of the normal; if negative, the origin is in the half-space opposite to the normal; if zero, the plane passes through the origin.

So when computing the position representing the location of the plane, we need to multiply the normal by the _opposite_ of the distance, rather than the distance as is.

**Comment by hpinkos** [comment]
Great, sounds good @ggetz!

I think this is good to go, but I'll leave it open until the 2nd so @lilleyse can take a quick look at it and merge before the release

**Comment by lilleyse** [comment]
> So when computing the position representing the location of the plane, we need to multiply the normal by the opposite of the distance, rather than the distance as is.

Alright, that does make sense.

I tested out the demos and ran the tests. This change looks good to me.

**Pull request merged**
