### PR TITLE
sandcastle 403 error handling

### PR DESCRIPTION
**Pull request by rahwang**
Fixing #2182. Is this right, @hpinkos ?

### CODE REVIEW

**Comment by hpinkos** [comment]
@emackey could you review this please?

**Comment by rahwang** [comment]
Hmm looks like my build fails on `makeZipFile`, which runs fine on my machine?

**Comment by emackey** [comment]
@rahwang I don't think you need to worry about the travis fail, I've seen a lot of that lately.

Code looks good I just want to replicate the `403` on my machine before I merge, hang on.

**Comment by emackey** [comment]
Well I gave myself a `401`, that's close enough for this test.  Behavior is just like master for `404`, great!  Thanks @rahwang.

**Pull request merged**
