### PR TITLE
Removed url and key from GeocoderViewModel

### LINKED ISSUE #4730: Remove deprecated properties in GeocoderViewModel in 1.31
The `GeocoderViewModel` and related classes have been updated as part of #4723.

Its `url` and `key` properties will be deprecated from 1.30 and removed in 1.31.

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #4730 

@hpinkos

### CODE REVIEW

**Comment by hpinkos** [comment]
@lilleyse remove `options.url` and `options.key` as params in `GeocoderViewModel`

**Comment by lilleyse** [comment]
My impression from https://github.com/AnalyticalGraphicsInc/cesium/pull/4723 is that only the getters were being deprecated.

**Comment by lilleyse** [comment]
Hm maybe not, this PR may require some deeper changes than this.

**Comment by hpinkos** [comment]
@lilleyse you're right, this ended up being a slightly bigger change.  The idea was that we removed these options from `Geocoder` by making them available in the `GeocoderServices` instead.  So I removed `key` and `url` from `Geocoder`/`GeocoderViewModel` and made a few changes to `BingMapsGeocoderService`

This is ready now.

**Comment by lilleyse** [comment]
Ok looks good now. Thanks for the changes @hpinkos.

**Pull request merged**
