### PR TITLE
fixed issue 4029

### PR DESCRIPTION
**Pull request by ateshuseyin**
issue 4029 fixed

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @ateshuseyin! 

Just so you know, if you use the notation `Fixes #4029` in your pull request comment, it links to that issue automatically which is helpful for us =)

**Comment by pjcozzi** [comment]
Fixes #4029

**Comment by pjcozzi** [comment]
This looks good, thanks @ateshuseyin.  Before we merge, could you please
* Update [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md)
* Add a unit test.  Ideally one that fails in master, but passes in this branch.  For more info on unit tests, see the [Testing Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/TestingGuide/README.md)

**Comment by ateshuseyin** [comment]
All done

**Comment by pjcozzi** [comment]
Looks great, thanks @ateshuseyin!

**Pull request merged**
