### PR TITLE
Enable `no-implicit-globals rule`

### PR DESCRIPTION
**Pull request by omh1280**
For #5456. Add [`no-implicit-globals`](http://eslint.org/docs/rules/no-implicit-globals) ESLint rule.

Disabled for `Apps/` because the html files in `Apps/` break this rule constantly. For an example, see https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/gallery/HTML%20Overlays.html#L27.

Disabled as well for `Specs/` because a) there was only one error and b) that error was in `Specs/SpecList.js`, which is not tracked by git.

### CODE REVIEW

**Comment by mramato** [comment]
Rather than disabling for `Specs` change the `SpecList.js` generation code to ignore it.  I agree that disabling it for Sandcastle is the right call.

As discussed offline, also move this setting into the shared config.  Also make it browser-only and not part of `index.js`, since it doesn't apply to node code.

**Comment by omh1280** [comment]
Do you mean add a `/*eslint-disable no-implicit-globals*/` at the top of `SpecList.js`? Is there a way to disable `.gitignore` for one commit?

**Comment by mramato** [comment]
> Do you mean add a /*eslint-disable no-implicit-globals*/ at the top of SpecList.js? Is there a way to disable .gitignore for one commit?

Sorry, I should have been more clear.  What I meant is to modify the `createSpecList` function in `gulpfile.js`, which is where `SpecList.js` gets generated.

**Comment by omh1280** [comment]
Bump!

**Comment by mramato** [comment]
Thanks.

**Pull request merged**
