### PR TITLE
Replace DeveloperError with Check in InfoBox

### PR DESCRIPTION
**Pull request by burn123**
Part of #4794.

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @burn123!  Please remove `DeveloperError` from being required in since it's not being used in the class anymore.

**Comment by hpinkos** [comment]
Thanks @burn123!
Next time make a comment when you've updated your pull request so I know its ready for another look =)

**Comment by burn123** [comment]
Will do!

**Comment by burn123** [comment]
@hpinkos Also, could you put my name in the list of contributors? I included it in the first pull request I made, but that one hasn't gotten merged yet, and it might be a while before it does. Then in the case it is closed my name is still on there.

**Comment by hpinkos** [comment]
Thanks for the reminder @burn123, I forgot about that.  I added it in this commit: 342a1a02d8c51d9638ce4eeceac02b378578ad18

**Pull request merged**
