### PR TITLE
Add default jsdoc tag for ShadowMap size property

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by lilleyse** [comment]
Thanks @fredj, the change looks good. Do we have a [CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) from you? Just send one over so we can merge this.

**Comment by lilleyse** [comment]
Also once that is sent over feel free to add yourself to `CONTRIBUTORS.md`.

**Comment by fredj** [comment]
we (camptocamp) have a corporate CLA. I should be included, see https://github.com/AnalyticalGraphicsInc/cesium/pull/2932#issuecomment-130127548

**Comment by lilleyse** [comment]
Ah I see, thanks!

**Pull request merged**
