### PR TITLE
Insert missing namespace declarations for KMZ files

### PR DESCRIPTION
**Pull request by nrivera-Novetta**
A function called insertNamespaces was added to the last release which added missing namespace declarations https://github.com/AnalyticalGraphicsInc/cesium/pull/5860. However, this worked only for KML files so for this PR I just added a call to the function when loading KMZ files as well, along with another test and test file.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@nrivera-Novetta, thanks for the pull request! Maintainers, we have a signed CLA from @nrivera-Novetta, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Great, thanks @nrivera-Novetta!  @tfili could you take a quick look?

**Comment by tfili** [comment]
Looks fine to me besides the conflicts in `CHANGES.md`. Thanks @nrivera-Novetta . Once you fix the conflicts I'll merge it.

**Comment by hpinkos** [comment]
@tfili I went ahead and fixed that conflict

**Comment by hpinkos** [comment]
Thanks for fixing this @nrivera-Novetta!

**Pull request merged**
