### PR TITLE
Fixed #3345. 

### LINKED ISSUE #3345: Replace "use strict" with 'use strict'
As mentioned here: https://github.com/AnalyticalGraphicsInc/cesium/pull/3312#discussion_r47279560

### PR DESCRIPTION
**Pull request by viraj96**
Did not touch Source/ThirdParty. Replaced in all other files.

### CODE REVIEW

**Comment by viraj96** [comment]
This is ready

**Comment by mramato** [comment]
Thanks @viraj96!

Before we can review and merge this, we need you to fill out and email us a CLA.  See [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) for instructions.

**Comment by viraj96** [comment]
Do you want me to print, scan and mail the CLA to you.

**Comment by mramato** [comment]
That's what most contributors do.  But you may be able to just fill out digitally without printing. The signature section says type your name, so that may be valid.

CCing @pjcozzi for clarification, since he manages CLAs.

**Comment by pjcozzi** [comment]
@mramato is right; either approach is OK.  Thanks for the contribution, @viraj96!

**Comment by pjcozzi** [comment]
We received @viraj96's CLA.

**Comment by mramato** [comment]
@viraj96 Thanks for the pull request and CLA, but it looks like you also modified a bunch of code in the top level ThirdParty directory, which shouldn't have been changed.  Given that #3535 fixes the same issue and doesn't have this problem, I'm going to go ahead and merge that one instead.

Thanks again for looking into this issue.

**Pull request closed without merging**
