### PR TITLE
Czml examples tweaks

### LINKED ISSUE #3063: CZML Example improvements
Since I missed the boat on #3050, here's some feedback I have.

__General__

- [ ] Most `var viewer` and `viewer.dataSources.add` lines are unecessarily indented and should just start at column 1.

- [ ] I'm guessing 99% of use cases want cartographicDegrees, so we should use that in all examples.  I love the `CZML Position Definitions` example, and I think that's the only place we need to have different formats.

- [ ] Similarly for colors, we seem to flop back and forth between `rgba` and rgbaf`.  For beginner examples, always using `rgba` might be easier and we can have a `CZML Colors` example showcases different formats`.

- [ ] We don't need to explicitly state `show: true`, which most examples do.  I think it's confusing and makes it look required. `show` should only be used in examples where it's time-dynamic or if you want it off by default for some reason.

- [ ] Screen shot sizes seem to vary, for example `CZML Polygon - Interpolating` example is wider than most others.  We should resnap all images to be the same size (using the `view as Thumbnail` button so they are consistent.

- [ ] Add `viewer.zoomTo(dataSource)` to the end of the following examples `CZML Point`, `CZML Circles and Ellipses`, `CZML Polygon`, `CZML Polyline`, `CZML Rectangle`, `CZML Spheres and Ellipsoids` and `CZML Wall`

__CZML Billboard and Label__

- [ ] The description doesn't need the  or \r\n tags.  It will always be treated as HTML.  Let's change it to something like

```	
<p><a href='http://www.agi.com' target='_blank'>Analytical Graphics, Inc.</a> (AGI) founded Cesium.</p>
```

__CZML Path__

- [ ] createDefaultTerrainProviderViewModels is not part of the public API.  This should just create and use the `CesiumTerrainProvider`.

- [ ] Might be cool to also add a billboard, model or something to this demo to both illustrate that it's possible but also make it easier to follow the path visually, especially since there is a lead time.  For a model, we'll need orientation (which is currently harder than it should be since it's all quaternions).

- [ ] The trail time seems too long and it's hard to notice it by just looking at the demo.

__CZML Wall__
- [ ] Perhaps a wall with per-position heights?  Maybe just mirror the [Geometry example](http://localhost:8080/Apps/Sandcastle/index.html?src=Wall.html&label=Geometries).

Here's a complete model example.  scale and minimumPixelSize are both optional.

```javascript
var czml = [
    {
        "id" : "document",
        "name" : "Basic CZML billboard and label",
        "version" : "1.0"
    }, {
        "id" : "aircraft model",
        "name" : "Cesium Air",
        "position" : {
          "cartographicDegrees" : [
            -77, 37, 10000
          ]
        },
        "model": {
            "gltf" : "../../SampleData/models/CesiumAir/Cesium_Air.bgltf",
            "scale" : 2.0,
            "minimumPixelSize": 128
        }
      }
];

var viewer = new Cesium.Viewer('cesiumContainer');
var promise = viewer.dataSources.add(Cesium.CzmlDataSource.load(czml));

promise.then(function(dataSource){
    viewer.trackedEntity = dataSource.entities.getById('aircraft model');
}).otherwise(function(error){
    window.alert(error);
});
```

### PR DESCRIPTION
**Pull request by tiffanylu**
close #3063, closes #3050 
@pjcozzi @mramato @adamdavidcole

### CODE REVIEW

**Comment by pjcozzi** [comment]
The CZML Path example is a little awkward since it uses the facility billboard as the moving object.  @mramato do we have anything handy that would be reasonable to use here?

**Comment by pjcozzi** [comment]
@tiffanylu @adamdavidcole nice job, at quick glance, that is the only comment I have.

@mramato is going to also do a quick review.

**Comment by mramato** [comment]
> @mramato do we have anything handy that would be reasonable to use here?

I found some public domain hangliding icons at https://thenounproject.com/term/hang-gliding/239/.  Since it's public domain, we don't even need to credit it.

If you don't want to use one of those, we can probably grab the aircraft icon we use in STK or just make it a point instead of a billboard.  I'm open to suggestions.

**Comment by mramato** [comment]
Thanks guys.  The one outstanding problem is still the thumbnails.  They are way bigger (file size wise and resolution-wise) than all of the other thumbnails.  I'm sorry I didn't give you better instructions in the previous issue I wrote up.  The should all be 225x150.  Normally we use the "Show as Thumbnail" button at the top of Sandcastle to create them.  In this case, just resizing the ones you already made should be pretty easy, no need to resnap them all.  We also usually save at 95% quality jpg.  Sorry again for the confusion.

Other than that, (and @pjcozzi's comment) this looks great.

**Comment by pjcozzi** [comment]
I suspect they are bigger than usual because of the Retina display...I run into it all the time.

**Comment by tiffanylu** [comment]
@pjcozzi @mramato ready

**Comment by tiffanylu** [comment]
Even after resizing the screenshots and saving them as high or medium (as opposed to maximum) quality, they were still much larger, resolution-wise, than the others... so I just ran all of them through ImageOptim and I think they should be fine now. So hopefully that's everything, and we're ready!
@pjcozzi @mramato

**Comment by mramato** [comment]
Thanks guys!  Nice work.

**Comment by pjcozzi** [comment]
Thanks for the review @mramato.

Awesome job @tiffanylu @adamdavidcole!  Good luck with #2814.

**Pull request merged**
