### PR TITLE
Fixed token issue in ArcGisMapServerImageryProvider

### PR DESCRIPTION
**Pull request by pierotofy**
When creating an instance of ArcGisMapServerImageryProvider and usePreCachedTilesIfAvailable is false (or _useTiles ends up being false because no pre-cached tiles are available), the token parameter is appended to the layer URL without adding the ampersand character. This results in the generation of an erroneous URL, which then causes errors.

The proposed fix modifies how the token parameter is appended to the URL, by adding the missing "&" character when appropriate.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @pierotofy!

@kring can you review this?  We have a CLA.

**Comment by kring** [comment]
Thanks @pierotofy, this looks good!  Can you please do two small things in this pull request before I merge it:
* Add yourself to `CONTRIBUTORS.md`.
* Add a mention of this fix to `CHANGES.md`.

**Comment by kring** [comment]
The `CHANGES.md` mention should go in a new 1.15 section dated 2015-11-02.

**Comment by pierotofy** [comment]
Thanks for reviewing the changes @kring. I've added my name to the contributors file and added a note for the change.

**Comment by kring** [comment]
Thanks @pierotofy!

**Pull request merged**
