### PR TITLE
implemented TMS in terms of UrlTemplateImageryProvider

### PR DESCRIPTION
**Pull request by tiffanylu**
due to its async nature, the benefits of implementing `TileMapServiceImageryProvider` in terms of `UrlTemplateImageryProvider` as it currently stands are limited
@pjcozzi it might be more complicated than just creating setter functions for the properties in `UrlTemplateImageryProvider`, since the `fileExtension` property pulls data from the promise but is also necessary to create the template `url` for `UrlTemplateImageryProvider`

### CODE REVIEW

**Comment by pjcozzi** [comment]
@kring do you have a minute to look at this and advise?

**Comment by kring** [comment]
Yeah there's not a ton of benefit here, because TMS URLs are so simple to build, and that's the only part that `UrlTemplateImageryProvider` really helps with.  But the code here can be simplified a bit more, making it shorter, more reliable, and faster than the current implementation, at least a little.

To make this simpler, don't set a bunch of fields on `TileMapServiceImageryProvider` and then call a parameterless `buildImageryProvider`.  Just construct the `UrlTemplateImageryProvider` directly from local variables in the two places.  You should be able to get rid of all the error event, credit, and ready handling.

**Comment by pjcozzi** [comment]
Part of #2814.

**Comment by pjcozzi** [comment]
@kring thanks for the review.

**Comment by tiffanylu** [comment]
I'm opening two new pull requests on two renamed branches, one for TileMapServiceImageryProvider and one for its test fixes. Will update this comment as soon I do so

**Pull request closed without merging**
