### PR TITLE
Throw if Plane normal is not normalized

### PR DESCRIPTION
**Pull request by hpinkos**
I spent a little while this afternoon trying to track down a problem that was caused because someone created a plane where the normal wasn't normalized.  The doc says it should be, so I added a `DeveloperError` check to make sure the normal vector has a magnitude of 1.0.

### CODE REVIEW

**Comment by bagnell** [comment]
Where was the error? Should we also check that it is normalized in the `from*` functions?

**Comment by hpinkos** [comment]
My problem wasn't a bug in Cesium, someone make a mistake using `Plane` in another app.  I just think throwing a `DeveloperError` here is helpful so next time it'll point out the mistake immediately.

**Comment by hpinkos** [comment]
And I don't think we need to put the check in the `from` functions because they each call `new Plane`

**Comment by bagnell** [comment]
> And I don't think we need to put the check in the from functions because they each call new Plane

Only when a result parameter isn't supplied.

**Comment by hpinkos** [comment]
Good point, I'll update that

**Comment by bagnell** [comment]
> My problem wasn't a bug in Cesium

Ok, I agree this is a good change.

**Comment by hpinkos** [comment]
@bagnell ready

**Comment by pjcozzi** [comment]
Please document the `@exception`.

**Comment by hpinkos** [comment]
@pjcozzi done

**Pull request merged**
