### PR TITLE
#6674 rename functions

### LINKED ISSUE #6674: Rename ApproximateTerrainHeights functions
To make the names more precise and less redundant:
* Rename `ApproximateTerrainHeights.getApproximateTerrainHeights` to `ApproximateTerrainHeights.getMinimumMaximumHeights`
* Rename `ApproximateTerrainHeights.getInstanceBoundingSphere` to `ApproximateTerrainHeights.getBoundingSphere`

@ggetz trivial and only used internally but perhaps a good beginner issue for Omar.

CC #6617

### PR DESCRIPTION
**Pull request by Rikku-x**
fix #6674 

rename ApproximateTerrainHeights & getInstanceBoundingSphere functions

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @Rikku-x! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/rename_functions/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks @Rikku-x! Can you send us a Contributor's Licence Agreement so we can review this?  See instructions here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by hpinkos** [comment]
@Rikku-x I didn't see your CLA come over yet.  We need that before we can review your pull request. 
 See instructions here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

Let me know if you have any questions!  If I don't hear from you by next week I'm going to close this pull request, but we can re-open it again later if you're able to get back to it.  Thanks =)

**Comment by Rikku-x** [comment]
hey @hpinkos!

Just send you CLA, please check it. Let me know if it is ok now :)

**Comment by pjcozzi** [comment]
Thanks again for contributing, @Rikku-x, we received your CLA.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Rikku-x! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by OmarShehata** [comment]
Looks great @Rikku-x ! There's a couple of failing tests which I think should be fixed if you merge in the latest `master` in your branch. If you do that I think it should be good.

Since it's a private class no change to `CHANGES.md` is needed.

**Comment by hpinkos** [comment]
Thanks @Rikku-x!  Thanks for reviewing @OmarShehata!

**Pull request merged**
