### PR TITLE
Don't throw out short polylines

### PR DESCRIPTION
**Pull request by hpinkos**
Made the epsilon values smaller for `Polylines`, `Corridors` and `PolylineVolumes`

[This forum post](https://groups.google.com/forum/#!topic/cesium-dev/kbTvRYF_q3g) reported a problem with the `PolylineVolumes`

### CODE REVIEW

**Comment by mramato** [comment]
@bagnell does the relative epsilon stuff you put in a while ago come into play here, or is this really just a case of the tolerance not being high enough?

Related question: Do we always render the polyline if there are only two points or do we end up deduping to 1 point and then throwing it out?

**Comment by hpinkos** [comment]
@mramato we'll throw it out if the polyline only has two points and the points are almost the same

**Comment by hpinkos** [comment]
Fixes #3293

**Comment by pjcozzi** [comment]
Update CHANGES.md.

@bagnell can you please review?

**Comment by hpinkos** [comment]
@bagnell this is ready now.

**Comment by bagnell** [comment]
>does the relative epsilon stuff you put in a while ago come into play here

@mramato Yes, it was changed to check the absolute or relative error. Here it would check the relative error. We need to go through and check all of the epsilon values, but I think we are just fixing them as issues come up.

**Comment by mramato** [comment]
Should there be a constant with a single epsilon defined somewhere that all of the geometry uses?  Should that be user settable?

**Comment by mramato** [comment]
And is 10 the right answer, or just a random guess?

**Comment by hpinkos** [comment]
@mramato 10 is a random guess.  It's probably small enough, but at some point we should probably figure out what's the smallest distance that's still worth rendering.  6 was definitely too big because you can still see things at that size even without being zoomed in all of the way.

> Should there be a constant with a single epsilon defined somewhere that all of the geometry uses? Should that be user settable?

I don't think it would need to be user settable, but having a constant somewhere that all of the geometries use is a good idea.  I added a note to #2364

**Pull request merged**
