### PR TITLE
Fixed 3D Tiles refinement bug when skipLevelOfDetail is false

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/5814

This bug was introduced in https://github.com/AnalyticalGraphicsInc/cesium/pull/5788/ which checks for a tile's visibility before loading it. This caused problems during the base-traversal step where it is expected that a replacement refinement tile loads all of its children, even if they are not visible. Otherwise the parent tile can never resolve.

This is not a problem with the internal-traversal (the skipping traversal), but since `skipLevelOfDetail=false` only uses the base-traversal it becomes a problem.

This PR limits the visibility check to additive tiles only. I think the visibility check would also work with replacement tiles during the skip traversal, but in practice this only saves a few requests and I don't want to mess with anything else.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@lilleyse, thanks for the pull request! Maintainers, we have a signed CLA from @lilleyse, so you can review this at any time.



__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by bagnell** [comment]
Looks good to me.

@lilleyse Is there a reasonable test you can add?

**Comment by lilleyse** [comment]
Hmm I'll try to think of one.

**Comment by lilleyse** [comment]
Added a test, it checks the combined functionality of this PR, https://github.com/AnalyticalGraphicsInc/cesium/pull/5778, and https://github.com/AnalyticalGraphicsInc/cesium/pull/5788, which are all basically related.

**Comment by bagnell** [comment]
Thanks @lilleyse!

**Pull request merged**
