### PR TITLE
Replace createSomeImageryProvider functions with SomeImageryProvider class

### LINKED ISSUE #4812: Imagery provider API consistency
From #2814, @mramato: 

> It is kind of weird and inconsistent that we use functions for some types classes for others. I know perfect is the enemy of the good and all that, but it makes our API harder to use.

I think we should change `createOpenStreetMapImageryProvider` and `createTileMapServiceImageryProvider` back into classes so they match the other imagery provider types.  They could inherit from `UrlTemplateImageryProvider` so we don't have to worry about introducing more duplicate code.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #4812

This has been a pet peeve of mine for a while so I wanted to take 5 minutes to fix it.

- createOpenStreetMapImageryProvider -> OpenStreetMapImageryProvider
- createTileMapServiceImageryProvider -> TileMapServiceImageryProvider
- Instead of using `createSomeImageryProvider` to return an instance of `UrlTemplateImageryProvider`, the `SomeImageryProvider` class inherits from `UrlTemplateImageryProvider`.
- No code changes or refactoring other than moving some of the `TileMapServiceImageryProvider` functions onto prototype

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hpinkos, thanks for the pull request! Maintainers, we have a signed CLA from @hpinkos, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by OmarShehata** [comment]
I just ran into a dead link related to this:

https://cesiumjs.org/tutorials/Imagery-Layers-Tutorial/#imagery-providers

This links to:

https://cesiumjs.org/Cesium/Build/Documentation/TileMapServiceImageryProvider.html

Which doesn't exist yet, but it sounds like it will with this PR. Are we still planning on merging this @hpinkos  ?

**Comment by hpinkos** [comment]
@OmarShehata I would love to get this merged, but it's not really a priority.

`TileMapServiceImageryProvider` did exist a long time ago, then we made a bad decision and replaced it with the `createTileMapServiceImageryProvider` function, and I want to change it back so our API is more consistent.

For now, just change the doc to `createTileMapServiceImageryProvider`

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@mramato ready for review

**Comment by hpinkos** [comment]
Or @OmarShehata if you have a chance to review this first, please do =)

**Comment by mramato** [comment]
Looks good, I'll merge as soon as its green

**Comment by thw0rted** [comment]
I just noticed that this removed `create*ImageryProvider` but missed `createWorldImagery` and `createWorldTerrain`.  Was that intentional?

**Comment by mramato** [comment]
Yes, `createWorldImagery` and `createWorldTerrain` are helper functions that are a proxy to create whatever the default Cesium imagery/terrain are. They are not Imagery/Terrain providers in and of themselves.

**Pull request merged**
