### PR TITLE
Adjust value of ellipsoid._oneOverRadiiSquared

### PR DESCRIPTION
**Pull request by SunBlack**
I played a bit ellipsoid._oneOverRadii and ellipsoid._oneOverRadiiSquared and was wondering why I'm getting different results depend on which of both I use.

So I debugged a bit with Chrome and I got following results
```
Cesium.Ellipsoid.WGS84._oneOverRadii.x
1.567855942887398e-7
Cesium.Ellipsoid.WGS84._oneOverRadiiSquared.x
2.458172257647332e-14
Cesium.Ellipsoid.WGS84._oneOverRadii.x * Cesium.Ellipsoid.WGS84._oneOverRadii.x
2.4581722576473315e-14
Math.sqrt(Cesium.Ellipsoid.WGS84._oneOverRadiiSquared.x)
1.567855942887398e-7
Math.sqrt(Cesium.Ellipsoid.WGS84._oneOverRadii.x * Cesium.Ellipsoid.WGS84._oneOverRadii.x)
1.567855942887398e-7
```

How you can see I get different results if use _oneOverRadiiSquared or multiply _oneOverRadii with itself.
Maybe current value of _oneOverRadiiSquared has a bit more precision, because of just on division with a float as result and not multiplying two floats, but I think the different results can sometimes strange, if you don't know it.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for investigating, @SunBlack, but I'm a bit hesitant to make this change without a more precise understanding of the root cause.  How did you find this?  Was there a specific bug somewhere?

**Comment by SunBlack** [comment]
I was looking into `scaleToGeodeticSurface`. There you have following code:

```
var x2 = positionX * positionX * oneOverRadiiX * oneOverRadiiX;
var y2 = positionY * positionY * oneOverRadiiY * oneOverRadiiY;
var z2 = positionZ * positionZ * oneOverRadiiZ * oneOverRadiiZ;
```
Instead of using ´oneOverRadiiX * oneOverRadiiX` we could use `oneOverRadiiSquared` here

**Comment by pjcozzi** [comment]
> Instead of using oneOverRadiiX * oneOverRadiiX we could use oneOverRadiiSquared.x here and remove the parameter oneOverRadii. With this change result will be change a bit, but not really much.

Sounds like a an OK change, feel free to update in this branch.

**Comment by pjcozzi** [comment]
There are still test failures in CI: https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/226762677

Unless we can point to a specific bug that is affect users, we may just want to pass on this pull request.

**Comment by SunBlack** [comment]
Sorry, didn't saw theere are other test failing, too.

**Comment by pjcozzi** [comment]
Thanks for looking at the test failure, but given my comment above, https://github.com/AnalyticalGraphicsInc/cesium/pull/5236#issuecomment-300007266, let's pass on this and revisit if a bug comes up in practice.

**Comment by SunBlack** [comment]
Should I cherry pick 0773f1a?

**Comment by pjcozzi** [comment]
> Should I cherry pick 0773f1a?

OK, please make sure all the unit tests pass and spot check the Sandcastle examples.

**Pull request closed without merging**
