### PR TITLE
Fix 3D Tiles depth picking

### LINKED ISSUE #5676: pickPosition only works on 3D tiles if depthTestAgainstTerrain = true
This picking example only works if you uncomment the third line

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;
//scene.globe.depthTestAgainstTerrain = true;

var labelEntity = viewer.entities.add({
    label : {
        text: 'X',
        fillColor: Cesium.Color.RED,
        show: false,
        horizontalOrigin: Cesium.HorizontalOrigin.CENTER,
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM
    }
});

// Mouse over the globe to see the cartographic position
var handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(click) {
    var foundPosition = false;
    if (scene.mode !== Cesium.SceneMode.MORPHING) {
        var pickedObject = scene.pick(click.position);
        if (scene.pickPositionSupported && Cesium.defined(pickedObject)) {
            var cartesian = viewer.scene.pickPosition(click.position);

            if (Cesium.defined(cartesian)) {
                labelEntity.position = cartesian;
                foundPosition = true;
            }
        }
    }

    labelEntity.label.show = foundPosition;
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);

var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url : '../../../Specs/Data/Cesium3DTiles/Tilesets/Tileset'
}));

tileset.readyPromise.then(function() {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0.0, -0.5, boundingSphere.radius * 2));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
});
```

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #5676, #5731, and #5683.

* Fixes picking depth on 3D Tiles.
* Adds `classificationType` property to `GroundPrimitive` and `ClassificationPrimitive` which specifies whether to classify terrain, 3D Tiles, or both.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Looks OK to me at quick glance.  Just one request: can you add - or update - a Sandcastle example that shows the differences between the different enum types, e.g., a polyline going over only terrain, only a tileset, or both.

@lilleyse can you review and verify each issue this fixed, and merge when ready? Thanks!

**Comment by bagnell** [comment]
@lilleyse This is ready for another look.

**Comment by lilleyse** [comment]
Could the rectangle in the demo be smaller so it doesn't cover the entire tileset? Maybe just the blue area:

area

**Comment by bagnell** [comment]
@lilleyse This is ready.

**Comment by bagnell** [comment]
@lilleyse Updated after our offline discussion.

**Comment by lilleyse** [comment]
Works well now.

@pjcozzi instead of offsetting the depth plane we now just render the depth plane after the 3D Tiles pass. A tileset on the opposite side of the globe would probably not be rendered at all due to SSE. Can you think of possible edge cases?

**Comment by lilleyse** [comment]
I'm going to merge, but if anyone has issues with the approach we can go back to offsetting the depth plane.

**Comment by pjcozzi** [comment]
> @pjcozzi instead of offsetting the depth plane we now just render the depth plane after the 3D Tiles pass. A tileset on the opposite side of the globe would probably not be rendered at all due to SSE. Can you think of possible edge cases?

Doesn't this mean that most apps will need to enable `depthTestAgainstTerrain`?

**Comment by lilleyse** [comment]
They shouldn't need to. The main side effect with moving the depth plane after 3D Tiles classification was that tilesets might show through the opposite side of the globe when `depthTestAgainstTerrain` is false. But we figured that a tileset on the opposite side side would not get rendered at all because its root would either not be visible or would not meet SSE.

**Comment by pjcozzi** [comment]
Maybe this isn't a common case, but what if I have a label or a 3D model in drawn in the area of a 3D tileset, then I take a 45 degree horizon or top down view, wouldn't the depth values of the tileset be gone and the label/model would shown in front?

**Comment by lilleyse** [comment]
I'm pretty sure that case is fixed with https://github.com/AnalyticalGraphicsInc/cesium/pull/5789. Now the depth plane doesn't overwrite the 3D Tiles depth.

**Comment by pjcozzi** [comment]
OK, sounds good!

**Pull request merged**
