### PR TITLE
Fix morph crash

### LINKED ISSUE #5258: Crash when switching from 2D to 3D
Looking at this now in case it's an easy fix, if not we'll, @bagnell we need this for today's release, since it doesn't happen in 1.32

1. Run http://localhost:8080/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases
2. Switch to 2D.
3. Switch back to 3D and click to end morph early
4. Crash.

```
Uncaught DeveloperError: A PerspectiveFrustum or OrthographicFrustum is required in 3D and Columbus view
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at Camera.update (http://localhost:8080/Source/Scene/Camera.js:922:19)
    at http://localhost:8080/Source/Scene/SceneTransitioner.js:860:26
    at completeMorph (http://localhost:8080/Source/Scene/SceneTransitioner.js:271:17)
    at handleMouseDown (http://localhost:8080/Source/Core/ScreenSpaceEventHandler.js:167:13)
    at handlePointerDown (http://localhost:8080/Source/Core/ScreenSpaceEventHandler.js:609:13)
    at HTMLCanvasElement.listener (http://localhost:8080/Source/Core/ScreenSpaceEventHandler.js:68:13) (on line 922 of http://localhost:8080/Source/Scene/Camera.js)
```

The problem appears to be that completing am morph  early causes `camera.update` to be called while in 3D mode but with the incorrect frustum.

### PR DESCRIPTION
**Pull request by bagnell**
Fix morph from 2D to 3D when cancelled before the frustum changes. Fixes #5258.

### CODE REVIEW

**Comment by mramato** [comment]
There are some failing tests here, but I can confirm the bug is fixed.

**Comment by bagnell** [comment]
Morphing from Columbus view to 3D with a duration of 0 was broken causing the tests to fail. Fixed in 2400e7c.

**Comment by mramato** [comment]
Thanks @bagnell!

**Comment by pjcozzi** [comment]
Did this also fix #5197?

**Comment by bagnell** [comment]
Yes, I closed the issue.

**Pull request merged**
