### PR TITLE
Change to a modern method of constructing synthetic pointer events.

### LINKED ISSUE #4740: ScreenSpaceEventHandler and ScreenSpaceCameraController test broken with Chrome 55
Chrome 55 added support for PointerEvent, which is awesome; but it looks like it broke a bunch of our tests which were relying on the ability to create `PointerEvent` instances via `document.createEvent`.  I'm pretty sure `new PointerEvent` is the proper syntax, but not positive.

Here's one example of the failing tests (they all have the same root cause): 

http://localhost:8080/Specs/SpecRunner.html?spec=Core%2FScreenSpaceEventHandler%20handles%20mouse%20down%20LEFT_DOWN%20action

@emackey any thoughts here?

### PR DESCRIPTION
**Pull request by emackey**
This should fix #4740.

This fixes the problem for Chrome, and seems to work in Firefox.  I believe this works in Edge but I haven't had a chance yet to copy the fix to a Win 10 box.

Note that this PR will break the tests in IE 11, which were previously working.  The breakage looks the same as what Chrome 55 does in master now.  I don't think IE is going to be upgraded to the new way of constructing pointer events.

### CODE REVIEW

**Comment by mramato** [comment]
> Note that this PR will break the tests in IE 11, which were previously working.

Should we detect IE and use the old way instead?  Permanently breaking the tests on IE seems like a bad idea until IE usage is much lower.

**Comment by emackey** [comment]
That's an option.  I didn't look into it yet because I wasn't sure if IE was still officially supported by Cesium.  But I can look into it.

**Comment by emackey** [comment]
Done.  Someone should test Edge too before merging this, I'm not on a machine that has Edge.

**Comment by mramato** [comment]
Thanks @emackey.  Edge and IE are both passing (there are some unrelated failures that have been there forever but nothing major)  Chrome looks good to.

**Pull request merged**
