### PR TITLE
remove extra package.json files

### PR DESCRIPTION
**Pull request by mmacaula**
First step for #2981
Most of these files haven't been touched in over a year and even then have way incorrect version numbers.

### CODE REVIEW

**Comment by emackey** [comment]
Maybe these are leftovers from our ancient Dojo-based build @shunter?

**Comment by emackey** [comment]
They reference *.profile.js files, are those obsolete too?

**Comment by mramato** [comment]
@emackey they are definitely dojo related but I think they are required for people using a dojo-based build with our modules (so it may technically be considered a breaking change).  That being said, I don't know of anyone using the Dojo build system with Cesium and lots of people are using webpack and browserify, so I'm okay with getting rid of these.  However, I would also like to hear from @shunter first.

**Comment by shunter** [comment]
Yes, they are used by the Dojo build process.  That said, I don't know how much the state of affairs has changed in Dojo in the last few years, and whether they are still necessary.  We do still use the Dojo build system for NORAD Tracks Santa, but we can re-introduce these files there I suppose, since they aren't really very complicated.

Might be worth asking on the forums to see if anyone else would be affected.

**Comment by mramato** [comment]
> Might be worth asking on the forums to see if anyone else would be affected.

I was thinking the same thing, I'll post a question.

**Comment by mramato** [comment]
https://groups.google.com/d/msg/cesium-dev/h2dXMdjZACM/L61NcIT-BgAJ (I also tweeted out a link to the forum so we can get as much feedback as possible).

**Comment by mramato** [comment]
So almost every response we got from the forum and twitter was related to browserify or webpack.  No one mentioned Dojo so I think this PR is safe to take.  Though, as @emackey mentioned, we should also delete the corresponding *.profile.js files they reference as well.  @mmacaula delete those files as well and then we'll merge this.  Thanks for the change.

**Comment by mmacaula** [comment]
Done

**Comment by emackey** [comment]
Adios, old Dojo build.  Sorry, Santa.  Thanks, @mmacaula!

**Comment by emackey** [comment]
I also updated CHANGES.md in master.

**Pull request merged**
