### PR TITLE
Log developer errors to console

### PR DESCRIPTION
**Pull request by RacingTadpole**
I found I was not noticing Developer Errors being thrown, which made debugging harder. This makes them more obvious to developers.

### CODE REVIEW

**Comment by pjcozzi** [comment]
I suspect we won't want to always do a `console.log` here, but it might be OK since this is optimized out in release builds.  Whatever the other devs think is OK with me.

**Comment by kring** [comment]
My first reaction was negative too, but then the idea grew on me.  DeveloperErrors are only thrown in cases of API misuse, that's why we're able to remove them from release builds.  Meanwhile there are some scenarios, like with promises, where it's easy for an exception to be silently ignored.  Most of us who work on Cesium are good at using the debugger and have clean apps that only throw if something is broken, so we just run with the debugger set to stop on thrown exceptions and we're fine.  But some apps throw exceptions pretty spuriously (I'm looking at you jQuery) so it's painful to run this way.  And plenty of devs don't even know you can make the debugger stop on caught exceptions!  So in those cases, dumping something to the console is helpful, and I can't really think of any downside.

**Comment by hpinkos** [comment]
I like this too

@RacingTadpole can you merge in master?

**Comment by RacingTadpole** [comment]
Thanks - done!

**Comment by pjcozzi** [comment]
All good with me.

**Comment by mramato** [comment]
The only question I have is why not include the stack as well?  I would move the actual `console.error` to after the catch block and include the entire thing.  Otherwise, they may see a message like `foo is required` but have no idea where it's coming from.

**Comment by pjcozzi** [comment]
I was also thinking about including the stack.

**Comment by RacingTadpole** [comment]
In Chrome and Firefox (at least) I'm actually finding the stack is available anyway as a dropdown, eg:
image
can be opened out into:
image

Do you know if that's true for all browsers used in development? If so, adding the stack to the error message is probably unnecessary, as it takes up extra room and is not formatted as nicely (nor does it use the source map):
image

**Comment by emackey** [comment]
I'm glad there's a dropdown.  I think this is better without the manual stack dump.

**Comment by mramato** [comment]
So testing this out in Sandcastle with the following code:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.imageryLayers.addImageryProvider();
```

Here's what I get in Chrome, notice the same error appears 3 times.

image

It happens in IE 11 as well, (and the new message in IE  does not have the collapse feature nor does it include the stack at all).  I think this is because we are printing in the try/catch block instead of after.

image

So I assume one of those times is the browser itself, another is Sandcastle (it turns out master prints out 2 as well) and a third is this new message.

I'm totally on board with better and more obvious error reporting, but we should be careful not to introduce too much noise and figure out exactly what semantics are going on that's causing the triple printout above.

**Comment by mramato** [comment]
One final thought.  There are definitely places where we manually call `console.log` in order to provide information about an error, we should probably search for `console.log` and remove calls for cases where we are just dumping `DeveloperError`, since it will now do so itself.

**Comment by RacingTadpole** [comment]
Following up on your sandcastle tests, in the existing master code, it prints the error message twice to the browser console:
- from Sandcastle-client's `window.onerror`
- the second time is identified as from `ImageryLayerCollection.js:134` (I'm not exactly sure where this is really getting printed from, as in master the DeveloperError does not log anything yet).

With my changes, it printed it an extra time, because of the DeveloperError console.log, which is displayed after it has passed through Sandcastle-client's `console.error` extension.

So, I've introduced a check in Sandcastle's `window.onerror` to check if the error contains "DeveloperError:", and if so, not to print it to the console. I have introduced the same check into the Sandcastle `console.error` extension so that DeveloperErrors are not displayed in the sandcastle console panel. We thereby get back to the original behavior. I don't really like basing this on a text search, but the type of error doesn't seem to be available any other way. If you can think of a better way, please let me know.

I also followed your suggestion and moved the console.log outside the try/catch block; I hope that helps on IE11 - unfortunately I'm not set up to test IE11 easily.

Finally, I also searched through `Source` for `console.`s and couldn't see any that obviously printed out info that could be coming from a DeveloperError.

What do you think?

**Comment by pjcozzi** [comment]
Can we reach a consensus here or close this?  I don't have a strong opinion, but this is fine with me.

**Comment by pjcozzi** [comment]
Did we reach a consensus here or should this be closed?

**Comment by emackey** [comment]
I'm not a huge fan of this, sorry @RacingTadpole, I feel like it adds extra noise.  But I don't have a strong opinion, if others want to merge or close that's fine.

**Comment by hpinkos** [comment]
I agree with @emackey, so I'm going to close this out.  I asked about this during the code sprint and the response was mostly indifferent.

Thanks for submitting this though @RacingTadpole!  Sorry it took us so long to reach a decision.

**Comment by RacingTadpole** [comment]
No worries - thanks for considering it!

**Pull request closed without merging**
