### PR TITLE
Fix undefined 'quadDetails' Error

### PR DESCRIPTION
**Pull request by njrivera**
Fixes this issue https://github.com/AnalyticalGraphicsInc/cesium/issues/8003. There is another proposed fix on the issue, but I feel that increasing the size of the `traversalQuadsByLevel` array is a smaller change and seems to fix the issue with no apparent regressions.

I'm not sure if I need a unit test here since there is no new code, and I'm not exactly sure how to write a unit test for this fix.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @njrivera! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/njrivera/cesium/blob/master/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
> I completed a CLA way back, but i've recently changed my username for github. Should I just do another CLA?

Yeah I would go ahead and fill it out (it's now a google form so should be faster!) and maybe just edit the old username to be the new one in `contributors.md`?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @njrivera! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by jburr-nc** [comment]
Are you wanting our company to submit a new CLA each time a new contributor is added (or changed in this case)?

**Comment by OmarShehata** [comment]
That would work, but you can also just shoot an email to hello@cesium.com and we'll take care of those changes @jburr-nc .

**Comment by hpinkos** [comment]
@OmarShehata did we figure out the CLA situation for this PR?

**Comment by OmarShehata** [comment]
We just got the email, @njrivera is covered by Novetta's corporate CLA.

**Comment by hpinkos** [comment]
Thanks for the PR @njrivera!  I confirmed that `southwest.level` is `30` in the particular camera view from the sandcastle example provided in #8003, so this fix makes sense to me.

**Pull request merged**
