### PR TITLE
Video materials

### LINKED ISSUE #2484: Ability to adjust image material translucency
There's currently no way (at least in the Entity API, but it wasn't clear to me on the lower-level material either) to indicate whether an image material is translucent and what the alpha level should be.

[fourm post](https://groups.google.com/d/msg/cesium-dev/ep9gKuIsibg/8P0w59FeUToJ)

### PR DESCRIPTION
**Pull request by mramato**
After over 3 years of tinkering, I finally found an approach to video material that I'm happy with.

__Add support for Video elements to materials__
This extends the `Material` object to support `HTMLVideoElement`, similar to how we already support `Canvas`.  It also adds similar support to the Entity layer, via the `ImageMaterialProperty`.

__Add VideoSynchronizer__
By default, video materials just use the current video frame as the texture, so if you pause, seek, or otherwise change the video, the material is updated to match.  VideoSynchronizer is a helper class that flips this so that the video time is controlled by the simulation clock, allowing for you to synchronize the video with the rest of your scene.

__Ability to adjust image material translucency__
Fixes #2484 by adding an `alpha` uniform to material `Image` types, defualts to 1.0.  Also exposes the uniform in `ImageMaterialProperty.alpha`.

__Sandcastle__
Added a new Sandcastle example using a small webm video from Big Buck Bunny, an open
source blender movie project from a few years ago.

__Browser Support__
IE will most likely never support video textures, but they are being added to Edge.  Chrome and Firefox work great, I don't know about Safari since I don't have a mac handy.

__Sound__
Sound works as expected, even when playing faster or slower than normal.  Ultimately it's browser controlled and users determine whether to include sound or not directly on the video element.  Our Sandcastle demo has sound.

### CODE REVIEW

**Comment by mramato** [comment]
Just realized I forgot to add doc to the next objects, so I'll fix that soon.

**Comment by pjcozzi** [comment]
It's a non-issue to me, but this doesn't work in Safari:

image

No console errors.

**Comment by pjcozzi** [comment]
At quick glance, this is fine with me.  Anyone want to review it in more detail?

**Comment by mramato** [comment]
> this doesn't work in Safari:

So I completely forgot that the reason this doesn't work on Safari is because they don't support webm, which is the codec the demo video is using.  WebGL video textures themselves do work, and so would this demo with a different codec.  We could provide an equivalent `mp4` file but it's an extra 10 megs we probably don't want to add to the install. (The webm is only ~2)

Long term, a good solution for the demo would be to make our own short video that's a small filesize and available in at least 2 formats so that all browsers work (except IE 11) @emackey maybe a video project for a rainy day? :)

Otherwise I pushed the doc fixes I mentioned and a few tweeks to improve seeking.  I'm in no rush to merge this in case anyone else wants to take a look, but this is ready.

**Comment by shunter** [comment]
Why not upload the video files to cesiumjs.org somewhere and just link to them rather than including in the repository?  that way you can have both mp4 and webm versions.

**Comment by mramato** [comment]
> Why not upload the video files to cesiumjs.org somewhere and just link to them rather than including in the repository? that way you can have both mp4 and webm versions.

Good point, that thought did occur to me, but I wasn't sure how we felt about having demos that required you to be online.  I'll give it a try locally and see how it works.

**Comment by mramato** [comment]
After some experimentation, I think putting on cesiumjs.org will work well.  I have webm, mp4, and mov versions.  The mov is way bigger (10 megs) but I want to look into re-encoding it to a smaller size, it should be fine for now though since the mp4 and webm might be enough for all browsers.  I opened a separate PR for the website and submitted changes to use it to this branch already.

Edge doesn't work yet, but the Edge team is actively adding this feature so I expect it to work soon.  Can someone try Safari again?

**Comment by mramato** [comment]
I submitted fixes for tests that also use the website video (this way tests work on all supported browsers)  I think this is ready to go again.

**Comment by emackey** [comment]
@mramato you may want to consider squashing and force-pushing the git commits on this branch, so we don't end up with the webm video sitting in git history permanently.

**Comment by mramato** [comment]
Thanks @emackey, I squashed everything down to 2 commits (without the video).  1 commit for the alpha material issue and another for video support.

**Comment by pjcozzi** [comment]
Safari 8 on OS X 10.10:

image

**Comment by mramato** [comment]
Are you sure that's Safari 8, or is it Safari 9?  This is a [bug in Safari](http://krpano.com/ios/bugs/ios8-webgl-video-cors/) either way.  They don't support CORS video textures.  Edge has this same problem but they are [actively working on it](http://connect.microsoft.com/IE/feedbackdetail/view/967946/support-crossorigin-cors-for-drawing-video-to-canvas-both-2d-and-webgl)

The good news is this means that Safari will work when used with non-CORS video.

One option would be to have the demo put up a message box if it detects Safari or IE, but I'm open to other ideas.

**Comment by pjcozzi** [comment]
Yes, 8.

I'm OK with whatever for the the demo.

**Comment by mramato** [comment]
Okay, I updated the demo to put up the below friendlier message on error instead.

image

This is ready.

**Comment by pjcozzi** [comment]
Looks good.

**Comment by adwin5** [comment]
@malaretv @shunter @pjcozzi 
Thank you for the work!
I can use webm video as texture in Cesium. But it only work with using the example video:
[working webm](http://cesiumjs.org/videos/Sandcastle/big-buck-bunny_trailer.webm)
but not work with below two webm videos:
[not working webm example](http://video.webmfiles.org/elephants-dream.webm), [not working webm example2](http://video.webmfiles.org/big-buck-bunny_trailer.webm)

I want to know if there is any constraint for the webm video, for example size should be small, or certain width/height ratio.

I also tried to work with my local hosted videos and never succeed. 

Could you please give me some hints?

**Comment by adwin5** [comment]
```
(function(){

  var viewer = new Cesium.Viewer('cesiumContainer', {showRenderLoopErrors : false});
  var videoElement = document.getElementById('trailer');
  var sphere = viewer.entities.add({
      position : Cesium.Cartesian3.fromDegrees(-79, 39, 1000),
      ellipsoid : {
          radii : new Cesium.Cartesian3(1000, 1000, 1000),
          material : videoElement
      }
  });
  
  viewer.trackedEntity = sphere;

  var synchronizer;
  Sandcastle.addToggleButton('Clock synchronization', false, function(checked) {
      // By default, the video plays normally and simply shows
      // whatever frame the video is currently on.
      // We can synchronize the video with the scene clock
      // using a VideoSynchronizer.

      if (Cesium.defined(synchronizer)) {
          synchronizer = synchronizer.destroy();
          videoElement.playbackRate = 1.0;
          return;
      }

      synchronizer = new Cesium.VideoSynchronizer({
          clock : viewer.clock,
          element : videoElement
      });
  });

  // Since it's just an image material, we can modify the number
  // of times the video repeats in each direction..
  var isRepeating = true;
  Sandcastle.addToggleButton('Image Repeat', isRepeating, function(checked) {
      isRepeating = checked;
  });

  sphere.ellipsoid.material.repeat = new Cesium.CallbackProperty(function(time, result) {
      if (!Cesium.defined(result)) {
          result = new Cesium.Cartesian2();
      }
      if (isRepeating) {
          result.x = 8;
          result.y = 8;
      } else {
          result.x = 1;
          result.y = 1;
      }
      return result;
  }, false);

  // Like Image, the video element doesn't have to be part of the DOM or
  // otherwise on the screen to be used as a texture.
  Sandcastle.addToggleButton('Video Overlay', false, function(checked) {
      if (checked){
          videoElement.style.display = '';
      } else {
          videoElement.style.display = 'none';
      }
  });

  // Older browsers do not support WebGL video textures,
  // put up a friendly error message indicating such.
  viewer.scene.renderError.addEventListener(function() {
      if(!videoElement.paused){
          videoElement.pause();
      }
      viewer.cesiumWidget.showErrorPanel('This browser does not support cross-origin WebGL video textures.', '', '');
  });
}())
```

```
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Use correct character set. -->
  <meta charset="utf-8">
  <!-- Tell IE to use the latest, best version. -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Make the application on mobile take up the full browser screen and disable user scaling. -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
  <title>Video</title>
  <script src="../Build/Cesium/Cesium.js"></script>
  <script type="text/javascript" src="Sandcastle/Sandcastle-header.js"></script>
  <style>
    @import url(Sandcastle/templates/bucket.css);

    #trailer {
        position: absolute;
        bottom: 75px;
        right: 0;
        width: 540px;
        height: 360px;
    }
  </style>
</head>
<body>
  <div id="cesiumContainer" class="fullSize"></div>
  <div id="loadingOverlay"><h1>Loading...</h1></div>
  <div id="toolbar"></div>
  <video id="trailer" style="display: none;" autoplay="" loop="" crossorigin="" controls="">
    <!-- <source src="http://video.webmfiles.org/elephants-dream.webm" type="video/webm"> -->
    <!-- <source src="http://video.webmfiles.org/big-buck-bunny_trailer.webm" type="video/webm"> -->
    <!-- <source src="http://localhost:8000/small.webm" type="video/webm"> -->

    <source src="http://cesiumjs.org/videos/Sandcastle/big-buck-bunny_trailer.webm" type="video/webm">
    <!-- <source src="http://cesiumjs.org/videos/Sandcastle/big-buck-bunny_trailer.mp4" type="video/mp4"> -->
    <!-- <source src="http://cesiumjs.org/videos/Sandcastle/big-buck-bunny_trailer.mov" type="video/quicktime"> -->
    Your browser does not support the <code>video</code> element.
</video>
  <!-- 5 examples, uncomment one to test -->

  <!-- <script type="text/javascript" src="EarthNow/Example/basicExample.js"></script> -->
  <!-- <script type="text/javascript" src="EarthNow/Example/blackMarbleandLogo.js"></script> -->
  <!-- <script type="text/javascript" src="EarthNow/Example/polyganandEllipse.js"></script> -->
  <script type="text/javascript" src="JSExamples/video.js"></script>
  <!-- <script type="text/javascript" src="JSExamples/3dMovingFlightandToolbar.js"></script> -->
  <script>
  </script>
</body>
</html>

```

**Comment by hpinkos** [comment]
@adwin5 please ask your question on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
A lot more people see the forum so it is more likely you'll get a response from someone who can help.  We use GitHub for tracking bugs and planning new features.  Especially since this pull request is closed, people might not see your question.  Thanks!

**Pull request merged**
