### PR TITLE
Update ion tilesets to 3D Tiles 1.0

### LINKED ISSUE #6832: Every 3D Tiles Sandcastle example warns of deprecation
Every 3D Tiles Sandcastle example warns of deprecation.  This switches the focus to the console and makes Sandcastle hard to browse.  It will also be really confusing to our end users.

@ggetz @lilleyse what are the plans to address this before the next release?

### PR DESCRIPTION
**Pull request by lilleyse**
For #6697 
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/5504
Fixes #6832 

Not complete yet, but opening now to show that it's in progress.

To do:
* [X] St. Helens
* [X] Chappes
* [X] AGI HQ
* [x] Update NYC tileset
    * [ ] Figure out glTF Validator error (skipped for now)
* [x] San Miguel - @likangning93 has a glTF 2.0 version, but we need to fix shininess problems
* [x] Power Plant - we can't upgrade this one yet. It requires `KHR_techniques_webgl` and this PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/6805. But we'll be able to update right after that is merged.
* [x] AGI HQ is now positioned on Cesium terrain
    * [x] 3D Tiles Photogrammetry Classification - need to update classification tileset to align with AGI HQ. Edit transform. The classification tileset can probably live in `SampleData` instead of ion now.
    * [x] Classification - need to move classification geometries to align with AGI HQ
* [x] Point Cloud Classification - the geometry tileset needs content.url to content.uri update. Small enough to live in `SampleData` now.
* [x] 3D Tiles Terrain Classification - the vector tileset needs content.url to content.uri update

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/sandcastle-tilesets/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
@ggetz could you take a look at the AGI HQ, Point Cloud Classification, and 3D Tiles Terrain Classification ones?

The [upgrade](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/2.0-tools/tools#upgrade) command in 3d-tiles-tools should be working properly now, though manually editing the tileset.json for some of these may be quicker.

**Comment by ggetz** [comment]
@lilleyse Updated all the Classification examples.

**Comment by lilleyse** [comment]
Made some small edits to the new tilesets in https://github.com/AnalyticalGraphicsInc/cesium/pull/6862/commits/ad21f1fe271b21daceacdc99640b03b048f08a86.

Someone besides @ggetz and me should test and merge. @tfili, since you are doing the release?

**Comment by tfili** [comment]
Thanks @lilleyse

**Pull request merged**
