### PR TITLE
Fix for stray point in center of screen

### PR DESCRIPTION
**Pull request by sir-chaos**
A stray point appeared in the center of screen instead of discarding under some systems when there were points with show = false style.
This should fix the issue.
See https://github.com/AnalyticalGraphicsInc/cesium/issues/5598

### CODE REVIEW

**Comment by lilleyse** [comment]
Hm unfortunately I don't think this fix works on my end. It seems like my hardware does not allow point sizes smaller than 1.

```
var viewer = new Cesium.Viewer('cesiumContainer');

var scene = viewer.scene;
var tileset = scene.primitives.add(new Cesium.Cesium3DTileset({
    url : '../../../Specs/Data/Cesium3DTiles/PointCloud/PointCloudWithPerPointProperties/'
}));

tileset.readyPromise.then(function() {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0.0, -1.0, 50.0));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
}).otherwise(function(error) {
    throw(error);
});

tileset.style = new Cesium.Cesium3DTileStyle({
    pointSize : 5,
    show : '${POSITION}[0] > 0.0'
});
```

point_size

**Comment by lilleyse** [comment]
Just for testing, does substituting with code like:

`            vs += '    gl_Position.x += (1.0 - show) * 5.0; \n';`

work for you?

**Comment by sir-chaos** [comment]
Unfortunately I don't have access to workstation where the bug showed up at the moment (on my current system all works fine). If the suggesteed fix fails in your situation, maybe nullification for both gl_Position and gl_PointSize would help?

**Comment by lilleyse** [comment]
Yeah that approach sounds good.

**Comment by lilleyse** [comment]
I made the change here. Does that work on your end too?

Also please add yourself to `CONTRIBUTORS.md`.

**Comment by rjeli** [comment]
Thank you, this fixed it for me as well, had the point at center of screen and could not zoom. Now works perfectly. Chrome on Ubuntu with Nvidia card.

**Comment by mramato** [comment]
@lilleyse what's the status of this PR?

**Comment by lilleyse** [comment]
Should be ready to merge.

**Comment by pjcozzi** [comment]
@lilleyse please update CHANGES.md in master if you haven't already.

@sir-chaos can you please add yourself to [CONTRIBUTORS.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md) and send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) since this PR includes one of your commits?

**Comment by lilleyse** [comment]
Updated CHANGES.md here: https://github.com/AnalyticalGraphicsInc/cesium/commit/2d6a5cfc9e063ec7c9c32733f4e0d381fe15b735

**Pull request merged**
