### PR TITLE
Added support for multi-line labels

### PR DESCRIPTION
**Pull request by andre-nunes**
This is related to issue #2402, more info there. 

Don't merge yet as I need to add tests. Please review.

### CODE REVIEW

**Comment by mramato** [comment]
@andre-nunes is there a reason this is only showing up as one commit?  Was @abwood's change already handling everything that was needed?

**Comment by andre-nunes** [comment]
Yes, I found his commit and used it as a starting point, as it seemed to be working already I didn't make any changes, is that a problem?

It just needs testing.

**Comment by abwood** [comment]
Yes, I recall getting to the point of this working,  but it was quick and
dirty and needed testing. Maybe ScaleByDistance issues with labels were
holding me back from a PR. Ultimately, around the time of this branch I
inherited some new responsibilities and it quickly fell off my radar.

Alex

**Comment by mramato** [comment]
Because this is a common request, I would be okay with ScaleByDistance not working with it (and just writing up an issue for us to explore in the future).  @andre-nunes can you add tests (One option would be to look inside the generated billboards and verify the offsets are what you expect). and let us know when it's ready to look at.

**Comment by andre-nunes** [comment]
I'm sorry there hasn't been progress lately, I've been a bit busy with school.

I'm not sure how to calculate the expected offset by hand, I apologize but the math is a bit fuzzy on my side. I know ``pixelOffset`` is a ``Cartesian2`` and the y offset depends on the number of newlines, the issue here is: how do I calculate that without replicating the code I'm trying to test. Do you see my point?

Thanks

**Comment by pjcozzi** [comment]
If we want this to make 1.8, please merge this coming week.

**Comment by pjcozzi** [comment]
Last call for 1.8.  Up to you guys.

**Comment by andre-nunes** [comment]
@mramato , I just need some tips on how to write the tests and I'll get this done today

**Comment by mramato** [comment]
Since the LabelCollection creates a BillboardCollection under the hood, it might be easiest to just just reach into the `this._billboardCollection` object and iterate over the individual billboards, making sure the y value in the pixel offset is properly computed.  You'll want 2 tests, one that creates a multiline label without a `LabelCollection.pixelOffset` set and one that does it with an offset set.  Don't worry about the x values of the offset, just the y values.

**Comment by andre-nunes** [comment]
My silly question is: how do I compute the expected y without using the code I'm trying to test? Do you get what I mean? I'm probably missing something

**Comment by mramato** [comment]
While not normally good practice, I would make a simple 2 line string, something like `I\nI`, then visually inspect that it is correct in Sandcastle and then look at what the computed offsets are.  Then just code those values into the test directly.  Not perfect, but it will tell us when something breaks.

**Comment by andre-nunes** [comment]
Thanks, I wasn't sure if that was a valid way to get the expected Cartesian values for the offset. I'll get to it!

**Comment by andre-nunes** [comment]
I'm doing something wrong. Do I have to render the label during the test, how do I do that?

Right now the test looks something like this:
```javascript
it('computes pixelOffset correctly for multiline labels', function() {
        var label = labels.add({
            position : Cartesian3.fromDegrees(0,0,0),
            text : 'HELLO\nWORLD'
        });

       labels.update(context, frameState, []);

        for (var i = 0; i < labels._billboardCollection._billboards.length; ++i) {
            var billboard = labels._billboardCollection._billboards[i];
            expect(billboard.pixelOffset.y).toEqual(-30);
        }
    });
```

**Comment by pjcozzi** [comment]
What's left for this?

**Comment by andre-nunes** [comment]
I need help writing the tests, @mramato could you please take a look at my previous comment? 

Thanks!

**Comment by emackey** [comment]
This came up on [gis.stackexchange.com](http://gis.stackexchange.com/questions/160448/print-label-text-in-multiple-lines-in-cesium-js-api).

**Comment by mramato** [comment]
Closing this due to lack of movement.  I might work on this as part of the code sprint this week.

**Pull request closed without merging**
