### PR TITLE
Fix pickPosition called after sampleHeight

### LINKED ISSUE #7111: scene.clampToHeight breaks pickPosition
Clamping an entity position breaks `pickPosition`.

@lilleyse Any ideas?

[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=nVdtc+I2EP4rvnzBtJww73BJrs0Ld8lMcskEN51O6XQUW4AaWfJIMkmuw3/vyrKNbeCuLZMJRrv77K722ZW8xtJZU/JCpHPqcPLiXBBFkwg9pmtuI0h/XgiuMeVENlrO33PuwEcTKWHpXoo1DcH6Q24ZSII1+VVIFvpWx23O+aZ5POdrcKYCwgn4sk5R+jMTBUwEz1tR+hNEVki4pvot04yFopoK4z0mslgOscYzkciAgCCiyvjJorr4GrHLQoyYwKHbQKhd/J3FsWrPcBQzYvTaFwyeffFZioSHKADzRpqCjW3rSSEchu6O5ybSK8LdRcIDE2hJoZnvoM0IQtzKULpGAXRJ9PnbNcRo47+l7NmXSfCcBmGs61sAOBYQ5ZLjbNft3mjKiCIa1NItR7GkEaitswQsaIkA9qt36Vs7NwvafBLJimpfC/5AlA1+AamfKVCGuIfeqN+0Jhv4zuLICosjIjECRcOyHDkkSlOOTeQfKoFgqeEJ857b6XaGfa+HxuP+YDAedseDlvO+P+oNe4MR6k96vUGnN4G1vjfudCcTNOoMhpPxpD9ptqwPISls0q6PK4JDypf3VAerB8GY20fd8aTb7YwAaeyNx94QPHmoP5pMvJHX6Y8GXhf+Ws4QdUeT0XjSGY3G/V6v08tdER76EnO1EDLaNsct1pK+9tH15fSLf+3/VpSILhzXFiawxLsidLnSsySOBeQfFqzJ6ogoh+phlpbnBthMQlPH6Rryu6FKA5J0lYa9M/gbhzDohgwiEFwJZppg6Tb8FVXOkxQvCpo4FEQ5XGhHWb9OJRiUkm9jws157aQu3CK6tGeRWomEhWecRjAJgHFaJiSjraGiePqLBFr5YvoasCQ0Gr9b7v6RaWUUFUo/wD4CZXZSKxqrcJ2j5/QH1HqPmK56xCwhro0zSKQEUJ9GJG+rbWOiEtCeyri5uLWTT461KbbLxLXCPGREptWewXOAlYYiQGa+EOwJy/NEa0iocU9hCuboMHB3UzVwDD8RNs1HSNZZxfgwLV3al1QZWFhaSrd5JV5gdYGBHK1d0TkOnpfp/AMlU8OazgJOBZA0Ov341YkEFyrGAWnUtFbQdF/N+cHuJF1Svm2Gq5oE3Uw/+TXrNdSNBru2j5V15N/d1wxj+krY3WJhZt7+edJ1OzArvObWblOqm31st51bkUDrCAjEgZHuLJl4Io4WjiIkXQgATywljlc0KMpmrbOSV0/WGRyQhM/MVqWUvrJKefdjIIvKGZQBmFF5zeNEn1kiFIyIIKwIMFJmVNtgYep2v6VwWuTjutaB0zhX2U6lSECfvjs93WYBq7ewiG7vHu6vrr98btbZtTWOgdF5KLsTrVJucw3IC1SLqwJTpA6cL9JsVvIrx5FFHZIF3GJCt3DR3BtFOZKitKdlAuWr6ZlXMKqEe3wYlQm+pBrmxAzOAr7cAsPhsEJaXJIlMES5Ze+oMIKLhfgE3A7d7jedwCH3n31kNv/SxcqeULmDCpSVVXH2I5XmWHniFjt5/H2z9Bmlw6xy1nzfRpNXuBHt1zafxo25KDScHx23YX7CQ616TaQYDYj7ftQEYWM+Tzzv3APFb4DO5/wG6zpupWD/E/aM1WHLRaqBRo1/VRS7U+SNZMP09MDlzEMeTFPz7/0eKjg/VCbJ6b5JMruYfpl2L52fnA4awNDuIK95mDj1AXeg8Jvq0qYy7auT7l0FcmcyHKRcPlrrx0jr0Mj332IzN3+ZTf+8vXucNvOb+lHr6ETpN0Y+WoSfaZTewuDC7cIriibwdgI3KtV+gjcBuAMGKj0pTtq50UlI1w4NT+dHtfe2+ZG5yikFkkXC2Ix+JfOjjydt0K+YmfciYModnHYMvxmVVefjjV1ECJ204eeulbYXmBLiPw)

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #7111 

If the previous pass was a `sampleHeight` call the state would be wrong for the `pickPosition` call. This resets `frameState` and `uniformState` in `pickPosition`.

Specifically `SceneTransforms.drawingBufferToWgs84Coordinates` requires log depth and inverse view projection to be correct.

Slightly modified demo as #711 I used for testing: [localhost:8080 link](http://localhost:8080/Apps/Sandcastle/index.html#c=nVdpb+M2EP0r2nyxjHrpS742B5rDuwkQr4NYTVHURcFItM2GIgWS8ia7yH/vULdkO9nWMGCJc73hvBnSWyytLSXfiLROLU6+WZdE0ShAD/Ga3fDi10vBNaacyEbL+rHkFnw0kRKW7qTYUh+sP2WWniRYk9+FZL6b6NjNJX9tHi/5FoIpj3ACsZKgKH5NRR4T3lMhil9BlAgJ11S/pJqhUFRTYaKHRObLPtZ4ISLpERAEVJk4KarL7wG7ysWICezbDYTa+fc8DFV7gYOQEaPXvmTw7IovUkTcRx6YN+IUEmxFJIWw79s7kZtIbwi3VxH3DNCSQjPbwSQjgFjIULxGwema6IuXG8CY4J9R9uTKyHuKQRjr+haAn8QhyiTH6a4ne6MpI4poUIu3HIWSBqC2TRNInJYIkPz0r9zEzk5Bm08kWV7tG8HviUrAryD1cwXKgHvYGTnNxOQVflMcaWFxQCRGoGhYlnn2idKUY4P8UwUIlhqeMO/b3V536HT6aDx2BoPxsDcetKyPzqg/7A9GyJn0+4NufwJrTmfc7U0maNQdDCfjiTNptpIYQlLYpN0Y1wT7lK/vqPY294Ix20G98aTX647A07gzHneGEKmDnNFk0hl1us5o0OnBt2UNUW80GY0n3dFo7PT73X4WinDflZirlZBB0RwzrCV9dtDN1fSre+P+kZdoyTOqQBsA8+ycJqZ44vEf4mnliumzxyLf8PrPpNp/HRdaWeFBWmeH4dMDZhGx465CXiQlOHBpQDJC1diTE8VLGuGa0PVG25m4tYPJ+HmtJKI0lK5IJImsNiJi/jmnAUwJCKJlRFIEKTGF0vewe0AUIOZ0C7huqdIgknaMJQ9kct5g7jMi4z1cwLOHlWbEWLpCsEcsLyKtof8acT9bWlibOBEYZHlv5ghTwEXjvOlxoUWYFOsdt/sTX2GmDmYuSSC25FDyPwHujsIozYq1F5XZPYYfCZtmcyhtz3wGmblQavtYGahcWoqxb8Q3WI3Tae2KLrD3tI6HKCiZYtd0VnC0gKTRdcJnKxBcqBB7pFHT2kDnfjeHEJtLuqa86KjrmgTdTj+7NesttAD1dm0fKuvoYu6681nNNqTPhM1XKzM798+lnt2FmdNpFnav2eCL62Qe221rJiI4kKCqMIs3xFoz8UgMcRQh8YIH/sRa4nBDvbxyiXVK8uoJvYCDlvCF2a2YJ9eJkp12LYb2UFlvpw7MyL3hYaTPEy7kpDBkC8BHTI4iD0ORlSndXTEUMtpWtQ6c6pkKXVkprkDA9PpwelpkAaszWESz+f3d9c3XL806wQrjEEidQVlEYSigAv6OfobJywpUw1Vxk6cOtM/TbFbyK+NIUftkBbch385DNPeiKCPJS3taJlC2Gp+dOaNKfo8Pe2WCr6mGybuAM4WvC8dwyGyQFldkDQxRdjk6yo3ggiI+A7d9u/dmEDgs/3OM1OYnQySTMw9QcZXIqn72eyqNsvIZlu/k8ftm8TOK51nlXHrfRpNnuFnt1zafxq25cDSsXyy7YV7hoVa9JlKMesT+OGqCsLFcRp3ORQcU33C6XPJbrOt+KwX7n27PWd1tuUg1p0HjYFHqw+ONTW23PcGVYOZuvrb3b/E+Fr1Wl14rU7g6gT5U4Ox07EEqlE/q8nhvHRrF7kto5tlvi+nfs/nDND+zj1pHJ0q/MHKWePiVBmaGmQu1DX9BNIF/H3A5UO1HuOkTjTwVT/CTdmZ04tOtRf3T5VHtf9nyyNxElALJKmJsQb+T5dHZSRv0K2bmfw9UcA6nEMMvRmXTPbtNFhFCJ2143bXSyd2i5PFf)

* [x] Still need to do more testing and write a unit test.
* [ ] I wonder now if `pickTranslucentDepth` really requires a manual `scene.render` call. It should be able to do something similar to this I think.
* [x] `CHANGES.md`

### CODE REVIEW

**Comment by lilleyse** [comment]
Updated. @bagnell could you review?

**Comment by lilleyse** [comment]
Also @ggetz can you test this in the demo where you first ran into this problem?

**Comment by ggetz** [comment]
I'm still having problems picking when zoomed in close to the entity in [this example](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fix-pick-position/Build/Apps/Sandcastle/index.html#c=nVdtb9s2EP4rar5Y3lxa8rubuFte3CZA0gSxlmGYh4GWaJsLRQok5SQd/N931Jsl2W63GUEr8e6eu+M9d6Q2WFobSl6ItCYWJy/WJVE0DtFTsmY3/OT1UnCNKSey0bL+nnMLfppICUsPUmxoANYfcktfEqzJr0KywEt17Oacb5unc74BZ8onnICv1ClKXjORz4T/vBMlryBKhYRrqt8yzUgoqqkw3iMii+UAazwTsfQJCEKqjJ8sqsuvIbsqxIgJHNgNhNrF33kUqfYMhxEjRq99yeDZE5+liHmAfDBvJCmkse08KYSDwN7z3ER6Tbi9jLlvAi0pNPMdTDOCEHcylKxRAF0RffF2AzGm8d9R9uzJ2H9OgjDW9S0AnBQQ5ZLTbNfTvdGUEUU0qCVbjiJJQ1DbZAmkoCUCpP91r7zUzs6CNr9YsqLaN4I/EpUGv4TUzxUoQ9wDZ9hrtnY2AVnEq0vBhKRfSYIJjNEyJqnKFiiSxZoVH4dEYgRghom594AoTTk22X2oBIulhifMu7bbcQc9p4tGo16/Pxp0Rv2W9b437A66/SHqjbvdvtsdw1rPGbmd8RgN3f5gPBr3xnm0ECFs5L6Pa4IDylcPVPvrR8GY3UOd0bjTcYeANHJGI2cAnhzUG47HztBxe8O+04G/ljVAneF4OBq7w+Go1+263dwV4YEnMVdLIcNdA91hLelrD91cTb94N95vRRnp0rLT4vkpOa8JXa31LI4iAfkHBbOyWiPKocKYJdt9C4wngan1dAP53VKlAUnaSsPeGfytRRh0TAbhC64EM42yshvemiprIcWLgkYPBNSOC22p1K9VCQYlBN2acHPuW4kLu4gu6Wuk1iJmwTmnIUwLYKXhQkZtQ1ex+Iv4Wnli+uqzODAav6f8/iPTymgslH6EfQTK7KVWNF/hOkfPWwRQ631kOu8Js5jYaZx+LCWAejQkeevtmheVgA5Uxs7Frb18cqxtsV0mrjXmASMyqfYMnn2sNBQBMvOEYAssL2KtIaHGA4VJmaPDUN5P1cAxvCBsmo+ZrLOKEWPavrQviTKwsLSUbPNavMDqEgM5WvuiC+w/r5IZmfVzTWcJJwdIGm4verVCwYWKsE8aNa21GQvmjGH3kq4o3zXDdU2CbqefvJr1BupG/X3bp8o68u4faoYRfSXsfrk0c/HwPOnYLswKp7mz25bqlj6229adiKF1BARiwdi3VkwsiKWFpQhJFnzAEyuJozX1i7Kl1lnJq6fvDA5RwmdmqxJKX6dKefdjIIvKGZQBmFF5w6NYn6dEKBgRQlghYCTMqLbB0tTtYUfhpMinda0jJ3ausptKoYA+fTeZ7LKA1TtYRHf3jw/XN18+N+vs2hlHwOg8lP2JVim3uSrkBarFVYEpUgfOF2k2K/mV48iiDsgSbjqBXbhoHoyiHElR2kmZQPlqci4WjCrhnh5HZYKvqIY5MYOzgK92wHA4rJEWV2QFDFF22TsqjODyIT4BtwO7800ncMj9Zx+Zzb90sU5PqNxBBSqVVXEOI5XmWHniFjt5+n2z5Bklw6xy1nzfRpNXuDUd1ja/xq25KDSsHy27YV7hoVa9JlKM+sR+P2yCsDGfx45z4YDiN0Dnc36LdR23UrD/CXvO6rDlItVAw8a/Kkq6U+SNZMN0cuRy5iAHpqn55/0BKlg/VCbJ5NAkmV1Ov0w7V9ZPlov6MLRd5DSPE6c+4I4Ufltd2lamfXXSvatA7k2Go5TLR2v9GGkdG/neW2Tm5i+z6Z9390/TZn6bP2mdnCn9xsjHFOFnGia3MLiU2/AZowl8wcCNSrUX8LUAd0BfJSfFWTs3OgvoxqLBZH5S+7abn5irnFIgWcaMzeCiPj/5eNYG/YqZ+XYCptzDacfwm1FZux9v00WE0FkbXvetdHqBKSH+Aw)

When the camera is close to the entity, it doesn't work at all. At a medium zoom level, it works at positions that are far enough from the camera. It works fine when the camera is zoomed out far enough. Could it be a picking frustum issue?

**Comment by lilleyse** [comment]
That might be a different problem related to the label offsets. I see it too when `clampToHeight` isn't called. With a few label tweaks it seems to work better:

[Modified example](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fix-pick-position/Build/Apps/Sandcastle/index.html#c=nVdtc+I2EP4rvnzBtJww73AJ1+aFu2QmHJngptMpnY6wBaiRJY8kk+Q6/Peu/IZt4K4tk7mztbvP7mqfXclbLK0tJS9EWmOLkxfrmigaBegpXrNrXvx6LbjGlBNZa1h/L7gFP02khKUHKbbUB+sPmaUnCdbkVyGZ7yY6dn3Bd/XzBd+CM+URTsBX4hTFr6nIY8J73oviVxAlQsI11W+pZigU1VQY7yGR+bKPNZ6LSHoEBAFVxk8a1fXXgN3kYsQE9u0aQs387zIMVXOOg5ARo9e8ZvDsis9SRNxHHpjX4hSS2PaeFMK+bx94riO9IdxeRdwzgRYU6tkOJhlBiHsZitcogK6Jvnq7gxiT+KeUPbsy8p7jIIx1dQsAJwFEmeQ83fVkbzRlRBENavGWo1DSANS2aQIJaIEAyX+dGzexs9OgzS+SLK/2neCPRCXBryD1SwXKEHffGXTrjb2NT5bR+lowIelXEmMCY7SMSKKyA4qksabFxwGRGAGYYWLm3SdKU45Ndh9KwWKp4Qnzjt1qt/pdp4OGw26vN+y3h72G9b476PQ7vQHqjjqdXqszgrWuM2y1RyM0aPX6o+GoO8qihQhhIw993BLsU75+oNrbPArG7C5qD0ftdmsASENnOHT64MlB3cFo5AycVnfQc9rw17D6qD0YDYaj1mAw7HY6rU7minDflZirlZDBvoGmWEv62kV3N5Mv7p37W15GurLspHheQs5bQtcbPY/CUED+fs6stNaIcqgwZvF23wPjiW9qPdlCfvdUaUCSttKwdwZ/ZxEGHZNCeIIrwUyjrO2au6HKWkrxoqDRfQG140JbKvFrlYJBMUF3JtyM+1bsws6ji/saqY2ImH/JaQDTAlhpuJBS29BVLP8inlaumLx6LPKNxu8Jv/9ItVIaC6UfYR+BMgep5c2Xu87QsxYB1Gofmc57wiwidhKnF0kJoC4NSNZ6++ZFBaAjlbEzceMgnwxrl2+XiWuDuc+IjKs9h2cPKw1FgMxcIdgSy6tIa0io9kBhUmboMJQPUzVwDC8Jm2RjJu2sfMSYti/sS6wMLCwsxdu8ES+wusJAjsah6Ap7z+t4Rqb9XNFZwckBklqrG75ageBChdgjtYrWxowFc8awmaRryvfNcFuRoPvJJ7divYW6Ue/Q9qm0jq5mrjubVmxD+krYbLUyo/H4SGnbLRgXTn1vtyuULnlsNq2piKB7BMRiweS31kwsiaWFpQiJFzzAE2uJww318sol1mnVywfwHM5Rwudmt2JW3yZK2QDAwBeVkSgFMNPyjoeRvky4kJMigLACwIjJUe6ElSndw57FcZ3Pq1onDu1MZT+YAgGt+m483mcBq1NYRNPZ48Pt3ZfP9SrB9sYhkDoL5XColSpubgtZgSpxlWDy1IH2eZr1Un7FONKofbKCy45v5y7qR6MoRpKXdlwkULYaH405owq456dRmeBrqmFUzOE44Os9MJwPG6TFDVkDQ5Rd9I5yI7h/iE/Abd9uf9MJnHP/2Udq8y9dbJJDKnNQgkpkZZzjSIVRVhy6+U6ef98sfkbxPCsdN9+30eQVLk7Htc2vdm/uCjXrR8uumVd4qFSvjhSjHrHfD+ogrC0WkeNcOaD4DdDFgt9jXcUtFex/wl6yKmyxSBXQoHayKM3m4V6RN5KO0/GJG5qDHJin5p/3R8hg/VCaJeNjs2R+Pfkyad9YP1kt1IOx3UJO/TR1qiPuROl35aVdad6XZ927EuTBbDhJumy4Vg+Sxqmh776FZnL+Mp/8OZ09TerZlf6scXah9BsjHxOEn2kQX8XgZm7Dt4wm8BkD1yrVXMInA1wEPRWfFRfNzOjCp1uL+uPFWeUDb3Fm7nNKgWQVMTaH2/ri7ONFE/RLZuYDCrgyg/OO4Tejsml9vE8WEUIXTXg9tNLJLaaA+A8)

**Comment by ggetz** [comment]
@lilleyse Got it. I'm not running into any other picking problems here, and this also resolves the issue with the original tileset I saw. Thanks!

**Comment by lilleyse** [comment]
Merged in master. @bagnell could you review?

**Pull request merged**
