### PR TITLE
Camera improvement when moving to a rectangle which crosses the antimeridian

### PR DESCRIPTION
**Pull request by michaelhayes-dev**
- Previously, if a user attempted to call camera.setView({ destination: rectangle }) or camera.flyTo({ destination: rectangle }) in the Cesium 2D View with a rectangle that crossed over the International Date Line, the camera would zoom out to show the entire map often making it difficult to see what the user intended the camera to zoom to.
- This has been resolved, and in the Cesium 2D View, flyTo and setView will now work as intended.

Discussed in Issue #6936 
Discussed in [this Cesium forum post](https://groups.google.com/forum/#!msg/cesium-dev/p5ygxIQA490/mbAYcjUlBgAJ)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @michaelhayes-dev!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fly-to-antimeridian/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by michaelhayes-dev** [comment]
CLA has been sent in

**Comment by michaelhayes-dev** [comment]
Re-ran the tests on my machine and I reproduced the same error Travis threw, but I also got that error on my unmodified master branch too. It appears to be an issue with some of the node_modules; I will investigate further this evening.

**Comment by pjcozzi** [comment]
Thanks again for contributing, @michaelhayes-dev!  We received your CLA.

**Comment by michaelhayes-dev** [comment]
Not sure if this was lost amidst everything else, but this is ready to be merged!

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @michaelhayes-dev! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
Thanks for the contribution @michaelhayes-dev ! @hpinkos are you the best person to look at this? Seems like a straightforward PR for an issue multiple users have reported.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @michaelhayes-dev! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks for the pull request @michaelhayes-dev!  This fix is great.  I'll merge this as soon as CI passes

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!msg/cesium-dev/p5ygxIQA490/mbAYcjUlBgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/7909 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Pull request merged**
