### PR TITLE
GML simple features profile 

### PR DESCRIPTION
**Pull request by ayk115**
This is a pull request for GML simple features profile support. Note that this is not complete. It may also be unstable. I am working on it with Kevin.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @ayk115 and @kring.

Can you please add a TODO with checkboxes to this pull request so we know what is left?

**Comment by ayk115** [comment]
@pjcozzi 

# TODO
- [ ] Display metadata information when a feature is clicked.
- [ ] Curve segments integration.
- [ ] Exhaustive testing.
- [ ] Unit tests.
- [ ] Documentation.

**Comment by pjcozzi** [comment]
What's the latest here?  Are we in good shape for finishing this for GSoC?

**Comment by sushrut141** [comment]
Hey,
I'm interested in continuing this work and addding WFS support in Cesium.
Could someone let me know what needs fixing here?

**Comment by kring** [comment]
@sushrut141 The TODO list above summarizes it pretty well.  I'd probably start by merging in master.

**Comment by ezze** [comment]
Do you still plan, guys, to add GML support?

**Comment by pjcozzi** [comment]
@ezze we would like to at some point, but it is not a priority for the core team right now.  In the meantime, perhaps conversion to CZML, KML, or GeoJSON may be a reasonable approach.

**Comment by hpinkos** [comment]
Thanks for the initial work on this @ayk115!  I've parked the changes on this branch so someone can pick it up in the future: https://github.com/AnalyticalGraphicsInc/cesium/tree/gml

**Comment by ruimaciel** [comment]
Over a year has passed since the last update.  Does anyone know if any progress was made in adding support for GML and WFS?

**Comment by hpinkos** [comment]
@ruimaciel this isn't a priority for our team right now, so I don't think we'll pick it back up any time soon.  However, we would be more than happy to review a pull request if you have time to finish up the work started in this branch! https://github.com/AnalyticalGraphicsInc/cesium/tree/gml

**Pull request closed without merging**
