### PR TITLE
Update all npm packages to latest versions.

### LINKED ISSUE #7536: Un-pin version changes for eslint
Once https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/113 is fixed, undo pinned version changes in `package.json` from https://github.com/AnalyticalGraphicsInc/cesium/pull/7535.

### PR DESCRIPTION
**Pull request by mramato**
Closes #7536 and also updates some other packages greenkeeper recently reminded us about.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/npm-updates/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@ggetz since you found the original eslint issue, I figured you were a good person to review this.

**Comment by mramato** [comment]
Bump.  Please get this merged ASAP.

**Comment by hpinkos** [comment]
👍 thanks!

**Pull request merged**
