### PR TITLE
Image optimizations

### PR DESCRIPTION
**Pull request by danielwhatmuff**
- This was done using [pngquant](https://github.com/kornelski/pngquant) with command `find . -iname '*.png' | xargs pngquant --quality=80-100 --skip-if-larger -f --ext .png`
- Sizes reduced significantly for performance
- Rich diffs below show the before and after images (should be no noticeable reduction in quality)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @danielwhatmuff!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/image-optimizations/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by danielwhatmuff** [comment]
Awaiting approval to sign the Corporate CLA.

**Comment by OmarShehata** [comment]
Thanks @danielwhatmuff ! I'm all for anything to trim down the library size. At a quick glance the diffs look unnoticeable.

Have you measured any performance difference in your app after optimizing these images? That might be useful to share here.

**Comment by shunter** [comment]
We probably shouldn't change files that come from third party sources.

**Comment by hpinkos** [comment]
Thanks for the PR @danielwhatmuff, but I don't think this is one we want to take.

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @danielwhatmuff! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request closed without merging**
