### PR TITLE
fixed reversing non alphabetic characters on RTL labels

### PR DESCRIPTION
**Pull request by hodbauer**
fixing issue [#7501](https://github.com/AnalyticalGraphicsInc/cesium/issues/7501)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hodbauer!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for opening the pull request @hodbauer!

@mramato can you review this?

**Comment by hodbauer** [comment]
amm @hpinkos , how could I remove all the mess that I done about the last push?

**Comment by hpinkos** [comment]
@hodbauer I was able to fix it by merging in master again.

```
git checkout master
git remote add public-cesium https://github.com/AnalyticalGraphicsInc/cesium.git
git fetch public-cesium
git merge --ff-only public-cesium/master
git checkout fix-rtl-label
git merge master
git remote rm public-cesium
git push
```

**Comment by hodbauer** [comment]
@hpinkos any news?

**Comment by hpinkos** [comment]
Sorry for the delay on this!  Everything looks good.  Thanks for the fix =)

**Pull request merged**
