### PR TITLE
Fix model crash by adding default pbr material

### LINKED ISSUE #6891: Cesium no longer adds a default material for gltf 2.0 as needed
See attached. This is a gltf 2.0 containing a `primitive` that doesn't have an assigned material.
Cesium 1.47 handled this [according to spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#default-material) and assigned a default material, but 1.48 crashes instead.

[CUBE.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2266741/CUBE.zip)

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #6891 

Like https://github.com/AnalyticalGraphicsInc/cesium/pull/6857#discussion_r206158454, this fix is temporary until #6805 is in.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/default-material-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@lilleyse do you think #6805 will make it in this release?  I don't think we should merge this workaround if we're going to have the actual solution ready to go shortly

**Comment by lilleyse** [comment]
Fine by me, #6805 should made the release.

**Comment by lilleyse** [comment]
It's looking like https://github.com/AnalyticalGraphicsInc/cesium/pull/6805 won't make the release so I reopened this PR.

**Comment by hpinkos** [comment]
I'm still not convinced we should rush to get this workaround in for the release since we have the actual fix coming soon.  Was this issue a common problem that a number of our users are experiencing?

**Comment by lilleyse** [comment]
It has been brought up twice
* https://github.com/AnalyticalGraphicsInc/cesium/issues/6940
* https://github.com/AnalyticalGraphicsInc/cesium/issues/6891

**Comment by hpinkos** [comment]
Okay, that's significant

**Comment by hpinkos** [comment]
Who should review this? @likangning93?

**Comment by lilleyse** [comment]
I think @ggetz has more familiarity with the gltf-pipeline code and would be better to review this.

**Comment by ggetz** [comment]
Since `Source/ThirdParty/GltfPipeline/addDefaults.js` will be overridden by the rebuilt `GltfPipeline` files, I think this fix will be fine temporarily.

**Comment by ggetz** [comment]
Code looks good and the model  from https://github.com/AnalyticalGraphicsInc/cesium/issues/6891 loads correctly.

**Comment by hpinkos** [comment]
@lilleyse open an issue or add a comment to #6805 to revert this workaround when the actual fix comes in.

**Comment by ggetz** [comment]
#6805 completely rebuilds the files in `GltfPipeline` from the new `master` (as opposed to a previous branch just fro cesium) so this fix will already be overridden.

**Pull request merged**
