### PR TITLE
Fix imagery request render

### LINKED ISSUE #6193: Imagery stops loading when changing terrain in request render mode
image

Easiest way to reproduce
- Zoom in close to the ground and hit the `Disable terrain` button until the imagery stops loading in  (usually 2-5 clicks)
- Hit the `Enable terrain` button
- Now the imagery never loads in, even after the camera moves

I wasn't able to reproduce this when `requestRenderMode: false`, so it seems to be related to those changes.
It seems like it might be related to changing the terrain before all imagery tiles are loaded, but I'm not sure.

``` js
var viewer = new Cesium.Viewer('cesiumContainer', {
    requestRenderMode : true,
    animation: false,
    timeline: false
});

var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles',
    requestWaterMask : true,
    requestVertexNormals : true
});
viewer.terrainProvider = cesiumTerrainProviderMeshes;

Sandcastle.addToolbarButton('Enable terrain', function() {
    viewer.terrainProvider = new Cesium.CesiumTerrainProvider({
        url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles',
        requestWaterMask : true,
        requestVertexNormals : true
    });
    viewer.scene.requestRender();
});

Sandcastle.addToolbarButton('Disable terrain', function() {
    viewer.terrainProvider = new Cesium.EllipsoidTerrainProvider();
    viewer.scene.requestRender();
});
```

### PR DESCRIPTION
**Pull request by ggetz**
Fixes #6193

`invalidateAllTiles` was not being called reliably at the correct time.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@ggetz, thanks for the pull request! Maintainers, we have a signed CLA from @ggetz, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@ggetz I'm seeing a crash if I alternate between `Enable terrain` and `Disable terrain` in the example I pasted in #6193

```
DeveloperError: requestTileGeometry must not be called before the terrain provider is ready.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:43:19)
    at CesiumTerrainProvider.requestTileGeometry (http://localhost:8080/Source/Core/CesiumTerrainProvider.js:569:19)
    at doRequest (http://localhost:8080/Source/Scene/TileTerrain.js:149:48)
    at requestTileGeometry (http://localhost:8080/Source/Scene/TileTerrain.js:163:9)
    at TileTerrain.processLoadStateMachine (http://localhost:8080/Source/Scene/TileTerrain.js:97:13)
    at processTerrainStateMachine (http://localhost:8080/Source/Scene/GlobeSurfaceTile.js:384:20)
    at Function.GlobeSurfaceTile.processStateMachine (http://localhost:8080/Source/Scene/GlobeSurfaceTile.js:281:13)
    at GlobeSurfaceTileProvider.loadTile (http://localhost:8080/Source/Scene/GlobeSurfaceTileProvider.js:505:26)
    at processSinglePriorityLoadQueue (http://localhost:8080/Source/Scene/QuadtreePrimitive.js:768:26)
    at processTileLoadQueue (http://localhost:8080/Source/Scene/QuadtreePrimitive.js:759:9)
```

**Comment by hpinkos** [comment]
I'm also still seeing a problem where sometimes the tiles don't load in if I zoom in and click the `Disable terrain` button.  The tiles start loading when I move the camera.

**Comment by mramato** [comment]
Just a reminder not to forget about this for next release, I've hit it several times today.

**Comment by ggetz** [comment]
@hpinkos I believe this is resolved. I moved the invalidate logic to right before we process the tile load queue. I am no longer seeing any errors when switching back and forth, and repeatedly clicking disable terrain always reload the globe.

**Comment by mramato** [comment]
@ggetz, not sure if this is the same bug but I still see this in this branch:

1. Start Cesium Viewer: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fix-imagery-requestRender/Build/Apps/CesiumViewer/index.html
2. Switch to Ellipsoid via Base Layer Picker (nothing will update until you move the mouse)

**Comment by ggetz** [comment]
@mramato That's a regression because of the changes here. Fixed and added a new spec. @hpinkos in your sample code, you should no longer need to request a render after setting the terrain provider.

**Comment by hpinkos** [comment]
@ggetz I'm still seeing issues here.  If I double click the `Disable terrain` button, I can still get a globe with no tiles.  It doesn't happen as consistently, but I can still reproduce it within a few tries.

**Comment by ggetz** [comment]
@hpinkos I don't think I can reproduce.

The first time I hit `disable terrain`, it takes a second or two for the new terrain provider to load in, but will re-render without mouse input. That's the same behavior as when we are not in requestRender mode.

If you comment out 
`viewer.terrainProvider = cesiumTerrainProviderMeshes;` in your example, `disbaleTerrain` doesn't cause that initial delay since it was initially loaded with the `EllipsoidTerrainProvider`

**Comment by hpinkos** [comment]
@ggetz I can show you when you're in the office

**Comment by hpinkos** [comment]
@ggetz I just merged master and pushed it to your branch

**Comment by hpinkos** [comment]
Looks like this fixed the issue!  Thanks @ggetz

@bagnell can you please review the `Globe` and `QuadtreePrimitive` changes?

**Comment by bagnell** [comment]
@hpinkos @ggetz This looks good to me.

**Comment by ggetz** [comment]
Thanks @bagnell! @hpinkos tests are cleaned up as well now.

**Comment by hpinkos** [comment]
Thanks @ggetz!

**Pull request merged**
