### PR TITLE
Make drop down widgets go away on lost focus in IE

### PR DESCRIPTION
**Pull request by hpinkos**
Quick and easy fix for #2464

### CODE REVIEW

**Comment by emackey** [comment]
@shunter can you take a quick look at this?

**Comment by emackey** [comment]
@shunter suggested that you use [FeatureDetection.supportsPointerEvents](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/FeatureDetection.js#L172) to register listeners only on pointer, or only on touch+mouse, but not all together.

**Comment by hpinkos** [comment]
@emackey okay, thanks.  I made that change.

**Comment by emackey** [comment]
Tests pass, and I confirmed this fixes the problem on a Surface Pro 3.

**Pull request merged**
