### PR TITLE
Fix drill picking ground primitives

### LINKED ISSUE #5971: Drill picking polygons causes browser to hang
After upgrading from 1.38 to 1.39, drill picking certain polygons causes the browser to hang in an infinite loop at [this spot in the code](https://github.com/AnalyticalGraphicsInc/cesium/blob/1317bad025b6fb1183ad7e14a3e85a9c6a553cce/Source/Scene/Scene.js#L3371).

After quite a bit of debugging, I discovered that this happens on polygons that are missing a `height` attribute, even though [the API says it's an optional property](https://cesiumjs.org/Cesium/Build/Documentation/PolygonGraphics.html).  To fix the issue in 1.39 apps, you can explicitly set the height of all polygons to 0.0 (the default).  This isn't really a true workaround though, as your polygon will no longer conform to the terrain as it did when you completely omitted the property.

For example, drill-picking the polygon [in this Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=3712be60a2030e348df3584c2f962cfd) will result in the browser hanging. Add in `height: 0.0` and the drill picker will work again (albeit underground if you have terrain enabled).
```
var viewer = new Cesium.Viewer('cesiumContainer');

var wyoming = viewer.entities.add({
  name : 'Wyoming',
  show: true,
  polygon : {
    hierarchy : Cesium.Cartesian3.fromDegreesArray([
                              -109.080842,45.002073,
                              -105.91517,45.002073,
                              -104.058488,44.996596,
                              -104.053011,43.002989,
                              -104.053011,41.003906,
                              -105.728954,40.998429,
                              -107.919731,41.003906,
                              -109.04798,40.998429,
                              -111.047063,40.998429,
                              -111.047063,42.000709,
                              -111.047063,44.476286,
                              -111.05254,45.002073]),
    material : Cesium.Color.RED.withAlpha(0.5)
  }
});

viewer.screenSpaceEventHandler.setInputAction(function (movement) {
	var picks = viewer.scene.drillPick(movement.position);
	if (Cesium.defined(picks)) {
		console.log(picks.length);
	}
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);

viewer.zoomTo(wyoming);
```

EDIT: This applies to other primitives too -- not just polygons.

### PR DESCRIPTION
**Pull request by bagnell**
Update classification primitive pick commands to use show attribute. Fixes #5971.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@bagnell, thanks for the pull request! Maintainers, we have a signed CLA from @bagnell, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Is it possible to add a reasonable unit test to this?

**Comment by bagnell** [comment]
> Is it possible to add a reasonable unit test to this?

Yes, added.

**Comment by tfili** [comment]
Thanks @bagnell. Works great.

**Pull request merged**
