### PR TITLE
3D Tiles Sandcastle updates

### PR DESCRIPTION
**Pull request by lilleyse**
For #5308

### CODE REVIEW

**Comment by pjcozzi** [comment]
* Run http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/sandcastle-updates/Apps/Sandcastle/index.html?src=3D%20Tiles.html&label=3D%20Tiles
* Check "Annotate"
* Without changing the default view, right click on the top of the building in the center:

image

**Comment by pjcozzi** [comment]
Will the requested photogrammetry, CAD, etc. Sandcastle examples be in a separate PR?

**Comment by lilleyse** [comment]
I had noticed that too and added a related note on the to-do list, but haven't been able to track it down yet:

>  Why is annotation on translucent features not working in Sandcastle when scene.pickTranslucentDepth = true?

**Comment by lilleyse** [comment]
> Will the requested photogrammetry, CAD, etc. Sandcastle examples be in a separate PR?

Yeah

**Pull request merged**
