### PR TITLE
Decrease frustum overlap for opaque pass.

### LINKED ISSUE #5083: Two-pass labels intersect the depth buffer differently
Noticed in #5066:

Here's an example of labels sticking into mountains.  I know the text looks crowded and bad, but there are not supposed to be any holes in the glyphs.  The holes appear to be the opaque pass finding different depths to intersect than the translucent pass.

Cesium 1.28 needs to be manually set to "Natural Earth II" base map, but then it works, and it looks fine:

* [Cesium 1.28 large label demo](http://cesiumjs.org/releases/1.28/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=b3026fe9bc53ad4c3717360d436158ea)

Cesium 1.30 exhibits the label depth strangeness:

* [Cesium 1.30 large label demo](http://cesiumjs.org/releases/1.30/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=b3026fe9bc53ad4c3717360d436158ea)

bigbadlabels

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #5083.

### CODE REVIEW

**Comment by emackey** [comment]
I want to help review this, in particular look for any effect it has on frustum overlap cracks.  I don't have time today.

**Comment by pjcozzi** [comment]
@bagnell update CHANGES.md.

@emackey please merge once you are able to test.

**Comment by emackey** [comment]
I haven't found any cracks.  Looks good!

**Comment by bagnell** [comment]
Thanks! I'll update CHANGES.md in master.

**Pull request merged**
