### PR TITLE
Fix bad eslint change.

### LINKED ISSUE #5528: Model textures broken in master
Notice anything strange about this model 😄 

image

If not, look at the propellers.  Most likely caused by unexpected changes from 3d-tiles.

Someone should look at this ASAP.

### PR DESCRIPTION
**Pull request by emackey**
Fixes #5528, which was caused by an eslint change in #5483.

/cc @mramato @omh1280

### CODE REVIEW

**Comment by emackey** [comment]
This wasn't released, so no mention needed in CHANGES.md.

@moneimne This will be a small but important merge conflict to bring into your branch.

**Comment by omh1280** [comment]
Thanks Ed! Could you explain how my change broke it? What's the difference between `var binary` and `var binary=undefined`?

**Comment by emackey** [comment]
The difference is several lines above:

```
for (var id in textures) {
```

The code is executed multiple times, and old values were surviving!

**Comment by omh1280** [comment]
Ah, gotcha. Thanks

**Comment by hpinkos** [comment]
Thanks @emackey!

**Comment by mramato** [comment]
Thanks @emackey, sorry I missed this when I merged #5483.

The ship has sailed, but I'm surprised this wasn't caught by a unit test.

**Comment by emackey** [comment]
@mramato We could still add a unit test, but keep in mind that model code is already refactored for the glTF 2.0 effort, and these lines in particular don't exist in this form on @moneimne's 2.0 branch.

**Pull request merged**
