### PR TITLE
Add Box, Cylinder and Corridor to CZML

### PR DESCRIPTION
**Pull request by hpinkos**
For #3062 
Adds support for Box, Cylinder and Corridor to CZML

### CODE REVIEW

**Comment by pjcozzi** [comment]
@mramato will you be able to review and merge this during the code sprint?

**Comment by mramato** [comment]
Please update CHANGES then I'll merge.

I ran `sortRequires` to fix the formatting of the require block, but other than that, looks great!  Thanks.

**Comment by hpinkos** [comment]
@mramato ready

**Comment by mramato** [comment]
Open an issue in `czml-writer` for this too (or just add support and open a PR if you want).

**Pull request merged**
