### PR TITLE
Update kdbush to be a require module.

### LINKED ISSUE #4418: kdbush causes webpack warning
As [previously reported with earcut](https://github.com/AnalyticalGraphicsInc/cesium/pull/4097), kdbush is producing the following warning with webpack.

```
./~/cesium/Source/ThirdParty/kdbush.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/cesium/Source/ThirdParty/kdbush.js 1:479-486
```
I haven't noticed any runtime issues yet, but it would be good to have a better strategy for these third party dependencies such as pulling in the un-built source via an npm dependency.

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #4418.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Update CHANGES.md.

@chris-cooper could you please verify this?

**Comment by mramato** [comment]
I honestly think the warning @chris-cooper  reported is a false positive.  It's not really a pre-built javascript file, it just has the UMD boilerplate at the top so that it can be used in multiple different module loaders.

The main (and only) problem I have with this manual clean up that @bagnell did is that it means we have to do it every time we want to update to a new version of kdbush.

If we really want to "fix" this, we should be automatically grabbing the version from npm and doing whatever we need automatically during npm install.  Of course this is a longer-term change I'd like to see where we use npm for front-end dependcies as well (for non-built versions).

Whatever you guys decide for now is fine with me, but we need to strive to be able to effortless update third party libraries on a regular basis.

**Comment by pjcozzi** [comment]
@mramato is right in general.

For now for this case, this change is fine since kdbush is pretty stable and has not had significant updates recently: https://github.com/mourner/kdbush/commits/master

@chris-cooper please merge once you confirm, thanks.

**Comment by pjcozzi** [comment]
@bagnell update CHANGES.md.

**Comment by chris-cooper** [comment]
Yes this makes the warning go away.  I'm happy for it to be merged once @bagnell has updated CHANGES.md.

**Comment by bagnell** [comment]
@pjcozzi @chris-cooper CHANGES.md has been updated. This is ready.

**Comment by pjcozzi** [comment]
Thanks @bagnell @chris-cooper

**Pull request merged**
