### PR TITLE
Fix rectangles at north and south poles

### LINKED ISSUE #1297: 2D/Columbus-view artifact with extent geometries at the pole
From https://groups.google.com/forum/#!forum/cesium-dev

In the [Geometry and Appearances Sandcastle example](http://cesium.agi.com/Cesium/Apps/Sandcastle/index.html?src=Geometry%20and%20Appearances.html&label=Showcases), replace Line 119 with

``` javascript
extent = Cesium.Extent.fromDegrees(-180.0, 45.0, -160.0, 90.0);
```

Given that `90.0` is at the pole, we get artifacts in 2D and columbus view.

3D:

image

2D:

image

Using `89.99` instead of `90.0` does not cause artifacts.

Perhaps the geometry is optimizing for this in 3D and not introducing a northern row.  If that's the case, we can pass an `allow3DOnly` option that defaults to `false`.

### LINKED ISSUE #4760: RectangleGeometry fails at latitude -90
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Zz91b7MEVeY

There's a normal that's going to `NaN` in `GeometryPipeline.splitLongitude`

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var redRectangle = viewer.entities.add({
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-120.0, -90.0, 120.0, -80.0),
        material : Cesium.Color.RED.withAlpha(0.5),
        outline : true,
        outlineColor : Cesium.Color.RED
    }
});

viewer.zoomTo(viewer.entities);
```

### LINKED ISSUE #7406: splitLongitude produces NaN texture coordinates
```js
worldRectangle = scene.primitives.add(new Cesium.Primitive({
        geometryInstances : new Cesium.GeometryInstance({
            geometry : new Cesium.RectangleGeometry({
                rectangle : Cesium.Rectangle.fromDegrees(-180.0, -90.0, 180.0, 90.0),
                vertexFormat : Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT
            })
        }),
        appearance : new Cesium.EllipsoidSurfaceAppearance({
            aboveGround : false
        }),
        show : false
    }));
```

I've discovered that the texture coordinates attribute has NaN's in it. If I put the following check in `Source/Core/AttributeCompression.js` everything works fine:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/AttributeCompression.js#L308-L316

```
if (isNaN(textureCoordinates.x) || isNaN(textureCoordinates.y)) {
       return 0;
}
```

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #7406
Fixes #4760

When the rectangle north is the north pole, it comes to a single point instead of a row of points at the top edge.  `RectangleGeometry` was creating a ton of duplicate points and every other triangle at the north pole had zero area, which was causing things to go weird further up the geometry pipeline (specifically when `splitLongitude` was trying to use barycentric coordinates to compute attributes).

Similarly for the south pole and the bottom edge.  

This change creates a single north pole position and/or south pole position and triangulates accordingly.

For an example, this rectangle crashes in master, but is fixed in this branch:

``` js
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.scene.primitives.add(new Cesium.Primitive({
    geometryInstances : new Cesium.GeometryInstance({
        geometry : new Cesium.RectangleGeometry({
            rectangle : Cesium.Rectangle.fromDegrees(-180.0, -90.0, -179.0, 90.0),
            vertexFormat : Cesium.VertexFormat.POSITION_AND_NORMAL
        }),
        attributes: {
            color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(0.0, 1.0, 0.0, 0.5))
        }
    }),
    appearance : new Cesium.PerInstanceColorAppearance({
        closed : true
    })
}));
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Thanks @hpinkos!  Please merge in master.

@bagnell I think you're most qualified to review this.

**Comment by bagnell** [comment]
This doesn't fix #1297. It doesn't crash, but the artifact is still there. Here is the updated code example:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.entities.add({
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-180.0, 45.0, -160.0, 90.0),
        outline : true,
        outlineColor : Cesium.Color.WHITE,
        material : Cesium.Color.BLUE,
        height : 0.0
    }
});
```
The only difference between this code and that in the issue is `height : 0`. So for some reason a rectangle clamped to the ground is different from a normal rectangle geometry?

**Comment by hpinkos** [comment]
Gotcha.  I remembered to set `height: 0` when i was testing out some other things but I must have forgot to set it when I was testing that example

**Comment by hpinkos** [comment]
@bagnell merged in master.  Anything else?

**Comment by bagnell** [comment]
No, this looks good. Merging.

**Pull request merged**
