### PR TITLE
Straight CorridorGeometry.

### LINKED ISSUE #2511: Incorrect straight CorridorGeometry
Copy the below code into Sandcastle. The corridor should be straight along the longitude.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', { infoBox : false });
var entities = viewer.entities;

entities.add({
    corridor : {
        positions : Cesium.Cartesian3.fromDegreesArray([
            -67.655, 0.0,
            -67.655, 5.0,
            -67.655, 10.0,
            -67.655, 15.0,
            -67.655, 20.0,
            -67.655, 25.0,
            -67.655, 30.0,
            -67.655, 35.0,
            -67.655, 40.0,
            -67.655, 45.0,
            -67.655, 50.0,
            -67.655, 55.0,
            -67.655, 60.0,
            -67.655, 65.0,
            -67.655, 70.0,
            -67.655, 75.0,
            -67.655, 80.0,
            -67.655, 85.0,
            -67.655, 90.0
        ]),
        width : 400000,
        height : 0,
        outline : true,
        outlineColor : Cesium.Color.WHITE,
        outlineWidth : 4,
        material : Cesium.Color.fromRandom({alpha : 0.7})
    }
});

viewer.zoomTo(viewer.entities);
```

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #2511 and also the same problem that was occurring for `PolylineVolumeGeometry`.

### CODE REVIEW

**Comment by mramato** [comment]
Anyway we can unit test this?

**Comment by SlySnake** [comment]
What about straight lines that aren't parallel to lines of longitude or latitude, like this case
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', { infoBox : false });
var entities = viewer.entities;

entities.add({
    corridor : {
        positions : Cesium.Cartesian3.fromDegreesArray([
-90,30, /*45 deg 100km*/
-89.260833,30.633889, /*45.373056 deg 100km*/
-88.511944,31.263611, /*45.758056 deg 100km*/
-87.753056,31.888889, /*46.155278 deg 100km*/
-86.983889,32.509444, /*46.565 deg 100km*/
        ]),
        width : 40000,
        height : 0,
        outline : true,
        outlineColor : Cesium.Color.WHITE,
        outlineWidth : 4,
        material : Cesium.Color.fromRandom({alpha : 0.7})
    }
});

viewer.zoomTo(viewer.entities);
```
Change width to 400 and it's straight as an arrow, but it is crooked when it's 40000.

I generated these series of points using 
http://www.movable-type.co.uk/scripts/latlong.html
Destination point given distance and bearing from start point

And converted to decimal degrees using
http://www.fcc.gov/encyclopedia/degrees-minutes-seconds-tofrom-decimal-degrees

**Comment by bagnell** [comment]
Thanks @SlySnake, I switched back to my first solution which is check the angle between the direction vectors projected onto the tangent plane. The first time I forgot to re-normalize.

@mramato I added tests. This is ready for another review.

**Comment by SlySnake** [comment]
You're welcome, I'm glad I could help. Though I haven't really studied the code much to see how it all works. It's strange that narrow widths are straight, but not wide widths. I thought widths wouldn't affect the path.

**Comment by pjcozzi** [comment]
Update CHANGES.md.

Can we merge this today so it makes 1.7?

**Comment by mramato** [comment]
Tests pass, example code in the linked issue is clearly fixed in this branch (and broken in master).  I updated CHANGES.

**Pull request merged**
