### PR TITLE
KHR_texture_transform shouldn't emulate sampler repeat options

### LINKED ISSUE #7916: Crash when loading glTF's KHR_texture_transform without a sampler
Cesium's implementation of the `KHR_texture_transform` extension of glTF makes poor assumptions that the optional `sampler` will be defined.

https://github.com/AnalyticalGraphicsInc/cesium/blob/90b130edea858b7b6b6a1575422b0b2654f2ae97/Source/Scene/processPbrMaterials.js#L94

In the above, `gltf.samplers` need not be defined, and `gltf.textures[n].sampler` is likewise optional, leading to a rather fancy message:

> Cannot read property 'undefined' of undefined

Here's a sample model for testing.

[TexRotateTest.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3262897/TexRotateTest.zip)

### PR DESCRIPTION
**Pull request by emackey**
The KHR_texture_transform extension was looking at texture repeat options and trying to factor them into the transformed texture.  This is not needed, as WebGL will do the correct thing with sampler repeat options regardless of whether the coordinates have been transformed or not.

Fixes #7916

Alternative solution to #8065

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/tex-transform-repeat/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by emackey** [comment]
Missing CLA??

**Comment by emackey** [comment]
Not sure if a unit test is needed.  This is strictly a removal of code, there's nothing new to test.

However, I can demonstrate that the clamping and mirroring features work fine even with this code removed:

[TexRotateTest_clamp.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3506152/TexRotateTest_clamp.zip)

[TexRotateTest_mirror.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3506153/TexRotateTest_mirror.zip)

The original test model shows repeating, which is the 3rd option and the default.

**Comment by mramato** [comment]
@OmarShehata can you look into why @emackey's CLA is missing?

@lilleyse is this good with you?

**Comment by mramato** [comment]
Closes #8065

**Comment by emackey** [comment]
Just for visual reference, this is the original test model from #7916, which doesn't specify a sampler and thus ends up with the default `REPEAT` behavior.  The texture coordinates are axis-aligned, but, the `KHR_texture_transform` extension introduces a small rotation, producing a slight diagonal edge.

The rotation reveals an area where the texture coordinates begin repeating. revealing block `A1` and its neighbors.

Sampler_Repeat_sm

With the samplers set to `CLAMP_TO_EDGE`, the texture rotation reveals an area that appears smeared.  This is intentional, from the texture coordinates being clamped along the edges after the rotation has taken place.

Sampler_Clamp_sm

Finally, the text model above with samplers set to `MIRROR` will show some reverse blocks, such as blocks `G8` and `F8` being shown from mirrored texture coordinates.

Sampler_Mirror_sm

The upshot of all this is, Cesium's implementation of the `KHR_texture_transform` extension was trying to emulate two of these options with shader code, but, the underlying WebGL sampler enums are still in effect from the main model, so it's safe to remove this code without losing the functionality.

**Comment by mramato** [comment]
This all _sounds_ correct to me, but I'm not qualified to merge.  @lilleyse or @likangning93 any thoughts here? Please merge if you are good with this.

**Comment by lilleyse** [comment]
Yup this looks good to me. I'll merge after the last merge commit passes CI.

**Comment by lilleyse** [comment]
Thanks @emackey!

**Pull request merged**
