### PR TITLE
fix: check cachedRendererResources.programs before get values

### PR DESCRIPTION
**Pull request by vla9isla8**
https://github.com/AnalyticalGraphicsInc/cesium/issues/7842#issuecomment-494471043

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @vla9isla8! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/vla9isla8/cesium/blob/issues/7842/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/issues/7842/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by vla9isla8** [comment]
@cesium-concierge CLA is sent

**Comment by vla9isla8** [comment]
fixed #7842

**Comment by vla9isla8** [comment]
@OmarShehata can you review this merge?

**Comment by OmarShehata** [comment]
Thanks for opening this pull request! I'd prefer to figure out exactly why `cachedRendererResources.programs` becomes null before we merge this fix, to make sure it isn't masking a bigger problem. 

Were you ever able to reproduce the issue in Sandcastle?

**Comment by vla9isla8** [comment]
@OmarShehata 
> Were you ever able to reproduce the issue in Sandcastle?

Unfortunately, not. I have no idea why is it happening and what i must render in sandcastle to reproduce it. But this error is block normal work for me and i can't make workaround fix in my app to avoid it

If I catch this bug in future or find cause, I will report about it )

**Comment by vla9isla8** [comment]
@OmarShehata my be problem in particular loading gltf models? We use multiple files(schema and data file) unless glb and not all data ready to render?

**Comment by vla9isla8** [comment]
Or may be you can help me to avoid this workaround?))

**Comment by vla9isla8** [comment]
Or may be you can help me to avoid this workaround?))

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @vla9isla8! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
I don't think this is the right fix and is probably masking the real problem as @OmarShehata suggested. I want to see if the workaround I suggested in https://github.com/AnalyticalGraphicsInc/cesium/issues/7842#issuecomment-532878979 narrows down the problem. Then I should be able to reproduce it and submit the right fix.

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @vla9isla8! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request closed without merging**
