### PR TITLE
Removing quadrilateral interpolation

### PR DESCRIPTION
**Pull request by moneimne**
There were jitter issues with the Polly model because of the quadrilateral interpolation. Spoke to @lilleyse and he said to remove it as long as it was causing issues. I tested Polly and other models with these changes and things seem to work fine.

### CODE REVIEW

**Comment by mramato** [comment]
@lilleyse is this PR still valid?

**Comment by lilleyse** [comment]
Yeah, I've been meaning to look at this. The code seems fine I just need to test a bunch of models.

**Comment by lilleyse** [comment]
My review is long overdue here. A model with some animation issues came up on the [forum ](https://groups.google.com/forum/#!topic/cesium-dev/Ktc9vwJiiTU) and was fixed by using this branch. I also tested all of the animated glTFs in https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0 which work fine on this branch.

The code looks good. I just made a doc fix and added a note to `CHANGES.md`.

Overall slerp seems to be more stable than squad, and I can't see a difference in animation quality.

@emackey - I'm curious if you have a take on this.

**Comment by emackey** [comment]
One deficiency in our current set of sample models is that all of our animated models use the default `LINEAR` interpolation.  Technically the glTF model is able to [specify a type of interpolation](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.sampler.schema.json) as `LINEAR`, `STEP`, or `CUBICSPLINE`, but we don't have samples of the other two yet.

Even so, if this makes things noticeably better (I didn't try it myself yet), then I think it's fine to merge this now and revisit in more detail when more rigorous tests become available.

**Comment by lilleyse** [comment]
Thanks @emackey.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/Ktc9vwJiiTU

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/5740 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Pull request merged**
