### PR TITLE
Don't add polyline to update list twice

### LINKED ISSUE #7153: 'instanceIndex is out of range' Error
I'm periodically (consistently with a particular action) getting the `instanceIndex is out of range` described in this issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/4983

After a bunch of debugging I've been able to reproduce the error in the 2 sandcastle examples given below. These are almost identical to the code in this comment on the 4983 issue -> https://github.com/AnalyticalGraphicsInc/cesium/issues/4983#issuecomment-381747401.
It seems that the fix that closed the issue did fix this for the situation in that code, but not for the situation in which multiple modifications to a line are being made before the line is removed.

The first sandcastle example is without `requestRenderMode` and always gives an error when clicking the `Change Polylines` button, and the second example only gives an error when you click it quickly while cesium is still loading everything OR if you click it more than once. I chose to put the second example there because in the actual codebase I'm using, `requestRenderMode` is used.

I don't mind working on this, but the code can be confusing. I've gotten as far as eliminating the the `instanceIndex` error, but I'm not sure if this is the best way to go about it (the code below). Also, I thought I found bug using this earlier, but for now I can't reproduce it. I'll keep testing this to see if I can reproduce it. The error had to do with trying to update a polyline that had already been destroyed.

I put this in there because duplicates were constantly being added to `_polylinesToUpdate`. Depending on how long I wait with nothing happening and no rendering for a while I can have 1 line thousands of times in that list.
```javascript
PolylineCollection.prototype._updatePolyline = function(polyline, propertyChanged) {
    // *** CODE I ADDED
    if (this._polylinesToUpdate[polyline._index] && this._polylinesToUpdate[polyline._index] === polyline) {
        return;
    }
    // ***

    this._polylinesUpdated = true;
    this._polylinesToUpdate.push(polyline);
    ++this._propertiesChanged[propertyChanged];
};
```

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVNNj9MwEP0ro1yaSqmjpSyVaFrBZvdWBGILF7IHrzNtLBw7sp1UYbX/HeezaRE3sBLFHs97M+/ZqaiGiuMJNWxA4gliNLzMyfc25s9Yu4yVtJRL1LP5OpGJrByqUKIWLmYugV/6cKyEQGa5kn6PaRmJYSiRFJrn3PIKDaFp6o9cXSpT0lg4cG1srJROmxI/FqvbAJbuXdy8aWdP6yHToPum16mroM9cPV2z7lwtlziWbZt4SSS4USjDm7YNvB80xVRbN6NySQ5a5fd41Ijmo9a09iddzoOO4cRTmzn0sl/n1KLmVJwJP/WRlm5fF+gnnjNM6cQL4IU1s0n1Zkm+Pty/zhP52jgEk3HpwT8UNjX1vyq72317GKUl8pHKlFFjBTbN75USz1Tflda6mzSLMyqPCMMlM7MADqXsrxn0QscjJl2/G3jbm3Y2ady6/fvWuzWEIURRtOgG7DNuwD2njDaGY27AKmC0NAg2Q0CtndDe7OEENOaqQv/M38h0Wr3Ai4ytBW47xAeeF0pbKLXwCQkt5oVwZprwuWQ/0RJm2r8jCgdQlPIKeLpJvKufNPGACWqM2zmUQjzyX5h42yh0+RcwoWjK5fFzhVrQuknJbra7LkgIiUK3/BNluxOZMP4G

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVNNj9MwEP0ro1yaSqmjpSyVaFrBZvdWBGILF7IHrzNtLBw7sp1UYbX/HeezaRE3sBLFHs97M+/ZqaiGiuMJNWxA4gliNLzMyfc25s9Yu4yVtJRL1LP5OpGJrByqUKIWLmYugV/6cKyEQGa5kn6PaRmJYSiRFJrn3PIKDaFp6o9cXSpT0lg4cG1srJROmxI/FqvbAJbuXdy8aWdP6yHToPum16mroM9cPV2z7lwtlziWbZt4SSS4USjDm7YNvB80xVRbN6NySQ5a5fd41Ijmo9a09iddzoOO4cRTmzn0sl/n1KLmVJwJP/WRlm5fF+gnnjNM6cQL4IU1s0n1Zkm+Pty/zhP52jgEk3HpwT8UNjX1vyq72317GKUl8pHKlFFjBTbN75USz1Tflda6mzSLMyqPCMMlM7MADqXsrxn0QscjJl2/G3jbm3Y2ady6/fvWuzWEIURRtOgG7DNuwD2njDaGY27AKmC0NAg2Q0CtndDe7OEENOaqQv/M38h0Wr3Ai4ytBW47xAeeF0pbKLXwCQkt5oVwZprwuWQ/0RJm2r8jCgdQlPIKeLpJvKufNPGACWqM2zmUQjzyX5h42yh0+RcwoWjK5fFzhVrQuknJbra7LkgIiUK3/BNluxOZMP4G

Browser: Chrome, FF, IE

Operating System: Windows 10

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #7153

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-polyline-crash/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
I'm pretty certain this exact code (or something like it) used to use indexOf and we changed it because it's a major performance killer.  You are basically doing a linear search for every polyline being updated.

What is the root problem here, we are essentially updating the line twice and that leads to an error?  Could we avoid the indexOf by using a dirty flag and simply not doing the second update if it's already been called?

**Comment by hpinkos** [comment]
Good call @mramato, I didn't realize polyline had a dirty flag.

**Comment by mramato** [comment]
> I didn't realize polyline had a dirty flag.

I didn't either, glad it was that easy :smile:  That being said, it would it make more sense to add this check in Polyline.js itself, that way it avoids calling `_updatePolyline` at all if it's already dirty?

**Comment by hpinkos** [comment]
@mramato no, I don't think that will work because the polyline might have multiple properties changed and the `_propertiesChanged` array in `PolylineCollection` still needs to be incremented.

**Comment by mramato** [comment]
Good call.  That makes sense.  Should we add a unit test for this?

@bagnell can you review and merge?  Thanks.

**Comment by bagnell** [comment]
Looks good to me. Can you add a test @hpinkos?

**Comment by hpinkos** [comment]
@bagnell ready

**Pull request merged**
