### PR TITLE
Added Promise in Model API

### PR DESCRIPTION
**Pull request by jpremkumar**
Hi @mramato, I've created a new branch from the master and committed my changes from [#3814](https://github.com/AnalyticalGraphicsInc/cesium/pull/3814). 

Can you please review and merge.

Thanks!

### CODE REVIEW

**Comment by jpremkumar** [comment]
Any progress on this branch?

**Comment by hpinkos** [comment]
@mramato do you have any feedback here?

**Comment by mramato** [comment]
First, I'm really sorry it took me so long to get to this, as a team we want to do a better job with reviews.

Unfortunately this approach won't really work well for several reasons.  The model can change dynamically with time or programatically, but the ready promise can only resolve a single time.  So promises may not be the best context here.  Additionally, the `ModelGraphics` object may actually be associated with several different visualizers, so there may not be a single "model ready" event.

I have some ideas on how to resolve this, but I need to think about it a little more.  I think a better solution would be to add generic events to all of the visualizers that get raised when an associated primitive is created.

I'm going to leave this open for now, but I'm actually going to look into tackling this issue right away and may open a new PR to replace this right away.

I appreciate the pull request just the same, so thanks @jpremkumar and I'm sorry again for not getting back to you sooner.

**Comment by hpinkos** [comment]
I wrote up #4727 to replace this PR.  I'm going to close this since we're not going to go forward with this approach.
Thanks again for taking a look at this @jpremkumar

**Pull request closed without merging**
