### PR TITLE
Travis Improvements

### PR DESCRIPTION
**Pull request by ggetz**
* Moved the deploy step to always run and to run after the `makeZipFile` step. 

* Set the status of the deployment before and after, using the same code from the `cesium-website` repo.
    * Both of the `deploy-status-` tasks will exit early if there is no `TOKEN` environment variable. 
    * I set the environment variable `TOKEN` in my own repo settings with my own token, and the status for my commits were set properly.
    * I also set the `TOKEN` variable in the settings for the AnalyticalGraphicsInc account, but I don't think I can test it myself.

### CODE REVIEW

**Comment by mramato** [comment]
Since the code looks fine (and we have to open a PR from the Cesium repository to test this anyway), I'm going to merge this and then the first PR that gets opened with this code should work.

**Comment by mramato** [comment]
Thanks @ggetz!

**Comment by mramato** [comment]
I merged these changes into #3766 and everything works great.

**Comment by ggetz** [comment]
Awesome!

**Pull request merged**
