### PR TITLE
npm audit: Update karma & gulp

### PR DESCRIPTION
**Pull request by SunBlack**
* Fixes all vulnerabilities found by npm audit (11 vulnerabilities (2 low, 5 moderate, 4 high))
* Update gulp@3.9.1 to gulp@4.0.0 (Fixes 5 vulnerabilities (1 low, 4 high))
* Update karma@2.0.3 to karma@3.0.0 (Fixes 6 vulnerabilities (1 low, 5 moderate))
* Reorder task in gulpfile.js to be compatible with gulp@4.0 (task must be defined before using them in gulp.series/gulp.parallel)

Not sure if gulp@4,0 is really stable, because you get it only via gulp@next and not via gulp@latest, but I found no issue by using it and due to security reasons I think we should update.

Maybe someone should a deeper look at this MR if `gulp.series` is always necessary or sometimes `gulp.parallel` would also work.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @SunBlack!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/update_dependencies/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by SunBlack** [comment]
Remaining Travis error seems not be related to this MR. I can reproduce this error on my machine... on this branch, but also with current master.

**Comment by hpinkos** [comment]
Thanks for the pull request @SunBlack!  Since gulp 4 doesn't seem to be their stable release, I'm not sure if we want to take this change quite yet.  @mramato what do you think?

**Comment by mramato** [comment]
I agree with @hpinkos while I have been waiting for gulp 4.0.0 forever so we can switch to it, I'm not comfortable switching to it until it's actually released.

**Comment by SunBlack** [comment]
Gulp 3.9.1 is 3 years old. If I install current cesium with gulp3.9.1 I get (node.js 10)
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
```
So I'm currently not sure if 3.9.1 is really more stable then 4.x, because dependencies are not anymore adjusted to upcoming node.js version (node.js 10.11 will be next LTS version next month). As long as we found no issue I think we can upgrade.

**Comment by SunBlack** [comment]
Today I looked how is the progress with gulp4 (if gulp@next is stable or just a 4.0.0-pre). It seems 4.0.0 is marked as stable since 1/1/18 - see [here](https://github.com/gulpjs/gulp/releases)

**Comment by mramato** [comment]
@SunBlack Thanks for the update.

It also looks like as of a few days ago, the Gulp team is officially recommending using 4.0, so I will review and merge all of our npm-related PRs right after the Cesium release this Thursday (to avoid any unforeseen complications).

Thanks again!

**Comment by mramato** [comment]
Thanks again @SunBlack.  I ran into some merge issues so I ended up starting over and updating to gulp4 as part of #7239.  Should go into master later today.

**Pull request closed without merging**
