### PR TITLE
Add showCredit to Scene options

### PR DESCRIPTION
**Pull request by oterral**
The new Credits behavior adds a lot of unwanted thing in the HTML  page (css, html elt, ion image loading...) when we have a custom credits management. 

This PR adds an option to the scene to deactivate all this stuff.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@oterral, thanks for the pull request! Maintainers, we have a signed CLA from @oterral, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the PR @oterral, but I'm not sure this is one we want to take.  The terms of use for data streaming from Cesium ion require that the Cesium ion attribution is visible on the screen.  See the 'Attribution' section at the bottom of this page: https://cesium.com/legal/terms-of-service/ 

It's fine if you have custom credit management in your application as long as it meets those terms of use, but we don't want to confuse other cesium users by making it too easy to hide the required attribution.

@mramato @pjcozzi do you have any additional thoughts on this?

**Comment by oterral** [comment]
I'm  totally agree if we used the Cesium ion services, but it's not our case we only use CesiumJS. 
And generally speaking, Cesiumjs uses a widget system so this kind of stuff (adding html or css dynamically)  should be added  via a widget.

It's just a proposal,  I totally understand if you think it's against your terms of service.

**Comment by hpinkos** [comment]
@oterral that makes sense.  We changed the default 'Cesium' credit to be 'Cesium ion' because we didn't want it blinking back and forth between Cesium and Cesium ion depending on what data you had on the globe.  You can see in the offline demo that just that credit is shown without anything extra: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Offline.html
If you wanted to replace that, you can set `CreditDisplay.cesiumCredit` to the logo for your app.

The reason the attribution system isn't a widget is because it's really closely tied to the frame state.  We change the credits that show up in the popup credit display based on what data is currently on screen.  For example, if you're using Cesium World Terrain, it might show different attributions when you're looking at the Grand Canyon than when you're looking at the Cliffs of Moher in Ireland.  The attributions we add for imagery and terrain sources like Bing and Cesium World Terrain are required, and we wanted to make it easy for users to be compliant.

**Pull request closed without merging**
