### PR TITLE
Force kill the development server on second SIGINT

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by emackey** [comment]
Does this happen a lot?  I don't recall seeing this server need a second kill.

Also, before we accept any contributions, we need a signed CLA (as outlined at the top of [Contributing.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md)).  This is pretty simple and can just be emailed, not a paper signature.  Thanks.

**Comment by icholy** [comment]
It hangs for me pretty often while waiting to for the server to close. End up having to `kill` it.

**Comment by hpinkos** [comment]
@emackey this happens for me occasionally also

**Comment by emackey** [comment]
@hpinkos OK, good to know.  And I just got the CLA email from @pjcozzi, that was fast.  I'll test this a bit and then merge.

**Comment by emackey** [comment]
Seems good.  @hpinkos let me know if you see another hang, and if this fixes it.  Merging.

Thanks @icholy for the contribution!

**Pull request merged**
