### PR TITLE
Added: Promise in ModelAPI

### PR DESCRIPTION
**Pull request by jpremkumar**
Added "readyPromise" and "ready" property to ModelGraphics and set the value when the new model is created in ModelVisualizer.

I was unable to write test case in ModelVisualizer while set the value to the [promise](https://github.com/jpremkumar/cesium/blob/model-promise/Source/DataSources/ModelVisualizer.js#L233)

Guide me to proceed further.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for the contribution, @jpremkumar!

Everyone - we have a CLA from @jpremkumar.

**Comment by jpremkumar** [comment]
Hello Team, 
Any progress on this commit?

**Comment by pjcozzi** [comment]
@jpremkumar sorry for the slow response; we had _a lot_ of conference work.

@hpinkos can you look at this?

**Comment by mramato** [comment]
@jpremkumar can you please merge in master and also undo any unnecessary code edits.  It looks like there are a lot of whitespace/formatting changes that are unneeded.

Because model data can be time-dynamic, I'm not sure exposing the readyPromise here is the best course of action, however I agree that a similar capability would be useful.  We should probably also make it generic enough so that other visualizers have similar behavior (like getting the billboard associated with an entity).  Let me think about it some more and when you're updates are in I'll review what you've done and write up what I think the best approach would be.

Sorry for taking so long to reply and thanks for taking a stab at this.

**Comment by pjcozzi** [comment]
Moved to #3910.

**Pull request closed without merging**
