### PR TITLE
Fix setView in 2D and CV

### PR DESCRIPTION
**Pull request by bagnell**
* Seperate set view for the three scene modes.
* Clone input.
* Add more tests to ensure correctness.

For #2943.

### CODE REVIEW

**Comment by mramato** [comment]
Running the sample code in the linked issue seems to cause multiple crashes.  Zoom in a little and hit `orient north`

**Comment by hpinkos** [comment]
@mramato it doesn't crash for me.

**Comment by mramato** [comment]
@hpinkos sorry, it only happens if you remove the clone.

This should definitely crash.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');

Sandcastle.addToolbarButton('Orient North', function(){
    viewer.scene.camera.setView({
        position: viewer.scene.camera.positionWC,
        roll: 0,
        pitch: -Cesium.Math.PI_OVER_TWO,
        heading: 0
    });
});
```

**Comment by bagnell** [comment]
@mramato The crash is fixed.

**Comment by mramato** [comment]
I updated CHANGES and everything looks good.  Thanks.

**Pull request merged**
