### PR TITLE
Frame state refactor

### PR DESCRIPTION
**Pull request by bagnell**
For #1753.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@tfili this may have some minor merge conflicts with #3039.

**Comment by pjcozzi** [comment]
Part of #3001.

**Comment by pjcozzi** [comment]
[QuadtreePrimitive.html](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Sandcastle/QuadtreePrimitive.html) needs to be updated.

**Comment by pjcozzi** [comment]
Tests and Sandcastle are good.  Just that one comment then this is ready to merge.

**Comment by pjcozzi** [comment]
Please also open a pull request from this branch (or master when it is merged) to `3d-tiles` and update `Cesium3DTileset` and friends.  Let me know if you need sample data.

Note that `3d-tiles` is a bit behind master so this will also bring the npm build changes into that branch.

**Comment by bagnell** [comment]
@pjcozzi Its updated. This is ready.

**Comment by pjcozzi** [comment]
Thanks!

**Pull request merged**
