### PR TITLE
ArcGIS link fix

### PR DESCRIPTION
**Pull request by slchow**
Link correction emailed to us from the community.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @slchow!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/arcgis-link-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks @slchow ! I can see that the old URL gets redirected to this new one. You might want to keep the format as `@see {@link https://developers.arcgis.com/rest/|ArcGIS Server REST API}`, that way when it appears in the docs it's "[ArcGIS Server REST API](#)" instead of "[https://developers.arcgis.com/rest/](#)".

**Comment by slchow** [comment]
Thanks @OmarShehata! Better?

**Comment by OmarShehata** [comment]
Thanks @slchow !

**Pull request merged**
