### PR TITLE
Change camera zoom to not pick positions in the middle of a zoom.

### LINKED ISSUE #4177: Zoom Crash from Touch Input on Viewer Initialization
After initializing a viewer, if any zoom touch events occur before a pan (rather difficult to gesture a zoom before a pan with touch, but doable), a render error occurs and causes the viewer to crash.

Here is a link to a Gist page with code that can be used to reproduce the error (a touch input device is needed, or some ability to emulate touch events):

https://gist.github.com/amc723/508009b296ca4783f7a55eb57e038ac6

### PR DESCRIPTION
**Pull request by emackey**
This fixes an issue where if you start zooming in from some point off the globe, when you're close enough that the limb of the globe touches your starting point, the globe suddenly twists.

This should also fix #4177 and #4440, but I could use some help testing.

Can someone test if this fixes the illusive zoom-crash? @amc723 @smills2929 @willemvdg @lucasvw

/cc @bagnell

### CODE REVIEW

**Comment by jbo023** [comment]
We checked this branch against the bug, we filed some time ago: https://github.com/AnalyticalGraphicsInc/cesium/issues/4407.
We could not reproduce the old Bug.

So it looks nice 👍

**Comment by jbo023** [comment]
During testing i also noted another Bug with touch pinch gestures. 

If you start with a pinch gesture the origin of the zoom/rotate gesture is in the upperleft corner of the screen. (Only if this is the first touch/mouse event)

If you then do a short  one finger movement the next pinch gesture will use the that movement position as a new origin.

Maybe you can also check this out.

**Comment by pjcozzi** [comment]
@emackey is it possible to write a reasonable unit test for this?

Also update CHANGES.md.

**Comment by pjcozzi** [comment]
CC @pmconne

**Comment by mramato** [comment]
@emackey I can confirm that this fixes the "upper left pixel zoom" crash you mentioned previously as well as the "pinch first" bug.  Awesome!  I agree it would be nice to add a test for this if we can, if perhaps indirectly test it at least if it was an initialization issue. Even a simple test without any expects that crashed in master but now doesn't crash now would be good.

If tests can't be done cleanly, I'm okay with merging this as-is.

**Comment by mmccartn** [comment]
Tested and can confirm this fixes #4177. Thanks

**Comment by jbo023** [comment]
Tested again, origin on pinch gestures is now correct. Thanks

**Comment by bagnell** [comment]
I updated `CHANGES.md` in `master` 39169f7b2f4cbde4d18cfe7b5d834bddbb91c67a

**Comment by pjcozzi** [comment]
@lilleyse can you please merge `master` to `3d-tiles` so @pmconne has this fix?

**Comment by lilleyse** [comment]
Done.

**Pull request merged**
