### PR TITLE
Geocoder on success event

### PR DESCRIPTION
**Pull request by hpinkos**
Added GeocoderViewModel.onSuccess, an event for the geocoder's flight completion (#1262)
I also made a tiny change to the camera sandcastle example, so the DOM elements are created in the HTML instead in the script.

(Clean up from #2706)

### CODE REVIEW

**Comment by pjcozzi** [comment]
Looks good.  Is there a reasonable way to add a test for this?

**Comment by hpinkos** [comment]
@pjcozzi I added a test for when the duration is 0.  I'm not sure how to test it for when the duration is not zero because i'm sending it in to `Camera.flyTo.complete`

**Comment by pjcozzi** [comment]
@bagnell is there an easy way to do this?

> I'm not sure how to test it for when the duration is not zero because i'm sending it in to Camera.flyTo.complete

Set a very small duration and then render the scene until the event is raised?

**Comment by bagnell** [comment]
There is an update function on flights you can call with a time. Just pass in the duration for the time and it will complete. See the [CameraFlightPathSpec](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Scene/CameraFlightPathSpec.js#L128).

**Comment by hpinkos** [comment]
@bagnell thanks! does this test look good?

**Comment by pjcozzi** [comment]
Can we aim to get this merged today to wrap up items from the sprint?

**Comment by bagnell** [comment]
The test looks OK to me. The `update` function takes a time argument. If you pass in a time where it should be completed, you wouldn't have to poll.

**Comment by hpinkos** [comment]
@bagnell I ran into issues doing it that way because `Camera.flyto` adds the flight directly to `scene.tweens`, and I couldn't figure out a way to get it back and also guarantee that it hadn't been executed yet.

**Comment by bagnell** [comment]
OK. This looks good to me. @pjcozzi can merge when he's ready.

**Pull request merged**
