### PR TITLE
make headingPitchRoll to quaternion counter clock wise

### PR DESCRIPTION
**Pull request by kaktus40**
Hello,
just to follow this [topic](https://groups.google.com/forum/#!topic/cesium-dev/2-Fn_8yeurY), I made a pull request to make the conversions between heading pitch roll and quaternion counter clock wise oriented (mathematical convention).

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks for submitting this @kaktus40!  I agree that we should probably be using counter clockwise rotation, but this would be a breaking change for a lot of people so we'll need to discuss how we want to approach this.

**Comment by pjcozzi** [comment]
@kaktus40 thanks again, and sorry for the long delay; this has been sitting in my queue.

Does this require any doc changes or updates to any of the Sandcastle examples, including the development ones?  Seems like it would.

As @hpinkos mentioned, even though this doesn't break the API it is still a breaking change that I suspect will break some apps so we would need to come up with a deprecation plan (see [Deprecation and Breaking Changes](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#deprecation-and-breaking-changes)).

@ggetz could you please work with @kaktus40 on this?

**Comment by ggetz** [comment]
Hi @kaktus40, I would suggest creating new functions for the new conversations and deprecating the old ones.

**Comment by kaktus40** [comment]
Hello, I can't work on this pull request until september. Nevertheless, I can read your suggestions!

Envoyé par BlueMail<http://www.bluemail.me/r?b=10066>
Le 21 juil. 2017, à 16:25, Gabby Getz <notifications@github.com<mailto:notifications@github.com>> a écrit:

Hi @kaktus40<https://github.com/kaktus40>, I would suggest creating new functions for the new conversations and deprecating the old ones.

**Comment by ggetz** [comment]
@kaktus40 Is it OK if we close this PR for now and move this to an issue until you're ready to work on this again?

**Comment by kaktus40** [comment]
From the time this PR is opened, I don't think that adding two months change something :-). I'm not a pro of git but if the PR is closed, should I make a new branch or an update on the branch reopen the PR?

Envoyé par BlueMail<http://www.bluemail.me/r?b=10066>
Le 21 juil. 2017, à 20:12, Gabby Getz <notifications@github.com<mailto:notifications@github.com>> a écrit:

@kaktus40<https://github.com/kaktus40> Is it OK if we close this PR for now and move this to an issue until you're ready to work on this again?

**Comment by ggetz** [comment]
Your branch will remain in your fork of cesium, and you can work on it there. You can re-open this PR when it's ready to go. I've open #5666 so we don't forget!

**Comment by kaktus40** [comment]
It's ok for me to close in this condition

Envoyé par BlueMail<http://www.bluemail.me/r?b=10066>
Le 21 juil. 2017, à 21:15, Gabby Getz <notifications@github.com<mailto:notifications@github.com>> a écrit:

Your branch will remain in your fork of cesium, and you can work on it there. You can re-open this PR when it's ready to go. I've open #5666<https://github.com/AnalyticalGraphicsInc/cesium/issues/5666> so we don't forget!

**Comment by ggetz** [comment]
Thanks @kaktus40 

@pjcozzi Could you please close this PR for now?

**Pull request closed without merging**
