### PR TITLE
Replace DeveloperError with new Check type

### PR DESCRIPTION
**Pull request by rahwang**
Part of #4794

### CODE REVIEW

**Comment by austinEng** [comment]
Looks good @rahwang. Please also add yourself to CONTRIBUTORS.md

**Comment by lilleyse** [comment]
Looks good to me too.

Also in the future make sure to create a branch off of master first.

**Comment by rahwang** [comment]
Ok! Sorry I forgot the new branch this time. Adding myself to CONTRIBUTORS.md @lilleyse

**Comment by lilleyse** [comment]
No problem, congrats on your first Cesium PR!

**Pull request merged**
