### PR TITLE
Honor devicePixelRatio take 3

### LINKED ISSUE #3249: Cesium looks aliased on MacBook Pro Retina display
@mramato perhaps this is due to #3233?

**master:**
image

**1.15:**
image

### PR DESCRIPTION
**Pull request by mramato**
This reintroduces #3233, but now uses the `image-rendering` CSS property to disable smooth scaling and avoid blurriness. Since this is a CSS4 property, it's not yet supported by all browsers (Safari/IE), so we detect if the property is supported and if it isn't, we fallback to full resolution rendering on those browsers so that the image is always crisp (at the cost of performance).

The other nice thing about this approach is that it's detect capability and not the browser itself, so when Safari and IE do add support, Cesium will automatically start taking advantage of it.

Given the previous false start, I'm in no rush to merge this, but I'm fairly confident that this is the right fix and tested out this branch on a variety of devices.

Fixes #3249

### CODE REVIEW

**Comment by pjcozzi** [comment]
I most likely will not be able to look at this until after the 1.17 release.  WebGL has been crashing my Mac.  I think the fan failed, but need to look into it.

**Comment by mramato** [comment]
No problem.  As long as we can get it merged in early Jan so it has time to sit in master in case before 1.18.

**Comment by mramato** [comment]
I'd like to get this into 1.18.  The better frame rate on android should also be a big plus for the new cardboard webvr support.

**Comment by pjcozzi** [comment]
Not sure when my Mac will be fixed.  @klim705 let's test this on your machine tomorrow.

**Comment by klim705** [comment]
It looks alright on my Mac. 
model-after

**Comment by pjcozzi** [comment]
Yeap, looks good!  Sorry for the delay.

**Pull request merged**
