### PR TITLE
sse-changes

### PR DESCRIPTION
**Pull request by lilleyse**
For #3177 

Updated `PerspectiveFrustum` and `QuadtreePrimitive` from `3d-tiles`.

I wasn't sure about the best way to test this besides checking the `sseDenominator` with a known value. But even then I'm just calculating it with the code already there.

### CODE REVIEW

**Comment by pjcozzi** [comment]
> I wasn't sure about the best way to test this besides checking the sseDenominator with a known value. 

That would be fine.  We could argue that it doesn't even need a test, but it would be better to have at least something and not just rely on higher-level tests.

**Comment by lilleyse** [comment]
I added a test.

**Comment by pjcozzi** [comment]
`QuadtreePrimitive` should be using `sseDenominator`: https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/QuadtreePrimitive.js#L447

**Comment by lilleyse** [comment]
I removed that line because it's not being used by anything.

**Comment by lilleyse** [comment]
Actually I see what's going on now, I'll make the change.

**Comment by lilleyse** [comment]
This is ready. That change needs to get into `3d-tiles` as well.

**Comment by pjcozzi** [comment]
Looks good.

**Pull request merged**
