### PR TITLE
Standardize object declarations.

### PR DESCRIPTION
**Pull request by mramato**
As discussed in #3329, jsDoc used to require object declarations of the type `var foo = function()`, but now properly suppoers `function foo()`. This changes streamlines all of our code to use the same style and also ends up shrinking the minified release output by a couple of kilobytes.

This also updates the test-only smallTerrain urls, which recently broken this afternoon with cesiumjs.org server changes and were causing some failing tests in all branches.

As far as I can tell, everything, including doc, is working as expected; but a second set of eyes is always appreciated.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Code, doc, and tests look good.

Does anyone else want to look at this?

**Comment by pjcozzi** [comment]
Last call if anyone else wants to look at this.

**Comment by pjcozzi** [comment]
@lilleyse just a reminder to please make this same change for the new classes in the `3d-tiles` branch.

**Comment by lilleyse** [comment]
> @lilleyse just a reminder to please make this same change for the new classes in the 3d-tiles branch.

Will do that soon, as well as merge master into 3d-tiles.

**Comment by ezze** [comment]
Guys, please, clarify the things. Is smallTerrain still available in Cesium? If yes, where is it hosted now?

I didn't find anything related to it in this pull request. Updated [Terrain tutorial](https://cesiumjs.org/tutorials/Terrain-Tutorial/) also has the only link to [quantized-mesh-1.0 terrain format](https://github.com/AnalyticalGraphicsInc/quantized-mesh). I remember that there was another one for smallTerrain.

**Comment by pjcozzi** [comment]
@ezze please ask questions like this on the Cesium forum.  See [Submitting an Issue](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#submitting-an-issue).

As for smallterrain, it was deprecated in May:
> Deprecated the smallterrain tileset. It will be removed in 1.11. Use the STK World Terrain tileset.

See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#18---2015-04-01

**Pull request merged**
