### PR TITLE
Add support for pointer events

### LINKED ISSUE #4495: Timeline should handle pointer events
From #4458, `Timeline` currently does not handle `pointer` events. It should do so.

### PR DESCRIPTION
**Pull request by erikmaarten**
- [ ] Timeline
- [ ] Timeline remove listeners on destroy
- [x] Animation
- [ ] Animation remove listeners on destroy
- [ ] Tests?

Fixes #4495.

Not sure about what kind of test could be useful here. Should I add tests that run only when PointerEvents are supported by browser running the tests?

### CODE REVIEW

**Comment by mramato** [comment]
Not sure tests are easily doable for this, so I wouldn't worry about them for now.

**Comment by mramato** [comment]
The one problem I found is that dragging the shuttle tick around on the Animation widget doesn't work.  For example, here is how it works with normal mouse events: 
scroll

But I can't seem to do that with the PointerEvents version.

**Comment by mramato** [comment]
@emackey do you want to look at this at all?

**Comment by mramato** [comment]
Dragging the timeline around is different as well.

Another good way to test this is to enable mobile emulation in the Chrome debugger, I'm not sure why, but that seems to be better about exposing pointer event related input issues.

**Comment by mramato** [comment]
I'm not 100% sure, but we may need to add `touch-action: none` as a CSS property on the `Timeline` and `Animation` widgets.  I'm not expert on PointerEvents, but I think that informs the browser that you actually care about the input.  @emackey or @bagnell  do you know for sure?  We already do this for the CesiumWidget canvas itself.

**Comment by emackey** [comment]
I'll have to make time to do a full review, but a quick glance suggests this treats pointerevents just like mouse events, so for example pinch-zoom would likely not work here (I haven't tried it though, I'll have to bring in my tablet).  Also I think we would want `touch-action: none` on the timeline and animation widgets.

**Comment by erikmaarten** [comment]
@mramato @emackey Thanks for the feedback. I think I need to do a retake on this, I'll try testing things with mobile emulation in Chrome, and see what I can do about pinch-to-zoom. Perhaps I'll need to rethink re-using the mouse event handlers.

**Comment by mramato** [comment]
I think reusing the handlers is the right approach, that's what we do elsewhere,  I would have to dig into this more to understand why the problem I found is happening.  Hopefully @emackey can beat me to it.

**Comment by erikmaarten** [comment]
With mobile emulation on Chrome, it seems to work as intended for half a second or so, then the mouse move callback is no longer called. Is this what you see too @mramato?

**Comment by erikmaarten** [comment]
It does indeed work when the `touch-action` property is set to `none`. I still need to make adjustments here for pinch-zoom to work though.

**Comment by erikmaarten** [comment]
@mramato @emackey do you know of any good way to test pointer events with pinch-to-zoom without a real device that supports that?

**Comment by emackey** [comment]
@erikmaarten No it should be tested on a real device.  I'll try to make time this weekend to test/review this on my Surface Pro at home.

**Comment by emackey** [comment]
So unfortunately it doesn't look like this is working, at least not for pinch-zoom on the timeline although most of the single-touch actions are OK.  Part of the problem is that pointer events don't return a full "list of active touches" like Apple touch events do, so it's up to client code to gather up movements of different touches and work out what the pinch-zoom gesture is doing.  In other words, if two pointers are actively pinch-zooming, you'll only see movement on one pointer per event and it's your app's responsibility to remember where the other pointer is.

@mramato I'm starting to think that Timeline & Animation should be upgraded to make use of ScreenSpaceEventHandler.  We were opposed to this before when SSEH was mostly an empty shell, but, these days the class has logic inside it for "capturing" pointers, and managing its own list of active pointers for the sake of multi-pointer gestures.  Also, notice that a lot of code in this PR reads like a copy-and-paste from SSEH, and indeed the remaining problems are that we actually didn't copy and paste enough logic from the pointer events side of things.

So I see two paths forward, one is to copy yet more logic from ScreenSpaceEventHandler, and the other is to scrap the existing native event wireup and use ScreenSpaceEventHandler directly.  @mramato thoughts?

**Comment by pjcozzi** [comment]
What is the plan with this pull request?

**Comment by erikmaarten** [comment]
@mramato any thoughts on the above?

**Comment by pjcozzi** [comment]
I'm not familiar with the code, but it sounds totally reasonable for Timeline & Animation widgets to use ScreenSpaceEventHandler.

@erikmaarten do you also agree with this direction?

**Comment by erikmaarten** [comment]
It does sound reasonable to use the functionality of ScreenSpaceEventHandler here (though I'm not deeply familiar with it). I suggest starting one PR each for Animation and Timeline, switching them over to use ScreenSpaceEventHandler. If everyone's on board with this, I'll start with a PR for Animation.

**Comment by mramato** [comment]
I'm okay with using SSHE if it encapsulate logic that we need anyway.  In the long run, it might be beneficial to have all internal Cesium mouse/pointer handling go through a common abstraction layer.

**Pull request closed without merging**
