### PR TITLE
Add Standard WMS 1.3 Support

### PR DESCRIPTION
**Pull request by cwgrant**
For WMS 1.3, use CRS query string parameter to request projection.  SRS is still used for older versions.  Some implementations of WMS are backwards compatible but CRS is consistent with specification (http://www.opengeospatial.org/standards/wms).

Note that CRS:84 is used for the CRS label rather than EPSG:4326 to preserve lon,lat ordering.

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @cwgrant!  We'll try to review this soon.
In the meantime, can you please send over a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)?  We'll need that before we can merge this pull request.  Thanks!

**Comment by pjcozzi** [comment]
Thanks again, @cwgrant, this looks nicely done!

@kring do you have time to review this?

**Comment by cwgrant** [comment]
CLA sent in - let me know if there are any issues.

**Comment by pjcozzi** [comment]
@tfili are you familiar with this part of WMS?  Perhaps you could also review this?

**Comment by tfili** [comment]
Thanks @cwgrant. Looks good to me.

**Pull request merged**
