### PR TITLE
Remove open street map imagery provider

### LINKED ISSUE #3222: Remove OpenStreetMapImageryProvider
Deprecated in #3146.

### PR DESCRIPTION
**Pull request by TomPed**
Fixes #3222

Cherry picked commits from #3421

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @TomPed!

**Comment by TomPed** [comment]
@hpinkos wait a second. I'm getting this error when I try to load sandcastle:

screen shot 2016-04-13 at 2 43 53 pm

**Comment by hpinkos** [comment]
Did you `npm run build` after removing the file?

**Comment by TomPed** [comment]
Oh right. Cesium.js still is looking for the file. Okay thanks.

**Pull request merged**
