### PR TITLE
Get rid of defineSuite

### PR DESCRIPTION
**Pull request by mramato**
Cesium traditionally had a custom `defineSuite` function that wrapped both the `define` used for importing requrejs modules and the `describe` used to define a jasmine test block.

In order to move to ES6, we need to get rid of this helper function and just use separate`define`/`describe` calls. Then, when we move to ES6, the describe calls will stay as-is and the define call will be replaced with ES6 module imports.

Since we also overloaded describe calls for category support, this was an easy change to make and has zero functional changes.

To make the diff easy, I left indentation as-is.  When we move to ES6, the indentation will actually go back to being correct.

This is a test-only change.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/jazzy/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Bump.  Now that the release is out, it would be a good time to get this merged.

CC @OmarShehata

**Comment by OmarShehata** [comment]
I was hoping to see two separate commits, one for the codebase-wide find all and replace, and one for the non-automated changes like the docs, `spec-main.js` and `customizeJasmine.js` to make it easier to review - but this seems to work pretty well.

Was there anything else the custom `defineSuite` did other than allow us to avoid having to write the name of the file twice in each spec?

**Comment by mramato** [comment]
> Was there anything else the custom `defineSuite` did other than allow us to avoid having to write the name of the file twice in each spec?

Nope. (Technically yes it had a second parameter that was a category, but it also did this for descrive already so it's zero functionality change).

**Comment by mramato** [comment]
> `spec-main.js` and `customizeJasmine.js` to make it easier to review - but this seems to work pretty well.

Also, there were no "changes" in this files per-se, it was just straight up delete the function.  The diff is really not bad at all.

**Comment by OmarShehata** [comment]
> Also, there were no "changes" in this files per-se, it was just straight up delete the function. The diff is really not bad at all.

It was more just that it was hard to find which files had these deletions among all the find-and-replace spec files.

**Pull request merged**
