### PR TITLE
glTF 1.0.1 default material

### PR DESCRIPTION
**Pull request by lasalvavida**
Part of #4009. Merge #4249 first.

### CODE REVIEW

**Comment by pjcozzi** [comment]
CC @lexaknyazev - glTF 1.0.1

**Comment by pjcozzi** [comment]
Couldn't this use or adapt [modelMaterialsCommon.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/modelMaterialsCommon.js) like [gltfDefaults.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/ThirdParty/gltfDefaults.js)?

**Comment by pjcozzi** [comment]
@lasalvavida should we close this PR and open a new one when 1.1 changes are ready?

**Comment by lasalvavida** [comment]
Yes. This will actually just be part of the gltf pipeline integration.

**Pull request closed without merging**
