### PR TITLE
Fix sun uniform

### PR DESCRIPTION
**Pull request by lilleyse**
For #3141

### CODE REVIEW

**Comment by pjcozzi** [comment]
Good catch. Update CHANGES.md and include a link to #3141.  We'll ship this with 1.16.

**Comment by lilleyse** [comment]
Updated CHANGES.md

**Comment by mramato** [comment]
I can confirm that this fixes the issue.  I was talking to @lilleyse offline as to why this ever worked on any system to begin with, and we think that correct implementations end up giving the uniforms default values, where as my phone's driver does not. (this is just conjecture though).

The end result is that this change affects the desktop as well, as you can see from the below screenshots and the end result is more correct visualization on all devices.

master:
image

this branch:
image

**Comment by mramato** [comment]
Thanks @lilleyse

**Pull request merged**
