### PR TITLE
Keep camera position during a morph when duration is 0.0

### LINKED ISSUE #451: Clean-up Columbus-view morph
From our Santa experience:

Free-roam 3D to Columbus-view morph should not result in the lame top-down view.

### LINKED ISSUE #1518: Toggling scene modes quickly leads to crash
From the mailing list: https://groups.google.com/d/msg/cesium-dev/Hc9r4hVfq1w/PBF4XVpPdRQJ

Run the [jQuery Sandcastle demo](http://localhost:8080/Apps/Sandcastle/index.html?src=jQuery%20UI%20Demo.html&label=Showcases) and quickly switch between scene modes (without waiting for them to finish).  You will quickly crash.

### LINKED ISSUE #2065: Camera jumps at the end of morphTo3D transition
To reproduce: https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/

1. click columbus view
2. drag the map to center somewhere in Africa
3. click 3d, observe the smooth transition but with the sudden jump back to US at the end

If it is to center back to US, the rotation should be part of the transition.  But I think if the user interacted with the map (with 2), the current center should persist after the morph.

### PR DESCRIPTION
**Pull request by bagnell**
For #1060.

Fixes #2065. May also fix #1518 and #1845, though I couldn't reproduce #1845 in master either.
Might want to close #451 too since the morph view at the end is whatever the user set it to.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@bagnell @mramato let me know when the kinks are worked out, and I will take a quick look at the code.

**Comment by bagnell** [comment]
@pjcozzi This is ready for another review. I decided for an incremental improvement until the other issues can be resolved.

If the duration is `0.0`, the camera will maintain its position and orientation. In the Sandcastle, add `viewer.sceneModePicker.viewModel.duration = 0.0;`. Also, the issues mentioned above should still be fixed.

**Comment by pjcozzi** [comment]
Code is OK with me.  @mramato can you test and merge?

**Comment by mramato** [comment]
I do not agree with going back to the old fly out behavior.  I also think it's confusing from a usability standpoint to have the camera stay where it is when duration is 0 vs fly out if it's non-zero.  I'm super excited about the other morph fixes though (no more crashes!)

@bagnell can you please list what the remaining issues were that caused us to go back to the old behavior?  The only thing I notice is jitter and tile seems.

In my opinion the graphical glitches during the morph are well worth the tradeoff to be able to morph in all cases without losing position.  I'm not sure if others had time to see it in action, but `git checkout 472d512cdf554fd1573dc4b42285b1743e66d741` in order to see for yourself.  I'd be interested to hear what others' opinions are.  If no one cases that we're still flying out, then I won't object to merging this; but it's such a common complain on the forum that I feel it's worth keeping the position around.

**Comment by hpinkos** [comment]
> I do not agree with going back to the old fly out behavior

:+1:  People hate that they lose their position

But I don't think the morph in commit `472d512cdf554fd1573dc4b42285b1743e66d741` is quite right either.  The morph between CV and 2D is good because even when you're zoomed in, you have a sense of what just happened.  3D to 2D, it's just weird to see the globe do a wiggle then stop.  There's no context.
It's a little silly, but I think flying out, doing the morph, then flying back in is a better solution.
And I think it should tilt when you get into CV, otherwise you don't notice that the mode is any different from 2D until you use the middle mouse button.

Either way, I think this is a huge improvement.  I haven't been able to switch between scene modes without the browser crashing in forever, so that's 100% worth merging in.

**Comment by pjcozzi** [comment]
This incremental improvement is OK with me.  The user this is for is just going to do a `duration=0` "morph."  We can revisit as time allows.

**Comment by bagnell** [comment]
@mramato Those are the only two issues. For the second, it's not just cracks between tiles. There are whole tiles missing for certain views because the quadtree isn't updated during the morph.

@mramato @pjcozzi @hpinkos What are we doing with this PR?

**Comment by hpinkos** [comment]
I'm in favor of merging this in.  I think there are some additional improvement that can be made further down the line, but this is much better than what we have now.

**Comment by mramato** [comment]
I changed the title so when people stumble on this they don't get their hopes up.  I just hope we eventually get back to making this work in all cases.

**Pull request merged**
