### PR TITLE
Zoom out from mouse cursor

### PR DESCRIPTION
**Pull request by bagnell**
For #2834.

### CODE REVIEW

**Comment by mramato** [comment]
Definitely an improvement.  One problem I see is that horizon/tilted views closer to the earth have problems when you zoom out without zooming in first.

**Comment by mramato** [comment]
Here's an example: http://localhost:8080/Apps/CesiumViewer/index.html?view=-111.94315241388823%2C35.686608457338345%2C4650.194613245701%2C11.293618898219192%2C-10.955901470244825%2C0.17868136467470513  It happens whether you zoom in first or not.  Grab the right side of the screen and zoom out some, the camera will pull hard in one direction (away from the mouse focus).

**Comment by bagnell** [comment]
@mramato This is ready for another look.

The hard pull in one direction is because the zoom behaves the same way as if it was looking straight down. We should wait for feedback before we change how it zooms for different pitch angles.

**Comment by mramato** [comment]
Thanks @bagnell this is definitely better and fixes #2834.  I'm sure there's room for improvement but as you said, we'll get plenty of feedback once this is live.

**Pull request merged**
