### PR TITLE
Tilted CV view and adjust transition from 2D to CV

### LINKED ISSUE #3878: Default CV view is now straight down like 2D
For example, just switch to CV in Viewer: http://cesiumjs.org/releases/1.20/Apps/CesiumViewer/index.html

Was this change intention?

### PR DESCRIPTION
**Pull request by ggetz**
Fixes #3878.

Columbus view now has a tilt and the animation from 2D to CV has been updated.

Based on the PR by @JoshuaStorm in #3983. I followed his camera setup for CV, but updated the transition to be smoother and crashes no longer happen when transitioning.

There is a slight jump in the transition from CV back to 2D, but that is the current behavior in master. I believe it is from the FOV switch from perspective to orthographic.

### CODE REVIEW

**Comment by ggetz** [comment]
Updated.

**Comment by pjcozzi** [comment]
@ggetz can you please merge in master and I'll test and merge?

**Comment by ggetz** [comment]
@pjcozzi Merged!

**Comment by pjcozzi** [comment]
@ggetz did you mean to delete your update to CHANGES.md?  I will update it.

**Comment by pjcozzi** [comment]
The new morph is good with me.

**Comment by ggetz** [comment]
> did you mean to delete your update to CHANGES.md? I will update it.

No, that was an accident.

**Pull request merged**
