### PR TITLE
Cesiumjs.org deployment

### PR DESCRIPTION
**Pull request by ggetz**
* Revert changes from previous deployment PR
* Adjust args in `.travis.yml` for this branch

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@ggetz, thanks for the pull request! Maintainers, we have a signed CLA from @ggetz, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Is there any clean-up that needs to be done in master for code that is no longer needed there?

**Comment by ggetz** [comment]
No, that code was reverted in master already.

**Comment by ggetz** [comment]
There's an error with deleting objects I need to take a look at before this gets merged.

**Comment by mramato** [comment]
Please work with @bagnell if there are any merge conflicts into cesiumjs.org from master as part of today's release.

**Comment by ggetz** [comment]
@bagnell `gulpfile.js` should merge fine, just make sure to use this version of `.travis.yml`.

**Pull request merged**
