### PR TITLE
Polygon graphics document default values updated

### PR DESCRIPTION
**Pull request by abuDarda97**
Hey @OmarShehata I updated the documentation, let me know if more changes need to be made.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @abuDarda97!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/PolygonGraphicsDoc/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks @abuDarda97 ! To help me out, can you post the lines of code that show where the default is being created to that value so I can easily verify?

Also, did you do a "find all" across all the files of code in the `Source/` folder to see if there are any other `heightReference` values that are similarly missing a doc in other files?

**Comment by abuDarda97** [comment]
@OmarShehata The default `heightReference` value is defined here https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/PolygonGraphics.js#L156 

For `extrudedHeightReference` it is stated here https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/PolygonGraphics.js#L173

I just carried out a find all search query for `heightReference` under the `Source` folder. I found a few files where the default value for `heightReference` is missing. I would update these files ASAP.

**Comment by hpinkos** [comment]
Thanks or the PR @abuDarda97!   This looks fine to me.

**Pull request merged**
