### PR TITLE
Set color expressions

### PR DESCRIPTION
**Pull request by ggetz**
I set the `color` property in `Cesium3DTileStyle` to the expression specified in the json if it is a string. If another type is supplied, I set color to undefined. I deleted `LiteralColorExpression` and the spec.

In Cesium3DTileStyleEngine I also check if the color expression evaluates to a `Color`.

I added more tests in `Cesium3DTileStyleSpec`, and some to check if the color style is applied in `Cesium3DTilesetSpec`. I only checked opaque colors since I wasn't sure how to check if transparent color are applied? 

I also updated the sandcastle example.

### CODE REVIEW

**Comment by pjcozzi** [comment]
> I set the color property in Cesium3DTileStyle to the expression specified in the json if it is a string. If another type is supplied, I set show to undefined.

I'm confused, why would we set `show` to `undefined` here?

**Comment by pjcozzi** [comment]
> In Cesium3DTileStyleEngine I also check if the show expression evaluates to a Color.

I don't get it.  Why?  `show` and `color` are separate properties in the JSON schema.

**Comment by ggetz** [comment]
Sorry, I copy/pasted my lasted PR because it was similar and missed those two instances. I edited it so it should make more sense now.

**Comment by pjcozzi** [comment]
OK, makes sense now.

Code looks great.

> I only checked opaque colors since I wasn't sure how to check if transparent color are applied?

An easy thing to do is to set the alpha to zero and verify that it did not render, for example: https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles-style/Specs/Scene/Cesium3DTileBatchTableResourcesSpec.js#L457-L460

**Comment by ggetz** [comment]
> An easy thing to do is to set the alpha to zero and verify that it did not render 

OK, thanks.

**Comment by ggetz** [comment]
Updated.

**Comment by pjcozzi** [comment]
Did you push?  I don't see the commite.

**Comment by ggetz** [comment]
Whoops, I just needed to pull your changes.

**Comment by pjcozzi** [comment]
:+1:

**Pull request merged**
