### PR TITLE
Untrack entity when double-clicking away

### PR DESCRIPTION
**Pull request by adridavid**
Fixes [#5959](https://github.com/AnalyticalGraphicsInc/cesium/issues/5959)

This modifies the viewer default input action for the LEFT_DOUBLE_CLICK event type.
If an entity is being tracked by the viewer, double-clicking away from it (except on another entity) will untrack the entity.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @adridavid! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/doubleclick-untrack/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Thanks again @adridavid, we received your CLA.

**Comment by hpinkos** [comment]
Thanks @adridavid!  This is a change I've wanted to make for a while.

**Comment by hpinkos** [comment]
Added a note to CHANGES here: https://github.com/AnalyticalGraphicsInc/cesium/commit/d6c71103640b7a170eae514c07bc8381acc8cb17

**Comment by emackey** [comment]
This is a good change, thanks @adridavid and @hpinkos

**Pull request merged**
