### PR TITLE
Use joinUrls function for path building in 3d-tiles

### PR DESCRIPTION
**Pull request by hpinkos**
This is a PR into the 3d-tiles branch

This preserves any query strings that may be added to the 3D tiles url
Requested by @mramato 

I'm pretty sure this covers all cases, but let me know if you think I missed something.

### CODE REVIEW

**Comment by mramato** [comment]
@lilleyse Can you review this?  Are there any other places where 3D tiles makes calls based on the root URL?

@hpinkos please add tests to verify query parameters are preserved in each case.

**Comment by pjcozzi** [comment]
Does this need to be threaded through for glTF external resources: .bin, images, and .glsl?

**Comment by mramato** [comment]
> Does this need to be threaded through for glTF external resources: .bin, images, and .glsl?

Yes.  Ultimately, it needs to be threaded through almost anywhere in the codebase where we currently just use `+` to glob two urls together.

**Comment by hpinkos** [comment]
Okay, I found the model stuff so I'll thread that through.

I really have no idea how to test this though.

**Comment by lilleyse** [comment]
The changes to 3d tiles look good, those are the only cases.

For testing you can add something simple to `Cesium3DTilesetSpec` similar to this test:

```javascript
it('url and tilesetUrl set up correctly given directory with trailing slash', function() {
```

**Comment by hpinkos** [comment]
@lilleyse ready

**Comment by lilleyse** [comment]
I made a few small edits, but this looks good to me.

**Comment by hpinkos** [comment]
Good catch @lilleyse, thanks!

**Comment by mramato** [comment]
Thanks @hpinkos and @lilleyse!  `getBaseUri` needs new unit tests to cover the functionality you added to it.  Please open a new PR with them when you get a chance.

**Pull request merged**
