### PR TITLE
bug fixed: empty flights when position remains

### LINKED ISSUE #3457: camera.flyTo not working when in 2D mode and only orientation changes
camera.flyTo not working when in 2D mode and destination remains but orientation changes.
I'm quite sure this happens because of line 303-304 in CameraFlightPath:
`var empty = scene.mode === SceneMode.SCENE2D;`
`empty = empty && Cartesian2.equalsEpsilon(camera.position, destination, CesiumMath.EPSILON6);`
`empty = empty && CesiumMath.equalsEpsilon(Math.max(frustum.right - frustum.left, frustum.top - frustum.bottom), destination.z, CesiumMath.EPSILON6);`

### PR DESCRIPTION
**Pull request by Larcius**
bug fixed: concerning heading/pitch/roll in 2d as well to not wrongly create an empty flight when camera position remains

fixes #3457

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @Larcius!  Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) before we review this?

**Comment by pjcozzi** [comment]
We now have a CLA from @Larcius.  Thanks!

**Comment by hpinkos** [comment]
Functionality looks fine.
But there's one test failure in `CameraFlightPathSpec`: 
`Scene/CameraFlightPath duration is 0 when destination is the same as camera position in 2D`

I think it's an error in the test though.
Adding `camera.update(scene.mode)` after `camera.frustum = createOrthographicFrustum();` (line 255) should fix the problem.

**Comment by pjcozzi** [comment]
Also, please update CHANGES.md.  Thanks for the contribution, @Larcius!

**Comment by hpinkos** [comment]
@Larcius can you merge in master?  It looks like there's a conflict.  It's probably just in CHANGES.md

**Comment by hpinkos** [comment]
Thanks @Larcius!  This looks great.

**Pull request merged**
