### PR TITLE
Imagery Provider Resource Fix

### PR DESCRIPTION
**Pull request by ProjectBarks**
This solves an issue where `createOpenStreetMapImageryProvider` would improperly handle a `Resource` object. 

I also fixed up `MapboxImageryProvider` to work in a more standardized and expected way. 

This is related to https://github.com/AnalyticalGraphicsInc/cesium/issues/4812

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ProjectBarks!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/imagery-provider-resource-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Looks like you have some test failures

**Comment by ProjectBarks** [comment]
@mramato Good catch. Submitted relevant changes.

**Comment by mramato** [comment]
Thanks!

**Comment by thw0rted** [comment]
I know this is already merged, but the current changes forgot to update the relevant documentation.  Is it all generated from the JSDoc blocks?

**Comment by OmarShehata** [comment]
@thw0rted the docs are indeed generated from the JSDoc blocks. You can run `npm run generateDocumentation` to see the docs locally.

**Pull request merged**
