### PR TITLE
Fixed "Scene/Model loads a glTF 2.0 with vertex colors" test on mac

### PR DESCRIPTION
**Pull request by IanLilleyT**
Used a different model for this test. The old model and test were pretty strange. It moved the camera around to different regions of the model and sampled the color at different positions. The thing is, the regions being sampled were actually textures. I replaced the model with two side by side cubes, one red, one blue. The test is basically the same but it reflects the new model.

I don't know why the original test failed on mac. I loaded the old model in sandcastle on linux and mac and they looked exactly the same. It could be the test's scene setup is different than sandcastle in some small way, or maybe the test was too fragile with the camera positioning.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/macVertexColorTestFix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@IanLilleyT did we have an issue open for this? You should link it in your PR description

**Comment by IanLilleyT** [comment]
I don't think there was an open issue for this.

**Comment by IanLilleyT** [comment]
I submitted a new test model that actually has vertex colors in it. It's also a much more simple model, just two planes side by side. Should be good for merge now

**Comment by lilleyse** [comment]
Thanks @IanLilleyT

**Pull request merged**
