### PR TITLE
Add Ellipsoid options from some missing places.

### PR DESCRIPTION
**Pull request by emackey**
There are still several places where the `ellipsoid` parameter is not getting passed through certain layers of the API, and the default ellipsoid is used instead.  In particular the terrain & imagery providers, I know several of them are specifically for Earth but I can imagine a case where one wanted to select a different Earth-based ellipsoid than WGS84.  @kring if you have time I'd appreciate some feedback here, as my changes to terrain/imagery are mostly copy-and-paste from providers that did pass the ellipsoid option through.

This will be useful for non-Earth visualization, for example the [recent Mars discussion](https://groups.google.com/forum/#!msg/cesium-dev/WOQEeH5VsUE/ITzuMFY6IBoJ) and the upcoming Pluto encounter, etc.

**Questions**
- [x] Enabling Earth terrain on non-Earth ellipsoids causes bounding spheres to run wild, and visibility calculations are wrong.  See example below, un-comment one line.  Is this expected? (Answer: Yes, these bounding spheres come from the server, not Cesium, so cannot be customized).
- [x] Core/RectangleGeometryLibrary constructs a scratch default `GeographicProjection` on [line 72](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.9/Source/Core/RectangleGeometryLibrary.js#L72) and then uses it without any option to override it, guaranteeing use of WGS84, although this doesn't appear to be called by a typical empty CesiumViewer.  Is there a performant way to add and use an ellipsoid option or projection option here?  (Answer: not a priority at this time.)

**TODO**
- [x] Tests
- [x] CHANGES.md

Here's an example of a crazily distorted custom ellipsoid:

```
var ellipsoid = new Cesium.Ellipsoid(200000, 200000, 100000);

var imagery = new Cesium.TileMapServiceImageryProvider({
    url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII'),
    ellipsoid : ellipsoid
});

var terrain = new Cesium.CesiumTerrainProvider({
    url : '//assets.agi.com/stk-terrain/world',
    requestWaterMask : true,
    requestVertexNormals : true,
    ellipsoid : ellipsoid
});

var viewer = new Cesium.Viewer('cesiumContainer', {
    mapProjection : new Cesium.GeographicProjection(ellipsoid),
    imageryProvider : imagery,
    //terrainProvider : terrain,
    baseLayerPicker : false
});

viewer.scene.globe.enableLighting = true;
```

### CODE REVIEW

**Comment by kring** [comment]
> Enabling Earth terrain on non-Earth ellipsoids causes bounding spheres to run wild, and visibility calculations are wrong. See example below, un-comment one line. Is this expected?

Yeah I can't imagine this going well.  The horizon occlusion point is computed based on the WGS84 ellipsoid (or whatever was used when the tiles were generated).  If you then use a different ellipsoid to test it, you'll get... something.

**Comment by kring** [comment]
Your changes all look fine to me!

**Comment by emackey** [comment]
Thanks @kring.  To be clear, this PR is not about swapping ellipsoids on-the-fly.  The sample code above constructs a single ellipsoid and specifies it three times while constructing the viewer and its terrain and imagery, so ideally all layers of Cesium should be on the same ellipsoid.  Indeed the tile bounding spheres do work for the imagery-only case in this PR, but when terrain is enabled, somehow the bouding spheres get Earth-radius numbers mixed into the calculations.  You can see the effect clearly by adding `viewer.extend(Cesium.viewerCesiumInspectorMixin);` to the sample above.

I'll take one more pass at this, to see if I can find where WGS84 is still sneaking into things.  I know the scratch variables for several classes construct default projections with default ellipsoids, and there are likely still some places where it's impossible to override them.

**Comment by emackey** [comment]
So I got this input from @abwood:

```
The bounding spheres are precalculated serverside and included in the Quantized-Mesh header.
```

So the answer is yes, this is expected behavior, and it's not valid to try to assign a custom Ellipsoid underneath Earth terrain.  Presumably the user would need to specify the Mars ellipsoid to go under Mars terrain, etc.  I'll add some new tests and this PR will be done.

**Comment by emackey** [comment]
This is ready.

**Comment by kring** [comment]
> So the answer is yes, this is expected behavior, and it's not valid to try to assign a custom Ellipsoid underneath Earth terrain.

Yep, for exactly the reason Alex mentioned.  That's what I was trying (and failing!) to communicate. :)

**Comment by kring** [comment]
It'd probably be a good idea to include ellipsoid parameters in `layer.json` and then make `CesiumTerrainProvider` use that, instead of requiring the user to specify a matching ellipsoid.  But not exactly how priority...

**Pull request merged**
