### PR TITLE
Fix terrain exaggeration bug

### LINKED ISSUE #3676: Problems with terrainExaggeration parameter in version > v.1.16
I expected some problems with the the `terrainExaggeration` parameter in cesium versions >= 1.17. I used a `terrainExaggeration` value of 4.0 in version 1.16 and it works for me. In newer versions, my terrain / imagery isn't display anymore if zooming to higher zoom levels. My area of interest was europe.

I reproduced the error running the [sandbox application](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) with this code: 

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainExaggeration: 4.0
});

var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : '//assets.agi.com/stk-terrain/world'
});
viewer.terrainProvider = terrainProvider;
```

### PR DESCRIPTION
**Pull request by bagnell**
Fix terrain horizon occlusion point when exaggerated. Fixes #3676.

### CODE REVIEW

**Comment by mramato** [comment]
I can confirm the problem is fixed.

Is it possible to add a unit test for this?

**Comment by bagnell** [comment]
@mramato I created #3902 to create tests. `createVerticesFromQuantizedTerrainMesh` isn't tested at all.

**Comment by mramato** [comment]
Update CHANGES, since this is a pretty popular bug.

**Comment by bagnell** [comment]
@mramato CHANGES.md was updated.

**Pull request merged**
