### PR TITLE
Added a link to gltf-vscode to VSCode Guide

### PR DESCRIPTION
**Pull request by ryki2658**
added a brief description and link to gltf-vscode

### CODE REVIEW

**Comment by emackey** [comment]
Can this be added as an additional bullet point under "VSCode Plugins (mostly optional)" instead of a whole new section at the end?  Thanks!

Also... while you're at it, please rename "VSCode Plugins (mostly optional)" to "VSCode Extensions (mostly optional)".  My mistake originally.

**Comment by emackey** [comment]
Actually change "plugins" to "extensions" throughout for that.  Thanks!

**Comment by pjcozzi** [comment]
@ryki2658 it is great to see you contributing here as well as gltf-pipeline!

Could you please also add yourself to [CONTRIBUTORS.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md) in this branch?

**Comment by pjcozzi** [comment]
Fixes #5137

**Comment by ryki2658** [comment]
Ok I signed the CLA for cesium and made the appropriate changes to the file. Please let me know if there are any other modifications I should make.

**Comment by emackey** [comment]
Awesome, thanks @ryki2658.

**Pull request merged**
