### PR TITLE
Replace "use strict" by 'use strict'

### PR DESCRIPTION
**Pull request by sanuj**
PR for issue #3345.
I have changed it everywhere except the following:
* `Specs/ThirdParty`
* `node_modules/`
* `ThirdParty/`
* `Source/ThirdParty`

@pjcozzi Kindly have a look. I ran the tests on my machine and got `7193 specs, 41 failures, 1 pending spec`. I think the failures are not related to my changes. I have also signed the Contributor License Agreement.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @sanuj!  Did the same tests fail before the change?

@hpinkos can you review this?

**Comment by hpinkos** [comment]
@sanuj add yourself to [CONTRIBUTORS.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md)

**Comment by hpinkos** [comment]
@sanuj it looks like you removed this line from gulpfile.js: 
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/gulpfile.js#L857

You should add it back in

**Comment by hpinkos** [comment]
We use strings to generate code for Sandcastle demos and our build.  The double quotes can be changed to single quotes there as well.  Can you change these two files please?

There are 5 lines in `gulpfile` that can be changed, like this one: 
https://github.com/sanuj/cesium/blob/use_strict_cleanup/gulpfile.js#L283

https://github.com/sanuj/cesium/blob/use_strict_cleanup/Apps/Sandcastle/CesiumSandcastle.js#L516

**Comment by hpinkos** [comment]
@sanuj looks great! looks like you got pretty much everything!
I just had those two comments.  Let me know when you made those changes.

**Comment by mramato** [comment]
Thanks @sanuj.  Given how many files this PR touches, I'm going to merge this now and make those last few tweaks @hpinkos suggested myself in master.

Thanks again and congrats on your first Cesium commit!

**Comment by pjcozzi** [comment]
If anyone has new files in branches, please update them.

@lilleyse I'll update the new files in `3d-tiles` and `3d-tiles-style`.

**Pull request merged**
