### PR TITLE
Doc restyle

### PR DESCRIPTION
**Pull request by emackey**
Some weekend hacking after looking at some other API docs.

Note this includes [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro) which has an open license and I think we are allowed to redistribute, someone should double-check before merging.

/cc @mramato @ggetz

### CODE REVIEW

**Comment by pjcozzi** [comment]
> Note this includes Source Sans Pro which has an open license and I think we are allowed to redistribute, someone should double-check before merging.

Yes, we can redistribute it, but we need to update Cesium's LICENSE.md to include the text of their license: http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt

**Comment by ggetz** [comment]
This looks great, especially the hover hyperlinks for each section! I think this would work well if we included these changes with the current redesign of the website.

**Comment by mramato** [comment]
Awesome @emackey, this is a good step to improving doc overall.  Here's what it looks like on the new site. (click for the bigger version)

image

Since we're dealing with an iframe, the double scrollbar is an unfortunate consequence for now.  In the future, the double logo can probably be removed and banner color of the class name can probably be updated to better match the outer doc. Our long term plan is still to update the generate doc to be exactly what we host at http://cesiumjs.org/documentation.html, but that's still a significant effort away.

Unfortunately, it looks like the new chain links and the link to code on GitHub don't work in the embedded iframe version of the doc (this might have always been a problem but I wanted to mention it).

Do you want to make any tweaks based on the redesign, or is this ready to go?  I'm fine with taking this as-is since we can continue to make incremental improvements in the future.

**Comment by emackey** [comment]
Ideally I would love for the docs to not be iframed, so that the address bar stays in sync with what the user is seeing as they navigate around.  This may mean we need to have a separate template customized for the site, with some extra links that aren't in the stand-alone template.  Maybe the docs could even iframe in a nav bar from the site, rather than the site iframing in the docs.  Or maybe the stand-alone docs simply do have links back to the blog and getting started etc.  Thoughts?

**Comment by mramato** [comment]
jsDoc has the ability to extend the generated reference doc with tutorials and other content.  We also have great control over how the tree on the left gets generated.  My plan is to have the entire documentation section of cesiumjs.org (including tutorials which will no longer be blog posts) be generated as part of the offline documentation.  This will allow us to integrate the API reference tree directly into the left side-bar in the above image and also allow us to get rid of the iframe embedding.  It will also make tutorials easier to manage.  In short, this basically makes documentation it's own mini-site that people can run locally and then it blends in seemlessly when hosted on cesiumjs.org.

**Comment by emackey** [comment]
That sounds awesome.  One of the things I didn't get to in this PR is figuring out how to divide up the tree, so that for example Entity API is under a different heading from Primitive graphics etc., so it's easier to avoid accidentally intermingling them.

I updated LICENSE.md, so this is OK to merge now if you like, or you could hold onto it and we could work on the site integration.

**Comment by mramato** [comment]
Thanks @emackey, I don't see any reason to hold off on merging this.  We can continue to make small incremental PRs in the future.

We have an issue (I think) to eventually tag different objects as belonging to a specific namespace so that we can categorize the ref doc as you suggest.  We may want to go a step further and make Cesium.js reflect these categories as well (but that's probably a Cesium 2.0 modularization thing).

**Pull request merged**
