### PR TITLE
Documentation fixes

### LINKED ISSUE #5586: OrthographicFrustum missing from documentation
OrthographicFrustum is missing from the documentation. I see that `@alias OrthographicFrustum` got changed (#5021) to `@alias OrthographicOffCenterFrustum` so the documentation got merged with OrthographicOffCenterFrustum. Was this on purpose? This creates duplicate near/far entries in the [OrthographicOffCenterFrustum documentation](https://cesiumjs.org/Cesium/Build/Documentation/OrthographicOffCenterFrustum.html#far).

Also the example code in OrthographicFrustum.js got changed to use OrthographicOffCenterFrustum instead of OrthographicFrustum.

### PR DESCRIPTION
**Pull request by slozier**
Fixes #5586 and other documentation issues.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks again @slozier!  @ggetz do you want to review this?

**Comment by ggetz** [comment]
Looks good, @slozier. Please update CHANGES.md.

**Comment by hpinkos** [comment]
Thanks @slozier

**Comment by pjcozzi** [comment]
@hpinkos please update CHANGES.md in master (it was requested above).  Even though this is a doc fix, it fixes a GitHub issue and exposes a "new" class.

**Comment by hpinkos** [comment]
@pjcozzi done 05b9dcec4e7e61476ff3055cf9c8bb8a08cd43d4

**Pull request merged**
