### PR TITLE
Added WebGLConstants class

### PR DESCRIPTION
**Pull request by lilleyse**
For #2989 

I confirmed that this works for r189569. Though I can't confirm that the specs pass because the page crashes.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Update CHANGES.md.

**Comment by pjcozzi** [comment]
Looks good to me.  I won't have my Mac until Monday.  Can someone verify this and merge?

@lilleyse update CHANGES.md in master if this gets merged beforehand.

**Comment by lilleyse** [comment]
Updated the rest of the hard-coded constants to use the new class.

**Comment by pjcozzi** [comment]
Looks good and fixes Safari, thanks @lilleyse.

**Pull request merged**
