### PR TITLE
Fix style colors interfering across tilesets

### PR DESCRIPTION
**Pull request by OmarShehata**
In [this Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=nVVtT9swEP4rVvahyVScUGCTaEGrQBpIoLG226d8cZJL6y2xK9sJK4j/vnNeG8YQW1Qltu/1uTs/LZkiJYd7UOSMCLgnF6B5kdPv1Zk7iqvthRSGcQFq5E1DEYoSrb4tbtCkUb+WYgFaFioGmiqZz7UGc524H4KPx97U98n88zW5+hoK36/tRpT63W++3Wp/yfJtBpfMML92enS54hlov3qD6Ra+qb/0h5ZiZJ0vuTVVJDpKctJI6ySbzRDbwD0Y9zEUBJ9CZacWVSieapRtHAUs2d0hKq6Bmg0INy1EbLgUbqPikcZHa6LNLoO/R11acRvXPrHMpDolo+rrhs67IEjxCR1vVCtVKdlF/a5bRnUMAuhW8ZwbXoKmLEm6nKYD1Qcp85VsheP9zK4QHxfrO27izYKJNbgBDcbkIKAn4w5RJAthtZbbDSigCk0KTd6TCQ28YW7YkFtZQt+IKgtsRsyUkWvFthse96NzsXdazY49QBHrqvs8NoI2oDp86FkXKmUxDJ1WPo4qlwvMlgnt7mdAMynW3BQJjMnwnJnmGMuwH0WmaT1L/xOEHFh3QXB48tZwRqE3K5XixZi6iFAlNm6d17itwqC3vb7btaktay4TyG6ZUfxXH6DeH1eIVn0G7l421s+TRyVeBXWPd6K/DqCUVN1liKXQMgOswbqRTLu7ZZmAzEvJExI6qqEOwjVhWXXdSATYcJICziQkoUMqByTaERxxK2EIIwdZ4HwhllW97jPxHvcKWeOdvIkFhkzQXb1B5SavUUIHf2Dwr4TwIimkqaWFnhSeZfdGYpi0c/BaDwfc9EIbu9BPY3KIY+1NnbEzq1Ce19JPSMpSGVtMFzneAHI0w1n0oyL+idMXa23tZ35rNEt4SXhyFjrP/nSw+3HGtEZJWmTZkj9A6JzPfNQfmGWy4rEvJaiM7azK5vD8pj6klM583P5pZaTMIqb2PP4G), there are two tilesets, each has a different color style. But if you zoom out so both are in view, they will be colored the same.

If you zoom in to one or the other, they will each have the right color. This is happening because a scratch variable is being re-used across all b3dm's:

https://github.com/AnalyticalGraphicsInc/cesium/blob/54acd32f50c332605615a7b37b774c04690ef55c/Source/Scene/Batched3DModel3DTileContent.js#L458

This only happens for tilesets that have 0 features.

I'm not sure if a more elaborate fix is needed here - should `model.color` have a setter, and use the underlying `._color` to keep track of when it changes etc? I noticed there was a `model._color` that wasn't being used for anything, which I've removed in this commit.  

This came up in [this forum thread](https://groups.google.com/d/msg/cesium-dev/jLoxC7jcbFY/IZeGDv6EBwAJ). 

Todo:

* [x] Update CHANGES
* [ ] Add some color tests?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/style-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks @OmarShehata!  This fix looks good.  I'll merge this as soon as CI passes

**Comment by OmarShehata** [comment]
Thanks for pushing this over the finish line @hpinkos !

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/jLoxC7jcbFY/IZeGDv6EBwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/8051 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Pull request merged**
