### PR TITLE
Replace gulp-eslint with eslint's CLIEngine

### PR DESCRIPTION
**Pull request by omh1280**
For #5449.

I replaced `gulp-eslint` in favor of the (more powerful and customizable) [`CLIEngine`](http://eslint.org/docs/developer-guide/nodejs-api#cliengine). This allows ESLint to use the `--cache` option, which brings `npm run eslint` from ~18s to ~2s.

Overall, the two affected tasks now look much less "nodey" and gulpy".

@mramato: It feels wrong to throw an Error, but it seems to be how you "fail" gulp tasks. Also, is it OK that this does not return a `Promise` or `stream`? Thanks!

### CODE REVIEW

**Comment by pjcozzi** [comment]
Sounds cool.

Will CI also have the performance impact or is this just for incremental runs?

**Comment by omh1280** [comment]
Unfortunately, just for incremental runs

**Comment by pjcozzi** [comment]
Gotcha.

**Comment by omh1280** [comment]
@mramato Mind doing a final review?

**Comment by mramato** [comment]
@omh1280 This PR is totally fine, but I ended up opening #5502 to replace this PR instead.  Let me know what you think and if you have any questions about it.

**Pull request closed without merging**
