### PR TITLE
fixed "funciton" typo in EllipsoidGeodesic

### PR DESCRIPTION
**Pull request by leesafini**
Fix for issue #4480

### CODE REVIEW

**Comment by lilleyse** [comment]
Looks good. Add yourself to `CONTRIBUTORS.md` and this will be ready to merge.

In the future you should branch off master before opening a pull request. This will make it easier to keep your local master safe from any local changes.

Also in the description box it is often convenient to write:

Fixes #4480

So that github automatically closes the referenced issue when the pull request is merged. This will also link the issue to this pull request so you don't need to update the original issue.

**Comment by leesafini** [comment]
Should I submit a new PR with a branch off master or is this fine? I've update contributors.md

**Comment by lilleyse** [comment]
> Should I submit a new PR with a branch off master or is this fine? I've update contributors.md
View changes

It's fine.

**Comment by lilleyse** [comment]
Thansk @leesafini!

**Pull request merged**
