### PR TITLE
Stop slow Camera inertia

### LINKED ISSUE #2839: Camera inertia takes way too long to finish
I noticed both in the camera move events example and via #2838 that the camera inertia takes several seconds to finish after the user lets go of the mouse.  It seems it continues to move a minuscule amount < 1 meter for several seconds.  This greatly decreases the usefulness of the move events because it creates what is perceived as lag.  We should shorten the inertia or have a cut off that once the inertia is less than a certain amount, we just stop.

### PR DESCRIPTION
**Pull request by bagnell**
Stop camera inertia when only moving small amounts. Fixes #2839. 

I couldn't reproduce #2715 which is related according to the issue and can probably be closed.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Update CHANGES.md.

Is there a reasonable test we could add that simulates the camera movement and tests that the inertia ends in a given time?

**Comment by pjcozzi** [comment]
Just that comment.  I can confirm both #2839 and #2715 are fixed.

**Comment by bagnell** [comment]
>Is there a reasonable test we could add...?

I don't think so. The camera inertia isn't tested at all right now.

**Comment by pjcozzi** [comment]
OK.

**Pull request merged**
