### PR TITLE
Fix signed distance to bounding sphere.

### LINKED ISSUE #6451: Model clipped inappropriately
While experimenting with lighting options for a glTF model provided in https://github.com/KhronosGroup/COLLADA2GLTF/issues/172, I discovered the model sometimes disappears from view while moving the camera.  This didn't start happening until I merged master into my branch, bringing in logDepth along with it.

Git bisect isolates a specific commit from LogDepth where the problem is introduced:  0d90d985b0179003b2

The original model from that issue has some un-related validation errors, here's a cleaned-up copy of the model:

[Collada2gltf_issue172.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/1916877/Collada2gltf_issue172.zip)

And the reproduce code:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    infoBox : false,
    selectionIndicator : false,
    shadows : false,
});

function createModel(url) {
    viewer.entities.removeAll();

    var position = Cesium.Cartesian3.fromDegrees(-123.074085, 44.050050, 10);
    
    var heading = Cesium.Math.toRadians(-20);
    var pitch = 0;
    var roll = 0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            scale: 10,
            uri : url,
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });
    viewer.trackedEntity = entity;
}

createModel('../../SampleData/models/emackey/Collada2gltf_issue172.gltf');
```

Here's the bad behavior:

logdepthclipissue

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #6451.

CC @emackey

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@bagnell, thanks for the pull request! Maintainers, we have a signed CLA from @bagnell, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by emackey** [comment]
Will wait for Travis...

**Comment by emackey** [comment]
Hmm.  Are there test failures here?

**Comment by bagnell** [comment]
Looks like it. I couldn't reproduce it locally though.

**Comment by emackey** [comment]
> Scene/LabelCollection computes bounding sphere in 3D
> Expected `111158688.34332076` to equal `4862789.037706432`.

I was able to see it in Jasmine locally when running the whole test suite, but not running `LabelCollectionSpec` in isolation.  It could be some bad interaction with other tests?

It's too much of a red flag that this is a bounding-sphere related test fail, and I don't see it in master or other recent PRs.  I think it's local to this branch, unfortunately.

**Comment by emackey** [comment]
Also Travis didn't get the same result as Jasmine.  Here's Travis:

> Expected 107984155.04338884 to equal 4862789.037706432.

**Comment by mramato** [comment]
Just to confirm, I can reproduce the failure locally every time with:

`npm run test -- --browsers Electron --webgl-stub --failTaskOnError --suppressPassed`

it does not happen at all for me in master

**Comment by bagnell** [comment]
I reverted the changes to what was in 1.44. The distance to bounding sphere wasn't needed for log depth but I noticed that it was returning a size for volumes behind the camera.

**Comment by emackey** [comment]
Looks good, tests pass.  Thanks @bagnell.

**Pull request merged**
