### PR TITLE
Added support for https and http/2

### PR DESCRIPTION
**Pull request by SunBlack**
I added support of HTTPS and HTTP/2 to my server. As far as I can see existing branch for http here does not have options to configure it, so I push my implementation for general use.

HTTP/2 will be only used on HTTPS, because no browser is supporting it over HTTP. Nevertheless we could always use `spdy` as server, because it will fall back to HTTP/1.1 in case browser does not support HTTP/2. Because of this fallback I don't know if we really need option `--disableHTTP2`.

### CODE REVIEW

**Comment by lilleyse** [comment]
Thanks @SunBlack. There's also some work towards HTTP/2 here https://github.com/AnalyticalGraphicsInc/cesium/pull/5317, but the configuration is more basic.

Since this area is still new to me would someone else like to do the first pass here?

**Comment by mramato** [comment]
I think Austin's stuff is based on my branch here: https://github.com/AnalyticalGraphicsInc/cesium/tree/http2.  To be honest, I'm not sure of the benefit of running http2 locally for Cesium development (which is why I didn't take it further), but maybe it's worth having it as an option.  That being said, we would probably want some keys available so it can be used out of the box without having to pass command line arguments.

I haven't looked at this yet, but I'll try to carve out some time next week.

**Comment by SunBlack** [comment]
Well locally you don't need currently http/2. But in some cases you need https for local development if you are working e.g. with GPS and device motions (chrome gives already a warning that using this sensor over HTTP is deprecated and will be not possible in future versions). And if you are using https you can also switch to http/2, because I don't see any contra by using http/2.

Btw.: We are using the server script as base for our public server with some advantage (e.g. http authentification, blocking access to server.js), because I have no preference which server I'm using for static content (and apache2 & http/2 is ugly ;-) ). Even if you are using a server script not basing on example server script it is a good example to other developers what a server could support (not all developers know http/2 and if they take a look into this script they will see that there exists a new version of HTTP protocol)

**Comment by pjcozzi** [comment]
Sounds like this or some variation of it will be useful.

Once we converge, please also
* Update CHANGES.md
* Add doc for each option to a new section in https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md#build-scripts

**Comment by SunBlack** [comment]
Makes it really sense to add a new section to Readme.md? Because are already getting help with option `-h`. If we extend this readme we have two documentation which need to be always synchronized.

**Comment by pjcozzi** [comment]
@SunBlack for the doc, users need to be able to discover it, and they probably will not with the `-h` option.  If updating the .md is too much, don't worry about it, and we'll find someone to do it.

**Comment by SunBlack** [comment]
I have modified Changed.md now.

@Readme: There is a hint in Reade.md that you can see more options if you enter `--help`. If someother want to add a documentation for server options there it would be nice - currently I have to many open task, so I have other priorities ;)

**Comment by hpinkos** [comment]
@mramato what's your opinion on this PR?  Do you think we want to add this option to `server.js`?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SunBlack! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for opening this PR @SunBlack, but unfortunately this isn't a priority for us right now.  We'll revisit something like this when we get back to working on http2 related changes.

**Pull request closed without merging**
