### PR TITLE
check for adjacent duplicate positions in GroundPolylineGeometry

### PR DESCRIPTION
**Pull request by likangning93**
@OmarShehata noticed that adjacent duplicates were crashing polylines on terrain.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@likangning93, thanks for the pull request! Maintainers, we have a signed CLA from @likangning93, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by likangning93** [comment]
Just realized this also isn't really sufficient, same lat/long but with different heights will still cause problems.
I'll fix this soon.

**Comment by hpinkos** [comment]
@likangning93 yeah, I would just set `height = 0` for each position, then remove duplicates.  We do that for other geometry types like the corridor

**Comment by likangning93** [comment]
Up-to-date and passing

**Comment by OmarShehata** [comment]
Just tested it out in my sandcastle example (https://github.com/AnalyticalGraphicsInc/cesium/pull/6692) and it seems to resolve the issue!

**Comment by OmarShehata** [comment]
Actually, I just encountered another issue @likangning93 . If a user passes a number of points, the `removeDuplicates` part filters that down to unique points. In some cases (in my case, for the first point you click on) this will filter down to just a single point. Which will cause [this line](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/GroundPolylineGeometry.js#L489) to throw a developer error.

I think it would be okay for it to assume you pass at least two points (perhaps with a more descriptive error message), but since it internally filters down this list, I could pass two points, and one gets tossed away, and as a user I wouldn't know what's happening.

**Comment by mramato** [comment]
> Actually, I just encountered another issue @likangning93 . If a user passes a number of points, the removeDuplicates part filters that down to unique points. In some cases (in my case, for the first point you click on) this will filter down to just a single point. Which will cause this line to throw a developer error.
> 
> I think it would be okay for it to assume you pass at least two points (perhaps with a more descriptive error message), but since it internally filters down this list, I could pass two points, and one gets tossed away, and as a user I wouldn't know what's happening.

Double check with other geometry, but I believe the official Cesium behavior here would be to simply not draw anything.  Otherwise loading external datasets (which are almost always noisy and have issues like this)  would be a giant pain for our users.

**Pull request merged**
