### PR TITLE
Implement polylineVolume for CZML.

### PR DESCRIPTION
**Pull request by MapLargeTeam**
Here's an implementation of polylineVolume for CZML, in reference to #3062.

I essentially followed the pattern from adding corridors. I created CzmlDataSource.processShapes that mimics the behavior for processPositions, except with Cartesian2's. In order to make processShapesPacketData easier to write, I created Cartesian2.fromRadiansArray, fromDegreesArray, fromDegrees, and fromRadians. The latter two just call into Cartesian3 with a height of zero to avoid copy/pasting the constants and calculation from there. 

I created an entry in Cartesian2Spec for polylines that's similar to how the corridors works. I also created specs for the new Cartesian2 methods I added. The sandcastle example recreates the same example polyline volumes as in the Polyline Volume example page. I ran eslint and got no warnings or errors.

Let me know what needs adjustment.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @MapLargeTeam! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/polylineVolumeCzml/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the PR @MapLargeTeam!  Please send over a Contributor License Agreement so we can review this.  See instructions here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by pjcozzi** [comment]
@MapLargeTeam did you mean to close this?  Let me know if you have any questions on the CLA.

**Comment by TravisDev** [comment]
Where are we at on this endeavor? I am in need of this functionality pretty badly in my app. If this line is dead, I would be willing to implement it and put out a pull request.

**Comment by hpinkos** [comment]
Hi @TravisDev, this isn't a priority for our team right now so I don't think we'll be adding support for this very soon.  However, we're always happy to review a pull request if someone else wants to add support!  You can add any comments or questions to this issue: #3062

**Pull request closed without merging**
