### PR TITLE
optimize performance when normal and tangent are not necessary

### PR DESCRIPTION
**Pull request by pasu**

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @pasu, good catch!

**Comment by pasu** [comment]
I add name to CONTRIBUTORS.md
But it seems there is a conflict and  I have no access to modify it
It is my pleasure to make this little contribution and I hope I can make more contributions in the next year
I really think Cesium is a great virtual globe project.

**Comment by pasu** [comment]
Shall I close this request?
It is a small improvement,and I feel a little shy to interrupt you:)
@hpinkos

**Comment by hpinkos** [comment]
@pasu this is a good fix and we'd love to take it!  I'm not sure if we've received your signed [CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) though.  Did you email that over to us?  That's the only thing holding this up, the code looks good to me =)

**Comment by hpinkos** [comment]
Hi @pasu!  Our contracts department is being really slow to review your CLA, so I opened my own pull request with this fix so we can get it merged in for the next release #4948 

Thanks for bringing this up!  It's a good improvement.

**Comment by pasu** [comment]
OK so glad to see it @hpinkos 

last week, it was the Chinese Spring Festive, that is why I did not visit here in time, 
Happy Chinese new year~

**Pull request closed without merging**
