### PR TITLE
Rename tiles to tileset

### PR DESCRIPTION
**Pull request by TomPed**
Renamed all `tiles.json` to `tileset.json` and fixed code to use `tiles`.

For https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/53

### CODE REVIEW

**Comment by lilleyse** [comment]
Can you merge `3d-tiles` into this branch? Once that is done you can also rename the function `loadTilesJson` to `loadTileset`.

**Comment by TomPed** [comment]
I've renamed the function and its one use in the `Cesium3DTileset` class and I'm getting this error:

screen shot 2016-01-18 at 2 31 50 pm

**Comment by lilleyse** [comment]
I would do a global search and replace, it's in a few areas including `Cesium3DTilesetSpec`.

**Comment by lilleyse** [comment]
> Could this have anything to do with the mock Cesium3DTilesTester?

Yeah it's in there too.

**Comment by TomPed** [comment]
Find and replace worked good, :+1:.

**Comment by lilleyse** [comment]
Thanks, merged.

**Pull request merged**
