### PR TITLE
When drawing primitives with no indices, no offset is necessary

### LINKED ISSUE #4237: Multiple meshes - No indices
Storing multiple meshes in one glTF without indices and loading it in Cesium results in an error. Only the first mesh shows up. While debugging Cesium, I can see that multiple meshes are loaded and this error message occurs while rendering:

[.CommandBufferContext]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 1

When debugging Cesium in Context.js line 934 [context._gl.drawArrays(primitiveType, offset, count);] a different offset is used than defined in the glTF file.
In the example ([testMulti.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/439284/testMulti.zip)) three Cubes are saved, but when loading the file only the first one is rendered.

I already posted an issue in the glTF repo (https://github.com/KhronosGroup/glTF/issues/694), but it seems that the model or the glTF spec is not the problem.

### PR DESCRIPTION
**Pull request by lasalvavida**
Fixes #4237. Our view of the buffer data already takes the offset into account, so that isn't necessary here.

### CODE REVIEW

**Comment by lilleyse** [comment]
This change should go in `Model` instead, as other areas in the code may be calling this.

Based on my testing changing [this line](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2899) to 0 works, but I haven't fulled looked into whether there are edge cases.

**Comment by lasalvavida** [comment]
Good catch @lilleyse, updated. As best I can tell this shouldn't have any other side effects.

**Comment by lilleyse** [comment]
One test is failing:

`Scene/Model loads a glTF model that doesn't have indices`

**Comment by lasalvavida** [comment]
Updated, `count` needed to be set as well. That test passes and the model from #4237 renders correctly.

**Comment by lilleyse** [comment]
Ok good now!

**Pull request merged**
