### PR TITLE
Remove Screen Space Quads at Poles

### PR DESCRIPTION
**Pull request by bagnell**
Remove code to fill the poles with screen space quads. We never execute this code. The terrain reaches the poles and the imagery is stretched. 

/CC @kring @pjcozzi

### CODE REVIEW

**Comment by kring** [comment]
Technically we still use that code if the terrain provider uses the Web Mercator projection, which is possible.  But admittedly I haven't tried actually doing that in a really long time and I wouldn't be surprised if it doesn't work anymore.

**Comment by pjcozzi** [comment]
Should we keep this and add tests?

**Comment by bagnell** [comment]
Ah OK. Do you know of any terrain provider that uses `WebMercatorTilingScheme` so I can test it? After doing a search that I thought was unrelated, I landed in this code and spotted something that looked broken.

**Comment by pjcozzi** [comment]
We will need this if we add BIL, right?  Perhaps it is fine to remove this, and submit an issue for that including a reference to this issue if we need the code.

**Comment by kring** [comment]
> We will need this if we add BIL, right?

Maybe, I'm not sure.  For dynamic layers, ArcGIS can reproject to whatever we ask.  If a MapServer has a fused cache (AKA thing that makes it actually fast enough to use for terrain!), it's going to be one particular projection and that projection might be Web Mercator.  But probably not, because World Wind wouldn't want Web Mercator either.  Not worrying about it until we need it seems wise.

**Comment by pjcozzi** [comment]
Sounds good.

**Pull request merged**
