### PR TITLE
Supporting presigned URLS for TMS imagery providers and Cesium Terrain providers

### PR DESCRIPTION
**Pull request by keattang**
Currently the TMS provider and cesium terrain provider blindly add the path to the resource it requires to the end of the url it is given. This does not allow for the serving of secure tiles via presigned urls (e.g. from S3). Therefore I have created a function that joins URLs taking into account query strings and modified  `CesiumTerrainProvider` and `TileMapServiceImageryProvider` to use them.

### CODE REVIEW

**Comment by kring** [comment]
Thanks @keattang, great to see you contributing to Cesuim, too!  A couple of things before we merge this:

* Have you signed the Cesium Contributor's License Agreement (CLA) yet?  Details [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).  It'd be great to get a corporate one from Propeller if possible.  You can just email it in.
* Add yourself to `CONTRIBUTORS.md`.
* Mind writing some tests for `joinUrls`?  Ideally there would be tests for your changes to `CesiumTerrainProvider` and `TileMapServiceImageryProvider`, too.

**Comment by keattang** [comment]
No worries I'll get on to that soon! Might not be till next week though.

**Comment by pjcozzi** [comment]
@kring @keattang what is the plan with this pull request?

**Comment by keattang** [comment]
I'm still keen to get this into the code base. Just trying to find time to write the tests.

**Comment by keattang** [comment]
I've written a new spec file for the `joinUrls` function. Is there anywhere that I need to include this file or will it be picked up automatically?

**Comment by kring** [comment]
@keattang it should get picked up automatically the next time you run the `build` task.

**Comment by keattang** [comment]
Awesome. I've just emailed in the CLA and all the tests pass so this should be ready to merge:)

**Comment by pjcozzi** [comment]
We received @keattang's CLA.  Thanks again!

**Comment by kring** [comment]
Thanks for writing the tests @keattang.  I'm seeing a failure in `CesiumTerrainProviderSpec` in `requestTileGeometry uses the proxy if one is supplied` on my system, though.  The problem seems to be that tile URLs are being built incorrectly when the base / template URL is a relative path rather than an absolute one.

**Comment by keattang** [comment]
Ah sorry missed that one. Fixed now, the issue was that it was double proxying the URL.

**Comment by kring** [comment]
Sorry @keattang, there are new problems now.  If I fire up Cesium Viewer and switch to STK World Terrain, I don't get a globe.  It's requesting tiles like this:
http://assets.agi.com/stk-terrain/0/1/0.terrain?v=1.16389.0
when the correct tiles look like this:
http://assets.agi.com/stk-terrain/world/0/0/0.terrain?v=1.16389.0

There are also a bunch of related test failures.

**Comment by keattang** [comment]
My bad, was in a bit of a rush. Should all work now. 

Although I am getting failures that seem unrelated in `BillboardCollection` and `LabelCollection`. They all state:
`TypeError: Cannot read property 'primitive' of undefined`

I get the same errors in the master branch.

**Comment by mramato** [comment]
> I get the same errors in the master branch.

These are unrelated problems and will be fixed if you merge in master.  That being said, I did that locally on my machine and all tests in the PR work without a hitch. Thanks a lot for this contribution, I actually need this myself too.

**Comment by mramato** [comment]
@keattang, thanks again for the contribution.  I wanted to do a little clean up before this went into master so I branched off your branch and submitted #3133 (which contains your changes as well as my own).  Hopefully @kring can merge that PR as soon as he wakes up on the other side of the world.  Either way, my PR now contains yours so I'm going to close this one.

Thanks again.

**Comment by keattang** [comment]
Awesome thanks!

**Comment by kring** [comment]
> Hopefully @kring can merge that PR as soon as he wakes up on the other side of the world.

Other side of the world?  @keattang works for the awesome startup next door.  You're the one on the other side of the world, mate. :)

In any case, thanks for that, @mramato, I'll review the new PR in a moment.

**Pull request closed without merging**
