### PR TITLE
Allowing kmz inflation/deflation to happen in workers across origins

### PR DESCRIPTION
**Pull request by madole**
- adding name to contributors list
- moving `getWorkerUrl()` out to its own file so it can be used in both `TaskProcessor.js` and `ThirdParty/zip.js`
- using `getWorkerUrl()` import in TaskProcessor
- using `getWorkerUrl()` import in zip.js to determine if the url is a cross origin url and if so, load the worker in via a blob url. 

Relevant forum post: https://cesiumjs.org/forum/#!msg/cesium-dev/dq2l5L69L0U/KppBFvozBAAJ

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @madole!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

:warning: I noticed that a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version. Once you do, please confirm by commenting on this pull request.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by madole** [comment]
- `Changes.md` updated
- CLA sent to `cla@agi.com`
- Confirmed that `zip.js` has a section in [`LICENSE.md`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md#zipjs)

**Comment by pjcozzi** [comment]
Thanks @madole!  We received your CLA.

Does anyone want to review this?

**Comment by ggetz** [comment]
I can review. @madole, can you provide instructions for replicating so we can test the fix?

**Comment by hpinkos** [comment]
@madole are the changes to Zip.js just updating it to a new version?

**Comment by mramato** [comment]
As @hpinkos hinted at already, Zip.js is a third party dependency so we shouldn't be changing it so much directly from it's initial release.  We may be able to push some changes upstream to them (assuming the latest version still has this issue) https://github.com/gildas-lormeau/zip.js

**Comment by madole** [comment]
The steps to reproduce are: 
- serve cesium and consuming code on one domain. In our case, it's sitting in an s3 bucket. 
- then access the app via a proxied url. We have cloudfront serving up some custom domains. 
- Call `KmlDataSource.load()` on a kmz file to activate the `zip.inflate` code path. 
- the browser will complain that it cannot create the worker because it's on a different domain. 

This PR does not update the `zip.js` dependency to a new version, and while I agree in theory that modifying third party dependencies is bad practice, it's already being done to bring in `buildModuleUrl` and `defineProperties` so that the workers can be built correctly. 

This PR takes that a step further and allows you to build the worker urls the same way that cesium does in other places using the `getWorkerUrl` function that resides currently in `TaskProcessor`

**Comment by hpinkos** [comment]
@madole okay, I get what you're saying.  I'm not sure who originally modified `zip.js` this way, but it really shouldn't be done that way.

I'm not sure if we will want to take this change as is since it's making more significant changes to `zip.js`.  @mramato do you have any suggestions?

**Comment by madole** [comment]
I can understand the risk here. However, the same risk of regression applies as the Third Party dependency has already been modified. 

It's unclear to see here as the formatting of the zip.js makes the diff look huge but this actually reduces the amount of code change to the file. 

I'll reformat the PR so it's clear what's actually being changed.

**Comment by mramato** [comment]
Thanks @madole that is a smaller change that I originally thought it was, and I noticed you did change the part that was already modified by @shunter at some point.  @shunter can you take a quick look at this since you know the Worker architecture best.  If not, I can do it.

Might be nice to find a to get some of these changes upstream or make it easier in the future to determine what is ThirdParty and what isn't; but that's outside the scope of this PR.

**Comment by shunter** [comment]
I didn't test anything but changes look OK.  I doubt upstream would be able to take these changes anyway.  The goal is just to minimize the number of modified lines as much as possible to make it easier to perform future merges.

**Comment by hpinkos** [comment]
Sounds good to me.  @madole can you just add a comment at the top of `Zip.js` linking to this PR noting that it was modified?

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @madole! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Sorry we never got back to you on this @madole.  Next time, please comment when a pull request is ready for another review so we get notifications to take a look at it.

When you have a chance, could you please merge in master?  Thanks!

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @madole! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Closing this due to a lack of response.  @madole if you have time to clean up this PR, feel free to reopen it!  Thanks for your contribution =)

**Pull request closed without merging**
