### PR TITLE
FlyTo: Convert numerical values to Number type

### PR DESCRIPTION
**Pull request by josh-bernstein**
The parameter to `flyTo` is an Object with contains a field called `destination` (a position vector) and optionally a field called `orientation` which contains rotation angles.  If these vectors contain values which are strings instead of numeric (i.e. strings of numbers), the code will return a DeveloperError

These changes are designed to convert these string values into Numbers, thereby ensuring the calculations will work correctly.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @josh-bernstein! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/josh-bernstein/cesium/blob/convert_flyto_params_to_number/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/convert_flyto_params_to_number/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by shunter** [comment]
I don't think these changes are appropriate.  Generally we don't silently coerce types of input data. 

In addition, the destination parameter is not always a Cartesian, it accepts a Rectangle as well.  Similarly, orientation doesn't have to be HPR either.  Coercing undefined to a Number will break the rest of the logic in the function.

**Comment by josh-bernstein** [comment]
Thank you for sharing your concerns.  That makes complete sense.  I will discuss with my coworkers, and decide whether to alter this pull request, or to submit an issue instead.

**Comment by shunter** [comment]
OK. If you can explain the actual problem you're attempting to solve on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev), perhaps someone in the community can help.

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @josh-bernstein! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Comment by josh-bernstein** [comment]
@cesium-concierge @OmarShehata @slchow I would love if you tweeted about it, but seems that this PR will not get merged as is.  I plan to raise this issue in the forum once I have a valid gmail address

**Comment by OmarShehata** [comment]
Looking forward to it Josh! The automated concierge post is something I've been wanting to fix. It should only post when the PR is successfully merged.

**Pull request closed without merging**
