### PR TITLE
(fix) display tooltips on All demos view

### PR DESCRIPTION
**Pull request by tekhaus**
https://github.com/AnalyticalGraphicsInc/cesium/issues/4454

### CODE REVIEW

**Comment by pjcozzi** [comment]
@emackey do you want to look at this?

**Comment by hpinkos** [comment]
@tekhaus we updated electron in master, so if you update your branch CI should pass

**Comment by tekhaus** [comment]
@hpinkos merged from upstream master and pushed to my fork... how do I get CI to rerun on this PR ?

**Comment by hpinkos** [comment]
merge your fork's master into this branch and push that up.  That should make CI run again

**Comment by hpinkos** [comment]
Thanks @tekhaus, I can confirm this fixes the problem.  There were some merge issues with your branch, so I just merged master and pushed that up.
Thanks again!

**Comment by hpinkos** [comment]
Oh actually, before I merge this, can you add yourself to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md?

**Comment by pjcozzi** [comment]
Also, one last small request: please update [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md).

**Comment by hpinkos** [comment]
@pjcozzi I'll update CHANGES in master

**Pull request merged**
