### PR TITLE
Use relative URL for video specs

### PR DESCRIPTION
**Pull request by OmarShehata**
These tests were passing in Travis but not locally, because the Data folder is inside `Specs/`. My bad for not running this locally.

### CODE REVIEW

**Comment by mramato** [comment]
That's weird, they past locally for me before I merged that PR.  (Maybe I was on the wrong branch and didn't notice).  Either way I'll merge when green.

**Comment by OmarShehata** [comment]
Yeah I can reproduce it locally on Windows and it was happening for @likangning93 as well (when running the tests via the in-browser SpecRunner).

**Comment by OmarShehata** [comment]
@mramato this is ready to merge.

**Comment by mramato** [comment]
Whoops, swore I merged this already.  Sorry for the delay.

**Pull request merged**
