### PR TITLE
Don't crash when inspecting a tile that is not loaded.

### LINKED ISSUE #5055: Cesium Inspector - Picking tile bug
When picking a tile and then clicking select relative NW, NE, SW, or SE I get an error

`Uncaught TypeError: Cannot read property 'minimumHeight' of undefined (on line 896 of http://localhost:8081/Source/Widgets/CesiumInspector/CesiumInspectorViewModel.js)`

### PR DESCRIPTION
**Pull request by kring**
Instead, just tell the user it's not loaded.

Fixes #5055

### CODE REVIEW

**Comment by hpinkos** [comment]
1. Pick a tile
2. Show only selected
3. Click one of the children buttons
Leads to this crash: `Cannot read property 'imagery' of undefined

If 'Suspend LOD' is selected and we click the children buttons it un-suspends updates and then proceeds normally.  We should do the same for the 'show only selected' option to avoid that crash.

**Comment by hpinkos** [comment]
Other than that the fix looks good to me!

**Comment by kring** [comment]
I just changed it to not try to render a non-renderable tile, even if it's selected.  It'd be sorta cool if it still loaded the selected tile, so it would render eventually, but I can't see an easy way to do it and it doesn't seem super important.

**Comment by hpinkos** [comment]
:+1: thanks @kring!

**Pull request merged**
