### PR TITLE
Fix billboard aligned axis

### PR DESCRIPTION
**Pull request by bagnell**
For #3318.

Fix billboard collection that has at least one billboard with an aligned axis and at least one billboard without an aligned axis. Adds a bit to a compressed attribute for valid aligned axes since zero is a valid encoded unit vector.

### CODE REVIEW

**Comment by hpinkos** [comment]
I can confirm the multiple aligned axis problem is fixed.

I did notice though, that when using an aligned axis, the billboard is all over the place when you rotate the globe.  It's particularly noticeable when using the pin builder.
If you're using aligned axis north, it should theoretically move exactly with the globe, right?
Should we write up a separate issue to improve that?

**Comment by bagnell** [comment]
>If you're using aligned axis north, it should theoretically move exactly with the globe, right?

Mostly. Think about the direction vector from the center of the billboard in 3D being projected to a 2D plane parallel to the camera viewing plane. What happens when the angle between the aligned axis and that plane's normal approaches 0 or 180 degrees? We could improve it. At this point I'm not sure how.

**Comment by pjcozzi** [comment]
@bagnell update CHANGES.md.

@hpinkos merge when you are happy with this.

**Comment by bagnell** [comment]
@hpinkos This is ready. Also, what you mentioned is already an issue #2487.

**Comment by hpinkos** [comment]
Sounds good.  Thanks @bagnell!

**Pull request merged**
