### PR TITLE
We now handle KML features with duplicate ids

### LINKED ISSUE #3941: KML with duplicate placemark ID's doesn't render duplcates
Duplicate ID's on KML <placemark>'s are eaten up by cesium (leaving only the last one parsed), but not by Google Earth.

Here is a minimally viable KML example:

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
	<name>test.kml</name>
	<Folder>
		<open>1</open>
		<Placemark id="pants">
			<name>Untitled Placemark</name>
			<Point>
				<coordinates>-100.3676476056248,35.68047362719558,0</coordinates>
			</Point>
		</Placemark>
		<Placemark id="pants">
			<name>Untitled Placemark</name>
			<Point>
				<coordinates>-99.88130689790214,35.74669558362526,0</coordinates>
			</Point>
		</Placemark>
	</Folder>
</Document>
</kml>
```

### PR DESCRIPTION
**Pull request by tfili**
Fixes #3941.

### CODE REVIEW

**Comment by hpinkos** [comment]
@tfili merge in master please

**Comment by tfili** [comment]
@hpinkos Should be good now.

**Comment by mramato** [comment]
Spoke with @tfili offline, there are some minor changes I requested, but then I'll merge this.

**Comment by mramato** [comment]
👍 Can you mention on the forum and the various bugs that this is fixed and will be out on the 1st.  Thanks.

**Pull request merged**
