### PR TITLE
Fix Undefined Min/Max Height in Inspector

### LINKED ISSUE #7672: Cesium Inspector Undefined min/max in 1.55
Go to:

https://cesiumjs.org/releases/1.55/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html

Click "Terrain > pick tile", notice the min/max is undefined.

Go to:

https://cesiumjs.org/releases/1.54/Apps/Sandcastle/index.html?src=Cesium%20Inspector.html

Repeat the above, notice the min/max works. Is this a bug in terrain, or does the inspector just need to be updated to account for @kring 's changes?

### PR DESCRIPTION
**Pull request by dennisadams**
Fixes #7672.
Following the terrain overhaul (#7061), the min/max height properties have moved from the `QuadtreeTile`'s `data` to `data.tileBoundingRegion` and not all places were updated.
This PR updates the cesium inspector and also a couple of other places: `Globe`'s `getHeight` and `QuadtreePrimitive`'s `updateHeights` which share the relevant code.
Hope I haven't missed any others.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @dennisadams!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/tile-height/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by kring** [comment]
Code looks good to me, thanks @dennisadams. Just needs a CHANGES.md update and confirmation the CLA has been signed.

**Comment by hpinkos** [comment]
No, I don't think we've received a CLA yet.

@dennisadams See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla for instructions for sending over a contributor license agreement.  Thanks!

**Comment by dennisadams** [comment]
I've just updated CHANGES.md and sent my CLA.
Thanks!

**Comment by pjcozzi** [comment]
Thanks again for the contribution, @dennisadams, we received your CLA.

**Pull request merged**
