### PR TITLE
Fixes #3945: Flickering when adding a new polygon entity

### LINKED ISSUE #3945: Flickering when adding a new polygon entity
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/xKVI49Ux430

In this example, the polygons flicker each time a new polygon is added to the collection.  It looks like the polygons are drawn solid instead of with an alpha for a split second.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var dataSource = new Cesium.CustomDataSource('Polygons');
viewer.dataSources.add(dataSource);

var x = 20;
var y = -120;

setInterval(function(){
   x -= 5;
   y += 2; 

    var area = [0 + y, 51 + x, 5 + y, 51 + x, 2.50 + y, 48 + x];
    dataSource.entities.add({
        name: 'test',
        show : true,
        polygon : {
            hierarchy :{
                positions: Cesium.Cartesian3.fromDegreesArray(area)
            },
            material : Cesium.Color.RED.withAlpha(0.5)
        }
    });
}, 1000);
```

### PR DESCRIPTION
**Pull request by roderickgreen**
This fixes the flickering when adding or modifying entities within a batch (#3945). Primitives are now created with show=false, then modified to show=true once the primitive is ready and the oldPrimitive is cleaned up.

Note that this same approach does _not_ work for StaticGroundGeometryColorBatch. When creating a GroundPrimitive with show = false, the primitive never becomes "ready." Reading the update code in GroundPrimitive this should be pretty easy to see, but I'm not sure if it's expected. I can provide a trivial failing unit test for this if you like. I decided to leave StaticGroundGeometryColorBatch unchanged.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@roderickgreen, thanks for the pull request! Maintainers, we have a signed CLA from @roderickgreen, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the contribution @roderickgreen!  This approach seems good to me.  We really need to figure out what do to for `StaticGroundGeometyrColorBatch` though because those are probably used more frequently when users add polygons.  Maybe we can do something by waiting for the [primitive.readyPromise](https://cesiumjs.org/Cesium/Build/Documentation/Primitive.html?#readyPromise)  @mramato do you have any ideas?

**Comment by roderickgreen** [comment]
Thanks for looking at this, @hpinkos. I'm really not sure what to do with `StaticGroundGeometyrColorBatch.` When asynchronously creating primitives, I think they have to be created with `show : false` or they will show up in the scene before we have a chance to remove the old primitive. That doesn't work at all with `GroundPrimitive` because of how it is implemented. There might be a solution if we create the `GroundPrimitive` with `asynchronous : false`, but that doesn't seem great. Or we can refactor `GroundPrimitive` so it can be created with `show : false` and shown when it is ready. Hopefully someone else has another suggestion.

FWIW, at first I was using readyPromise to show the new primitive and to lift the `oldPrimitive` cleanup out of `update`. I backed off of that because I thought it was higher risk because it might change the behavior in error paths. I'm happy to rebase my pull request to use this code instead if you like this approach more and don't think it will cause problems:

```
                primitive = new Primitive({
                    show : false,
                    asynchronous : true,
                    ...
                });

                var that = this;
                primitive.readyPromise
                    .then(function(primitive) {
                        primitive.show = true;
                    })
                    .always(function() {
                        if (defined(that.oldPrimitive)) {
                            that.primitives.remove(that.oldPrimitive);
                            that.oldPrimitive = undefined;
                        }
                    });
```

**Comment by mramato** [comment]
> When creating a GroundPrimitive with show = false, the primitive never becomes "ready."

We should probably change GroundPrimitive to remove this restriction CC @bagnell

**Comment by roderickgreen** [comment]
This is blocking on #6428. After that is merged, the StaticGroundGeometryColorBatch tests will pass.

**Comment by hpinkos** [comment]
Thanks @roderickgreen!  We should be able to review #6428 and this PR hopefully in the next few weeks.  We're pretty busy working towards a May 1st milestone, so it just depends on our progress towards that goal.

**Comment by mramato** [comment]
@roderickgreen I just merged #6428, so if you can merge master into your branch and bump when ready, we'll try to get this into the May 1st release.

**Comment by roderickgreen** [comment]
Thanks, @mramato. I merged master and updated changes.md, so I think this is done.

**Comment by hpinkos** [comment]
Thanks @roderickgreen, this is great!  I'll let @mramato take a final look but this should be good to go

**Comment by mramato** [comment]
Thanks @roderickgreen!

**Pull request merged**
