### PR TITLE
Fix for model coloring

### PR DESCRIPTION
**Pull request by szsolt**
[#1](https://github.com/AnalyticalGraphicsInc/cesium/issues/4797) Opened issue

### CODE REVIEW

**Comment by szsolt** [comment]
For some reason the CI system fails to run:

npm run makeZipFile

Running locally the command succeed without any issue.

**Comment by lilleyse** [comment]
Thanks for catching this @szsolt. This is a good initial solution, with the downside being if there is no `result ` parameter then a new Color will be allocated every time, which actually seems to be a problem with `silhouetteColor` too currently...

I think the proper solution may be to turn `model.color` and `model.silhouetteColor` into a getter/setter and mark that the colors as dirty in a different way. I am happy to add that work to this PR, unless you wish to look into it.

**Comment by szsolt** [comment]
@lilleyse Feel free to modify this pull request. Your expertise way bigger then mine.

**Comment by szsolt** [comment]
Updated pull request to avoid creating a new Color each update.

Is this good enough or you still prefer the getter/setter option?

**Comment by pjcozzi** [comment]
@szsolt can you please send in a [Contributor License Agreement (CLA)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request) so we'll be able to merge this?

**Comment by lilleyse** [comment]
I think the getter/setter is still preferable. If the model's color is not set the default color will be cloned every update.

**Comment by pjcozzi** [comment]
@szsolt do you have any update here?  We would like to get this fix into master since other users have also noticed it.  Do you prefer that @lilleyse or I finish this or are you able to?  Thanks!

**Comment by szsolt** [comment]
Updated the pull request. Now if the model color is not set, it will not be cloned for every update.
Also removed the unnecessary clone from updateSilhouette() as it was cloning the full Color() object and all it needed was the alpha value of it.

I was wondering if it would worth changing the behavior of getValueOrDefault() or introducing a new method which will allocate a new object when the result is frozen, something like:

```javascript
Property.getValueOrDefaultSafe = function(property, time, valueDefault, result) {
    return defined(property) ? defaultValue(property.getValue(time, Object.isFrozen(result) ? undefined : result), valueDefault) : valueDefault;
};
```

Of course we could implement isFrozen() method like you did for the freeze() method for older browser compatibility.

**Comment by szsolt** [comment]
Please feel free to modify / replace my implementation as you guys have more expertise on the implementation detail.

**Comment by lilleyse** [comment]
Cool nice idea with only storing the alphas to avoid the clone, and using the underscored colors as scratch variables. I think this is good to go for now, if we decide to use getters/setters for Color later that can be in a different PR.

@pjcozzi can you do the final review?

**Comment by pjcozzi** [comment]
Looks great, thanks again @szsolt!  Great job with this.

If you have the time to more involved with Cesium, there's [lots of ideas here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#getting-started-contributing).

**Comment by pikvic** [comment]
This bug still appears in 1.96.  Link to [Sandcastle](https://sandcastle.cesium.com/#c=tVdZjyI3EP4rDk+NRMwxsLshzCgcm2yUjLIZyCpSiFamu6CtcdvIds8wWc1/T9nuhuaIIkLgyS7b9R1dPoiVNJY8cXgGTW6JhGcyBsPzjH7ysWhei31/rKRlXIKe1xrky1wSwuVSjdSmT5ZMGGi4kAEBseVK/igTHjOr9N5oyhL1bPrE6ryMqFwkQ8kzZmEbf61/O5dzucylz0ViDTh8rxIQUa5Fg6TAV6mtBxqBOwVpueVgqIZMPcFQiCikIST2GtfKcJ/utlQ4Ztpii8kbutQqm8BKA5jILSHk63bnhrbedrtv2t80Qqjbpa1e6+Zt600RCDxc20EdAnUuReq++0ekHVoKLOFytcO6ZzalVj1gmEkTtW96e+S4jVOc3KrEtBLiIJSuD6rhQ4D56JY/4PyowG2EjA2fpAqkNMdPwvYdn2mktFQ6MzQ9SPhrjt9YS5xe2FLaWDqw1qX8kyCd/xularIvrhdEOCw2liTRl7BUsgxL2NXnfub+IUaFdL/aKYYzV+d9UmQlmJFX0+IEjvslzz7yDYgp/wtB2513u1G2caPTmAkc6bTwtx2LlXA7sixK1/P1+LBasKi16fVGo+FwMqmH+a9+3Wv1owYfOpca0fkXJzpXs+KEskKJ1Sx+hOR9+aWDVD+jUE09HepNrGxt7+LD+wlOfXW1WVTm2gkxOO8Pl6KQYGFj+2ReG3Ida7a0eJYWTshwdOJxWZ56UX0nvHoCljGszxqlzSnL1gImzLKm52eagRhCFK3P2KQrsdiCuV8PzaCtsh+c2BrTOEF5opWEK/L1+avtI8rt3nmMf9Aqlwn5BCmPxXWoB4gCYb93RP8c6h+UJfjVyIgJoZS8ou0Fwn7v2Ppzq+Wei0cy03n8eEXuDsRjHPYv8n76yKWEhIxThkeC9Q+eqylgpfOfsXkR7QmSVWSssrUGY5C/J3IV7h5qh3TCfbv8zzp+mv3eqco4cwvwJYm+Ko7m71FTrmECNjxKqcnXa6WtGTHDTVQc/CYGCfVKCkKeucSHKsVrQ9uKHc6QWcoNWWh8xuJ7OVFgiMS9WiQmPjH5TfIn0IYJvDW3Opw+JGPmtV3C0g604vIt7Iw7jpy9lf/0D6wpk0nMjMVzDG/2mVJiwfQ9yDwqLja3sNaozWvbl1JINDD2RcBdmf87nnlj8NKOUIIFlID6THOBhQKWxsaUFAbN6tJBwp8IT25P/P0gsWDG4MgyF/7Wn9fuBk2cf7RUKP/6+wW/hmAvblravvs5BCmlgyZ2T6+0QfFB5r8B)

**Comment by j9liu** [comment]
Hi @pikvic,

This bug has already been fixed in `main`, and the fix will be included in the CesiumJS 1.97 release.

**Pull request merged**
