### PR TITLE
Remove dependency of DataSourceDisplay on the Cesium visualizers

### PR DESCRIPTION
**Pull request by kring**
It's sometimes useful to use the Cesium DataSourceDisplay system without using Cesium for the actual visualization. Two examples of that are the 2D view in the Santa Tracker and the 2D view in TerriaJS. In TerriaJS, we take pains to avoid loading the visualizers (and their dependencies) unless we're really doing 3D, because that's a whole lot of code.

But that's currently difficult to do because `DataSourceDisplay.js` requires-in all the visualizers, even if you're planning to immediately replace them with something else. So this change creates a `DataSourceDisplayWithoutVisualizers.js` where the list of default visualizers is empty. `DataSourceDisplay` requires in `DataSourceDisplayWithoutVisualizers` and the new `createCesiumVisualizers` and combines them. Normal users won't notice any difference, but now advanced users have the option of putting the Cesium visualizers in a separate Webpack bundle, etc.

Unfortunately this is a huge PITA to review because Git is terrible at tracking renames. Best way to review it is to directly diff `DataSourceDisplay.js` from master with `DataSourceDisplayWithoutVisualizers.js` from this branch. There are very few changes.

I don't think it's necessary to mention this in CHANGES.md.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @kring!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/DataSourceDisplayWithoutVisualizers/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
We already have the entity definition separated from the visualization piece for this very reason.  I thought the idea was you would want to create a `DataSourceDisplay` for visualizing in Cesium and connect to an `EntityCollection` with some other class for visualizing in a different non-cesium map.
Can you explain what the difference here is?  `DataSourceDisplay` doesn't seem to have much functionality that's not directly related to the visualizers and creating Cesium primitives.  You should be able to just create a custom visualizer and connect to the entity collection for your other 2D map.

**Comment by kring** [comment]
Thanks @hpinkos, that's interesting. I've been using `DataSourceDisplay` with Leaflet for like four years now, so it never occurred me I wasn't supposed to do that. :) Originally it was even less Cesium-specific than it is now, but I guess the trend has been toward making it Cesium specific as its picked up clustering and ground primitives and whatnot. So I'm happy to switch to my own version of DataSourceDisplay for use with Leaflet, as you suggested.

Is this PR potentially still useful for the Cesium use-case in my comment above? i.e. excluding Models if you know you don't need them and want to make your app smaller? Of course you could do that just by forking `DataSourceDisplay` there too, but it seems less than ideal for that scenario. Up to you, I'm happy to close this if you don't think it's useful.

**Comment by hpinkos** [comment]
Hmm, I can see this maybe being beneficial for AMD users.  But considering the size of everything else that's required in as soon as you create a `new Viewer` (which most of our users use), I'm not sure that this has a significant impact.  I think we'll pass on this one for now.  At some point we need to overhaul our module system, and I think we want to componentize things better as part of that effort.  Thanks anyway @kring!

**Comment by hpinkos** [comment]
@kring I didn't delete your branch in case you needed it.  Please delete it if you don't =)

**Pull request closed without merging**
