### PR TITLE
Changed license structure Fixes:#4322

### PR DESCRIPTION
**Pull request by gautamkrishnar**
This one fixes:#4322
* Renamed LICENSE.md → Third-party-License.md 
* Added GitHub Standard  LICENSE file

It will now show up on the repo

### CODE REVIEW

**Comment by mramato** [comment]
Thanks @gautamkrishnar.

@pjcozzi can confirm this, but I think we would want the renamed file to be called `THIRDPARTY.md` and `LICENSE` should still be `LICENSE.md` and should be picked up by GitHub.

Also, since this is your first PR, in order for us to review and merge your change, you'll need to email us a CLA, as discussed in CONTRIBUTING/md

Thanks again in advance!

**Comment by gautamkrishnar** [comment]
Renamed the file :+1:

**Comment by gautamkrishnar** [comment]
Signed the CLA

**Comment by pjcozzi** [comment]
We have a CLA from @gautamkrishnar, thanks again!

I'd like to review this before merging.  I am on travel, but will try to look soon.

**Comment by pjcozzi** [comment]
> @pjcozzi can confirm this, but I think we would want the renamed file to be called THIRDPARTY.md and LICENSE should still be LICENSE.md and should be picked up by GitHub.

Exactly.

**Comment by pjcozzi** [comment]
@gautamkrishnar I don't think you renamed LICENSE to LICENSE.md.

**Comment by gautamkrishnar** [comment]
@pjcozzi  done :+1:

**Comment by mramato** [comment]
@pjcozzi any update here?

@gautamkrishnar can you please merge in master.  Thanks.

**Comment by pjcozzi** [comment]
Will look at this today or tomorrow at the bug bash.

**Comment by pjcozzi** [comment]
@gautamkrishnar thanks so much for looking into this, but the current GitHub license detection requires strictly using their exact text, which precludes us from including the copyright in LICENSE.md.  This is problematic for us to get signed off on right now so I am going to close this.

Thanks again for your interest in contributing, there are plenty of issues labeled [beginner](https://github.com/AnalyticalGraphicsInc/cesium/labels/beginner) if you want to explore something else.

**Comment by gautamkrishnar** [comment]
Thanks @pjcozzi

**Pull request closed without merging**
