### PR TITLE
upgrade Knockout to version 3.4.0

### LINKED ISSUE #3628: ThirdParty/knockout-3.2.0 not included in built release
I've been playing with Cesium and [jspm](http://jspm.io/)/[SystemJS](https://github.com/systemjs/systemjs), and I think I've stumbled upon an issue with the pre-built flavors of the release (as published to npm).

SystemJS is having trouble resolving the `"ThirdParty/knockout-3.2.0"` dependency.  Looking at the built source (Cesium.js), there is no module definition for `"ThirdParty/knockout-3.2.0"`, but there are references to (dependencies upon) it.  I'm not sure if this is a regression from the Knockout 3.2.0 update; I will test with previous releases (with older Knockout versions) to see and follow up.

### PR DESCRIPTION
**Pull request by nmschulte**
To resolve #3628.

### CODE REVIEW

**Comment by mramato** [comment]
Thanks @nmschulte!  Even though this is just upgrading third-party code, we need you to fill out and email us a CLA as described in [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request) before we can merge it.

Thanks again.

**Comment by nmschulte** [comment]
@mramato, I've already taken care of that process, see here:
https://github.com/AnalyticalGraphicsInc/cesium/blame/master/CONTRIBUTORS.md#L48

**Comment by mramato** [comment]
@nmschulte Sorry about that, for some reason you weren't listed on our internal CLA records, but clearly that's a mistake on our end.

**Comment by nmschulte** [comment]
Not a problem; thanks!

**Comment by mramato** [comment]
Thanks.

**Pull request merged**
