### PR TITLE
New Camera mode

### PR DESCRIPTION
**Pull request by bagnell**
Adds a new camera mode for horizon modes where the point on terrain picked is above the camera's position.

### CODE REVIEW

**Comment by mramato** [comment]
This is pretty awesome.  There is some weird interaction with collision detection though.

1. Turn on terrain and zoom to everest.
2. Zoom out a bit.
3. Grab the top of the peak and move the mouse up.

When the camera hits the ground, it starts zooming out like crazy.

**Comment by pjcozzi** [comment]
Update CHANGES.md

**Comment by pjcozzi** [comment]
Are the current tests enough to cover this?  Is it possible to write reasonable tests to cover it better?

**Comment by pjcozzi** [comment]
It's pretty easy to run into issues with horizon views using just the default Cesium Viewer without terrain.

For example, start with a horizon view then grab and drag the upper right corner of the ground with the left mouse and you get a view like:

http://localhost:8080/Apps/CesiumViewer/index.html?view=-103.65659160619491%2C-35.577131975876%2C19.969294224417173%2C265.7059227273983%2C-63.920647244975434%2C112.60188570528582

**Comment by pjcozzi** [comment]
@bagnell can you make a short animated gif of this feature so:
* @maikuru can post it on twitter to build interest in the 1.11 release
* we can include it in the 1.11 blog post

**Comment by pjcozzi** [comment]
Other than those issues, this feels pretty solid to me.

I'm not sure that we need to add it now, but I wonder if we want a key to override this, e.g., it always pans when Ctrl is down.

**Comment by bagnell** [comment]
>It's pretty easy to run into issues with horizon views using just the default Cesium Viewer without terrain.

That was a bug added in my last commit when cleaning up the code. It's fixed.

**Comment by bagnell** [comment]
>Is it possible to write reasonable tests to cover it better?

Not without terrain. All of the terrain interaction code is untested.

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look unless you have an idea for tests.

**Comment by pjcozzi** [comment]
Middle mouse rotate in a horizon view seems like it rotates around the center of the view not the point clicked now.

**Comment by bagnell** [comment]
>Middle mouse rotate in a horizon view seems like it rotates around the center of the view not the point clicked now.

It has always done that until the camera goes below `ScreenSpaceCameraController.minimumPickingTerrainHeight`.

**Comment by pjcozzi** [comment]
I don't think it is working in this branch.  Try the following in this branch and then with Cesium Viewer on the website:

http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?view=-82.48980344101658%2C35.097723283803745%2C31.71191579572227%2C343.51593308097296%2C-6.612181914702152%2C359.94832486804995

**Comment by bagnell** [comment]
It's working for me. It's hard to tell without terrain, but, instead of moving the mouse vertically, move it horizontally. If you click towards the bottom right or left, it will rotate around that point.

**Comment by pjcozzi** [comment]
Looks good, not sure what the mixup was on my end.

**Pull request merged**
