### PR TITLE
Fix TileBoundingBox

### LINKED ISSUE #4032: Black terrain artifact
See screenshot below:

image

Steps to reproduce:
- http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Camera.html&label=Showcases
- change setHeadingPitchRoll to function below
- run
- click "Set camera with heading, pitch, roll" from dropdown to run code

```
function setHeadingPitchRoll() {
    Sandcastle.declare(setHeadingPitchRoll);

    var camera = viewer.camera;
    camera.setView({
        destination : new Cesium.Cartesian3(1288857.3292931253, -4338373.750901034, 4488506.669268853),
        orientation: {
            heading : 0.1765,
            pitch : -0.4667,
            roll : 0
        }
    });
}
```

OS: Windows 10
Browser: Chrome 51.0.2704.103 (also seen on firefox)

### PR DESCRIPTION
**Pull request by duvifn**
Fixes #4032.

See [#4032 (comment)](https://github.com/AnalyticalGraphicsInc/cesium/issues/4032#issuecomment-289299812).

This PR changes the way that the south plane is computed on the northern hemisphere (same for the north plane on the southern hemisphere).

**Before:**

before_hopefully_final

**After:**

after_hopefully_final

I didn't check if this also fixes other issues.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for the detective work and fix, @duvifn, it is much appreciated!

@kring do you have any cycles to look at this?

**Comment by kring** [comment]
Looks good to me, thanks @duvifn!

**Comment by duvifn** [comment]
Thanks @pjcozzi and @kring for the quick treatment.
I really appreciate it!

**Comment by duvifn** [comment]
Just a little comment:
I added this fix to the top of `CHANGES.md` because I didn't know which version it would be shipped with.
Can you fix it in `master`?

**Comment by kring** [comment]
Yep, already did.  Thanks for the reminder though, I did almost managed to forget about it!

**Comment by pjcozzi** [comment]
Thanks for the quick review, @kring.  I will get to #5051 soon...this week, really.

**Pull request merged**
