### PR TITLE
Remove uneeded sourcemap directive from earcut.

### LINKED ISSUE #4094: Chrome dev tools loading incorrect source map (unminified build)
The earcut library has a source mapping url in the comments
```
//# sourceMappingURL=data:application/json;charset=utf-8;base64,...
```
When loading the unminified build in the Chrome dev tools it tries to be smart and picks this up as the source mapping for Cesium.js (which obviously it isn't).

### PR DESCRIPTION
**Pull request by mramato**
The sourcemap directive at the bottom of earcut was giving several users problems.  The simple solution is to just remove it.

Closes #4097
Fixes #4094

### CODE REVIEW

**Comment by chris-cooper** [comment]
This fix doesn't work for me.  This repo should repro the error, and you can hack on earcut in node_modules/cesium to test : https://github.com/PropellerAero/cesium-webpack .  I found the warning remains with your fix, but goes away with https://github.com/AnalyticalGraphicsInc/cesium/pull/4097.

**Comment by mramato** [comment]
Have you brought up the issue with the webpack team?  If the sourcemap isn't the problem and instead it's the UMD wrapper, it sounds like this may be triggering a bug on the webpack side of things.  Another option is that the bug is in the UMB wrapper itself and it's a bug in the earcut build, in which case you might want to open an issue with minimmal reproduction with the earcut folks.

I don't have a problem working around it with #4097 in the meantime, but it would be nice to determine the root cause and have that fixed in the proper repository

**Comment by chris-cooper** [comment]
It looks like there's already [this webpack issue](https://github.com/webpack/webpack/issues/1617).  One of the ideas mentioned is to pull module source code into your webpack built app rather than pre-built libraries.  Earcut on NPM already publishes the source under src/earcut.js but it's not AMD.  The change in https://github.com/AnalyticalGraphicsInc/cesium/pull/4097 is just providing the AMD boilerplate.

**Comment by mramato** [comment]
Thanks, I'll merge your other issue and link to this PR for more info.

**Pull request closed without merging**
