### PR TITLE
Fixed additional texture rotation issue. See Issue #2737.

### PR DESCRIPTION
**Pull request by dwhipps**
Fixes remaining texture rotation issue #2737 .

### CODE REVIEW

**Comment by hpinkos** [comment]
@dwhipps I don't think this is the right solution.
I was testing with this code:
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var rectangle = Cesium.Rectangle.fromDegrees(-86.69777, 30.03883, -76.69777, 40.03883);
var stRotation = Cesium.Math.toRadians(0.0);
var rotation = Cesium.Math.toRadians(30);
viewer.entities.add({
    rectangle: {
        coordinates: rectangle,
        material: '../images/Cesium_Logo_Color.jpg',
        rotation: rotation,
        stRotation: stRotation
    }
});
```

This is what I see in master: 
image

And this is what I see on your branch:
image

**Comment by dwhipps** [comment]
Hmm. Fair enough. That doesn't look right. I'll check it out.

**Comment by dwhipps** [comment]
Hannah,

Try this (notice the very small but non-zero texture rotation):

```
var viewer = new Cesium.Viewer('cesiumContainer');

var rectangle = Cesium.Rectangle.fromDegrees(-86.69777, 30.03883, -76.69777, 40.03883);
var stRotation = Cesium.Math.toRadians(0.0000000001);
var rotation = Cesium.Math.toRadians(30);
viewer.entities.add({
    rectangle: {
        coordinates: rectangle,
        material: '../images/Cesium_Logo_Color.jpg',
        rotation: rotation,
        stRotation: stRotation
    }
});
```

**Comment by dwhipps** [comment]
@hpinkos @jorpiell @pjcozzi Why would there be such a drastic difference between stRotation = 0.0 and stRotation ALMOST 0.0? I can't see anywhere Cesium is checking for stRotation == 0.0 or where we might be making the mistake of e.g.

`if (stRotation)` instead of` if (defined(stRotation))`

Anyone? I feel like I'm pretty close here, but could use another pair of eyes on this.

**Comment by dwhipps** [comment]
@hpinkos Do you think this might be related to your fix in [https://github.com/AnalyticalGraphicsInc/cesium/pull/4206](https://github.com/AnalyticalGraphicsInc/cesium/pull/4206) ? This seems to be another instance where the rotation (in this case the texture rotation `stRotation`) is zero and somehow breaks things.

**Comment by jorpiell** [comment]
Both @hpinkos and @dwhipps are right: in master, the rotation with the angle 0.0 doesn't fails because the pull request that @dwhipps did has not been pushed yet. But in master, the rotation problem has not been fixed yet.

Have a look to the pull request #4535. It includes the minimum changes that work with all the previous use cases and it also works when the angle is 0.

**Comment by dwhipps** [comment]
@hpinkos I think we need someone at AGI to take the reins on this one. Some combination of the pull requests should finish this off. Is there someone there who can do that? I'm not sure how else I can contribute.

**Comment by hpinkos** [comment]
Thanks @dwhipps, I'll take a look at this and @jorpiell's PR when I have a chance.  I'm in the middle of something else so it may be a little bit, but I'll try to get to this soon.

**Comment by dwhipps** [comment]
@hpinkos Any further thoughts on this? Technically this is still broken on master branch.

**Comment by hpinkos** [comment]
@dwhipps I submitted a fix for this in #4725.  Check it out and let me know if it's working for you!
Thanks

**Comment by dwhipps** [comment]
@hpinkos Looks good! Thanks.

**Pull request closed without merging**
