### PR TITLE
new equation in czm_alphaWeight shader function

### PR DESCRIPTION
**Pull request by arneschilling**
The current alpha blending function used in Cesium in not suitable for our vegetation models.
In particular, we have problems displaying a large number of trees from I3DM if they are modelled as transparent billboards. Blended colors from overlapping textures are way too bright. 

Changing the equation in function czm_alphaWeight fixed this problem.
The referenced paper in Shaders/Builtin/Functions/alphaWeight.js (http://jcgt.org/published/0002/02/09) mentions several alpha weight functions that can be used. Buildings and other geometries don't seem to be affected.
Equation (9) works best for us:
pow(a + 0.01, 4.0) + max(1e-2, min(3.0 * 1e3, 0.003 / (1e-5 + pow(abs(z) / 200.0, 4.0))))

comparison of alpha blending with current equation (8) - left and (9) - right:

treescomp
bahnhofcomp
oitdemocomp

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @arneschilling!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Thanks @arneschilling!

There is a corporate CLA covering this.  @arneschilling please add yourself to the **virtualcitySYSTEMS GmbH** section of [CONTRIBUTORS.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md).

**Comment by mramato** [comment]
Spoke with @bagnell offline, he's fine with this change (we both agree this is a big improvement, I've always need annoyed by it personally).

@arneschilling, please add an entry in CHANGES.md about this improvement and add yourself to CONTRIBUTORS.md (as @pjcozzi said above) and then we'll merge this.

Thanks!

**Comment by arneschilling** [comment]
okay, check

**Comment by mramato** [comment]
Thanks @arneschilling!

**Pull request merged**
