### PR TITLE
Added experimental jsdoc tag

### PR DESCRIPTION
**Pull request by ggetz**
As mentioned in #4665, @pjcozzi 

Adding the tag plus a description like so:
```
*
* @experimental This feature is using part of the 3D Tiles spec that is not final and is subject to change without Cesium's standard deprecation policy.
*
```

Results in:

image

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@ggetz, thanks for the pull request! Maintainers, we have a signed CLA from @ggetz, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
LGTM.

Please update CHANGES.md and https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#deprecation-and-breaking-changes to explain that a very small subset of APIs are `experimental` to, for example, allow for implementing draft formats and may have breaking changes without deprecation in future Cesium releases.

Anyone else want to look at this?

**Comment by ggetz** [comment]
Updated.

**Comment by pjcozzi** [comment]
Thanks!

**Pull request merged**
