### PR TITLE
Remove duplicate Rectangle#packedLength;

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by mramato** [comment]
Thanks, it looks like there are duplicate `pack` and `unpack` functions as well, care to remove them before I merge?

**Comment by icholy** [comment]
@mramato I saw that, but the type annotations for `pack` are different. One takes a `Rectangle` and the other a `BoundingSphere`.

**Comment by mramato** [comment]
Yes, but JavaScript does not have function overloading so really the second one just overwrites the first one.  `Rectangle` is the correct annotation, `BoundingSphere` is not.  After you remove everything, just make sure the 3 parts (packed/pack/unpack) are grouped together in the file, since they are related.  Thanks.

**Comment by icholy** [comment]
Should I squash?

**Comment by mramato** [comment]
No need, we don't really curate our commit history.  Thanks again.

**Pull request merged**
