### PR TITLE
update children transforms before checking their union for culling

### PR DESCRIPTION
**Pull request by austinEng**
@pjcozzi @rahwang This fixes the culling problems we were seeing in the game

### CODE REVIEW

**Comment by pjcozzi** [comment]
@rahwang could you please test this?  Feel free to just keep the game built off of this branch until @lilleyse is able to review and merge this.

**Comment by rahwang** [comment]
Works great! Thanks, @austinEng !

**Comment by lilleyse** [comment]
Thanks for the fix.

**Comment by pjcozzi** [comment]
Thanks @austinEng @rahwang @lilleyse!  Good eye and fast fix.

**Pull request merged**
