### PR TITLE
Added frustum offset to PerspectiveFrustum.

### PR DESCRIPTION
**Pull request by craigsketchley**
Added a simple frustum offset property to PerspectiveFrustum. This is something we require for the [Cesium VR plugin](https://github.com/NICTA/cesium-vr) and could be useful for others.

### CODE REVIEW

**Comment by chris-cooper** [comment]
Hi @bagnell, just wondering if you've had a chance to look at this?

**Comment by kring** [comment]
@pjcozzi or @bagnell it'd be really helpful if one of you guys could review this.  It's small, low impact, and well tested, and merging it will enable the [cesium-vr](https://github.com/NICTA/cesium-vr) plugin to use actual Cesium rather than a fork.  It also enables Cesium to be used in all sorts of interesting non-traditional displays.

My only hesitation in merging it myself is that Cesium also has a `PerspectiveOffCenterFrustum`, which _sounds_ like it should be usable for this purpose, yet Cesium gets cranky if you try to use it instead of `PerspectiveFrustum`.  I tried to fix this almost a year ago now and quickly realized I have no idea what I'm doing.

So perhaps you guys would be willing to merge this despite that quirk, given that making `PerspectiveOffCenterFrustum` work instead appears to be challenging and will require your expertise, and it's presumably not a high priority.

If merging this is unreasonable, we'll probably end up monkey patching `PerspectiveFrustum` in the cesium-vr plugin, but we'd rather not do that if we can help it.

We're happy to help any way we can, of course, with getting this merged or with figuring out why `PerspectiveOffCenterFrustum` is not an option.

**Comment by pjcozzi** [comment]
We have a few things we're trying to merge for 1.10 - binary glTF, depth picking, and billboards/labels on terrain.  We'll try to look at this after.  I agree that the off center should work here, we'll see what that takes.

**Comment by kring** [comment]
Ok, sounds good.  Thanks!

**Comment by pjcozzi** [comment]
I talked with @bagnell offline about this.  The off-center frustum doesn't work because it doesn't have a field of view and parts of the rendering pipeline depend on a fovy.  It would be a hack to add the field of view and we plan to do VR with one large centered frustum for culling/LOD that contains two off-center frustums for rendering each eye to a separate viewport as I [alluded to here](http://cesiumjs.org/2015/05/14/Graphics-Tech-in-Cesium/).

I would just monkey patch in the plugin until we have VR support in Cesium.  If you are interested in contributing the later, I can provide some guidance about where the code would go - it would probably take a week.

**Comment by hpinkos** [comment]
@craigsketchley I'm going to close this since we now have VR support in Cesium.  Thanks though!

**Pull request closed without merging**
