### PR TITLE
Altered matrix inversion code to behave correctly with single precision zero scaling

### PR DESCRIPTION
**Pull request by mksquires**
A fix for issue #6954 . Appropriate tests have been added.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mksquires!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
I'll let @bagnell review and merge, but this change looks fine to me

**Comment by bagnell** [comment]
I made some minor tweaks in 93cb38e. Thanks @mksquires!

**Comment by mksquires** [comment]
Hello @GatorScot! Sorry I didn't respond earlier, I just noticed your question. Thanks @emackey for responding. I'll add a few thoughts; to really check for a singular matrix the optimal route would probably involve checking the matrix's condition number or its rank (but maybe this is too slow?). The second thing is that we should consider why we elect to stop rendering when we have an ill-conditioned matrix in the first place. There may be a way to more gracefully handle this issue without crashing.

**Pull request merged**
