### PR TITLE
Remove GeometryPipeline.computeBinormalAndTangent for 1.31

### LINKED ISSUE #4859: Remove deprecated `createBinormalAndTangent` function from GeometryPipeline
This `GeometryPipeline.createBinormalAndTangent` function was deprecated in 1.30 and should be removed it 1.31 as a part of #4856.

Make sure to remove the spec for this function too.

### PR DESCRIPTION
**Pull request by shehzan10**
Fixes #4859

### CODE REVIEW

**Comment by hpinkos** [comment]
@shehzan10 merge master

**Comment by shehzan10** [comment]
I had pull the latest master, but I think one of the PRs got merged between fetching and pushing.

Updated now.

**Comment by lilleyse** [comment]
Looks good.

**Comment by lilleyse** [comment]
Ah forgot to remove the `deprecationWarning` include, I'll update master directly.

**Comment by shehzan10** [comment]
Oh I missed that too. Didn't show up in JSHint either (I don't think the AMD modules do anyway).

> Ah forgot to remove the deprecationWarning include, I'll update master directly.
Thanks

**Comment by hpinkos** [comment]
> Didn't show up in JSHint either

We don't have jsHint configured to detect unused parameters in this repo.  There are tons of defines that aren't actually used.  Someone usually goes through and cleans that up maybe once or twice a year.

**Pull request merged**
