### PR TITLE
Further optimizes SampleModels

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
Optimized the glTF 2.0 models upgraded in #8539

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/gltf-2-model-optimize/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@sanjeetsuhag looking at the files tab, it looks like some of these files are larger than what's in master.  Is that expected?

**Comment by sanjeetsuhag** [comment]
> @sanjeetsuhag looking at the files tab, it looks like some of these files are larger than what's in master. Is that expected?

@hpinkos Yes, these are minor size changes and it's just to do with the way the pipeline writes the glTF at the end.

**Comment by lilleyse** [comment]
The `addDefaults` stage is probably increasing the JSON size slightly, but not enough to worry about here.

This is more to get vertex cache optimizations and combining nodes/meshes/primitives to reduce draw calls.

I should be able to verify tonight.

**Comment by emackey** [comment]
Some of these models could probably benefit from PNG -> JPG conversion (when there's no alpha channel).

**Comment by lilleyse** [comment]
Looks good to me too.

**Pull request merged**
