### PR TITLE
Update San Miguel

### PR DESCRIPTION
**Pull request by lilleyse**
Updates the San Miguel model to the 2.0 version on https://casual-effects.com/data/ and re-tiled.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/update-san-miguel/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
screenshot

**Comment by pjcozzi** [comment]
Does this also update https://cesium.com/ion/viewer/c2345d04-b18d-4df0-946a-73bd7958e660 - if not - is there a new link like this that I can use?  I demo this sometimes.

**Comment by lilleyse** [comment]
New version: https://cesium.com/ion/viewer/e281993f-5974-49e4-b8a2-2f49a5af60c0

**Comment by pjcozzi** [comment]
Perfect, thanks!

**Pull request merged**
