### PR TITLE
Use polylines on terrain for CZML, KML, and GeoJson

### LINKED ISSUE #6700: Switch datasources to use polylines on terrain
At least `KMLDataSource` is using corridors for polylines clamped to terrain, but now we can use polylines when available.

What other datasources can be updated?

### PR DESCRIPTION
**Pull request by likangning93**
Fixes #6700

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@likangning93, thanks for the pull request! Maintainers, we have a signed CLA from @likangning93, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@likangning93 I'm seeing 1 failing test:
`DataSources/KmlDataSource when a LineString is clamped to ground and tesselated with z draworder, entity has a polyline geometry and ColorProperty`

**Comment by likangning93** [comment]
@hpinkos fixed, missed something while fixing an eslint error... whoops.

**Comment by mramato** [comment]
1. This is a breaking change, please add a separate item to CHANGES.md that specifically mentions that KML and GeoJSON now use PolylineGraphics instead of CorridorGraphics when clampToGround is true.

2. Also add a separate CHANGES item stating the new CZML properties

**Comment by likangning93** [comment]
@mramato @hpinkos updated!

**Comment by hpinkos** [comment]
Looks great @likangning93

**Pull request merged**
