### PR TITLE
Fix entity visibility for non-dynamic show

### LINKED ISSUE #7132: Updating a hidden polygon with defined height causes other hidden polygons with defined height to be shown
Updating a hidden polygon can cause other hidden polygons to be shown. It appears this only affects polygons that have a defined height (either zero or non-zero). 

Sandcastle example:

```
var viewer = new Cesium.Viewer('cesiumContainer');

var greenPolygon = viewer.entities.add({
    id : 'GreenPolygon',
    name : 'Green polygon',
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-108.0, 42.0,
                                                        -100.0, 42.0,
                                                        -104.0, 40.0]),
        material : Cesium.Color.GREEN,
        height: 0
    }
});

var bluePolygon = viewer.entities.add({
    id : 'BluePolygon',
    name : 'Blue polygon',
    polygon : {
        hierarchy : {
            positions : Cesium.Cartesian3.fromDegreesArray([-99.0, 30.0,
                                                            -85.0, 30.0,
                                                            -85.0, 40.0,
                                                            -99.0, 40.0]),
        },
        material : Cesium.Color.BLUE,
        height: 0
    }
});

viewer.entities.add({
    id : 'RedPolygon',
    polygon : {
        hierarchy : {
            positions : Cesium.Cartesian3.fromDegreesArray([-108.0, 30.0,
                                                            -100.0, 30.0,
                                                            -104.0, 32.0]),
        },
        material : Cesium.Color.RED,
        //height: 0
    }
});

Sandcastle.addToolbarButton('Hide', function(){
    viewer.entities.values.forEach(function (entity) {
        entity.show = false;
    });
});

Sandcastle.addToolbarButton('Update green polygon', function(){
    var entity = viewer.entities.getById('GreenPolygon');

    entity.polygon = new Cesium.PolygonGraphics({
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-108.0, 42.0,
                                                        -100.0, 42.0,
                                                        -104.0, 40.0]),
        material : Cesium.Color.GREEN,
        height: 0
    });
});

viewer.zoomTo(viewer.entities);
```

• Click Hide button to hide all the polygons
• Click Update green polygon button
• The blue polygon (which has a defined height) is incorrectly shown. The red polygon (which does not have a defined height) is correctly not shown. The green polygon correctly remains hidden.

#2909 appears related, but it's not clear whether this is the same issue.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #7132

Updating the `show` property has a special case if show is constant.  Instead of checking the value of the attribute every frame, we listen for changes to the `isShowing` property and update the attribute value without creating a new primitive.  The the old polygon was showing when the new polygon was added because we reused the geometry instance that still had the old attribute value when the new primitive was created with both geometry instances.

``` js
var viewer = new Cesium.Viewer('cesiumContainer');

var greenPolygon = viewer.entities.add({
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-108.0, 42.0,
                                                        -100.0, 42.0,
                                                        -104.0, 40.0]),
        material : Cesium.Color.GREEN,
        height: 0
    }
});


Sandcastle.addToolbarButton('Hide', function(){
    greenPolygon.show = false;
});

Sandcastle.addToolbarButton('Add polygon', function(){
    viewer.entities.add({
        polygon : {
            hierarchy : {
                positions : Cesium.Cartesian3.fromDegreesArray([-108.0, 33.0,
                                                                -100.0, 33.0,
                                                                -104.0, 35.0]),
            },
            material : Cesium.Color.RED,
            height: 0
        }
    });
});
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/entity-show/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
I tested to make sure this didn't introduce a regression for any of these cases: #7053 #7048 #2909 #4714 #6830 #5371

**Comment by mramato** [comment]
This all sounds vaguely familiar to me, but do we know when this regression happened?  This is just putting back old behavior, right?

**Comment by mramato** [comment]
`git bisect` points to 6d11d0fdf5c8e4474a46d7d7665d2a6527df8263 as the first bad commit.  Does that change how this should be fixed at all?

**Comment by hpinkos** [comment]
This is a better fix than the old behavior because it specifically addresses changes to show for static geometry.  The code from that commit you mentioned was removed because it was causing problems for dynamic geometry #7048

**Comment by mramato** [comment]
Sounds good. Can we add unit tests?

**Comment by hpinkos** [comment]
Thanks for pushing back on this @mramato!  I assumed we didn't have many unit tests for things like this because they were difficult or impossible to write, but it was actually pretty straight forwards.  This is ready now

**Comment by mramato** [comment]
You have some failing tests

**Comment by hpinkos** [comment]
@mramato this should be ready now

**Comment by mramato** [comment]
Travis builds are down while GitHub is still recovering from earlier failure.  So I'll have to test this locally but will merge if there aren't any problems.

**Pull request merged**
