### PR TITLE
Event class - removing multiple listeners from within a callback(s) yields some unexpected results

### PR DESCRIPTION
**Pull request by duvifn**
I found 3 problems with current implemetation:

1. [This code](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Event.js#L154) changes the `listeners` array within a loop so the next indices are pointing to the wrong position in the array, and the wrong elements are deleted.
[This spec](https://github.com/duvifn/cesium/blob/fix_Event.removeEventListener/Specs/Core/EventSpec.js#L71), running with current Event class code, would fail.

2.  When calling `raiseEvent` recursively  (listener that calls the `raiseEvent` again).
In this case the delete operation occurs despite the fact that it inside a 'raiseEvent' since `this._insideRaiseEvent` is reset by the second call.
[This spec](https://github.com/duvifn/cesium/blob/fix_Event.removeEventListener/Specs/Core/EventSpec.js#L100) running with current Event class code, would fail.

3. `toRemove` array has to be sorted before [this loop](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Event.js#L154).
[This spec](https://github.com/duvifn/cesium/blob/fix_Event.removeEventListener/Specs/Core/EventSpec.js#L172) running with the **fixed code**, when toRemove.sort() is commented out, would fail.

I fixed the code and added some new specs.

### CODE REVIEW

**Comment by duvifn** [comment]
I had a typo in the commit message (`toDelete` instead of `toRemove`). So I made `commit amend` and now it's ready

**Comment by hpinkos** [comment]
Thanks @duvifn, we'll take a look at this soon =)

**Comment by hpinkos** [comment]
@mramato do you want to review this?

**Comment by pjcozzi** [comment]
@duvifn we have a bug bash coming up in a few weeks, we'll see if someone can review this then.

**Comment by hpinkos** [comment]
Thanks for the pull request @duvifn!  Sorry we didn't get a chance to review it.
I believe this issue was fixed by this recent pull request though: #5833
That change is included in the Cesium 1.38 release.  
I'm going to close your PR.  If I misunderstood and this was fixing a different issue, please re-open it.  Thanks again!

**Pull request closed without merging**
