### PR TITLE
Fix for 3D Tiles Interactivity demo

### PR DESCRIPTION
**Pull request by lilleyse**
CC #5676

Sort-term fix for the 3D Tiles Interactivity demo.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@lilleyse thanks for the pull request!

I noticed that [`CHANGES.md`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the Cesium API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and bump this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by pjcozzi** [comment]
Do any other Sandcastle examples need this?

I suggest parking this PR and then merging only if we are not able to do the real fix in time for 1.37.

**Comment by mramato** [comment]
> Do any other Sandcastle examples need this?

Pretty much everything using 3D Tiles has a problem, both with picking and draw order/translucency.  So we definitely need to fix this for real ASAP.

**Comment by bagnell** [comment]
Closing this in favor of #5770.

**Pull request closed without merging**
