### PR TITLE
Update AMD loaders

### PR DESCRIPTION
**Pull request by mramato**
Update `requirejs` from 2.1.9 to 2.1.20.
Update `almond` from 0.2.6 to 0.3.1.

Someone related to #3106, but this can go into master at any time.

### CODE REVIEW

**Comment by mramato** [comment]
Don't merge this yet, there may be an issue with minified Workers that I'm looking into.

**Comment by mramato** [comment]
It looks like the upgrade causes all release tests that use `Specs/TestWorkers` to fail.  @shunter were we abusing the loader at all in any way that would cause this to fail?  After doing a build the path ends up being something like `Specs./Specs/TestWorkers/returnParameters.js` instead of `./TestWorks/returnParameters` or `Specs/TestWorkers/returnParameters` (I'm not sure which one is correct(.

**Comment by mramato** [comment]
@shunter I noticed `cesiumWorkerBootstrapper` has an entire copy of requirejs in it (which I hadn't updated but assume we should).  There's definitely an issue between either that, or something we are doing in `TaskProcessor` that are causing a few Spec test failures.  Cesium itself seems to work fine, but some worker-related tests are failing.  Any ideas?

**Comment by shunter** [comment]
I tried this branch and everything seems to be working.  TaskProcessor specs are passing for me in normal mode, combined mode, and minified mode.

Aside from that, yes, you should update the copy of require.js in the bootstrapper.

**Comment by shunter** [comment]
Nevermind, I just noticed that your force push made my git update fail.  I'll try again.

**Comment by mramato** [comment]
> Nevermind, I just noticed that your force push made my git update fail. I'll try again.

Sorry about that, I've been a little force push happy lately to clean up my own commit histories.

**Comment by shunter** [comment]
I fixed the problems with workers in the tests, and updated the version of RequireJS in the bootstrapper.  Merging.

**Comment by mramato** [comment]
Awesome, thanks @shunter!

**Pull request merged**
