### PR TITLE
Fix pickPosition accuracy when depthTestAgainstTerrain is false

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/8179. Merge https://github.com/AnalyticalGraphicsInc/cesium/pull/8205 first.

[Local sandcastle for testing](http://localhost:8081/Apps/Sandcastle/index.html#c=7Vdtb9s2EP4rQr5ELmxa75TctJjjuK2xdA0Sr9sAAwUj0TZRWhQoym025L/vKJm25MQdEPTjDMMSeXe89+PjLZHWltFvVFpvrJx+sya0ZNUGfa737PO0Xk5ErgjLqTzvW/8scgs+ikoJWzdSbFkG0iMjmUpKFP1DSJ7NGx67129khATOWZ7RgsJPruaS5CWvUpqnD3DAkvCSLvLH3utFvgW7SiBQMKuxD9VLIAGxtYFWXNxTBGeq9ZyWarwCjaXaqQbp+tTXR0JcrIhkar1h6ZWWvKyWyzoESlZPmFOyoZKgpaxKBQ7mlGhOFzmNMbBSjNOSqiNbUSHZhim2pSUiWWa3wts8/Kt5I2jvglpJvo/jTOS3tBSVTCmoFptxCYyzzPbiJAhNRAvBcjXhosru1iRj+Wpk8qM/RCmaV0QxkY9qzxrS4054IzLKPxIl2fdRO/fNVmC7fcupvwM3QZHnRInnx47jhEES1PsNQ4SR5/khjuIkjBMv8owYkAfYRX4cBQ72gjjCYbwnanpPJ7v3NKW7gIO/ugxNcDLILstrb6yOvRMiFbyR3LddL/QDz0Uu9h14w6BuEHhJ5EYBSmLHjcI4iPtWEPquhzGKcYSjxMf4UKEM6vIZHR9oHd4bptL1reDcdlHsR5EbuK7jgq4QTh04KI4iP4rjIIBzXd/XAUKOEySg20mcOExCD1ZGG3RB3QJLITeHBtqFH82upr/NZ/O/dh3RVNqa5Bk/btY76Dma3xUkpdMt2P+hYbJNNEGy1EfshHVgZ3lRqXGqHbWXVd68bMSWbkC+Z4pIa0xNdEHnrqxZ+vVGlKwjg4rdjlZkZO95Raecs6IULDt0B7AD664rWvWaQ94hDueXIGZRI3feP3AYJaODWS3qXsTqtIH+SEgfO1k2IYJyND+9fld0A+NMMsIPGZoILiS6vP59euB83PWWdv+xfyoz84eCouvpu/mXyfVs8muT1xck5pCIHyfg/+T97OTdzt5/OMqeCbRYSVKsWdptzkmLYg9c5MGMgCHhYRiaMD9CPSJwAiM1djF2nSAM9d4Aoyh0YVrhIIap60ZYa2trQWvKVmt95wxCR19FzcV7V6yppHabEyat4/S7/t9Or04f6L/oPPQNLtQxL9bEdlDYO328+2JzF7lpCesH4rpcqrJvpVq0M8tMBYIRz2QHKbEvq86R7a5oavHNiVo0qrvPtnzr0j1YYUa+vucbUFRfQfZzbbnvk/dUbKiSD11jpsfkdo9uKVj6/R1cN0QdOuJGg7JSkTyldbTHRQEQRy/R5+ntfPrnl3efbj+O563WMh1ZP1vN88RIc3DXSGObobZtXBm3Rk9dbVnQjuOovep38I9k9xUk5+lMqYvjaCocmzU28nViaha7KarnR0drMp9EfjeG8pzPRnHZdt5sth3bZ6g7FU9n0j5yX+2hty6E2ilEdO9aFxrZHk3RlIuS6sF8AJGN08b5enDq/ryDmywlpeJUOz4XqxWnl5VSUMznNdK2NEiHvxE1LIeHueLSNU2/0uzohvsvcL+Ter3HSMNXPw1JJgEgXpR4roND38M1koy9MMQIKAD8angHSBKAXYBCDMAOXr2XIMkwgTsBcKEf+K4fxw2U9OIg8kBLjBM4F4BqgyX9IMG+CxDcxV6S+GHwIjD5anjWP7so1QOnbxvxX9imEFLpvyA2QkNFNwUMIVoO7yuIsEJpWY+xi6ERusjY1mLZm8XZ0X/ExRnUCylLoCwrzu/Y33Rx9vZiCPwdMS7qQHyCocTJg2ZZu2+vm02E0MUQlk+llBD8nsjWif8C)

This builds on top of https://github.com/AnalyticalGraphicsInc/cesium/pull/8205 by using the "everything-else" color texture to determine whether the pick depth should take the scene's depth value or the globe's depth value for a given pixel. If a pixel in the color texture is opaque it writes the scene depth, otherwise it writes the globe depth.

The one downside I noticed so far is that is breaks `scene.pickTranslucentDepth` since those commands are depth-only and the color texture can't be relied on. I tried a few ideas like writing color in that pass but it exposes a different bug that is very similar to https://github.com/AnalyticalGraphicsInc/cesium/issues/7429 (because my testing Sandcastle happens to use EDL). I have an idea for doing this whole PR differently by rendering a stencil bit for the depth plane and doing a two-pass copy. I'll see how that goes and then bump this PR for review.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@lilleyse the only change in this PR is to CHANGES.md, did you PR into the right branch?

**Comment by lilleyse** [comment]
@mramato looks like I accidentally pushed these same changes to the target branch. Should be fixed now.

**Comment by lilleyse** [comment]
Need to check if this fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/4368

**Comment by lilleyse** [comment]
Decided to go with a different approach. See https://github.com/AnalyticalGraphicsInc/cesium/issues/8179#issuecomment-544529884.

**Pull request closed without merging**
