### PR TITLE
Updates of SampleData models to glTF 2.0

### LINKED ISSUE #7802: Upgrade all SampleData models to gltf 2.0
Looks like there are several glTF 1.0 models still being shipped with Cesium, since almost no one else supports glTF 1.0, we should make sure everything we ship uses 2.0.  We probably also want to revisit how many different versins of some models we have and perhaps more cleanly label some of the files/folders.

Might be a good idea to make everything glb as well.  This is sample data, not test data so we should treat it like we were shipping production-ready models.

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
Fixes #7802

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
This is a great start @sanjeetsuhag. Thanks for wrangling together all the blender / COLLADA files I passed along.

There's a few issues I came across while testing the Sandcastle examples:

* By convention glTF 1.0 models are +X forward. glTF 2.0 models are now +Z forward. All the models will need to be re-exported so they are facing +Z. I wish I remembered this sooner. CesiumBalloon will also need to be fixed since I forgot to fix it in my PR.
    * gltf-pipeline might fix this when it upgrades 1.0 to 2.0. Otherwise it'll need to be fixed in Blender.
* CesiumMan looks thinner now near the torso... not sure why. What does it look like in Blender?
* `CZML Model - Node Transformations` and `Development/3D Models Node Explorer` operate differently than master. See if re-exporting as +Z helps. 
* Remove `CesiumMilkTruck-kmc.glb`. See my comment here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7802#issuecomment-573816822
* `Development/Multiple Shadows` throws an error when loading the model
* `Development/Shadows`
    * `Shadow Tester` is missing its floor
    * `Shadow Tester 3` - some shapes have smooth normals when they should be hard normals

Based on offline discussion the new strategy might be to use gltf-pipeline to convert 1.0 to 2.0 then import/export from Blender to remove the `KHR_techniques_webgl` extension. This will hopefully produce more stable results across the board. I suggest trying this before looking too deeply at any of the bullets above.

And for final testing make sure to check every Sandcastle example that loads a model and compare it side-by-side with `master`.

**Comment by emackey** [comment]
There's a long pause after the end of the CesiumMan animation, so it doesn't loop smoothly in this latest version.

**Comment by sanjeetsuhag** [comment]
> There's a long pause after the end of the CesiumMan animation, so it doesn't loop smoothly in this latest version.

The latest update fixes it. Turns out you have to clip the Blender animation timeline to the animation's end timestep to make sure only the active loop is embedded and not the whole timeline.

**Comment by emackey** [comment]
Animation looks good!  But validation fails.  When you export from Blender, be sure to pick "glTF Binary" and not "glTF Embedded".  The latter is a base64-encoded version that is much less space-efficient.  You'll get a smaller file if you pick Binary.  Thanks!

**Comment by emackey** [comment]
Looks good!  One (hopefully last) comment, in the Shadow tester Sandcastle demo, if you switch to Cesium man, his feet appear to plunge into the ground.  Is that expected?

All of the models validate correctly now, and look good.

**Comment by sanjeetsuhag** [comment]
> Looks good! One (hopefully last) comment, in the Shadow tester Sandcastle demo, if you switch to Cesium man, his feet appear to plunge into the ground. Is that expected?
> 
> All of the models validate correctly now, and look good.

@emackey Good catch! Looks like both Cesium_Man and GroundVehicle clipped through the ground so I've clamped them both to the terrain.

**Comment by emackey** [comment]
@sanjeetsuhag Great work on this.  Any chance you can share the CesiumMan Blender project files with me?  I'm trying to learn more about skinning/rigging in Blender.

**Comment by emackey** [comment]
Or wait... Did you get COLLADA2GLTF working?  What happened to the 90 deg rotation?

**Comment by sanjeetsuhag** [comment]
> Or wait... Did you get COLLADA2GLTF working? What happened to the 90 deg rotation?

@emackey Getting it all to work with Blender and COLLADA2GLTF was a...process. The primary issue with Blender was that it caused the applied the transformation of the first frame of the animation. This is a [known issue](https://github.com/KhronosGroup/glTF-Blender-IO/issues/823), however, following the workaround provided did not work for my case. And the primary issue with COLLADA2GLTF was that it rotates the mesh from the skeleton by 90 on the Y axis (if we're using the glTF co-ordinate system).

To get it all to work, these are the steps I had to take:

*Note: I used Blender v2.82 Beta and COLLADA2GLTF v2.1.5*

1. Take the original [COLLADA file](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.35/Apps/SampleData/models/CesiumMan/Cesium_Man.dae) and open it in Blender.
2. Rotate the whole model to face -Y (rotate by -90 on Z axis).
3. Rotate the mesh (not the skeleton, only the mesh) to face -X. (Rotate on Z axis by -90)
4. Trim Blender's animation timeline to end at whatever time the animation ends. (End it at 50, instead of 250)
5. Export as COLLADA
6. Run COLLADA2GLTF to export to glTF 2.0 file.

**Comment by emackey** [comment]
That's quite a process, thanks for documenting.  Someday the extra trip back through COLLADA needs to be destroyed in a fire.  I have a lot yet to learn about skinning if I want to be the one who does that.

**Comment by emackey** [comment]
@lilleyse please disregard the red X from a different repo shown above.  This is ready.

**Comment by lilleyse** [comment]
The only sandcastle discrepancies I noticed were:
* `CZML Model - Node Transformations` - the waving motion is different than master. I pushed a commit to tweak it slightly: https://github.com/AnalyticalGraphicsInc/cesium/pull/8539/commits/3092b5de654ee93c145f4e2e6e11068631143259
* `3D Models Node Explorer`: if you select leg_joint_R_1 you'll notice that pitch and roll have swapped behavior. Though I actually think the new behavior is more intuitive (roll literally rolls the heel).

Other than that, everything looks great!

**Pull request merged**
