### PR TITLE
Fixing CZML Polygon heightReference and extrudedHeightReference parsing

### LINKED ISSUE #7691: CzmlDataSource not parsing Polygon heightReference and extrudedHeightReference
When providing extrudedHeightReference and heightReference settings like in the following CZML

```
[
  {
    "id":"document",
    "version":"1.0"
  },
  {
    "id":"Polygon1",
    "description":"4m tall",	
    "polygon":{
      "outline":true,
      "extrudedHeightReference":"CLAMP_TO_GROUND",
      "heightReference":"RELATIVE_TO_GROUND",
      "outlineColor":{
        "rgba":[
          0,0,0,255
        ]
      },
      "height":4,
      "extrudedHeight":0,
      "material":{
        "solidColor":{
          "color":{
            "rgba":[
              112,128,144,255
            ]
          }
        }
      },
      "positions":{
        "cartographicDegrees":[
          -84.195222,39.717012,4,-84.195247,39.716866,4,-84.195334,39.716875,4,-84.195309,39.717021,4,-84.195222,39.717012,4
        ]
      }
    }
  }
]
```

These settings are not parsed by the CzmlDataSource for Polygon objects, but are for Labels and a few other objects. For Polygons, the setting comes through as Undefined.

CzmlDataSource.js needs the following lines added in processPolygon method:

```
processPacketData(HeightReference, polygon, 'heightReference', polygonData.heightReference, interval, sourceUri, entityCollection);
processPacketData(HeightReference, polygon, 'extrudedHeightReference', polygonData.extrudedHeightReference, interval, sourceUri, entityCollection);
```

Cesium Versions: 1.55 and earlier

### PR DESCRIPTION
**Pull request by Flexei**
Added HeightReference parsing for Polygon heightReference and extrudedHeightReference CZML settings.

Fixes #7691

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @Flexei! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Flexei/cesium/blob/master/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for the PR @Flexei!  We'll take a look at this after the release today

**Comment by mramato** [comment]
Sorry for the delay here @Flexei, we received your CLA and these changes look good to me.  I think these properties are missing from a number of geometries, so I'll push a small fix and then merge this.

@shunter am I correct that these properties haven't made there way into czml-writer yet?  Should I write up an issue?

**Comment by mramato** [comment]
I was having some issues pushing to your branch so I'll merge this and open a small follow-up PR.  Thanks again @Flexei!

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @Flexei! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Comment by Flexei** [comment]
By all means, tweet away.  I'd also noticed some issues with getting a
polyline to follow terrain and was going to take a look at that next time I
got a chance (if it hasn't already been addressed).

Trubie

**Comment by slchow** [comment]
@Flexei Could you also add your name to the [contributors](https://github.com/Flexei/cesium/blob/master/CONTRIBUTORS.md) file? We want to give you credit for your work. 

Thanks for the contribution! Do you have a twitter handle you'd like us to mention?

**Comment by Flexei** [comment]
Sorry for the slow reply.  Been a little busy here lately.  My Twitter is @Flexei but I don't really use it,, but feel free to use it for a mention. I'll try to get myself added to the contributors file here soon.

**Pull request merged**
