### PR TITLE
Add initial CZML validation document and spec that verifies correct loading

### PR DESCRIPTION
**Pull request by shunter**
This document and the assertions are code-generated by a new generator in the czml-writer project.

Currently, the document contains packets that define every property in CZML, including all materials, and the new key-value properties (node transformations) as:

* Constant value (including all possible representations, e.g. position as cartesian/cartographicRadians/cartographicDegrees/cartesianVelocity)
* Reference value
* Sampled value (for values that are interpolatable)

Future updates may add additional kinds of packets, such as interval-based, but already this effort exposed several bugs in CZML loading, fixed in recent PRs).

### CODE REVIEW

**Comment by pjcozzi** [comment]
Did this bump code coverage?  :)

Can you add a comment to the top of the .js file to explain this and link to the code generator?

**Comment by shunter** [comment]
I don't know if it will increase coverage, but it certainly increases the amount of code that is actually verified, not just executed.  I added a comment briefly explaining how the assertions are generated.

**Comment by pjcozzi** [comment]
Thanks @shunter!  Are any old tests just dead weight at this point that we can remove?

@mramato did you want to look at this?

**Comment by shunter** [comment]
Given that the new tests are more difficult to understand (have to correlate assertion values with packets in an external document) I see no reason to get rid of the current tests, since they are more self-contained and clear.

**Comment by mramato** [comment]
Out of curiosity, did this really not expose any bugs, or did you fix those already in separate PRs?

**Pull request merged**
