### PR TITLE
Extension of the use cases to classify a tileset with a B3DM tileset

### PR DESCRIPTION
**Pull request by ppoulainpro**
Extension of the use cases to classify a tileset with a B3DM tileset.

**Removed restrictions:**
- Only one node is supported for classification and it must have a mesh.
- Only one mesh is supported when using b3dm for classification.
- Only one primitive per mesh is supported when using b3dm for classification.

**Updated restrictions:**
- The mesh primitive must have a position attribute.
- The mesh primitive must have a batch id attribute

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ppoulainpro!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/B3DM_classif_remove_limits/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks Pascal! Do you have a Sandcastle example or test case to help the reviewer test out these changes?

**Comment by ppoulainpro** [comment]
@OmarShehata. I need to do some checks with Draco based B3DM. I have detected some issue at update that I don't have when I don't apply Draco at tiling level.
I will upload after an example that will look like to:

**Comment by ppoulainpro** [comment]
Hi @OmarShehata, I have uploaded an update with Draco support and an example to test it. 
It should be ok now.

**Comment by ppoulainpro** [comment]
Replaced by #8316

**Pull request closed without merging**
