### PR TITLE
Add holes and stRotation to coplanar polygon

### PR DESCRIPTION
**Pull request by hpinkos**
As much as I didn't want to do this, as soon as I looked at wiring up `CoplanarPolygonGeometry` to the entity layer it was very obvious that I should make `CoplanaryPolygonGeometry` supported features mirror what we do in `PolygonGeometry`.

- Added support for holes using a `PolygonHierarchy`
- Added stRotation option (You were right @ggetz =P)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/polygon-api/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@bagnell can you review please?

**Comment by bagnell** [comment]
👍

**Comment by Alegriabaile** [comment]
Hi, hpinkos. Thanks for provide the CoplanarPolygonGeometry && CoplanarPolygonOutlineGeometry interface, it really helps!

**Comment by Alegriabaile** [comment]
If anyone wants a demo of CoplanarPolygonOutlineGeometry, here is how I found:
I tried to find a demo of CoplanarPolygonOutlineGeometry with google but failed. I tried create the outline like PolygonOutlineGeometry/CoplanarPolygonGeometry but still failed. By the way, I found the description of the constructor of CoplanarPolygonOutlineGeometry is outdated.
At last, I found the demo【Sandcastle/gallery/development/Coplanar Polygon Outline.html】 and applied CoplanarPolygonOutlineGeometry to the project.

**Pull request merged**
