### PR TITLE
Improved AO, DoF, bloom, lens flare, and sun with varying resolution scale

### PR DESCRIPTION
**Pull request by IanLilleyT**
More #8113 fixes

Fixed several postprocessing stages that didn't account for pixel ratio

Notes:
- AO still looks slightly wrong, see the sharper edges in the low res version. I'm guessing this is similar to the silhouette problem at low resolutions. See https://github.com/AnalyticalGraphicsInc/cesium/pull/8243
- There was a bug where the sun could jump in size when resizing the browser a single pixel. This was caused by a ceil in the wrong place.
- Added a `dirtAmount` field to lens flare because it was too strong at `1.0`.
- I put `czm_pixelRatio` into `GaussianBlur1D` when `USE_STEP_SIZE` is defined. All of the postprocessing stages in this PR, and nothing else, use this version of the shader. I'm wondering if instead all the post processing stages should take a `frameState` so they can calculate the blue step sizes themselves, and then remove the `USE_STEP_SIZE` define.

**Ambient Occlusion**
new 1X resolution
Screen Shot 2019-10-03 at 4 55 17 PM
new 0.25X resolution (notice slightly sharper edges, needs more investigation)
Screen Shot 2019-10-03 at 4 55 23 PM
old 0.25X resolution
Screen Shot 2019-10-03 at 4 55 05 PM

**Depth of Field**
new 1X resolution
Screen Shot 2019-10-03 at 4 56 19 PM
new 0.25X resolution
Screen Shot 2019-10-03 at 4 56 26 PM
old 0.25X resolution (note the wider blur)
Screen Shot 2019-10-03 at 4 55 54 PM

**Bloom**
new 1X resolution
Screen Shot 2019-10-03 at 4 52 25 PM
new 0.25X resolution
Screen Shot 2019-10-03 at 4 52 35 PM
old 0.25X resolution
Screen Shot 2019-10-03 at 4 54 04 PM

**Lens Flare**
new 1X resolution
Screen Shot 2019-10-03 at 4 57 46 PM
new 0.25X resolution
Screen Shot 2019-10-03 at 4 58 08 PM
old 0.25X resolution
Screen Shot 2019-10-03 at 4 57 36 PM

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/CSS_AO/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
All these look good.

Does the Custom Post Process demo need any changes?

**Comment by IanLilleyT** [comment]
Good catch. The custom post process sandcastle is fixed now. Ready to merge @lilleyse

**Comment by lilleyse** [comment]
CI failed for an unrelated reason (this branch doesn't have the https://github.com/AnalyticalGraphicsInc/cesium/issues/8260 fix merged in).

**Pull request merged**
