### PR TITLE
Resolve issue #3170

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @slozier.  Can you add a test?

@bagnell can you review this?

**Comment by slozier** [comment]
@pjcozzi Done.

**Comment by pjcozzi** [comment]
@bagnell can you review this?

**Comment by bagnell** [comment]
@slozier This looks good. Can you merge in master? Thanks!

**Comment by slozier** [comment]
@bagnell Done.

**Pull request merged**
