### PR TITLE
Fix credits for multiple viewers

### LINKED ISSUE #6965: Cesium logo not showing with multiple viewers
The data attribution is displayed, but the cesium logo and access token message is not.
image

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #6965

We had some some class scoped credits that were causing the same credit instance to be used by the credit display in every viewer.  This change clones the credit so each `CreditDisplay`/`IonGeocoderService`/`IonResource`/`MapboxImageryProvider` has it's own instance of that credit.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Rather than adding clone and making sure we clone the module scroped credits when we add them, wouldn't it just be way cleaner to turn the module scoped credits into per instance credits? (i.e. create them in the consutrctor instead of at the module level?)

**Comment by hpinkos** [comment]
@mramato How is that different than what I'm doing?  I'm creating new credit in the constructor of these classes now. 

We still need module scoped something because we use these to have the same credit used for multiple classes.  Or things like `CreditDisplay.cesiumCredit` are settable by the end user to swap out the default cesium credit.  I guess since we're using all html credits now I could change the module thing to a string instead of a credit instance and call `new Credit(moduleScopedCreditString)` instead of `Credit.clone(moduleScopedCredit)`, but I'm not sure that's much of a win.

**Comment by mramato** [comment]
Fair enough, we've got plenty of bigger fish to fry,

**Pull request merged**
