### PR TITLE
(mostly) fix ellipse rectangle

### PR DESCRIPTION
**Pull request by likangning93**
This isn't a complete fix for https://github.com/AnalyticalGraphicsInc/cesium/issues/6347, but it should be "correct enough" for most use cases. It's on the conservative side, but should be reasonable for "small-ish" (less than 1000 km) ellipses. Quick overview of behavior:
* for "small" ellipses (less than 10 km semi major axis) compute the bounds in 2D space using [IQ's method](http://www.iquilezles.org/www/articles/ellipses/ellipses.htm) and "splat" onto the planet
* for "large" ellipses:
  * compute the bounds in 2D space
  * compute the lat/long needed to achieve those bounds as arc lengths in a local spherical coordinate system that puts the ellipse center at 0, 0
  * compute cartesian positions in a local coordinate system, then transform them to world space and compute the actual rectangle
* for "polar" ellipses, create a rectangle that wraps around the pole entirely and extends to the southernmost/northernmost extent of the computed rectangle from the "large ellipse" method

The "breaking" cases are extremely large ellipses placed on the equator and tilted by about 45 degrees.
I've put together a Sandcastle for comparing, here on [cesiumjs](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVZtb9s2EP4rhL9YHlzKGRBgSBxjjue1QR0EcLIOBQwUlHSxWVOkQFJO3MH/fUe9S7FbF8P8xTre+8PnTtoxTXYcXkCTGyLhhczA8DSmn7Izrx9m4kxJy7gE3R9cr+RK7tArZNqiksnrXNbKMsuVxDgjOioODcT8nkulp6/coOZy5H5NJftaKS9GTa2r6l5FIFDzz0oS/FUprqrHYa5ph7rqyH4WeiUPWfFFh1upwq1KLbWahVuvSpd3+JzKMEsVsy3MheCJAS8EaUEPynJy3CgecsvBUA2x2sFUCC+PccyGRZFXuLtfogx3aa5IHntYqyBPis007KteK0yv2vLwiO0pXDq2DXQLiO6Z3VCrlizCazZeaTDoOMYMK+dM1I4zJZSmy/kf9IXbzVQkG+aN6GXXcQN8vbHoNqrPD/njoYbQ98nX1Fi01kCelSZ2A0RDaJlcCyhgRsIUgL0HFYPVe6RNk9DztrZ5CTn05MgdnAv1uTCfD/EbFFyHaw0gl2Xn2OAP2FWB9JZEoVI64hJvztXbgY5Wjmfe9Of5YvHw97mX3VHgDArcLaixOoWhu+/CNnbXHgDCabOLLy2tIhE3iWD7o5Gymrol3i6ms4/HaXYoV5pVSgTMbcJIhWmMsNI12LkA93i7v4u8fmGS7cHuImFJIva3XCKua1MvlGEZd3B0/WCGh8CA3rFAQNOrX5KhP6AmDUyoeQBeXne5njxk+CcmUhg0L7ixihOmDfwpFLO16XVt2dpu5UIvDRCXny25Rfyfrrv7QjhWPPklW+bXp4b05s3u/7Vhy5+JV3QTwTNyJWq0PegOyXfRabKoBCp7DzrqfmAyEt136mPo5vcxYSHMd8iowsgrptjg+gEaMoxiXLhmIIojcCeT1E5z+Coc3RvHsbOqvaqzXg8hi0EzmvBwm3ejeFQ50vIVNCStOtZCBUChtC+7dgDWUDQB+xGVDsNTODztE6DLu/cfnr7MFnezjwWWeTXflIqflNfZdLlJb9gbG7sXMMmz/M7jRGlLUi08Sn0LMe4ILMQP0nALloYmcxz7pdM44jvCo5tVr/Ods+qRUDBjUPOcCvHIv8GqNxn7aN9yQ266aX/YgXbbCE02F5NFfkgpHfsovvUq9gGa53WPrRukydgGKtpPakjHVuNhNFkW8zz2UWiqm1J2wh1HiEVAMY3GFY5lk5hLlN5d/IbfZU5kryiWkrGQODETImbZuwA3GJ7s3Lg1PrRIdvBXgjZ43M8y9asWjldg4dW6HAgfSpffz9CKdaTVR5xrkg02ySb7NVsE/wmTJiDu07SJyOUpRNov9/8NllaaU9jgI1LEz4mD/xmPHMNzyv0L).

### CODE REVIEW

**Comment by hpinkos** [comment]
Why can't we just

``` js
var positions = EllipseGeometryLibrary.computeEllipsePositions({
    semiMinorAxis: ...,
    semiMajorAxis: ...,
    rotation: ...,
    center: ...,
    granularity: ...,
}, false, true).outerPositions;
return Rectangle.fromCartesianArray(positions)
```

?

It'll always be correct and we don't have to add a ton of new code for something we already know how to do.

**Comment by mramato** [comment]
Unless there is a demonstrable performance barrier, I'm with @hpinkos, less is more.

**Comment by mramato** [comment]
Also, is there a reason this needs to be computed at constructor time?  Couldn't it just be done in the worker and use the same result of the existing creategeometry call?

**Comment by bagnell** [comment]
> Also, is there a reason this needs to be computed at constructor time? Couldn't it just be done in the worker and use the same result of the existing creategeometry call?

It's used to get the min/max heights for terrain which is needed to create the geometry on the web worker.

**Comment by mramato** [comment]
Maybe a bigger change after this initial PR, but can't we just fetch the terrain heights on the worker as well?

**Comment by likangning93** [comment]
newly opened here: https://github.com/AnalyticalGraphicsInc/cesium/pull/6382

**Pull request closed without merging**
