### PR TITLE
Reduce sample data size

### LINKED ISSUE #8284: Look into why CesiumJS release zip grew significantly larger in the 1.50 release
Screenshot_20191014-125239~2

I noticed this recently, and I couldn't find anything in CHANGES.md that explains why the packages suddenly grew by almost 30MB. It would be a good idea to make sure this is expected and not something we need to fix in our release.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #8284

- Removes unused source model files from `Apps/SampleData`
- Hosted the environment map for the `Image Based Lighting` sandcastle example
- Better compression for `fire.png` image used for particle system sandcastle example
- Resized PNGs for boombox test model used in specs

In total, this reduced the release zip file size from ~92MB to ~52MB

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/reduce-zip-file-size/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Maybe keep the shadow tester models? They are used in the shadows development sandcastle. At least they aren't too big.

**Comment by hpinkos** [comment]
@lilleyse if you ever need them for testing, you can use them on your local machine.  I don't see a need to package them up as part of sample data in our library.

**Comment by mramato** [comment]
I don't see anything wrong with keeping non huge models around in the repository if they are useful for debugging, but that doesn't mean they need to be part of the release zip.  Perhaps have a data subdirectory or something under Development Sandcastle examples? This directory is already ignored for release so it will stop the models from being included but still have them available for testing.

**Comment by hpinkos** [comment]
Added back the shadow test models.  Anything else?

**Comment by mramato** [comment]
Awesome, thanks @hpinkos!

**Pull request merged**
