### PR TITLE
Freeze renderstate

### LINKED ISSUE #3752: Freeze RenderState
`RenderState` objects are supposed to be immutable so we can map the minimal amount of GL state changes between draw calls. All `RenderState`s should be frozen as well as all of the object literal properties, except for `_applyFunctions`. We'll need a function that freezes an object and its properties recursively so we can use a pragma to remove it from release builds unless it has a negligible performance impact.

### PR DESCRIPTION
**Pull request by ateshuseyin**
fixes #3752

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @ateshuseyin!  @bagnell can you take a look at this?

**Comment by bagnell** [comment]
@ateshuseyin, this doesn't entirely fix the issue. You wrote a function to do a deep freeze of objects, but does not freeze the render states.

Take a look at `RenderState.fromCache`. We want to freeze all new `RenderState`s.

**Comment by ateshuseyin** [comment]
@bagnell I caught a problem or have a problem :)

3 tests of ShadowMap fail. I mutates render state.

**Comment by hpinkos** [comment]
@bagnell do you have any feedback here?

**Comment by hpinkos** [comment]
@bagnell I fixed the failing tests.  This is ready for another look

**Comment by bagnell** [comment]
@hpinkos looks good. Can you fix the whitespace in `RenderState` and for the requires in `freezeRenderState`?

**Comment by hpinkos** [comment]
@bagnell ready

**Comment by bagnell** [comment]
Thanks @hpinkos and @ateshuseyin!

**Comment by mramato** [comment]
@bagnell this PR breaks master because we only freeze in debug mode and the tests don't account for it.  Should be an easy fix if the tests can detect which mode they are in.

**Comment by hpinkos** [comment]
@mramato @bagnell fixed in #5925

**Pull request merged**
