### PR TITLE
Don't clamp KML or GeoJSON billboards and labels if `clampToGround` is false.

### LINKED ISSUE #4415: KML sandcastle demo really slow in IE
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/ko8w1DEhjgU

This is especially slow in loading the second GDP example.  The user says when toggling between the first and second example he expeienced an out of memory error after a few times.

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML.html&label=DataSources

### PR DESCRIPTION
**Pull request by mramato**
Closes #4415 

@tfili can you review this.  Was this an oversight from when we added clamping, or did we specifically have it always clamp billboards and labels?  I feel like the clampToGround option should be consistent throughout KmlDataSource.

### CODE REVIEW

**Comment by mramato** [comment]
@tfili GeoJsonDataSource was doing the same thing, so I updated the code there too.  However, I'm not 100% this is what we want, lets discuss tomorrow.

**Comment by mramato** [comment]
To expand on this a little more, the root of the problem is that clamping to ground is currently prohibitively slow on some browsers or with lots of data.  It's also buggy (which we definitely want to fix this week).  However, even if we fix the bugs, I'm not sure performance is there yet and as I said in my originally post, it's weird to me that the `clampToGround` option was being ignored for billboards and labels to begin with.

So I think I want this PR to get merged, but I'm open to discussion or other people's thoughts as to what the default behavior should be.

**Comment by tfili** [comment]
This looks good. Thanks @mramato.

**Comment by denverpierce** [comment]
Wasn't this intentional?  CHANGES made it seem like it was supposed to be this way:

> Point and Model features will always respect altitudeMode

> Points with a height will be drawn at that height; otherwise, they will be clamped to the ground.

**Comment by mramato** [comment]
Yes it was; (apparently I wanted it that way even though @tfili disagreed). Because of some issues that have been reported and performance work that still needs to be done on clamping, I think this is the better (and more consistent) strategy for the time being.  Our goal is still terrain on by default, at which point the `clampToGround` options on datasources will most likely get deprecated (and always be true); but we're just not there yet.

**Pull request merged**
