### PR TITLE
Fixed "Scene/Model renders with lightColor" test

### LINKED ISSUE #8127: Model rendering test failures in master
I'm doing the 1.61 release, and the following 3 tests are failing in master:

* http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20loads%20a%20glTF%202.0%20model
* http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20renders%20with%20the%20KHR_materials_unlit%20extension
* http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FModel%20renders%20with%20lightColor

@lilleyse I know we made some changes to lighting in 1.61, like turning off HDR, but I wouldn't expect this to cause an unlit model to render darker than it should be. 

Although actually inspecting the color drawn for this unlit model in the specs, it seems to be exactly the same from 1.60 to 1.61 (it's slightly darker than the base color in both versions). 

Here's a [Sandcastle in 1.60](https://cesiumjs.org/releases/1.60/Apps/Sandcastle/index.html#c=tVVhb9owEP0rFl8IUpZAgXZrabWWTuukoXWl65cxTW5yIRaOjWyH0k38952dBEIqbZXWWgjZ5/O7d+98zooqsmLwAIqcEgEPZAya5Vlw52xeO3LLsRSGMgGq7ZPfM0FwMJHIC7kmxyShXINfWDVwiAyT4pOIWUSNVE2HlMbyQaPVqHxnlDmPzwXLqIFyayY2nZOZmIkkFw6RRApweyJj4F6uuE9SYPPUdCpGRRoBCMMMAx0oyOQKzjn3CiDng+kupWYO8LRKdkyVwRkV/SBRMruEuQLQ3pveQT/oHg0Gh713PhkMgu6w2z/qHm4jn+xAU6AxE/Md5oSaNDDyBs1UaK/XH9bdl8xEKTp3azYlOW+Y0mWjLFdFmGt7/Ab9vTKuXyD6DqQeSCqGgtD9fG8VUkqkynSQNgC/5qixEujuVTr5lsa+hE7jRwRsak7j2CvLYYegma2nrdbOuNX/eDut7dYJH9dXNZ/M3gHcrUWyI1fsSTDnzvBm5dk1WwOfsl+WUe/gbdOJrq3TNKLcOhx0cTRcwpDbso8ld9e6VpbdBfKGQdcn1V9nB7ApppttcQrljKLRAuIPlaCFsuizsXq7Ci5t9hr3vpf5GlgbjN8+ZypSNDHtkid6ufazLVc2jdepi1TvoHYQhMVvuoRIh5fU0NBt6fD64ibE3v4mODPbSTDnJsH+H6IwmFmZBtLcbN+EithHJXMRkztIWcThf+hNabbk4LhlBbcCu4TeXyHDeyT4d25X0hAUjlxQzqUUL0uuuA4l9P6qJNf7t3oTxhfkVuXR4jXIWXQH3ly/WWTRsxScLpgQEJNxSvHyGvtReAWatNLvJ06fxesS2UgyltlSgdZI0AV6WXIuxi5EU8OqR/aI/nBP55SKOKLa4DXFR/JWSn5P1QRE7pUNbo+0/NZIm0cOZ8Xx9yxbSmXsm+YhHwPIB0nq8B6DgQki7Y6NwurQKGYrwuLTWavx4Z61SMSp1riT5Nw9g7PW2ShE/71jXLrvwZcVKE4frUvaO/tcGIMgGIW4fHrKFOnUEP8A) if you use the browser's color picker you'll see renders as `#00d100` and not the expected `#00ff00` both in 1.60 and in master.

### PR DESCRIPTION
**Pull request by IanLilleyT**
Fixes #8127  

As guessed by @OmarShehata in https://github.com/AnalyticalGraphicsInc/cesium/issues/8127, this test is affected by the current time at which it is run. So I hardcoded a time that works.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/testRenderLightColorFix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by IanLilleyT** [comment]
Actually I need to check the other tests mentioned in that post before merging

**Comment by IanLilleyT** [comment]
Ok, looks like the other tests have been fixed already. I also improved this test to expect exact colors instead of not(0,0,0,255). The test works on linux, mac, and windows.

Ready to merge

**Comment by lilleyse** [comment]
> expect exact colors

Yeah that's fine since it has `5` epsilon

**Pull request merged**
