### PR TITLE
Added support for large Rectangles in OrientedBoundingBox.fromRectangle

### LINKED ISSUE #4483: GroundPrimitive bounding volume doesn't take curvature of the earth into consideration
For example, the bounding box for this rectangle is too short:

image

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var primitive = viewer.scene.primitives.add(new Cesium.GroundPrimitive({
    geometryInstances : [new Cesium.GeometryInstance({
        geometry : new Cesium.RectangleGeometry({
            rectangle : Cesium.Rectangle.fromDegrees(-110.0, 20.0, -80.0, 25.0),
            vertexFormat : Cesium.PerInstanceColorAppearance.VERTEX_FORMAT
        }),
        attributes: {
            color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 0.0, 0.0, 0.5))
        }
    })],
    appearance : new Cesium.PerInstanceColorAppearance({
        closed : true
    })
}));
primitive.debugShowBoundingVolume = true;
```

### PR DESCRIPTION
**Pull request by IanLilleyT**
There have been reports of 3D tiles that use `TileBoundingRegion` disappearing when viewing from a horizon angle. This is because the root tile generates a broken `OrientedBoundingBox` when the `Rectangle`'s width is greater than half the ellipsoid. The terrain system doesn't have this problem because it handles this edge case and generates a `BoundingSphere` instead.

In this PR `OrientedBoundingBox.fromRectangle` has been made to work with larger rectangles. The approach is different than small rectangles which orient the OBB around the rectangle's center normal. I tried doing it this way for large rectangles but it produced very poorly fitted, albeit correct OBBs. The final approach ignores the latitude when calculating the OBBs orientation.

With this fix, all of the special case code is gone. I did a good amount of testing but this change impacts a lot of core systems so more eyes on it the better.

Fixes #4483

[Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=tVdfb+M2DP8qXh+uzs51k3QH7HJpsbbr7Qr0H9ruuocCg2IzqVBbDiQ5TTr0u4+ULVu2212yw/khkSiSIn+kKGrBpLfg8ATS2/cEPHnHoHiehl8Nzd+OzPQ4E5pxAXK79+leLFBGRSAARQrZ0ExxqVgk4nkWQ4IM/9wLD78nUNobeTuDvX7YDwoaMEN779JUlusHYhzWNJFJQ3tPtHvxYvYp7XwUWfSIMqGWLHr0q52tnTrLkgkj5+IsylMQOpyBPkmAhker09jfLlmMa22tbD5PVkdcxFzMVK09sHpJZppJz6e9BEvB46J2v2e951OvFg4fmLp8Elcym4PUK5/EehUrfW0r0OLLiQK5YJMEXCuMaKjyiYokn4Cfz2Om4RoizcQsAbKO9L0gaITZNBeR5pnwWnx+tbsbznAueco1X4AKJaTZAg6TxLc6S35024R237vI0wlmTO0m0S038Zlwv8JHdJevSIFXGM2Cy1kkxiucZsHl1JDOTdrYaBSi42KzBvjESmeBGD7VZLuXEXDo1tpyhxLuJkLSAo18ZWwr7MOpzNLfYSYBlE+QBYXKwOAVeJUrtbqUC57m6RfgswdC9EOfvrDv+JuyZYNl0O/ySIgrK06FwkEEzSLwB2QpaLmyq74D06xcw3PpSFQKragrQl8NxageB02eBR4LWH7OZMqoPpSqr0BaO46zJJOH8zkwSdPw68n17clff3++vD4/vG0pg6WWeQxxCcWoCU2L+aFiciGueV56jgDTGg9drkGNvJaXERlYWW7MbWN5aKVNAhgW3wGyIAywBnp95+dDr+dYU6ZbnR2dc8vi2NV6ZVdei6S1TJnQdHPDdb3Cvhn+t2PUzoMoyRTEKI3RARdg61O3zmSTSX1+LiXHAg7xUZab4nyULQ2QdU2rs6sZzaCZAd19cFX1653OGQZquUdFGH3KU+GjIVjDk+nhEhQGJXAROGaYu4ozsef33AJESgfrKx2srXS4vtLh2kr7ZyBQ7zDsez93+cOUzQTXeKp8w9zxcxPpQcehTaSHvUZVr2z/aX+fjoz37l1tUYs2dGiNC6AC4QIrUI2uY4Og0pTw59L/b8LaAGdNrYONtA7X1DpcW2tEx4v6JsqhYlJBbXlijl2UwoZCNe8NR6+NSFDFIajQ73UUTrKlucCLTG4qLWi/+M06UgUqXAY1vnYytJPCARy9Jb1ypVeu9KqSXr0p/exKP7vSz5X0c0u636ztA2pt7dqryFzmOsEe3F4kdbSPOmtFU1FFp118nbiNnIlbhv/DgM17hVa/0PWlBU3q5MColRTtGFSXsNe5haub2Nv8Knb5w7svp7cnvabylzfR+l+X8FsXcRf2NgDffRXTN01Mq0WXcdBdlSBikDca3wyvo0wf2XjHY/NSw1A9hHjr+kNK7QKQ8tY9TDjDm//Mcve62l5aSLstD9Ype1cXr5rOUwZjsRVsjZVeJXBQcP7G0zm20V4uEz8Md6lVR39B7U7y6BF0GClFYuNdKzSO+cLj8f79Vuv9e7+FnQtTClemeZLcYF293zoY7yJ/QyzJGHUll9jKJmxFLA+Dg7OCGIbheBenXanyUYnsSNX02DsY60kWr0o/xloe1FiMdXxwhw+G8S4OmuQxF/Nce3o1B1SLUZ+hmdQG4Wxn8GufJmyJk2KsNMxpgkMEk+1M8MGL8wVLchh5xaPETP40YI+8baN/27hebY5D+aahJ+zHG1o8mL7T0Bt6fG1q6cfa0I/ftrN8332noRf0MPyxhpq35waG4p/JVvw3yUsUTO5/AQ)

Examples:
Screen Shot 2019-12-18 at 5 46 45 PM
Screen Shot 2019-12-18 at 5 45 45 PM
Screen Shot 2019-12-18 at 5 45 33 PM
Screen Shot 2019-12-18 at 5 44 46 PM

3D tile before (incorrectly culled):
Screen Shot 2019-12-18 at 5 53 26 PM
3D tile after:
Screen Shot 2019-12-18 at 5 51 35 PM

@loshjawrence 
@lilleyse 
@jasonbeverage

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/obbBigRectangle/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by jasonbeverage** [comment]
Very cool, this will help tremendously with global datasets!

**Comment by hpinkos** [comment]
@IanLilleyT could this fix #4483?

**Comment by IanLilleyT** [comment]
Just tested and it does not fix it, but I'm looking into it

**Comment by IanLilleyT** [comment]
@hpinkos  Looks like `GroundPrimitive` swapped the order of the `minimumHeight` and `maximumHeight` parameters to `OrientedBoundingBox.fromRectangle`. My newest commit fixes it.

[Sandcastle from #4483](http://localhost:8080/Apps/Sandcastle/index.html#c=dZJha9swEIb/ivCX2pDKyaAwWjc0zdox2GhJSxjMYyj21RWTJXOSnKUl/72SPaeKx/RB6HT3vLo7XcuQtBy2gOSSSNiSJWhua7ru7uKTojOXShrGJeBJcpHL1jEN8pob3oLDep7qAiTQg0NTVpZxIPkZlZXl/eCPX3NJ3KpA1WBw90Vqw6R7j5yTHyE28g9cyDokIFZQuMhKwICGiF84BDhuzNAnVPUnqBBAx6ez2ZROJ+RDt59+7I0zOk0mx4otoIE/twprZt5F7wGHrJdKKFw0DTD0Jl3frB5vvv+6vVt9Wzy+a+1DYWYM8o01oM/JqILCyx3e6cTHfVoMdFdRFxL+Rn8x8wVNg+0sSYJs+uM++fk3K3Yo4Ljj/y80bH0hlIbSkQYtDNK53Cd+qA5zQ0vY2OrhWW2v/bxwWa2VsLUfNM9dRJMo02YnYN5LXPG6UWiIRRFTmhqoG8Fcz9KNLX6DoYXWXj9LBygreUt4eZlHo+HOI5ci09p5nqwQD/wF8miepS7+CBOK+bTu3KcLtvMhz7P51/6SUpqlzvyXMkqJDcNA8Q0)

**Comment by hpinkos** [comment]
> GroundPrimitive swapped the order of the minimumHeight and maximumHeight parameters

:woman_facepalming: 

Nice catch @IanLilleyT :laughing:

**Comment by IanLilleyT** [comment]
@lilleyse fixed some bugs, ready for review

**Comment by lilleyse** [comment]
Looks good based on my checks
* The number of render tiles is the same between this branch and master. I tested all the different terrain providers and 3D Tiles.
* The OBBs look good with rectangles spanning from positive longitude to negative longitude (crossing IDL)
* Confirmed that the Alaska tileset above and another tileset that had this problem are now working in 3D.

The only thing to fix now is there's a crash when switching to 2D or CV with the Alasaka tileset.

crash

**Comment by hpinkos** [comment]
@lilleyse did you check rectangles at the poles?

**Comment by lilleyse** [comment]
@hpinkos yes I forgot to mention that, I checked as many extreme cases as I could in the Sandcastle example including poles.

This is how I ended up hitting this bug, which also happens in master: https://github.com/AnalyticalGraphicsInc/cesium/issues/8478

**Comment by IanLilleyT** [comment]
@lilleyse That crash you posted is a different problem which is fixed here: https://github.com/AnalyticalGraphicsInc/cesium/pull/8482/

**Comment by lilleyse** [comment]
@IanLilleyT cool, I'll check that out next

**Pull request merged**
