### PR TITLE
3D Tiles - Refinement based on proximity

### PR DESCRIPTION
**Pull request by lilleyse**
For https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/101

Not ready until #4130 is ready.

>  If viewerRequestVolume has multiple sub-properties, the viewer needs to be in the union of them?

I'm not handling this right now. We don't handle it for our other bounding volumes either so maybe we should wait to do them all at the same time.

> For replacement refine, I think it is fine to refine the parent and only render the children that base the new volume test (even if it isn't all of them), but we should refine the parent until at least one child is ready to render and visible.

For the sake of making the implementation super easy, I left out this point for now.

To do:
* [x] Fix debug volume not drawing.
* [x] Add debug volume button to Sandcastle example.
* [x] Example dataset for Sandcastle example.
* [x] Unit tests
* [x] Replacement refinement, https://github.com/AnalyticalGraphicsInc/cesium/pull/4138#issuecomment-233813604

In action, and working with the `transform` property:
capture
capture2

### CODE REVIEW

**Comment by pjcozzi** [comment]
>> If viewerRequestVolume has multiple sub-properties, the viewer needs to be in the union of them?

> I'm not handling this right now. We don't handle it for our other bounding volumes either so maybe we should wait to do them all at the same time.

Should be trivial, just check each with `||`, but....maybe we should just change the spec to allow only one sub-property (for this and all BVs.  We could loosen it later if there is a good use case.

What do you think?

We don't handle it for other bounding volumes because for them the spec says that it is OK to use any bounding volume.

**Comment by pjcozzi** [comment]
Hopefully this was obvious, but this

> For replacement refine, I think it is fine to refine the parent and only render the children that base the new volume test (even if it isn't all of them), but we should refine the parent until at least one child is ready to render and visible.

should have been:

> For replacement refine, I think it is fine to refine the parent and only render the children that **pass** the new volume test (even if it isn't all of them), but we **shouldn't** refine the parent until at least one child is ready to render and visible.

OK to wait on this.

**Comment by pjcozzi** [comment]
Added above:

> * [ ] Add debug volume button to Sandcastle example.
* [ ] Unit tests

**Comment by pjcozzi** [comment]
Also added:

> * [ ] Example dataset for Sandcastle example.

**Comment by pjcozzi** [comment]
Looks good!

**Comment by pjcozzi** [comment]
>>> If viewerRequestVolume has multiple sub-properties, the viewer needs to be in the union of them?

>> I'm not handling this right now. We don't handle it for our other bounding volumes either so maybe we should wait to do them all at the same time.

> Should be trivial, just check each with ||, but....maybe we should just change the spec to allow only one sub-property (for this and all BVs. We could loosen it later if there is a good use case.

I changed the spec so that only on property will be in any `boundingVolume` object.

**Comment by pjcozzi** [comment]
>> For replacement refine, I think it is fine to refine the parent and only render the children that pass the new volume test (even if it isn't all of them), but we should refine the parent until at least one child is ready to render and visible.

> For the sake of making the implementation super easy, I left out this point for now.

Looking at this again, the request volume test only applies to the parent so if it passes, replacement refinement continues as usual with no special cases needed.  Implicit in this is some or all of the children may have request volume tests that fail.  See how these feels in practice and we'll update the spec accordingly.

**Comment by pjcozzi** [comment]
@lilleyse should this be retargeted to `3d-tiles` so we can delete the `3d-tiles-transform` branch?

**Comment by lilleyse** [comment]
This is now ready.

I added https://github.com/AnalyticalGraphicsInc/cesium/pull/4138/commits/1513fbbf51c35f0a977e1e5fc782e0df184e24a0 to address https://github.com/AnalyticalGraphicsInc/cesium/pull/4138#issuecomment-233813604, but I'm not sure if the overhead is worth it.

**Comment by lilleyse** [comment]
@pjcozzi Ready when you have a chance.

**Comment by pjcozzi** [comment]
> I added https://github.com/AnalyticalGraphicsInc/cesium/pull/4138/commits/1513fbbf51c35f0a977e1e5fc782e0df184e24a0 to address https://github.com/AnalyticalGraphicsInc/cesium/pull/4138#issuecomment-233813604, but I'm not sure if the overhead is worth it.

Looks OK to me.  We'll reconsidered later if need be.

**Comment by pjcozzi** [comment]
Part of #3241

**Comment by pjcozzi** [comment]
Looks good!

**Pull request merged**
