### PR TITLE
8479 - Fix grey screen on Other/Unclassified toggle

### LINKED ISSUE #8479: Point covers entire screen when hidden
[Sandcastle](https://sandcastle.cesium.com/#c=vViNc9q4Ev9XNLk3A0yJMDZfSUjmJZD06CvJXUL72iadjLBlrGJbPltOSjrc334rGRsbQiHXTp0wtqX9+O1qtbtyj0Ys9vCA+9iiNoldcWqaNIpGfEp9dIxKdPbGGb822RV7M3j3NKhfskE08K+bZm/QGkyDD+97bw4wEP1lvZ5KIjYcnX251M+NIdOMT68/Td+Orp2P3kBc/f/86bJXZ1cj68tV//xp+DRsDp8m7G3vTfAJhF32/4wGnutY8Dwc/dm4/AK//lAbGho+M3rtS05nxqc/Pph2+/7iw9n5x0cWmkI37OgdNa/9m7p+4YrLTunozr/zH0iIHhh9pCHY4NNH1EvsfK/GyiVTvfa4LwjzaViqJFxqFkcm9Sl2+YSETDgeM/s0EM5ZbNtKnE3ciCr6Wg2dor/rGhoz12XcRwFnvkBGH42YSyMqELeRcCgymZjJ5yEoDClxq6hHfGIRZJJAxCG1EPORrtWb6BE0IoJCGnE3FlImsOkaMj2shFqI+BZyeCTgcTxb2IWAECdWi4XmY1SwJgiZxwR7oBEmllW+8xFcOcckN6O/AF7+llDIKw7dw5QM4uQaoMWhSbEdcu80AuKBVW42O51WpbpkUp7ouTy2bhxiMX9yiHIi5UWEoH5MpI2HSIQxrRbnPfKVebF3mifTlyTz5HFeufOfWTyTeDQkGMDJFU+tsWgkmK9kocOC9SQU8ER8o1zXm4bWPMBGp6039Xa906ii/Ubb0Du6hhtao2609E6zihpau9HsNPHBQUNrNZpau5maz0NGIa7WtfxOlSf+YMJ0rrnrlnXc0g+0Vqt10GnUG+32AaiqY3jU602j2W4caA3jAHRpWKtrutbUO1qnCcr0didVRn1rFBI/snnooWyZhkSE7GsDD/rnl6PB6OOdP6+kEXsDwREHyHSoOR3zrzRCwIsEn0xcAKfCFeKI8ThCpkuiiNnMTIwBb4L7JhFe7q8ht6gLsbZw8CTksW8VlpODwLAwMo6ZK/0QFUZd/nj/QCdUrEeERy0watOswybO2hwYnO1QMGHiI5O7PIzATkSJ6ayaJmYBXZilIvdGzGAfLA0rxX7KQa0SKgSzknyI7vbUQ7n0m21rcJUqd3u5kI4c/ohScCpyF5Mln4t78khCa7vki4v++Wl/Z8nJcvxkocWF2ia8ZVxctM93Fr621D9Z/kqwbJOu62eGcbqz9Cyyt8mltvx7kctVWG6TC/kB/naWC1WGhg/Uupf16d5ith1HO3hlRy3pHpSbqrjd+syUNxLOcjtsZRvU14NY3xyCxncDqPGd5W8+u3itZ13f3sFxneqGjLFfzyWlkcMiBP8EOdQNoK2wgTzJRByK/z4JAnemcnGUZCKVtATzqBp8N6jl8jcJKWR0i0BLADksk6RkqERWXjQF1YW0Sup0uTRq6Gr8hZqyafgmIRam/kdnMhEmFHgKb+WFFGWMWvulCKyCZLmsSQD5FpOQIOPffl5Ex9E6qwqhnTiXEG2o524vJcumZEkry3kGArUjuHWX1mCX+hPhHKFXr1glr04ygIHAktHess9HRQJmwfymeL4F9s8ZipRF+SQDCey3pf986xVEzNHxMXTb6BXIT5dJCUscugpCuurfCpS8RYzMRmVpFjDs1yurjVoR/a32GfTJbX5UJCtAKlAV6YorVlzv51UerrxX1xkKyg+Lr0XqeQ72HFFo5VcBrEUzXoYhDuLIKRfhVI4280sga+wFdHnueZY5kwe5LouODg5ncFCxykXvVQqLtR14kRtvtmOrDSuSnjUps2ORfrCSWjyQ5c8dSa7KqZaC5mkbpzIi8eGkBEqIm0CEfPdcmsv1cEmWWmib+tyc8lhgERJzWs462EpWqATn7pjIBGZxM/agkcdQLc5dKh/PZnDUKS1I1JlxVa4Cc8Z8VUiW8qup3NUuXB0Os0yO1wWC8quxLDZkDAbmBKZ1sYKjeByZIRvTcpr6VYRloZFzBk6Y0kwrb0frRLlKvEKZ0O7g8fnzbt9szUpJf5lVReZfhnm913gZ7DX+X4Z8tQ96Ge4V7l+GetmhvQxvxvfLkKpD778IYvW+ZXdu6D23cOW70R9yw151r6tS70nC91/mBTwU8itRGeOaoF7gQica1caxOYWcb0ZRWg9+S5NrrmaNIQ+nXw3CyZiUG3oVpT8Nd/JFKSBW8iWpEXzNDY85ZKpwPySwm6L85HxFLfODWBT6PRoKaJfcfeKyCbQNHrMsl65r3Bc8gONHQWs6NeZCcC8/u6oWO5QAwLxim/ti/5HCPhKHgN+1lqzdWurdrsUeoHk7hoNX8Wvl3V7Sf8KMHbvuDXuid3sn3RrQF9hcrr43XYGZLplJEqd+8jYZxBh3a/C6zrWADeQJpq6Q4X3SFWNuzbKxEAasDEZiIbAUe1A0mgU06taEBXqAZcm8dAWIOXmtAkDRFSe6yZLJrzPSDYtCCfbDYYfsj6HOpsMU4ieJI+WKTNJ39b6FbfA+y2M/rL9Yhl6AY6gKwc+EslZaXoDmdwjLn4llpVy8AMlZmrh/GENWAl6g/Uom8dq7XOL8YRiqLmyGUEv2GNzVlpPJINmd/wA) - looks good until you uncheck `Other/Unclassified`. This is a linux only bug. The way we hide points in `PointCloud.js` is to multiply `gl_Position` by 0.0 and hope the point is outside the clip space cube, but I could see how gl_Position.x / gl_Position.w (i.e. 0 / 0) might be undefined behavior. A better fix is to explicitly change the xyz coordinates to be greater than the w value so it clearly gets clipped. It would be nice to do this without the if statement though.

```
        if (hasShowStyle) {
            vs += '    if (show == 0.0) \n' +
                  '    { \n' +
                  '        gl_Position.xyz = vec3(gl_Position.w * 2.0); \n' +
                  '    } \n';
        }
```

Whatever we go with here we should test with every other system that hides points, like https://github.com/AnalyticalGraphicsInc/cesium/issues/7557#issuecomment-550485788. Look for any code that hides points by doing `*= show` and switch to the new approach.

### PR DESCRIPTION
**Pull request by Samulus**
Fixes #8479 , tested on Linux / Firefox / Proprietary NVIDIA driver.  Also tested on Windows with the proprietary Nvidia driver

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @Samulus!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/8479/grey_screen/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Confirmed this works on Linux/Chrome/Nvidia and Mac 2015/Chrome/AMD.

**Comment by lilleyse** [comment]
@Samulus just add an entry to CHANGES.md and I'll merge

**Comment by Samulus** [comment]
@lilleyse Added CHANGES.md

**Comment by lilleyse** [comment]
Thanks @Samulus!

Hopefully this same fix can apply to https://github.com/AnalyticalGraphicsInc/cesium/issues/7557 and any other systems that hide points in this way.

**Comment by Samulus** [comment]
> Thanks @Samulus!
> 
> Hopefully this same fix can apply to #7557 and any other systems that hide points in this way.

Doesn't apply from what I can see, I'm able to reproduce that bug with this commit on Nvidia / Linux still

**Comment by lilleyse** [comment]
@Samulus ah too bad..

**Pull request merged**
