### PR TITLE
Ensure Sandcastle gallery is sorted alphabetically

### LINKED ISSUE #4056: Sandcastle doesn't always alphabetize gallery
image

This happens intermittently when loading Sandcastle

### PR DESCRIPTION
**Pull request by twpayne**
This is an attempt to fix #4056.

Changes:

* Sort gallery entries when building `gallery-index.js`, so that the order is deterministic (previously the order of entries depended on the order in which they returned when reading the directory entries).
* Assume that `gallery_index` is already sorted.

With this PR, the order of `gallery_index` should never change, so entities should remain sorted.

cc @emackey

### CODE REVIEW

**Comment by emackey** [comment]
Reviewing this now

**Comment by emackey** [comment]
Ah, sorry Tom, this actually doesn't fix the problem.  Here are some better reproduce steps:

1. Load Sandcastle into Chrome.  Make sure normal network caching is enabled (ie, you're not "Incogneto" and you don't have "disable cache" checked on the network panel of DevTools.

2. Using a text editor, modify and save (or just touch) the file `gallery/Geometry and Appearances.html`.

3. Click reload on Chrome.

4. Look for `Geometry and Appearances` in the list, and see if it is in the correct place.

These steps use the Chrome network cache to load all demos, but force one demo to come from the server.  The result is the modified demo lags a bit and ends up in the wrong place.

My theory is that the sorting of `gallery_demos` happens correctly on the client, and then the network requests are fired off in alphabetical order, but the buttons appear in whatever order the server responses come back in.  The button order needs to be preserved.

**Comment by pjcozzi** [comment]
@twpayne I cherry picked 9addd0eed43f6ae1822aef084abb25952d03d38d into master given #4449 and #4450.  Thanks again!

**Comment by twpayne** [comment]
Ah, thanks for the explanation and steps to reproduce.

As per our offline discussion, I've updated the code to maintain id order when inserting gallery buttons. There are a couple of minor code-cleanups in separate commits.

**Comment by emackey** [comment]
Minor jsHint fixes needed.

**Comment by twpayne** [comment]
Fixed offline comments:

* Replace `!=` with `!==`.
* Use new variable instead of re-using `demo`.

**Comment by emackey** [comment]
Looks good, thanks!

**Pull request merged**
