### PR TITLE
Add polylines on 3D Tiles Sandcastle Example

### PR DESCRIPTION
**Pull request by hpinkos**
Shows polylines on a BIM model:
image

And on Photogrammetry:
image

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/sandcastle-poly-3dtiles/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by pjcozzi** [comment]
* Please add to CHANGES.md
* BIM model looks great
* (1) are we sure about the photogrammetry model?  The orignial request was to use a higher-resolution one to show the benefit when zoomed in close how the polyline is "pixel perfect."  (2) if that is unrealistic, are we sure this is a good location for the line given the building's facade geometry?

image

**Comment by hpinkos** [comment]
@pjcozzi do you have a photogrammetry tileset in mind?  This is the only one we have in other Sandcastle examples.

**Comment by pjcozzi** [comment]
No, I was hoping you or @ggetz could explore.

**Comment by hpinkos** [comment]
In the interest of getting this merged before the release, I removed the photogrammetry example.  I'll open an issue to add something better for the next release.

**Comment by pjcozzi** [comment]
> I removed the photogrammetry example. I'll open an issue to add something better for the next release.

I dunno, this seems like the most prominent use for this polyline feature.  Why not just move the polyline on the current model and write an issue to create a higher quality example that shows the full value compared to the sub-sampling example that already exists?

**Comment by hpinkos** [comment]
@ggetz the problem with going along edges is you get lots of things like this because the walls of the building are wavy: 
image

**Comment by hpinkos** [comment]
@ggetz ready

**Comment by ggetz** [comment]
Thanks @hpinkos!

Regarding 

> write an issue to create a higher quality example that shows the full value compared to the sub-sampling example that already exists?

Let's write an issue to include a higher quality photogrammetry model for sandcastle examples, and mention this example could benefit from using it, along with the sub-sampling example.

**Comment by hpinkos** [comment]
Done https://github.com/AnalyticalGraphicsInc/cesium/issues/7532

**Comment by ggetz** [comment]
Can you add a note to `CHANGES.md`? We did that with the model wheel animation sandcastle example this release.

**Comment by hpinkos** [comment]
Yep, sorry I missed that @ggetz 
This is ready now

**Comment by ggetz** [comment]
Thanks again @hpinkos !

**Pull request merged**
