### PR TITLE
Able to pick entities from cluster

### PR DESCRIPTION
**Pull request by moneimne**
Fix for #5286

### CODE REVIEW

**Comment by hpinkos** [comment]
@bagnell is this what you had in mind?  This sets the id property of the cluster primitive to the array of entity ids.  Then in the Sandcastle example, it changes the color of the billboards that were in the cluster you clicked on.

**Comment by bagnell** [comment]
Yes, thanks @moneimne!

**Comment by bagnell** [comment]
Can you update `CHANGES.md` and update any forum threads linked in the issue that this is fixed and will be in the next release?

**Comment by hpinkos** [comment]
@moneimne is this ready?  Make sure you add a comment whenever a pull request is ready for another look so the review gets notified

**Comment by moneimne** [comment]
Yes, this is ready. I haven't updated the forum thread, though. Should I do that?

**Comment by hpinkos** [comment]
This looks great @moneimne, thanks!  When users report bugs on the forum, we like to give them an update when the bug is fixed.  So now that this is merged you can reply to the forum post linked in #5286

**Comment by hpinkos** [comment]
Side note: In your initial comment, say 'Fixes #5286' instead of 'Fix for #5286' so github will automatically close the linked issue when a pull request is merged

**Comment by moneimne** [comment]
Done! Thanks for all the help, @hpinkos!

**Pull request merged**
