### PR TITLE
Fix for Camera lookAtTransform method when tracking entity

### PR DESCRIPTION
**Pull request by jk12559**
Fix for: #5850 
When the camera is tracking an entity, the EntityView object will overwrite the camera's transform property every update, so trying to set the transform and position of the camera with lookAtTransform was giving undesirable results when tracking an entity.  

My fix for this was to transform the offset vector from the reference frame provided to the lookAtTransform method into Earth-fixed and then immediately transform it from Earth-fixed to the reference frame defined by the camera's current transform.  This new offset vector in the camera's reference frame is then set to the camera's position so that it will match with the reference frame defined by the EntityView in the next update.

This now correctly allows the use of lookAtTransform to provide the offset vector in the transform reference frame that's input to the method.  

I also added an optional parameter to lookAtTransform that allows you to specify an up vector for the camera, again referenced to the transform frame.

I then updated the unit tests for lookAtTransform to account for this change.  Some unit tests in other places were now failing because of this change.  I discovered that all of these were using lookAtTransform(Matrix4.IDENTITY) to set the camera's transform back to identity for checking their expectations, but this was not actually setting the transform of the camera because no offset was provided.  I set these to use setView with an endTransform option instead to achieve what was originally intended.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@jk12559, thanks for the pull request! Maintainers, we have a signed CLA from @jk12559, so you can review this at any time.

I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).



__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by ggetz** [comment]
Thanks for the PR @jk12559 ! 

The build is failing due to some linting errors, could you take a look at those?

**Comment by pjcozzi** [comment]
@bagnell can you review this?

**Comment by jk12559** [comment]
lint errors fixed.  This is ready for review.

**Comment by emackey** [comment]
There's some odd behavior here when "letting go" of a trackedEntity via the crossed-out camera icon in the top-left header of the InfoBox.  The camera jumps oddly to a spot nearby, and the previously tracked entity is not always in view anymore.

**Comment by emackey** [comment]
Would be great to have a little demo of saving and restoring a camera view.  I'm thinking something like this, but it doesn't appear to work like this right now:

```
var viewer = new Cesium.Viewer('cesiumContainer');
var camera = viewer.scene.camera;
var savedView = {};

Cesium.CzmlDataSource.load('../../SampleData/simple.czml').then(function(dataSource) {
    viewer.dataSources.add(dataSource);

    // Not working yet
    Sandcastle.addToolbarButton('Save Camera', function() {
        var entity = viewer.trackedEntity;
        savedView.trackedEntityId = entity ? entity.id : undefined;
        savedView.offset = viewer.scene.camera.position.clone();
        savedView.transform = viewer.scene.camera.transform.clone();
    });

    Sandcastle.addToolbarButton('Restore Camera', function() {
        viewer.trackedEntity = savedView.trackedEntityId ?
            dataSource.entities.getById(savedView.trackedEntityId) : undefined;
        camera.lookAtTransform(savedView.transform, savedView.offset);
    });
});
```

**Comment by jk12559** [comment]
@emackey It seems like your example works as long as the time is paused.  If time is progressing it is incorrect because you're using the transform for the objects old position when you hit Save Camera.  I think this entity-tracking stored view is going to be a little more to think through.

As for the view jumping to some other spot when clicking the crossed out camera, what is the desired behavior here?  Should the camera just stop in place relative to the fixed frame or should it return to the home view?

**Comment by jk12559** [comment]
I fixed the camera behavior Ed was seeing when the camera stops tracking an entity.  Ready for review.

**Comment by hpinkos** [comment]
@jk12559 merge in master when you get a chance

**Comment by jk12559** [comment]
@hpinkos merge from master complete

**Comment by hpinkos** [comment]
@emackey what's the status of this PR?

**Comment by emackey** [comment]
We still want @bagnell to review this when time permits.  When Jordan and I first talked about this, I was pretty excited for it, but in early testing of this branch I was seeing more regressions than benefits.  For example, I want to make sure that merging this doesn't cause the initial view of an entity to become time-dependent (which I think I was seeing back then, it's been a while though).  For example, double-clicking the Molniya satellite in `simple.czml` should always produce the same view like in master, it shouldn't be a different view depending on what the current animation time happened to be when the double-click took place.  I would need to re-test to see if this is still a problem here.

Also, it would be great to have a code sample here showing how one saves a view of a tracked entity, and then restores the view at a different time.  My desired outcome for that is, imagine if one set the animation time to the stored view time, tracked the entity, restored that view, and then reset the animation time back to its previous value.  Cesium (master) does the "right thing" now as far as keeping the current view up to date while tracking an entity in time, but, it would be nice to be able to restore a view of a tracked entity without the manual set-time-back-then-set-it-forwards trick.  I wanted this branch to solve that, but it sounds like that's not in scope here.

Still we should make sure that restoring a view to the original time at least works.  @bagnell is there a good way, in master now, to restore a view of a tracked entity, at least to the animation time the view was originally saved?  The description of this branch sounds like that's one of the main issues being addressed by this branch.  Does master offer that now, and does this branch make that any easier/better?

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
cc @shunter

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @jk12559! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @jk12559! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @jk12559! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by emackey** [comment]
There doesn't seem to be enough interest in this for now.  Feel free to bump the issue if the priority changes again.

**Pull request closed without merging**
