### PR TITLE
Remove Autolinker from global scope

### LINKED ISSUE #3497: Autolinker being added to global scope
Below is a modified version of `HelloWorld.html` that compares items in the global scope before and after the combined `Cesium.js` is loaded.  This spits out 4 values

```
"Autolinker"
"Cesium"
"viewer"
"loadJsonp445142"
```

Cesium, viewer, and `loadJsonp445142` are all expected, but `Autolinker` is being required in `KmlDataSource.js` and should not be setting a global.  This is either a bug in Autolinker or something we are doing in correct.  In either case, we should investigate and fix the issue.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <title>Hello World!</title>
    <script>
        function arr_diff(a1, a2) {
            var i, a = [], diff = [];
            for (i = 0; i < a1.length; i++) {
                a[a1[i]] = true;
            }
            for (i = 0; i < a2.length; i++) {
                if (a[a2[i]]) {
                    delete a[a2[i]];
                } else {
                    a[a2[i]] = true;
                }
            }
            for (var k in a) {
                diff.push(k);
            }
            return diff;
        }
        var original = Object.keys(window);
    </script>
    <script src="../Build/Cesium/Cesium.js"></script>
    <style>
        @import url(../Build/Cesium/Widgets/widgets.css);

        html, body, #cesiumContainer {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
    </style>
</head>
<body>
<div id="cesiumContainer"></div>
<script>
    var viewer = new Cesium.Viewer('cesiumContainer');
    console.log(arr_diff(original, Object.keys(window)));
</script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by ajlende**
I'm trying to build Cesium with Webpack and I ran into the same error as #7981.

```
TypeError: Cannot set property 'Autolinker' of undefined
```

I'm guessing it has something to do with the bundled code being run in strict mode, but I didn't dive very deep into why Webpack was treating `this` as `void 0` in the bundle.

Either way, this also happens to resolve #3497, and cleans up the global scope.

Autolinker fixed this in [v0.24.1](https://github.com/gregjacobs/Autolinker.js/commit/e9538d2749fcb41d0aa6ff761d411d4c5fdb8aba#diff-66c5b43b132e359efd6ab0fac6c2c819R12), but the bundled version here is 0.17.1, so to keep it safe, I just updated the UMD header.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @ajlende! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/ajlende/cesium/blob/patch-1/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/patch-1/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by ajlende** [comment]
I signed the Individual CLA and added myself to CONTRIBUTORS.md

**Comment by OmarShehata** [comment]
Thanks @ajlende ! I can confirm we received your CLA. Looks like a pretty straightforward change, hopefully we can get it in in the next release.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ajlende! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks for the PR @ajlende!  Sorry it took so long to get you a review on this.

Instead of modifying the version we have in the repo, can you please update the library to the latest version which you said has a fix for this?  Thanks!

**Comment by mramato** [comment]
@ajlende thanks again for this PR.  Were in the process of migrating Cesium to ES6 modules and Autolinker has been updated to the latest version and fixed as part of that process.  It should go into master and be part of the Nov 1 release.

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @ajlende! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request closed without merging**
