### PR TITLE
Fix error with creating billboards without a globe

### LINKED ISSUE #6109: Add billboard crash with  globe :false option
Add billboard crash without globe. 

var viewer = new Cesium.Viewer('cesiumContainer',{globe:false});
viewer.entities.add({
        position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
        billboard :{
            image : '../images/Cesium_Logo_overlay.png'
        }
    });

### PR DESCRIPTION
**Pull request by ggetz**
Fixes #6109

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@ggetz, thanks for the pull request! Maintainers, we have a signed CLA from @ggetz, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@ggetz can you write a unit test?

**Comment by ggetz** [comment]
@hpinkos Updated. CI didn't run for some reason, but eslint and tests are passing.

**Comment by hpinkos** [comment]
@ggetz did you check if labels and point primitives have the same problem?

**Comment by ggetz** [comment]
@hpinkos No updates need for label or point primitive, but fixed in model.

**Comment by hpinkos** [comment]
Looks great, thanks @ggetz!

**Pull request merged**
