### PR TITLE
Added a missing param to he reference document

### PR DESCRIPTION
**Pull request by s093294**

### CODE REVIEW

**Comment by s093294** [comment]
Hi guys. Do you want PR like these when noticing some missing docs elements?

**Comment by pjcozzi** [comment]
> Do you want PR like these when noticing some missing docs elements?

Yes, please.

I don't think we have a CLA from your or your organization.  Can you please send one in?  See [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).

**Comment by s093294** [comment]
I just emailed the CLA.

**Comment by pjcozzi** [comment]
We received your CLA.

Thanks for the fix!

**Pull request merged**
