### PR TITLE
Fixes #4481

### LINKED ISSUE #4481: Fix typo in Build Guide
@Dylan-Brown

In the [Build Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide) change `to take affect` to `to take effect`.

@sumitshyamsukha and @JudyWeng can help with opening a pull request.

### PR DESCRIPTION
**Pull request by Dylan-Brown**

### CODE REVIEW

**Comment by lilleyse** [comment]
Nice, add yourself to CONTRIBUTORS.md and I'll merge this in.

**Comment by lilleyse** [comment]
Side note, when fixing an issue, add this line:

Fixes #4481

So that the issue can automatically be closed when merged.

**Comment by lilleyse** [comment]
Also use a more descriptive title (even if its just the same as the issue).

**Comment by Dylan-Brown** [comment]
Committed the change to Contributors!

**Comment by lilleyse** [comment]
Resolve the merge conflict in CONTRIBUTORS.md. Also in general you should branch off of master before opening a PR.

**Comment by pjcozzi** [comment]
@Dylan-Brown can you please merge in the `master` branch from the main Cesium repo and fix the conflict.  It is likely a trivial conflict in CONTRIBUTORS.md were another name was added since you last updated the branch.

**Comment by Dylan-Brown** [comment]
The conflict is  indeed trivial, but I can't rebase (ie, fetch upstream and then merge upstream/master) because I committed changes to my forked repo. I'm not sure what to do, as I can't just delete my fork and start over, because that solution is not sustainable for every time I make a pull request and then changes  are made to the original repo.

**Comment by lilleyse** [comment]
I would cherry-pick the commits over to a different branch, pull master so it is up-to-date with the AGI remote, and then rebase/merge should work better.

**Comment by hpinkos** [comment]
:+1:

**Comment by lilleyse** [comment]
Thanks @Dylan-Brown! When a PR is ready for review just leave a quick comment like "Updated" so we get notified.

**Pull request merged**
