### PR TITLE
Rebuilt draco module with support for IE11

### LINKED ISSUE #6404: Use legacy environment enabled build for draco decoder module
CC #6399

There's an error when loading the draco decoder module in IE as the build of the deocder we are using (https://github.com/google/draco#javascript-encoderdecoder) does not support IE as it is a "Legacy environment". We need to use a version built with legacy support.

### PR DESCRIPTION
**Pull request by ggetz**
Fixes #6404
 
Rebuild the draco decoder JS module and passed the compile flag `-s LEGACY_VM_SUPPORT=1` to Emscripten (which includes some polyfills, see https://github.com/kripken/emscripten/issues/6204). I saw no difference in decode time when compared with the "official" draco JS decoder module (and IE11 doesn't support wasm at all). The new module is only 1KB bigger size, so I just replaced the previous version with this legacy-enabled module rather than having a fallback

### CODE REVIEW

**Comment by hpinkos** [comment]
I can confirm this works!  But I'll let @lilleyse take a quick peak and merge

**Comment by ggetz** [comment]
@mramato I have a modified draco `CMakeLists.txt` file. Should I put a branch of my fork of Draco and link to it?

**Comment by lilleyse** [comment]
I can also confirm Draco works in IE and tests pass.

As we predicted, the decode is pretty slow in IE. It shouldn't hold back this PR but it might be worth considering for https://github.com/AnalyticalGraphicsInc/cesium/pull/6555/.

Draco vs. uncompressed:
nyc-draco
nyc

**Comment by ggetz** [comment]
@lilleyse The reason for that is that IE doesn't support WebAssembly at all, therefor we always have to fallback on the JS module which is significantly slower, rebuilt or not.

**Comment by lilleyse** [comment]
Yeah, plus the number of web workers is limited in IE. I'm not too surprised by the results but thought it was worth documenting.

**Comment by lilleyse** [comment]
Thanks @ggetz!

**Comment by OmarShehata** [comment]
> Can we please document somewhere (dev guide?) exactly how to update draco dependencies for Cesium since we can no longer rely on the official non-wasm releases.

Was this ever documented @ggetz ? I don't see anything about it here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md

I'm asking because the WebP decoder WASM will have the same workflow (WASM, with an ASM fallback?) and I curious if the Draco steps were written anywhere as reference when documenting mine.

**Comment by ggetz** [comment]
@OmarShehata It's at https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/DracoModuleManagement

**Pull request merged**
