### PR TITLE
Add credit option to ArcGisMapServerImageryProvider

### PR DESCRIPTION
**Pull request by mircokroon**
I noticed that the [ArcGisMapServerImageryProvider](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ArcGisMapServerImageryProvider.js) doesn't allow for a credit option, possibly because it may be overriden by the metadata request. Since some of the other options may also be overriden (tileWidth, tileHeight) and simply have a sentence pointing that out in the docs, I thought it wouldn't hurt to allow for the credit option also.

I am not too familiar with the codebase so I tried to base it somewhat on the handling of the credit option in [createOpenStreetMapImageryProvider](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/createOpenStreetMapImageryProvider.js).

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @mircokroon! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mircokroon** [comment]
I had already done both the CLA and Contributors entry.

**Comment by pjcozzi** [comment]
Thanks again for the contribution @mircokroon, we received your CLA.  Someone will review this pull request.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mircokroon! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the contribution @mircokroon!

**Pull request merged**
