### PR TITLE
fix : radius should scale as well?

### PR DESCRIPTION
**Pull request by xdontwox**
fix : radius should scale as well?

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for the fix, @xdontwox!  Can you please send in a [CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can review this?

**Comment by xdontwox** [comment]
Sorry, I did not read that.
A CLA e-mail is sent.

**Comment by pjcozzi** [comment]
@twpayne perhaps we can finish this one at the bug bash?

**Comment by hpinkos** [comment]
@pjcozzi maybe we should write up an issue for this and close out this PR instead?  It's not clear to me what the problem is that this is trying to fix.

**Comment by pjcozzi** [comment]
I think we can fix it as part of the bug bash; the scale just needs to be applied to the radius everywhere the radius is used, not just in the one spot changed.

**Comment by hpinkos** [comment]
Thanks for the pull request @xdontwox, but this fix needs a little more work than just updating that one line.
I've opened up #4508 so we know this needs to be addressed.  I'm going to close this PR for now, but if you get a chance to update the code throughout `Model` we would gladly accept the contribution!  Thanks!

**Pull request closed without merging**
