### PR TITLE
 CesiumMath.factorial has issue #7888

### PR DESCRIPTION
**Pull request by rshaikhha**
current version of CesiumMath.factorial function has a bug reported in issue #7888. 
the problem can be fixed by a simple logic correction

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @rshaikhha!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by rshaikhha** [comment]
This request is ready

**Comment by rshaikhha** [comment]
Contributor License Agreement (CLA) set via email rshaikhha@gmail.com

**Comment by hpinkos** [comment]
Thanks @rshaikhha! We got the email, but the person who reviews the CLAs is out of the office. We'll review this PR as soon as we get the okay.

**Comment by rshaikhha** [comment]
@hpinkos Thanks Hannah, any news from CLA?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @rshaikhha! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @rshaikhha! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
This was actually fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/7969. Thanks again for reporting this!

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @rshaikhha! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request closed without merging**
