### PR TITLE
Allow local-running Cesium to load its resources

### LINKED ISSUE #5830: Using Cesium in a local application silently fails to display entities
As mentioned in the forum ( https://groups.google.com/forum/#!topic/cesium-dev/iNuC3h8FQ4U ), I'm attempting to use Cesium in a local application using Chromium with cross origin requests and disk access enabled.  However, accessing Cesium locally causes entities to never display, due to approximateTerrainHeights.json silently failing to load. 

If I change loadWithXhr.js to accept the a zero HTTP status when a URL starts with "file://", then Cesium starts working as expected.  I'd like to pull request this, assuming Cesium will accept it.  Hope we can keep local use alive.

### PR DESCRIPTION
**Pull request by pizza2code**
Fixes #5830

### CODE REVIEW

**Comment by ggetz** [comment]
Hi @pizza2code , thanks for the PR!

So this issue of using the file protocol with Cesium has come up before, see https://github.com/AnalyticalGraphicsInc/cesium/issues/5326 and https://github.com/AnalyticalGraphicsInc/cesium/issues/3935

Instead of this change, we'd reccomend using something like Electron to run your app. See our blog post on getting that set up here: https://cesium.com/blog/2016/04/04/an-introduction-to-cesium-desktop-apps-with-electron/

**Comment by ggetz** [comment]
@hpinkos Can we consider reopening this?
 See https://github.com/AnalyticalGraphicsInc/cesium/issues/5830#issuecomment-329907123.

Sorry for the additional noise.

Also, per that comment, we can skip the `localFile` check and just check for `xhr.status === 0` in the `onload` function.

**Comment by shunter** [comment]
Actually, I think checking for file protocol will still be necessary.  From reading the spec, "0" would appear to be a valid error indication for a network-level error for HTTP requests.

**Comment by ggetz** [comment]
OK, thanks @shunter !

**Comment by mramato** [comment]
@pizza2code we can't merge this until you send in a CLA (as noted above).  Since this is a small change, if you are unable or don't want to fill out a CLA, I can make the change myself in a different PR.  Just let us know either way.  Thanks for the PR either way!

**Comment by pizza2code** [comment]
@mramato Sorry, not sure I'll be able to sign the CLA due to clauses in my employment agreement.  You can go ahead and make the change (you're right, it's pretty small) in another PR.  :)

**Comment by hpinkos** [comment]
Thanks @pizza2code!  I've opened a PR to add the changes here: #5892
Thanks for bringing this up

**Pull request closed without merging**
