### PR TITLE
Call QuadtreePrimitive.tileLoadProgressEvent after rendering frame state

### LINKED ISSUE #3450: Use frameState.afterRender to fire QuadtreePrimitive.tileLoadProgressEvent
In case, for example, someone adds new primitives in the callback.

For example, see https://github.com/AnalyticalGraphicsInc/cesium/blob/7d449906cf65cf06e75d5cde7bf2dd5921bc95dd/Source/Scene/ModelAnimationCollection.js#L387

### PR DESCRIPTION
**Pull request by bampakoa**
Closes #3450. References #5134

### CODE REVIEW

**Comment by bampakoa** [comment]
this is ready

**Comment by pjcozzi** [comment]
Thanks @bampakoa.

@rahwang could you please review and test this?  Replaces https://github.com/AnalyticalGraphicsInc/cesium/pull/5134#issuecomment-289621681.

**Comment by rahwang** [comment]
Thanks @bampakoa ! I tried the branch -- everything looks good to me, @pjcozzi

**Comment by pjcozzi** [comment]
Thanks @bampakoa @rahwang!

**Pull request merged**
