### PR TITLE
Make PinBuilder tolerant of icon retrieval failures, instead of throwing exceptions, which aborts whole GeoJSON loads.

### PR DESCRIPTION
**Pull request by stevage**

### CODE REVIEW

**Comment by mramato** [comment]
Thanks for the contribution.  Am I correct in that we don't have a CLA from you already?  If not, can you send in a Contributor License Agreement (CLA) so we can review and merge this?  See [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md) and let us know if you have any questions.

While I can see what you're going for, I don't think `PinBuilder` always returning a pin is the correct behavior.  I would rather see PinBuilder continue to fail but have GeoJSON handle the failure more gracefully (by using it's default pin instead).  I think this would be a little cleaner and not lead to confusion down the line for people trying to use PinBuilder directly.

Thanks again.

**Comment by stevage** [comment]
CLA sent. I don't have strong enough opinions on the pin thing to want to debate it...

**Comment by pjcozzi** [comment]
Thanks @stevage.  We received your CLA.

**Comment by kring** [comment]
@mramato and @pjcozzi, @stevage works at NICTA so you have a corporate CLA for him already.

**Comment by hpinkos** [comment]
@mramato have your thoughts changed on this? I think this behavior is fine.  
What do you want to do with the PR?

**Comment by pjcozzi** [comment]
@mramato should we close or merge this?

**Comment by mramato** [comment]
Sorry it took so long to get to this, replaced by #4452.  Thanks again.

**Comment by stevage** [comment]
Aw, and I was so close to being a contributor. :)

**Comment by mramato** [comment]
Sorry @stevage, the good news is there's plenty more to do and I'd be happy to look at more pull requests 😄  (I promise to take less than a year this time)

**Pull request closed without merging**
