### PR TITLE
Composite tiles

### PR DESCRIPTION
**Pull request by pjcozzi**
Adds support for accessing the composite features/properties in the Sandcastle example.

Also
* Removes `batchTableResources` from the `CesiumDTileContentProvider` interface and implementations.  `Cesium3DTileBatchTableResources` is now private.
* Adds `hasProperty` and `getFeature to the `CesiumDTileContentProvider` interface and implementations.

More refactoring to come.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@lilleyse wait a few hours on this, I'm going to make some tweaks.

**Comment by pjcozzi** [comment]
Never-mind, my other plan is not going to fly.

**Comment by lilleyse** [comment]
Everything here looks great to me. Merged.

**Comment by lilleyse** [comment]
With all the recent activity we should add some more tests to support get coverage back to 100%. Not needed right now, but just something to do eventually.

**Comment by pjcozzi** [comment]
Yes, I want to add fine-grained dependency-injected tests for each content provider and `Cesium3DTileFeature`.

**Pull request merged**
