### PR TITLE
Updated getStringFromTypedArray and added getMagic

### PR DESCRIPTION
**Pull request by lilleyse**
For #3177 

Updated `getStringFromTypedArray` and added `getMagic` from 3d-tiles.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Can we move `getMagic` to `Core` just like `Core` has `getStringFromTypedArray` and the imagery providers?

**Comment by mramato** [comment]
Is `getMagic` getting the magic number of the file?  If not it's a confusing name.  If it is, then we have code in KmlDataSource that is also looking for a magic number that should use this new function instead.

**Comment by mramato** [comment]
Here's the code I was talking about: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/KmlDataSource.js#L195

**Comment by lilleyse** [comment]
Ok, we may have to make a few changes to `getMagic` for this to work. Right now it gets the first 4 bytes of the buffer without considering endianness. Also `getMagic` returns a string, but the zip magic has some non-letter characters.

**Comment by mramato** [comment]
> Ok, we may have to make a few changes to getMagic for this to work. Right now it gets the first 4 bytes of the buffer without considering endianness. Also getMagic returns a string, but the zip magic has some non-letter characters.

In that case, it might not be worth worrying about it for now, unless the endianess issues are a bug waiting to happen in code that's already using `getMagic`?

**Comment by pjcozzi** [comment]
3D Tiles and glTF are always little endian.  We can rework `getMagic` to work with KML if we really want, but it doesn't need to be part of this PR.

**Comment by mramato** [comment]
Okay, I'm fine with merging this as is then, since `getMagic` is private anyway.

**Comment by lilleyse** [comment]
Moved `getMagic` to `Source/Core`

**Comment by pjcozzi** [comment]
Thanks, looks good.

**Comment by pjcozzi** [comment]
I'll handle the updates to merge this into `3d-tiles`.

**Pull request merged**
