### PR TITLE
glTF material improvements

### PR DESCRIPTION
**Pull request by pjcozzi**
#3410 by @mlimper, now targeted for master.  I also added tweaks e0c2716d227325aaca9d51a263059d9cb727b9a0 and f539f4801a9cd15393ae7bb61b8c58f86eb2cb41.

@tfili can you finish this for the 1.18 release?

* [x] Update converter to output `"binary_glTF"` buffer
* [x] Update converter to output latest KHR_common_materials
* [x] Update sample models
   * [x] in Cesium
   * [ ] in the glTF repo
* [x] Fix `Scene/Model loads a glTF with KHR_materials_common using an ambient light` test. @mlimper did you [run the tests](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/TestingGuide/README.md)?

@lilleyse do you need to update OBJ2GLTF for the fix to KHR_materials_common?

### CODE REVIEW

**Comment by tfili** [comment]
Should be doable from my end.

**Comment by pjcozzi** [comment]
@tfili any update here?

**Comment by tfili** [comment]
@pjcozzi Just have to update the models.

**Comment by pjcozzi** [comment]
Changes from @mlimper and @tfili.

**Pull request merged**
