### PR TITLE
Make defined check for null as well

### PR DESCRIPTION
**Pull request by mramato**
Having `definedNotNull` and `defined` seems silly in hindsight and has been the source of bugs when someone uses `defined` when `definedNotNull` is needed.  This simply makes `defined` check for null as well and deprecated `definedNotNull`.

There were only two objects in the code that relied on `defined` returning true for `null` `GeoJsonDataSource` and `Fullscreen`.  Both only required minimal changes and they were for edge cases.

Also ran `sortRequires`

I still want to run some performance numbers against the built Cesium to see if this has any affect (but I doubt it will).

### CODE REVIEW

**Comment by gberaudo** [comment]
Have you considered deprecating `defined` and keep `definedNotNull` instead?

**Comment by mramato** [comment]
> Have you considered deprecating defined and keep definedNotNull instead?

Talking with some of the other devs offline, most people prefer the shorter `defined` and feel that it makes reading the code easier.  `definedNotNull` is both wordy and longer to type.

**Comment by hpinkos** [comment]
@mramato looks great! 
My only comment is that there are a few places in the code that do `if (whatever !== null) { ...`
Do you think those should be updated to use `defined` instead?

**Comment by pjcozzi** [comment]
Please profile as we discussed offline.

**Comment by mramato** [comment]
> Please profile as we discussed offline.

Yes, I said tha tin my PR description, I just didn't get to it yet.

**Comment by mramato** [comment]
Profiled the combined file with pragmas removed and a CZML file loaded and animating, performance was identical in both cases.  So this is ready.

**Comment by pjcozzi** [comment]
Did you check the profiler or just the frame rate?  In the profiler, how much did `defined` show up before and after?

**Comment by pjcozzi** [comment]
Also, don't test with the CZML example; it has bottlenecks elsewhere that could hide if there is an issue here.  Test with a full-screen horizon terrain view in the steady state (no new tiles being loaded).  That is worse-case-ish.  I expect the different will be insignificant, but it will be good to know since we've put a lot of effort into not burning CPU cycles in the low-level code.

**Comment by mramato** [comment]
Of course I checked the profiler.  The results were negligible in both cases and defined doesn't always even show up.

I feel CZML is a better test case here because anything time-dynamic using data sources ends up calling defined a lot in the visualizer and those checks can't be inside a pragma so they don't get taken out at build time.  I also think it's more of a real world test case since most users use the Entity API.

That being said,  I ran the case that you asked for and the results were unchanged.  `defined` only shows up in the profile sometimes and when it does it was  ~0.01% to ~0.03% of the overall time.

**Comment by pjcozzi** [comment]
Ah, excellent!

**Comment by mramato** [comment]
Merged in master, this is ready unless anyone has any additional feedback.

**Comment by pjcozzi** [comment]
@hpinkos please merge when you are happy with this.

**Comment by hpinkos** [comment]
Looks good. Thanks @mramato!

**Pull request merged**
