### PR TITLE
Fix getting stuck when zooming

### PR DESCRIPTION
**Pull request by nikakhov**

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @nikakhov.  Can you send us a Contributor Licence Agreement (CLA) so we can review this?  You can find instructions here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by pjcozzi** [comment]
@nikakhov were you able to send in a CLA?  Perhaps I missed it?

**Comment by nikakhov** [comment]
Let me share a few thoughts.  Perhaps we are not yet at that point where this code should be merged.  In the issue discussion, I mentioned how this fix is incomplete and needs to be supplemented with additional changes, such as setting minimum and maximum zoom limits.

**Comment by pjcozzi** [comment]
@nikakhov please open a new pull request when you think this is ready, thanks again for supporting Cesium.

**Pull request closed without merging**
