### PR TITLE
Issue no #3372

### PR DESCRIPTION
**Pull request by AmayAgrawal**
Made 3 changes 
1. Now getting started links to new url
2. Forums link to cesium forums instead of google groups
3. Added a new download link which links directly to cesium downloads page

### CODE REVIEW

**Comment by AmayAgrawal** [comment]
Sir Can you please look over the following changes and suggest me what can I add for npm??

**Comment by pjcozzi** [comment]
@AmayAgrawal can you give me commit access to your Cesium fork so I can make some edits to this?

**Comment by AmayAgrawal** [comment]
Sir I have done that

**Comment by pjcozzi** [comment]
Thanks @AmayAgrawal!

**Pull request merged**
