### PR TITLE
Fixed issue #3342

### PR DESCRIPTION
**Pull request by Decatek**
All @namespace that was followed by @alias has been removed and @alias has been replaced with @exports.

There where 3 more @namespace in the project, they have been kept as they are.

### CODE REVIEW

**Comment by pjcozzi** [comment]
For #3342

**Comment by pjcozzi** [comment]
Thanks @Decatek, this looks good.

> There where 3 more @namespace in the project, they have been kept as they are.

Which ones?  And why did they need to stay?

**Comment by pjcozzi** [comment]
For many types, like `CesiumTerrainProvider`, the generated doc is the same.  For some types, like `BingMapsApi`, the doc is slightly different since the default constructor is now shown.

**Before**:

image

**After**:

image

This is OK with me, perhaps even better (definitely better for writing the doc).

**Comment by Decatek** [comment]
Hey Patrick,
These are the namespaces that I didn't change, the reason is because they
don't follow the pattern that you described in the issue itself (they are
not followed by an @alias):

../cesium-fork/ThirdParty/codemirror-4.6/demo/lint.html:
   98: @namespace "http://www.w3.org/1999/xhtml";
   99: @namespace svg "http://www.w3.org/2000/svg";

../cesium-fork/ThirdParty/codemirror-4.6/mode/css/less.html:
   45: @namespace foo url(http://www.example.com);

I also just noticed that /Source/Core/EasingFunction.js:14 has a namespace
that DOES follow the pattern you described and it has been already fixed
and pushed to my fork.
Let me know if I need to change the aforementioned namespaces as well (and
please tell me how you would like them to be, since just removing them will
remove the entry from the docs completely, I guess).
That was my first Pull Request, so I don't know if and how I can update it
with the new commits I will be pushing to my fork, so any heads up on how I
should update those new changed are well appreciated!

**Comment by Decatek** [comment]
The pull request get's automatically updated, that's awesome!

On 27 December 2015 at 20:14, Giacomo Camporini <giacomo.camporini@gmail.com

**Comment by pjcozzi** [comment]
Thanks again for this contribution, @Decatek!

**Pull request merged**
