### PR TITLE
Fix ellipse triangulation

### LINKED ISSUE #3078: EllipseGeometryLibrary's computeEllipsePositions misses critical points
Because the logic for computing the positions about the ellipse works by computing the "north" half of the ellipse (by computing the "west" half and then its reflection) and then its reflection, with low granularities, say a granularity of `PI_OVER_TWO` (to retrieve the four critical points, 0, pi/2, pi, 3pi/4), all of the resolution is focused around the west/east points, and none about the north/south points.  (In fact, with `PI_OVER_TWO`, the two east/west points are duplicated in the calculation).

You can see this visually in the screenshot from @bagnell's work here re: granularity:
https://github.com/AnalyticalGraphicsInc/cesium/pull/2283#issuecomment-64254710

I'm wondering if simply adding the calculation for the critical points would be enough to resolve this?  Perhaps changing the math to mirror about the 45, 135, 225 and 315 degree angles (rather than the current 0/90/180/270) would help in conjunction w/ adding the critical points.  This seems like it would always ensure an accurate representation of the ellipse from the computation.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #3078

This also fixes a crash if you tried to create an ellipse with `VertexFormat.ALL`.  The tangents and binormals weren't normalized.

Before: 
image

After: 
image

### CODE REVIEW

**Comment by hpinkos** [comment]
normals/tangents/binormals and texture coordiantes should be correct:

image

image

**Comment by bagnell** [comment]
Try this example code that doesn't generate that many triangles:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;

scene.primitives.add(new Cesium.Primitive({
    geometryInstances : new Cesium.GeometryInstance({
        geometry : Cesium.GeometryPipeline.toWireframe(Cesium.EllipseGeometry.createGeometry(new Cesium.EllipseGeometry({
            center : Cesium.Cartesian3.fromDegrees(-100.0, 40.0),
            semiMinorAxis : 300000.0,
            semiMajorAxis : 400000.0,
            vertexFormat : Cesium.PerInstanceColorAppearance.VERTEX_FORMAT,
            granularity : Cesium.Math.PI / 32
        }))),
        attributes: {
            color: Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.RED)
        }
    }),
    appearance : new Cesium.PerInstanceColorAppearance({
        translucent : false,
        closed : true
    }),
    asynchronous : false
}));
```
image

It looks like there are 22 triangles and 16 vertices. If you put a breakpoint in `EllipseGeometry.createGeometry`, there are 24 triangles and 18 vertices in the mesh.

**Comment by hpinkos** [comment]
@bagnell that's because there are duplicate positions at the points on the left and right end.  It was that way before I changed the code.  I'll see if I can fix it though.

**Comment by hpinkos** [comment]
@bagnell ready

**Comment by pjcozzi** [comment]
@bagnell any update here?

**Comment by bagnell** [comment]
Looks good. Thanks @hpinkos!

**Pull request merged**
