### PR TITLE
Use minified Cesium in Node.js unless NODE_ENV=development

### PR DESCRIPTION
**Pull request by mramato**
We know that removing debug code in Cesium can provide a substantial speed improvement, but previously the Node.js version would always use separate modules.  This change allows Node.js to load the combined/minified version by default, for improved performance, and only loads the old
separate modules if NODE_ENV=development (which is the standard mechanism for enabling extra debugging checks in most node packages.

@shunter I was fumbling around with getting the minified version to load at all in node, my changes in `Source/main.js` were needed to get it to happen.  As far as I can tell, this has no impact on browser-based usage; but can you take a look and let me know if there's a better approach here.

Partially stems from discussion in #7508, but this is something we've tried in the past and I finally bit the bullet to figure it out.

CC @shehzan10

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@shunter any comments here?  If now, should be ready to merge.

**Comment by mramato** [comment]
Is anyone else comfortable reviewing this?

CC @ggetz @hpinkos

**Comment by mramato** [comment]
image

**Comment by hpinkos** [comment]
Looks fine to me.  Thanks @mramato

**Pull request merged**
