### PR TITLE
Fix for binary glTFs storing CRN and KTX textures

### PR DESCRIPTION
**Pull request by lilleyse**
Bug report and fix from the forum, with some modifications: https://groups.google.com/forum/#!topic/cesium-dev/02M8ho6hONo.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@lilleyse thanks for the pull request!

I noticed that a file in `ThirdParty/` or `Source/ThirdParty/` has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.  Once you do, please confirm by commenting on this pull request.

__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by pjcozzi** [comment]
Does this need new unit tests?

**Comment by lilleyse** [comment]
Improved the tests a bit. They were able to pass before because the default texture was being used.

**Comment by pjcozzi** [comment]
Are these CI failures related?
```
  Core/sampleTerrain
    ✗ queries heights from Small Terrain
	Expected undefined to be greater than 5000.
	    at Specs/Core/sampleTerrainSpec.js:42:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
	Expected undefined to be less than 10000.
	    at Specs/Core/sampleTerrainSpec.js:43:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
	Expected undefined to be greater than 5000.
	    at Specs/Core/sampleTerrainSpec.js:44:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
	Expected undefined to be less than 10000.
	    at Specs/Core/sampleTerrainSpec.js:45:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
```
https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/266571774?utm_source=github_status&utm_medium=notification

**Comment by lilleyse** [comment]
It also fails on master locally, so not related.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:
- https://groups.google.com/forum/#!topic/cesium-dev/02M8ho6hONo

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/5753 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium!
> Or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium

__I am a bot who helps development running smoothly!__ Have a great day.

**Pull request merged**
