### PR TITLE
Fix polyline clipping against the near plane.

### PR DESCRIPTION
**Pull request by bagnell**
Fixes the issue from this comment: https://github.com/AnalyticalGraphicsInc/cesium/issues/6741#issuecomment-408198164

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @bagnell!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-polyline-clipping/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
polyline

@bagnell This seems to fix the camera angle posted in that issue, but I'm still seeing some weirdness from different angles.

**Comment by bagnell** [comment]
Thanks @hpinkos. It's fixed. This seems like it should have been a bug for a while, but I couldn't find any issue for it.

**Comment by hpinkos** [comment]
@bagnell looks fine in chrome now.  It's doing something weird in IE though.

image

That doesn't happen in master.  It happens in this branch with `logarithmicDepthBuffer` set to true or false.

```js
var viewer = new Cesium.Viewer('cesiumContainer');
var scene = viewer.scene;
scene.logarithmicDepthBuffer = false;

var blueCartographic = new Cesium.Cartographic(-1.3196863177294136, 0.6988508714746624, 30.0);
var redCartographic = new Cesium.Cartographic(-1.319681841889412, 0.6989153500784591, 30.0);

var arrowPositions = [
    Cesium.Cartographic.toCartesian(blueCartographic),
    Cesium.Cartographic.toCartesian(redCartographic)
];

var line = viewer.entities.add({
    polyline : {
        positions : arrowPositions,
        width : 50,
        followSurface : false,
        material : new Cesium.PolylineArrowMaterialProperty(Cesium.Color.CYAN)
    }
});

viewer.zoomTo(viewer.entities);
```

**Comment by bagnell** [comment]
@hpinkos this is ready for another look.

**Comment by hpinkos** [comment]
Looks great, thanks @bagnell!

**Pull request merged**
