### PR TITLE
Change JSDoc to correctly document Cesium.Math.*

### LINKED ISSUE #6233: CesiumMath vs Math naming ambiguity
It's not clear that the `CesiumMath` class is included in the namespace as `Cesium.Math`. This is also inconsistent with other classes that have the Cesium prefix, like `Cesium3DTileset`. If this is not something we want to change in the API, this should be made clear in the documentation.

Relevant forum thread: https://groups.google.com/forum/#!topic/cesium-dev/icpMxc_bea8

### PR DESCRIPTION
**Pull request by emackey**
Fixes #6233.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@emackey, thanks for the pull request! Maintainers, we have a signed CLA from @emackey, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks @emackey!  I would make a comment in `CHANGES.md` since this was a doc error reported by our users

**Comment by emackey** [comment]
Done.

**Comment by hpinkos** [comment]
Thanks @emackey!

**Pull request merged**
