### PR TITLE
Entity ease of use

### PR DESCRIPTION
**Pull request by mramato**
This isn't ready yet, but I'm opening it up for early review.

The goal here is to further enhance the `DataSource` layer so that it can be easier to use for beginners and also become the primary high-level API for Cesium.  This would eliminate the need for the "mid-level" api we've considered adding, such as the current `Polygon` primitive (which would eventually be made obsolete). While the overall goal is still a long way off, this PR gets it a lot closer.

This change looks bigger/scarier than it is, but it mainly does 4 things:
1. For simple values, you no longer need to create an instance of `ConstantProperty`, `ConstantPositionProperty`, `ColorMaterialProperty`, or `ImageMaterialProperty`.  We create a new property on the fly if needed, mirroring the behavior of C# `implicit` types. `createPropertyDescriptor` has been deleted and replaced with several `PropertyHelper` functions to achieve this goal.
2. All of the constructor functions for `Entity` and the various `xxxGraphics` objects now take an `options` argument which mirrors their public properties.
3. A new `CustomDataSource` object, which makes easy to add Entities to a viewer instances in very little code.  This is in lieu of simply having an `entities` property on `Viewer`.  It fits a little better in the existing architecture.  `viewer.entities` isn't off the table, but I think it would require more rework for not a lot of benefit. I've also thought about renaming the existing `DataSource` interface to something else (`DataSourceInterface`?) and renaming `CustomDatasource` to `DataSource`.  This would be a non-breaking change that only affects documentation.
4. `EntityCollection.add` now takes either an `Entity` instance or an options object. The options themselves can either be `xxxGraphics` instances or options objects themselves.

Here's a complete Sandcastle example that puts the above changes to use.
```
var viewer = new Cesium.Viewer('cesiumContainer');

var entity = viewer.entities.add({
    name: 'example',
    description : '<b>HTML description!</b>',
    position : Cesium.Cartesian3.fromDegrees(3, -4, 50000),

    label : {
        text : 'A label!',
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM
    },

    point : {
        pixelSize : 15,
        color : Cesium.Color.RED
    },

    polygon : {
        material : Cesium.Color.BLUE,
        extrudedHeight : 50000,
        outline: true,
        outlineColor : Cesium.Color.BLACK,
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-2, -2, 3, -4, 2, -2, 2, 2, -2, 2])
    }
});

viewer.zoomTo(entity);
```

__TODO__
* [x] Update documentation
* [x] Update CHANGES
* [x] Finish tests
* [x] Fix circular dependency in `PropertyHelper`
* [x] Add `Checkerboard` material property.
* [x] Port relevant Sandcastle examples 
* [x] Add `PolylineVolumeGeometry` support to entity
* [x] Rotation broken when tracking in 2D.
* [x] Model.boundingSphere is wrong with Model.scale is set.[#2444]

__TODO post-merge (will write issues when ready)__
* Detect and automatically use `EllipsoidSurfaceAppearance`
* Port Materials Sandcastle example and add entity features needed to do so.
* Geometry Showcase: Support for per-segment or per-vertex polyline color.
* Billboards/Labels: Define entity position in another reference frame.
* Write blog post/tutorial for 1.6 release.
* Update all tutorials (especially G&A) to distinguish between high-level and low-level functionality.
* `BoundingSphere.fromBoundingSpheres` does not always produce a good sphere for view.

### CODE REVIEW

**Comment by mramato** [comment]
@pjcozzi as you requested, `viewer.entities` has been added and is ready for use; removing the need for users to create a DataSource instance themselves.  I updated my original description with the latest example code.

**Comment by pjcozzi** [comment]
Beautiful.

**Comment by mramato** [comment]
Also fixes #2403

**Comment by mramato** [comment]
Unless anyone has any other comments, this is ready to be merged up to master.

**Comment by mramato** [comment]
@kring and @chris-cooper, since I know you were interested in it before, this change also introduces a dev-only Sandcastle folder of examples that get filtered automatically in the release.  Just be sure it has the `Development` label and is in the development subfolder of the gallery.

**Comment by pjcozzi** [comment]
No need to hold this up, but coverage for several classes is pretty weak:

image

**Comment by mramato** [comment]
I'm pretty sure coverage is the same (if not a little better) than master.  I agree it needs to be improved, but this branch isn't the cause.  Either way, I'll add improved coverage to the roadmap issue.

**Pull request merged**
