### PR TITLE
Added support for dimensions in WMTS

### PR DESCRIPTION
**Pull request by tfili**
The same as #5542 but without the `SingleTileImageryProvider` stuff.

CC @bagnell

### CODE REVIEW

**Comment by pjcozzi** [comment]
Do we want this for the 1.35 release?  If so, please merge by noon on Wednesday.

**Comment by tfili** [comment]
It's been ready since last week, unless there is more changes people suggest.

**Comment by pjcozzi** [comment]
OK, let's ship it!

**Comment by kaktus40** [comment]
Hello,
is there a prevision for support of dimensions in WMS. If help needed, I can work on it (previous help on this subject [here](https://github.com/AnalyticalGraphicsInc/cesium/compare/master...kaktus40:OGCHelper#diff-4d2d8ba8d16dfa08df4f17d1e3942fe5R20))

**Comment by tfili** [comment]
@kaktus40 There isn't a current plan to work on extending WMS. If you'd be interested at working on it, that would be great. I envision it being very similar to WMTS support and mostly relying on the `TimeDynamicImagery` class. The only difference would probably be how the URL is built and what data is stored in the time intervals.

**Pull request merged**
