### PR TITLE
Support html and css in Github Gists

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/4125

### CODE REVIEW

**Comment by emackey** [comment]
Does this break compatibility with old gists?

**Comment by lilleyse** [comment]
Oh good point, it does. I'll fix that.

**Comment by lilleyse** [comment]
Updated

**Comment by emackey** [comment]
I still think it's unfortunate that Sandcastle treats gists as proprietary data storage, rather than saving a working example to the gist.  I think Sandcastle should save to the gist almost exactly what it offers for download, with the exception that (a) the references to Cesium should be via CDN rather than relative links, and (b) the JS file could be broken out to a separate file, as it is on this branch, so long as the HTML file references the JS file.  Done correctly, we could easily enable [Bl.ocks.org URLs](http://bl.ocks.org/-/about) to display working Sandcastle demos, outside of Sandcastle.

That said, if the team wants to merge this as a quick fix for lack of HTML save on gists, I'm not opposed.

**Comment by pjcozzi** [comment]
I don't know the details here, but if this is too hacky, I would rather wait for a solid implementation since this isn't widely requests (albeit useful).

**Comment by lilleyse** [comment]
The change here is just mirroring the existing system, I think it's ok to go in now until we restructure things.

**Pull request merged**
