### PR TITLE
base polygon geometry rectangle IDL handling on Rectangle.fromCartesianArray

### PR DESCRIPTION
**Pull request by likangning93**
@shehzan10 noticed that geodetic polygons had weird rectangles sometimes when crossing the PM.

[Here in master](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/Sandcastle/index.html#c=jVNdb5swFP0rKC8FKXNsjAGnabQqnbpI+6i2aNI09uAQJ7UKdmQMbTblv89AaEiWh94HZN97z7kfx1RMO5Xgz1w7N47kz86MF6LMwY/G516lzXWmpGFCcn3lXScykZVFbZWQprCoX4l0rB2AM6aNPTGJwVqr/Btb2XPhvoMAwgBC6gc0ItSPfB+SoQMBpgGOoxhjQuKY+tQbvp0OhZhgCkMYIxQFQUMXxwgGQUAoxMhHwdvoajYCY9se8jEMSej70YEN0hhiEiIa0jB6O1sQIYriiIYhhhhjGBxmJTGM7cTEfhDxEvm73WezbVCkXHKw0aqUqwctcmFExQvAViu3J839adz92/a04SrnRu/msjBMWt2ccV/Q+7NwB+tDTxEPKtttlOyAfUBt2zb8UXDNdPq4u4R9Dbrta/GOFPtul7UxY7RYlnaZY+esTKoypcevG69v56PcduhGhSalv6/WgQCsJTh+iNfvpj3urWvveX1NUpbbGUCm1NOtcS8Lf8c3mvNG+KHj+5Z62F/GMds9NuDD2gBsql2qtdD2La2Vzruin5kd8yUA87sPXxbzxU/vejAcTAqzy/i0bf+9yLdKG6fUmQvAyPB8mzFberQs0yduQFoUdbXJqANNVqJyxOomGZz958nASTNWFDayLrPsu/jDk8F0MrL5J7BM2TcvN18rrjO2q1Me0fRT6wQATEb2+j/KKJUtme4x/gM)

This PR updates the IDL handling for geodetic polygons to more closely match what `Rectangle.fromCartesianArray` does, which seems to be correct.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @likangning93!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fixPolygonRectangleIdl/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by likangning93** [comment]
Fixes a bug introduced in this release, so no CHANGES.md update.

**Comment by hpinkos** [comment]
@likangning93 should there be a unit test for this?

**Comment by likangning93** [comment]
There's an IDL test case already, the corner case @shehzan10 found was a false-positive for IDL cross. I can add the cases from `RectangleSpec` to make sure coverage is similar.

**Comment by ggetz** [comment]
Thanks @likangning93 this fixes the issue. We can get it in if you fix up those tests soon.

**Comment by likangning93** [comment]
> There's an IDL test case already

Looks like the previous case was also only for rhumb, whoops.

**Comment by likangning93** [comment]
Okay looks like eslint 5.13.0 is breaking things everywhere: https://github.com/eslint/eslint/issues, holding off on this until next release...

**Comment by likangning93** [comment]
@ggetz @hpinkos updated!

**Comment by hpinkos** [comment]
Looks great, thanks @likangning93!

**Pull request merged**
