### PR TITLE
Fixed tile triangle picking

### PR DESCRIPTION
**Pull request by IanLilleyT**
The old tile picking code returned the first occurring triangle intersection, but it should be finding the _closest_ triangle intersection. This PR fixes that.

[Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=hVTRbts4EPwV1i+WAYWWLEeSL07Q1kkR49K7wDauKGDgwEgbmyhFCiTlxFfk37uUrFhO0StfJC1nZ5a7Q+2YJjsOT6DJJZHwRGZgeFXQf+qY18/qz5mSlnEJuu+T72tJcFnQGkP3Wu14jtl/tJmZBmbhi9IiXzUYb+A3OWbLcvVkEGt1BWv5MrhYy7UcDj/k+SGdzKUpIbNKr2VTF4VnCzL3DvRNsPl4xX7mz1w2ZPyReO8OmSYDCXTLN9vrvWQFzxZMbmBZlaXSFvJBe5YnLrEuygRo6/VXW27Ig8ZC8Vi5AkOkssQ0WcSxkbyhI9rx0b5TfnHiJ7oZK0AzasC6ZnoHrRyM5ZJZriT2odPxGcOaDGcy8s7CSTgZTxJ6HgVhGkyi0Cdn4wTf4pimqXsmycgnUXKOrykNgjSZnMdRNCZtq5XmgDP7WeYWWM7l5p7bbLtQQnghHcXn4TiKk1ESjdIkHaNY4IJRHE7SOBzFURikPglQJwrjUYy4OEhHiAxbORzQCpthHpUujlb4zKzmz2M6v775azVffX2d+P/OB43o7FEDl0zmGTNWAGV5vlKbjYCPlbVKev3b6wXa0UF98ljJzJ3Vy7aQfeuM9ndKB/zFsTS8EFtUFW9vxBKNDXJZsgxudtjb2wbkvZk5EhjHdOBw45/LsrIfmvpeCy3UDgqkOVaKwjUJynY5L47bjaNwv2uwuuoWUajKwL0yvB78JWlVaHmIddg027sGNC7dgL3n2bcF23snHIMT+hIhHfamjI1QD0DdloeUfhPt5B1usbSYBsbNsb0LbrWFoWu67P4RAULw0iieI6ST6JZGL/NfXqMwQMv6pPsY+KcEBf6qNGfi6NmZEkrTxc31EfjSvNYGefF/5YfVvgR6d/Np9e/sbj7704F7fm9q7F7AVcPwnhf1P6TSwqN0aKEoBRZghg8VmtDSzNTWmQ7bpGnOd4Tnl+vem//wukcywYzBncdKiCX/D9a9q+kQ8SdpQtW3/e8daMH2DrINr+6aIKV0OsTPn7OsUuKB6Q7jDw)

Click at arrow:
Screen Shot 2019-11-13 at 3 51 51 PM
Old behavior:
Screen Shot 2019-11-13 at 3 51 13 PM
New behavior:
Screen Shot 2019-11-13 at 3 51 40 PM

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/tilePickFix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
The code looks good. Can you add an entry to `CHANGES.md` and add a test. For the test maybe model it after https://github.com/AnalyticalGraphicsInc/cesium/blob/7dd9bbb45dc2475eed6316124ee24034a088a29f/Specs/Scene/GlobeSurfaceTileSpec.js#L286

**Comment by IanLilleyT** [comment]
@lilleyse ready for review

**Comment by lilleyse** [comment]
I did some performance testing to make sure this change didn't introduce too much slowness. Not the most scientific test, I just clicked around a bunch of times and averaged the result. Both tests were on built versions of Cesium.

**This branch** [Sandcastle](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/tilePickFix/Build/Apps/Sandcastle/index.html#c=hVXdbupGEH6VFTcxElnbmNgmIVGPOLQHnaSNgnWqqlTVxp7A6phda3cNoVXu+mZ9sY7/wEBofGPv/Hwz8+3MeM0UgTTlmZY8eVRyzRNQ5JYI2JAxaJ6v6KRRR6AU46Kxsro3czEXa0RYq2gJv0qVnoH49tTojzH+nguCT65Sck0ulsZk17a92WzoWl2aJWwKHxrLld0624anoF3qUMcOPPuiV2HEChJuCpg6CEmYYSSWuTKgt+RbRB7+/efrxVy87TNnKv6J66OsDpP/hCbTWYQxk0kKa2a4FOfLqKvQWAY01l5CMc6C67KS6tNWoI2tQa15DNouydnBe5/tOgJ+TVdsATM0BHWYe1zm16YVE6+TRjKYOaC8fV0cNidXVMqsiwp0LIVBH4zYI3Vt5oij63fi79Mr0Si8GhCJVYeohNVhKnQGsZHqgb9ysU9NxyAAM6sByuNNXS5bgWKoK4W0Ota6RSqfYacqT7Vm19yoLeV0JymDvuQiLignesNNvGzIOqq227CgwORKkMbL2imKp07anHTTkeSmcnnD91tTuMwKPI3Gv+8Ify27uSKMlDyTOr+m59EDuywu7A7zP72bLgZrXWaFvR/MDxFPZ/xdxGpaPkR7d+7eBdytnw8xT/ZYgfdHecszJpKYaZMCZUkSSZk+M/UAIrdq3g/att1gVIMpZqMZ8QTHlotySjGB1gCNWbFmOBOedekO3eFgGNArz3FDZ+i5PXI5CPDL92kYFu8g6PeIF1zhZ0gdJwyGV77nDUi3KVJxwBE8DfMFWMLF4rEo/EmmqeXSvn/lDjw/6AdePwzCAQZzCqHnu8PQd/u+5zphj+C6dDzX7/to5zthHy3dJhxOaaSY0C9SrTBeHeuBGcVfB3T6efJzNI1+O9g+S6Q0Pd4iM9w7IGYZi2GyxgK+VEbWEbEIUDJeYxQcT0WWm0/VUO2mayXXsEKY3ZT9z4po1OfWxN5iJXMNj1Lzkt1b0kShWS1roSm2RYu6FRZgHnn8/YltrQOM7gH8MyCLRYIZqIJPJmKgQm7KBdwYZYjTSqG1t2ihsjBur5K2vdiLKRk/hxxjJ0vs8VQurMr2sk6nsMDZOnNN0TYDej/5MfpzfD8dfy2MO73OSJttCncV9A98lUllil+cRaltYJWl+IfR9nMefwdDY13e6MhunEYJXxOe3M47R7+UeYfEKdMaNS95ms74XzDv3I1stD9wS2XZ6b/gfy9l28Jk6d7dV0JK6cjG46mXqWa7hfgf)
```
10.650000000168802
2.1549999983108137
1.6600000017206185
1.3450000005832408
3.1449999987671617
6.38500000059139
3.280000000813743
13.504999998986023
14.585000000806758
7.570000001578592
3.5449999995762482
2.639999998791609
2.7300000001559965
23.05500000147731
8.679999999003485
3.1449999987671617
2.40000000121654
3.3000000003085006
21.26499999940279
9.569999998348067

Average: 7.2304999999687
```

**Master** [Sandcastle](https://sandcastle.cesium.com/#c=hVXdbupGEH6VFTcxElnbmNgmIVGPOLQHnaSNgnWqqlTVxp7A6phda3cNoVXu+mZ9sY7/wEBofGPv/Hwz8+3MeM0UgTTlmZY8eVRyzRNQ5JYI2JAxaJ6v6KRRR6AU46Kxsro3czEXa0RYq2gJv0qVnoH49tTojzH+nguCT65Sck0ulsZk17a92WzoWl2aJWwKHxrLld0624anoF3qUMcOPPuiV2HEChJuCpg6CEmYYSSWuTKgt+RbRB7+/efrxVy87TNnKv6J66OsDpP/hCbTWYQxk0kKa2a4FOfLqKvQWAY01l5CMc6C67KS6tNWoI2tQa15DNouydnBe5/tOgJ+TVdsATM0BHWYe1zm16YVE6+TRjKYOaC8fV0cNidXVMqsiwp0LIVBH4zYI3Vt5oij63fi79Mr0Si8GhCJVYeohNVhKnQGsZHqgb9ysU9NxyAAM6sByuNNXS5bgWKoK4W0Ota6RSqfYacqT7Vm19yoLeV0JymDvuQiLignesNNvGzIOqq227CgwORKkMbL2imKp07anHTTkeSmcnnD91tTuMwKPI3Gv+8Ify27uSKMlDyTOr+m59EDuywu7A7zP72bLgZrXWaFvR/MDxFPZ/xdxGpaPkR7d+7eBdytnw8xT/ZYgfdHecszJpKYaZMCZUkSSZk+M/UAIrdq3g/att1gVIMpZqMZ8QTHlotySjGB1gCNWbFmOBOedekO3eFgGNArz3FDZ+i5PXI5CPDL92kYFu8g6PeIF1zhZ0gdJwyGV77nDUi3KVJxwBE8DfMFWMLF4rEo/EmmqeXSvn/lDjw/6AdePwzCAQZzCqHnu8PQd/u+5zphj+C6dDzX7/to5zthHy3dJhxOaaSY0C9SrTBeHeuBGcVfB3T6efJzNI1+O9g+S6Q0Pd4iM9w7IGYZi2GyxgK+VEbWEbEIUDJeYxQcT0WWm0/VUO2mayXXsEKY3ZT9z4po1OfWxN5iJXMNj1Lzkt1b0kShWS1roSm2RYu6FRZgHnn8/YltrQOM7gH8MyCLRYIZqIJPJmKgQm7KBdwYZYjTSqG1t2ihsjBur5K2vdiLKRk/hxxjJ0vs8VQurMr2sk6nsMDZOnNN0TYDej/5MfpzfD8dfy2MO73OSJttCncV9A98lUllil+cRaltYJWl+IfR9nMefwdDY13e6MhunEYJXxOe3M47R7+UeYfEKdMaNS95ms74XzDv3I1stD9wS2XZ6b/gfy9l28Jk6d7dV0JK6cjG46mXqWa7hfgf)
```
5.420000001322478
12.865000000601867
10.935000002064044
7.324999998672865
1.524999999674037
1.5050000001792796
1.069999998435378
5.430000001069857
11.41500000085216
6.965000000491273
2.8450000027078204
15.204999999696156
12.47999999759486
14.244999998481944
12.930000000778819
3.3149999981105793
4.354999997303821
2.870000000257278
0.9299999983340967
1.4300000002549496

Average: 6.7529999998442
```

So a bit worse as expected, about 1 ms on average for Cesium World Terrain, but it's also accurate now. @IanLilleyT is going to open a separate issue for general picking slowness, especially with detailed terrain like `ArcGISTiledElevationTerrainProvider`.

**Pull request merged**
