### PR TITLE
 Fix sandcastle development links in reference documentation #3020 

### PR DESCRIPTION
**Pull request by AmayAgrawal**
I don't know why but when I am pushing the changed files all the files with extension .js~ also gets pushed.Will I have to remove this from here or its fine.

### CODE REVIEW

**Comment by hpinkos** [comment]
@AmayAgrawal yes, please remove the extra files.

**Comment by AmayAgrawal** [comment]
Is there any way where I can delete all files at once.Like above if I am deleting one file then I have to commit one per file

**Comment by hpinkos** [comment]
What are you using to push changes to your repository?
If you clone the project to your computer, you can delete all the files, commit the changes all at once, then push them back up to GitHub
Here's a guide for setting up git on your computer if you haven't done so already: https://help.github.com/articles/set-up-git/#platform-all

**Comment by AmayAgrawal** [comment]
Ya I am looking over it and as soon as I remove all the unnecessary files I will let u know

**Comment by hpinkos** [comment]
great, thanks @AmayAgrawal!  I'm happy to help if you run into any issues.

**Comment by AmayAgrawal** [comment]
@hpinkos I think that now it is ready.Now u can review it and let me know if anything else needs to be added

**Comment by hpinkos** [comment]
Great, thanks @AmayAgrawal !

**Comment by pjcozzi** [comment]
Nice, thanks @AmayAgrawal!

**Pull request merged**
