### PR TITLE
Added pixelRatio parameter to camera and the frustum objects

### PR DESCRIPTION
**Pull request by IanLilleyT**
Another CSS pixel fix for https://github.com/AnalyticalGraphicsInc/cesium/issues/8113

All frustums have a `getPixelDimensions` function that didn't account for different pixel density displays. So this PR adds a new `pixelRatio` parameter to these functions. Most systems should pass in `frameState.pixelRatio` to get a value in css pixels. This fixes a few different files that use minimum/maximum pixel size, including `BillboardCollection`, `Model`, `Primitive`, and `PointPrimtiveCollection`. This [before](https://cesiumjs.org/releases/1.62/Apps/Sandcastle/index.html#c=zVoLb9y4Ef4rRIpitc0urffDj2sdx7m4SC5G7NyhiIOCK9G7qrWiIFG2t0H+e4cPvXbl3N6dW9RIbEkcfhwOvxkORzo4QJ8qiuIsLYo0X6IiIzmtEGeoohmNeXpPsw1apQlFBSl5hdgt4iuKlhlbUFTV5S2JKb7Jb/J7UqL7lD7QEp2gnD6gM1ql9Rr/LJ8Zk1jenrGckzSn5WSGvt7kCH6qu80pX7OqWNGSHqJbklV0pptWrM6S0zxdE07RIeJl3TRxWpYAdFmye1CuPGyGi0sKsr+wMkuulYgxbdBimlPn9Yc82yiom/zb9EjofkXyJCYVzygmSXLNlsuMvqo5Z7kxUXeopBXLap6yHDRXOqLbOo/FEyNe0fiOJlM9JWUGXFf0VckeKlp+pDFbr2me0ORjiwNm0v2OWkWEEZVpTxoUqTWWD1sR+kjWRUavNwWs1Qn6PFGTR++J0G5yxTF6C8uXV+LuxxJmh85IvoExL2B0sE8y+XLULdl7ltAMcPSCDNAPB7faknFdljTn513Lltxn80sjqpl1KYl1npNFRpPhUtJkSa/4JgOpYTuYRWvJGcsWRDArYXENluR4Sfl5RsXlq81FYky0yEQYUnPhLmfxHas55iWJ74x2qmMipCiyzas0T0CLqhOdNUOr9Tk4QG8YqCPwhLtUXBDzYUVzVD2kPF6Jh31DKPXHjXAiJ6lnOGKEtl3bIM1oRbm8zxhJ1AxgyQ2lW8NGQVXKjYaMDY/AUClPaYVLumb39DTLZL+ehGJaUabrVPh9I2nogYX0t8FAW1q0A4KyBatSTXJt6TMIH3BFcgfflmz9kSRwXRlzG5uhb0dB5AaO41l26M+QiX0v9H3bNC3HdHzLd2fIck0Tm2qqzShyTpvOV9o5ghcbWhvx02pz2F7OutYFe4SGnrj4SVKgVgWCwgV64aybhqE0ajSbITuUGs6GQCJ0lSnJUBuizljGSvzL24vrcwykWZ1mxYoYJna2uwIvgQ9bgW+rUYKNYnfi39Tlt57x/oi91jJc7FisLlN4OMH4AP5dSRd4TTg5kOLVQUsUffVPuISwtphs2yuFcF+vL9NHml2l/xazB1LsGPVRCF3FJBMCYPjvzVYGT5zQgq+uacVPl7ArVFxvD52bdaJDfx3uZ2f9NjC33CVhD/i6ZaD3hJepIJYiKYYdoKg5fd+1GRrx73UGfAJbUZyzB2Pap4Hejw/R56EBnlLIGKcqsgRBkaSp5CiaB2Nk/Y2w8/8OrAJUOj877HwXtkP90htBRORf0oSvDseC81+FerAuAnPYR7rgmEP25dp9bnRreMpf5b5Dk/Mm7ClqjcblK64ygC4sw951JpOjnWzvlomAnW2W0JeUrIZ0gYCkyAIXWpomuB/c05zLxKOb0RMEsR0vdB0XO55peZ7vBhDJ507gOp7nYnhmW6ZnR/DQ9ULLDE0cBJYfumbo9hf7afAgDH3suqHtB57lanDX9QPs+XYQhEEYaWzbxJEVRYEfmKG3J7gdRRjU9xzT8zR0BHqbYRCZbhAFPb2jyHZ8M/Kj/aB914KNz7P8KPJ8Be05oYcd2PEC03bcQEKbYeRg2BgD2wxCa0+1PTewcRhGruP7TgNuez6GCXkALrdTobft2diB4OrZvufvCe4KLQEvDGw7dBqDO1aEnRAsEPqu6Ul0G5SG1TRNx3LCPa3iBF6IYUkt2P0trTnYHjwNtAROWKHSHBIFWHXPsQLfdMI9scEYGOYcRlHke44CB8AAaGH7YeDawlYA7ppBhF3IQ3zPM/dU3LUtB/vAwQguNDasmKB45PqOpZE90xbItunAeuy5mF7kY9uJoC9QQyI7UWSCSWzgvANmcTW25WGYmO15gbsvwf3IBYWswAQKh6amuOmIh57rR6EfqrUU64r9yAR5cLU9nQf8GgMXQyc07agxie+Dp3jwV3JHQFuuB47gOW4InrYfNHicD5QIQts2fU1By3Vg1RzBEYgoioHAemxH4JZAcGtPaA9gYDl9YANYXmEDPSAw2WYEEzEt5Tt+BP5rg8cHXgCOqbC/DLJTFSbf0XzJVxAs1S3O5H0r2IvKEM1pG1xFTKYkXm0F6w59J0f5/EXnMKKrIURSeGoewZ/jgS5H6OXLdNpP34RwTh/5BZxQH6GTkaKXyJqiPw/7DTus00S2jqb4IqFUfT+nX2Ya5nM7BjwaX4PptDfKd0dY1xlPxZltI7JAUhqNtNjcgbbNbbeJNorXxShgzso1ySDj7CHtoaRALNPlalzLql6ITZsbIxb4TcM8PUSnt5SZKdHdaSu5UYi4ZFXVdK+LvRT6DlynkbqaaeGhToL5KieGwxYcpPOYosUGFSXlVB7DZaFJsh6lFSJc3jPQMt2amXp2Jv2HJtIhhjm7zgq1MvoY2UdoFTgZdBFFhkuxRK91uzEy1FNUGzooLupqZTydsWrdGkVaU397xnNJe5gY4vyf5rzAj3eQyDZ1D132UzdbU5d/nNfXqtH4CmfRrNXmguWi6FaXMZWVh9MKZC4SA+K2M1UDSgejvC7zZgAMMTnZXIJ4WlEMxMuNtto3CJ2NvCTAWcbq5GpFBHsx4cDjmugqSFvK6dH/NPlXXXG0otK3K9bODugOB1Nd4hwyNQY3Y8uSFKs0Hjpf81ROsvXGpnqDFyKvB72uZJ0Vq91m2w90QfdXqzZ9LXDG8mXK6wQ8Yfgc5q4ej3gcu71V6/isA83tkaEgAOdVRp4sR7UxWuk0a6ywVxhszNs/87eDqHtXzui608LoaTSMGQ1aBY5Hnya58EtqbNVfYl0JmpTLhQHnhRmyxakFrqaTXnVka2N4ovQn9u9e3W9o0CGVBLlHObbTr4RFrUXY2uKien60o1VM1rQkWNy9GvQwhgCDhXpLpftdimrsR5IvqSHTgbmJISvUGvwFwSFuuIsPRswYuzvlcsUgmVobW8t58fr8p+uL63+0MXqKGYSI8gFiRRcmwHtZOYwVq5I96OdHvXi3e3qXNXtVsjem3fn9Mo3vEOnKc3pP7Ff4f60E2zoNZ12M2OL5IJK8psuS0sqYW3DEscWhSGTuDiTgkRM5LpjWMjtbbm2mjikKLL22Her0ht5a47by2G2KWxW9Zy3T6X7toleYkor/xEq++lRcszfpI03elMCPVrH/SZ2unftzV+qeCXi3VveswPMx4PF6XZ3DmjTIH+lS1+7Vi6TxetozBxj4PRrZIN54vXjzu2ONjBPbL64gRf2wqGh5L7Ko/ouryWiaNZmK/a6Ky3TRi1X3JKtpG6vGvAvT9q2UFD763uu9TkbbfH+ld9POfTQefXvW13N8Sk22K0qp3013f89Mdl+Sjs8EqPXzYDL6/Z3WPL1FrQg6OTnZfs862GF23wtK4iOaVfRXkKxdpK6G/FuA7F2gwXbWHWy0SV/MXhzLhOcH1fK3dF1A2BVJvIHxAaeATSAsHCzq+A6yjLiqGpA/NS+GewMuSHy3lFXsQwSpEDFcUQ7S/00c9rf9AvIcWPFD5BaPR/03gmVCy7ny3n7jt61h0xzOr4NKCi15GpNsDuffZX4ojoZJRndHnHNWHCJ7MGrTtGCcs3W/FYY9PmhMdJyk9yhNTm5ebH1ScfMC3JFUFbTc1pl8eXbz4ofjA5AfdBMrAuN8AF0zshEiK+uHd+ohxvj4AG53e+kpg7jS6Vh9IIISwsl8keZChhWC0dXWNwPKEQ9HvhqQ6imcBlVZlEOjmKD4PmLBHmFmEkPMTHx6Aff9YfVnFE8cLPX4nwroAlpM5AgTGBr9KL+02H4bQvvn0T+mz25QeVqZc5BFlRLudGjW4T8) and [after](http://localhost:8080/Apps/Sandcastle/index.html#c=zVoLb9y4Ef4rRIBitc2aq/fDj7SO7TQukosR+y4obKPQSvSuzlpxQVG2t0H+e4cPvXblZHN1ixpGLJHDj8PhN8PhKNMp+rUkKMmz1Sor5miVxwUpEaeoJDlJePZA8jVaZClBq5jxEtE7xBcEzXM6I6is2F2cEHxT3BQPMUMPGXkkDB2hgjyiE1Jm1RL/JtuMUSJfT2jB46wgbDRBX28KBD/l/fqYL2m5WhBG9tFdnJdkorsWtMrT4yJbxpygfcRZVXdxwhgAXTD6AMqx/Xq6hBGQ/UJZnl4pEWNcoyWkIM7ppyJfK6ib4tv4QOh+GRdpEpc8JzhO0ys6n+fkbcU5LYyRekOMlDSveEYL0FzpiO6qIhEtRrIgyT1Jx3pJygy4KslbRh9Lwj6ThC6XpEhJ+rnBATPpcQeNIsKIyrRHNYrUGsvGRoQ8xctVTq7WK9irI3Q9UotHH2Oh3eiSY/Qetq8oxdvfGKwOncTFGuY8h9nBPuno9qDdso80JTng6A3poe/3XrUlk4oxUvCztmdD7tq8rUU1sy4ksc6KeJaTtL+VJJ2TS77OQarfD2bRWnJK81ksmJXSpAJLcjwn/Cwn4vHt+jw1RlpkJAypuXBf0OSeVhxzFif3RrPUIZF4tcrXb7MiBS3KVnRST632ZzpF7yioI/CEu5RcEPNxQQpUPmY8WYjGriGU+sNGOJKL1CscMELTr22Q5aQkXL7nNE7VCmDLDaVbzUZBVcKNmow1j8BQGc9IiRlZ0gdynOdyXEdCMW3FsmUm/L6WNPTEQvpbb6INLZoJQdkVLTNNcm3pEwgf8BQXDr5jdPk5TuG5NPZsbIa+HQWRGziOZ9mhP0Em9r3Q923TtBzT8S3fnSDLNU1sqqXWs8g1rVtfadYIXmxobcRPo81+8zhpe2f0CTo64uInzYBaJQgKF+iEs3YZhtKo1myC7FBqOOkDidDFsjhHTYg6oTll+Mv786szDKRZHOerRWyY2NkcCrwEPmwEvo1OCTaI3Yp/U4/fOsb7T+y1lOFiy2IVy6BxhPEUfi+lC5zGPJ5K8XLaEEU//RMeIazNRpv2yiDcV8uL7Inkl9m/xOqBFFtGfRJCl0mcCwEw/PdWK4MnTsmKL65IyY/ncCqUXB8PrZu1on1/7Z9nJ90+MLc8JeEM+LphoI8xZ5kgliIphhNgVXHyse0zNOLfqxz4BLYiuKCPxrhLA30e76PrvgGeU8gYpiqyBEGRpKnkKNoLhsj6k7B7/x1YBah0fnHYvW3YFvW2M4OIyF+ylC/2h4LzX4R6sC8Csz9GuuCQQ3blmnNu8Gh4zl/luUPSszrsKWoNxuVLrjKANizD2XUik6OtbO+OioCdr+cwNma0gnQhBkmRBc60NElxN7hnBZeJR7uiZwhiO17oOi52PNPyPN8NIJLvOYHreJ6Loc22TM+OoNH1QssMTRwElh+6Zuh2N/t58CAMfey6oe0HnuVqcNf1A+z5dhCEQRhpbNvEkRVFgR+YobcjuB1FGNT3HNPzNHQEepthEJluEAUdvaPIdnwz8qPdoH3XgoPPs/wo8nwF7Tmhhx048QLTdtxAQpth5GA4GAPbDEJrR7U9N7BxGEau4/tODW57PoYFeQAuj1Oht+3Z2IHg6tm+5+8I7gotAS8MbDt0aoM7VoSdECwQ+q7pSXQblIbdNE3HcsIdreIEXohhSy04/S2tOdgePA20BE5YodIcEgXYdc+xAt90wh2xwRgY1hxGUeR7jgIHwABoYfth4NrCVgDumkGEXchDfM8zd1TctS0H+8DBCB40NuyYoHjk+o6lkT3TFsi26cB+7LiZXuRj24lgLFBDIjtRZIJJbOC8A2ZxNbblYViY7XmBuyvB/cgFhazABAqHpqa46YhGz/Wj0A/VXop9xX5kgjy42o7OA36NgYuhE5p2VJvE98FTPPgruSOgLdcDR/AcNwRP2w0aPM4HSgShbZu+pqDlOrBrjuAIRBTFQGA9tiNwSyC4tSO0BzCwnT6wASyvsIEeEJhsM4KFmJbyHT8C/7XB4wMvAMdU2Le97FSFyQ+kmPMFBEv1inP53gh2ojJEc9IEVxGTSZwsNoJ1i76Vo1zf6hxGDDWESAat5gH8OezpcoBev87G3fRNCBfkiZ/DDfUJBhkZeo2sMfpTf1x/wDJLZe9gii8SSjX2OrudaJjrZg5oGt6D8bgzy3dnWFY5z8SdbS2ywJgZtbQ43IG29Wt7iNaKV6tBwIKyZZxDxtlB2kFJgciy+WJYy7KaiUObGwMW+Klpnp+i1VvKTJTo9rKV3CBEwmhZ1sOr1U4KfQeu1Ug9TbRwXyfBfJUTw2ULLtJFQtBsjVaMcCKv4bLQJFmPshLFXL5T0DLbWJlqO5H+Q1LpEP2cXWeFWhl9jewiNAoc9YaIIsOF2KJT3W8MTPUc1foOildVuTCez1i1brUijam/veC9pLlM9HH+T3Ne4McHSGTruocu+6mXjaXLP87pleo0vsJdNG+0OaeFKLpVLCGy8nBcgsx5akDcdsZqQulghFesqCfAEJPT9QWIZyXBQLzCaKp9vdBZy0sCnOS0Si8XsWAvjjnwuIp1FaQp5XTof5z+XpUcLYj07ZI2qwO6w8VUlzj7TE3AzeicxatFlvSdr26Vi2y8sa7e4JnI60GvS1lnxeq02fQDXdD9YdWmqwXOaTHPeJWCJ/TbYe2qecDj6N2d2scXnWjPHpgKAnBR5vGz5agmRiudJrUVdgqDtXm7d/5mEvXuyhVdtVoYHY36MaNGK8HxyPMkF35JjI36S6IrQSM2nxlwX5ggW9xa4Gk86lRHNg6GZ0p/4vzu1P36Bu1TSZB7kGNb4xhsaiXC1gYXVfvBllZJvCQsxuLtbW+E0QfobdR7It3vQlRjP8fFnBgyHdgzMWSFWoM/I7jE9U/x3ow5pffHXO4YJFNLY2M7z0/Pfrk6v/pHE6PHmEKIYI8QK9owAd5LWT9WLBh91O0HnXi3fXuXNXtVsjfG7f39IkvuUdyW5/SZ2K3w/6gE2zgNp22M2OB5L5KckjkjpDT2LLji2OJSJDJ3BxLwyIkcF0xrma0tNw5TxxQFlk7fFnU6U2/scVN5bA/FjYrei5bp9Lhm00tM4pL/Qhlf/Lq6ou+yJ5K+Y8CPRrH/SZ2uWftLV+peCHi7VveiwHtDwMP1uqqAPamRP5O5rt2rD0nD9bQXDjDw72Bkg3jjdeLNH441Mk5sfriCFPXTrCTsQWRR3Q9Xo8E0azQW512ZsGzWiVUPcV6RJlYNeRcmzVcpKXzwvc97rYy2+e5Kb6edu2g8+PWsq+fwkupsV5RSv5vu/pGVbH8kHV4JUOu33mL09zuteXaHGhF0dHS0+Z21d8JsfxeUxEckL8kPkKxtpLaG/DNA9jZQ7zhrLzbapK8mrw5lwvNG9fw1W64g7Iok3sB4yglgxxAWprMquYcsIylLMfBwWg86TLMHlKVHN682/pPBzSsgaFyW0HNX5fJz0s2rN4dTkO8NEzrCxn96ICyP10JkYb35oBoxxodTeN0epb8MdxD/DQ) are particularly noticeable on high dpi displays. Toggle the resolution checkbox. In the new version the model stays the same size.

Note: `Picking.getPickOrthographicCullingVolume` and `Picking.getPickPerspectiveCullingVolume` pass in `1.0` instead of `scene.pixelRatio` because picking wants to select from a physically smaller region on higher density screens (aka work with native device pixels instead of css pixels)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by IanLilleyT** [comment]
@lilleyse I made some changes. Now camera uses its own scene's pixel ratio, so the Camera.getPixelSize function signature is the same as pre-PR. Anything that needs the more custom behavior can use camera.frustum.getPixelDimensions and pass in its own pixel ratio.

**Comment by hpinkos** [comment]
@IanLilleyT @lilleyse what's the status of this?  Are we trying to get this in for the release?

**Comment by lilleyse** [comment]
Yes the plan is to get into the release - I'm good with everything here just need to do some final testing and review. Thanks for the reminder @hpinkos.

**Comment by lilleyse** [comment]
@IanLilleyT looks good. Write an issue to remove the deprecated function definitions and add the 1.65 label. See https://github.com/AnalyticalGraphicsInc/cesium/issues/8183 for an example.

**Comment by IanLilleyT** [comment]
Here's the issue for the deprecation: https://github.com/AnalyticalGraphicsInc/cesium/issues/8320

**Pull request merged**
