### PR TITLE
Fix missing wall segments for some extruded polygons

### PR DESCRIPTION
**Pull request by likangning93**
When generating vertices and indices for extruded polygons, we only generate indices for vertices that aren't too close together. However, the array that we were allocating for these indices was sometimes too small, which was most apparent with rhumbline polygons like geojson. This PR allocates a larger array up-front and slices it down to size after all indices have been generated.

I'm not 100% sure how the original index count was computed, @hpinkos @lilleyse is any of that familiar?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @likangning93!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@likangning93 do you have a sandcastle example to reproduce this?  Your fix doesn't look right to me.

**Comment by likangning93** [comment]
[Sandcastle on CesiumJS](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dVTvb5swEP1XUL6ESJGBQAxu02ppWm2Rlm5q00lT0w8uXBKrBke2oc2m/u878pOsG18Md++e796zqbh2KgGvoJ0Lp4BXZwRGlDn5sYm57XTzOVKF5aIA3e46v2eFg4/I+QL0+rtWlciw+mxfmWrgFqZCwoSv7kFXIoXxKdjdcdRPqeWx9rkUMpuorJTwoKXbHhoD1nhTeLOlBuPdcly5vOHaLsfjdmdL847re+d8VsyKCsdZKSOsUIXBiXa8IyzAN16EZK5Vfg0LDWCGWvO1+7gliUncjwMa+DT0WRyyXteJEtKnCY1pzBgNKQ2j7hEbMpr0mN/rsSCiW2wcxIxGNPYZ8+O4ge2Hke8jp0/7SbzHsihJ+pGP5FHSwNIeDUMWRkHUT9gRG7N+QLEx/wSbsCiKaBT0giTc9cuwsdgP/ShkrDcrnra6oDIbQwkUFsUBQ3iW7W1YKbleqAJtaPiyFKC5TpdrDB8U7R7zaIkuM8i+gFgs7ZkT+D7xG/kcD4EWvGHuSEmlyee7m5vbBk6VVuLJQhjyQSORSmVgqlaYmXNpPqSulLUq/0cWu56uV3DceLgNkLsvD5Mrx/OclJcGjJMLY0SxcColyxx2Z+lwlOZlkdZDO1Kpl6F1O3t1dkqmPEeFyC57kOgxeOo2L9Lx6LkoUa2Rc7p26u3+xzvVvDBzpXN3RzfhVou3iIyvb26n4+nPuvi9bveeF1nKjZVQWztVSj5zfVWiRoXbxrsDdrMBXuD9YMeJ9hOeH4Y/RFrd1sDYtYTLLfSTyFdK2/rauoR4FvKVRKeN91ymL2BJakzNMPD2RYNMVI7ILmatv34lsxb6yI3BzLyU8l78glnrcuAh/qRMKp6hS98q0JKva8gyuPy6DRJCBh5+fqyyWwEajH8A)
[Sandcastle on branch](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fixExtrudedPolygon/Apps/Sandcastle/index.html#c=dVTvb5swEP1XUL6ESJGBQAxu02ppWm2Rlm5q00lT0w8uXBKrBke2oc2m/u878pOsG18Md++e796zqbh2KgGvoJ0Lp4BXZwRGlDn5sYm57XTzOVKF5aIA3e46v2eFg4/I+QL0+rtWlciw+mxfmWrgFqZCwoSv7kFXIoXxKdjdcdRPqeWx9rkUMpuorJTwoKXbHhoD1nhTeLOlBuPdcly5vOHaLsfjdmdL847re+d8VsyKCsdZKSOsUIXBiXa8IyzAN16EZK5Vfg0LDWCGWvO1+7gliUncjwMa+DT0WRyyXteJEtKnCY1pzBgNKQ2j7hEbMpr0mN/rsSCiW2wcxIxGNPYZ8+O4ge2Hke8jp0/7SbzHsihJ+pGP5FHSwNIeDUMWRkHUT9gRG7N+QLEx/wSbsCiKaBT0giTc9cuwsdgP/ShkrDcrnra6oDIbQwkUFsUBQ3iW7W1YKbleqAJtaPiyFKC5TpdrDB8U7R7zaIkuM8i+gFgs7ZkT+D7xG/kcD4EWvGHuSEmlyee7m5vbBk6VVuLJQhjyQSORSmVgqlaYmXNpPqSulLUq/0cWu56uV3DceLgNkLsvD5Mrx/OclJcGjJMLY0SxcColyxx2Z+lwlOZlkdZDO1Kpl6F1O3t1dkqmPEeFyC57kOgxeOo2L9Lx6LkoUa2Rc7p26u3+xzvVvDBzpXN3RzfhVou3iIyvb26n4+nPuvi9bveeF1nKjZVQWztVSj5zfVWiRoXbxrsDdrMBXuD9YMeJ9hOeH4Y/RFrd1sDYtYTLLfSTyFdK2/rauoR4FvKVRKeN91ymL2BJakzNMPD2RYNMVI7ILmatv34lsxb6yI3BzLyU8l78glnrcuAh/qRMKp6hS98q0JKva8gyuPy6DRJCBh5+fqyyWwEajH8A)

**Comment by OmarShehata** [comment]
I can confirm this fixes the issue I was seeing which came up on the [forum here](https://groups.google.com/d/msg/cesium-dev/kaAIg-6-XdM/-ob0p_wlBgAJ).

**Comment by hpinkos** [comment]
I'll take a closer look at this soon

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @likangning93! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Replaced  by #8177

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/kaAIg-6-XdM/-ob0p_wlBgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/8035 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Pull request closed without merging**
