### PR TITLE
Get Cesium Viewer working using ES6

### PR DESCRIPTION
**Pull request by mramato**
One of my first goals for ES6 was simply getting Cesium Viewer working as an ES6 application. Which proved easier than I thought.

1. Update GLSL shader gulp task to generate ES6 modules instead of AMD.

2. Update Cesium.js build task to generate ES6 Source/Cesium.js instead of AMD

3. Add rollup as a new dependency that will ultimately replace requirejs.

4. Create a simplified `createWorkers` task that runs as part of `build` this generates one AMD module per-worker that is then loaded by `TaskProcessor` just as before. This step is way faster than I expected and also extracts common code into separate bundles, reducing overall file size and load time.  We will make this more robust when we go to build the release/minified workers, right now I just care about running locally as a dev. I had to modify `TastProcessor._defaultWorkerModulePrefix` to point to `Workers/Build` instead of `Workers`, we'll have to change this somehow when we do a release build.

5. Updated our mostly manual shims on Source/ThirdParty files to use ES6 instead of requirejs.

6. I'm using `import.meta.url` in buildModuleUrl, which may not be the
ideal solution but gets the job down for now. It's only a stage 3 proposal
so eslint fails to aprt it.  Open to any ideas on an alternate approach
here (or should ES6 apps just always set CESIUM_BASE_URL before including
anything)

7. Also updated eslint to treat most of our code base as ES6, there are
still some errors but nothing that won't go away on its own as we progress.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@shunter obviously I would love to get your eyes on this if you have the time, but if you're busy with other stuff, that's fine.

Who else wants to review?  We're all learning here so consider the review process part of taking the time to understand the new architecture and learn more about ES6.

**Comment by hpinkos** [comment]
Edge and IE don't seem to be working.  Is that expected?

**Comment by hpinkos** [comment]
Should `buildApps` work?

**Comment by hpinkos** [comment]
This crashed: http://localhost:8080/Apps/CesiumViewer/index.html?source=../SampleData/simple.czml&inspector=true

**Comment by hpinkos** [comment]
Code changes look fine to me though

**Comment by mramato** [comment]
Talking with @hpinkos offline, to move faster we're going to switch to a coarse 2 PR approach. Basically #8192 will stay open until the end (as planned) but everything else will go into this right away. This way you don't have the 16k lines of cruft getting in the way of the review, but reviewers can just do on PR review at the end.

**Comment by mramato** [comment]
Closing this to open a new PR with full summary and ready for review!

**Pull request closed without merging**
