### PR TITLE
Update semver major npm modules

### PR DESCRIPTION
**Pull request by mramato**
No code changes, but we did have to disable random test ordering in jasmine since Cesium's unit tests unfortunately do not work when ran in a random order.

I'll write up an issue to re-enable random test running (and fix broken tests).

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@mramato, thanks for the pull request! Maintainers, we have a signed CLA from @mramato, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Whoops, looks like there was some unexpected breakage (probably do to globby update), Looking at it now.

**Comment by mramato** [comment]
Turns out globby 8.x is fundamentally broken (negated globs don't work): https://github.com/sindresorhus/globby/issues/75

I rolled back to 7.x for now, which is still a newer version, just not the latest.

**Comment by hpinkos** [comment]
Looks good, thanks @mramato!

**Pull request merged**
