### PR TITLE
Update gltf-pipeline and fix model test

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/7205

Nodes containing extensions or extras where being removed in the glTF 1.0 to 2.0 upgrade stage. This was removing nodes that represented light sources with the `KHR_materials_common` extension. The test is now the same as it was originally written.

The gltf-pipeline fix is here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/431

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
@ggetz can you review?

**Comment by lilleyse** [comment]
@ggetz Can you check this out soon? It would be nice to get this into the release.

**Comment by lilleyse** [comment]
The CI failure seems to be https://github.com/AnalyticalGraphicsInc/cesium/pull/7207 related.

**Comment by hpinkos** [comment]
This all looks good to me.  All the tests pass locally.  Just waiting for CI to pass

**Pull request merged**
