### PR TITLE
Minor 3D Tiles reference doc improvements

### PR DESCRIPTION
**Pull request by pjcozzi**

### CODE REVIEW

**Comment by lilleyse** [comment]
Looks good.

**Comment by lilleyse** [comment]
Do you want to keep this branch?

**Comment by pjcozzi** [comment]
No, I deleted it.  I thought I was going to do more, but that is all that is needed for now, and I didn't want to clump it together with a longer-term style branch.

**Comment by lilleyse** [comment]
Ok

**Pull request merged**
