### PR TITLE
Fix ground polyline with dynamic color

### LINKED ISSUE #6925: CallbackProperty callback not firing on clamped polylines using ColorMaterialProperty
Clamped to ground Polylines which use a ColorMaterialProperty based material do not update each frame.

[Sandcastle Example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=xVZrT9swFP0rVr80lYoLDDapDzRUqoG0qmgt8GGdJpPcUg/HjhynKEz977tOnDZpKXuwsUitEvvc4+Nzrx8LpsmCwwNo0iMSHkgfYp6E9Dpr8+p+9tlX0jAuQdcbnalcYMxcLUAPpOEmxZapnCXSN1xJErJ76Cuh9KVWEWiTepChGuT7VBJ8NJhEy/JYfSbELfPvVxEFmWd4CE2MiBNhVgT24TPieEmv1yurqcDsUwxiNdGb84vJgPpCSfAcbWcNXxIQMTxL8Glwtjt8/eommWMcZNkkM4b8NmRZ8YwZw/z5s65Zz/0yANO102o3YP5FIyVSgcmjITOgORPVTGcMQ9e1YqqMtUvxKDGW+PU1X7puJ2BLfSmDmYB2VUdz3a1yhhsemHmb7Lue5WrG2RwEC6P0ACXkK4VmIjnElAVBMZZkIZA2qfctGALyEVnJDTdz8qTBdTdSMVEMLYmOVMytzzE2rxaJNvjG5Bs60yo8gzsNEJ9qzVLv89674yZ5e9ysFu7vPHsHhxnFl0aJ5MG6ghLKxKuEtLcWRgmVWTZRH7RKZIBQoxNw1qKxjU7V2sM/tfYndfAPTD5+ucnHr23yTCiWLb5f8PhK+v+tgI9e7u3R3/B27d5TG7PbDSzg6V3Q1fQaUI3Ps+GykyfkUalworyN9DSqB+ucyUDAUCUx/i3AgwUCK3ttxP17CEa338A362zHPuA+avvyEOQPLl16muRw3/6K3dceq2WWymFaOmSRvQyjPCjOuK0TtBolEyE6a5eLCs3ntnEFGftYIHIcMR8GVvh5DvIq8/IZEmRWOQ4ag7mQUWJO8yvEhm3NXeyTNAI6HF2NB1+Ho+tBo1Nr1rqxSQWc5Hrf8zBS2pBEC4/SloEwElhKces2QScM9eNMRrdVBHUDviA86E1rG5eoac0u3TjGnhn6MeaPMK2ddFuIr4RhoQRc3o3QQMFSC5kfnHzMGyml3RZ+bkcZpfA2pUuMPwA)

cesiumclamphoverbug

The issue seems to be caused by [`StaticGroundPolylinePerMaterialBatch.js`](https://github.com/AnalyticalGraphicsInc/cesium/blob/f6fa481ce1b1a133a0cb305a78b5ca768c277f2a/Source/DataSources/StaticGroundPolylinePerMaterialBatch.js#L181) not updating the material property when using [`ColorMaterialProperty.js`](https://github.com/AnalyticalGraphicsInc/cesium/blob/f6fa481ce1b1a133a0cb305a78b5ca768c277f2a/Source/DataSources/StaticGroundPolylinePerMaterialBatch.js#L35).

Using a different material property such as `PolylineOutlineMaterialProperty.js` works fine.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #6925

This is the same thing we do for other static geometry types, we must have just missed putting it in for ground polyline

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-ground-polyline-color/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by bagnell** [comment]
Code looks good. Can you add a test?

**Comment by hpinkos** [comment]
Thanks @bagnell, this is ready

**Comment by hpinkos** [comment]
@bagnell fixed

**Comment by bagnell** [comment]
Thanks 👍

**Pull request merged**
