### PR TITLE
*3DTileContentProvider* renamed to *3DTileContent*

### PR DESCRIPTION
**Pull request by TomPed**
For #3241 

Reamed `*3DTileContentProvider*` to `*3DTileContent*`.

As for the change in `CHANGES.md` does it make sense to have this change or no? (I think that it does).

### CODE REVIEW

**Comment by lilleyse** [comment]
> As for the change in CHANGES.md does it make sense to have this change or no? (I think that it does).

Yeah that change makes sense.

**Comment by lilleyse** [comment]
Make sure to also change the names in

* `Cesium3DTileBatchTableResources`
* `Cesium3DTileBatchTableResourcesSpec`
* `Composite3DTileContent`

**Comment by TomPed** [comment]
I did a search for `3DTileContentProvider` in these files and I don't see anything. Should I just be looking for the word `Provider` and remove that?

**Comment by lilleyse** [comment]
I just did a search for `ContentProvider`.

**Comment by TomPed** [comment]
Oh, okay, I thought we where only changing `3DTileContentProvider`s. I'll make these changes.

**Comment by TomPed** [comment]
Updated.

**Comment by TomPed** [comment]
Okay I'll change that, I was not sure so I took a look at [this](http://dictionary.cambridge.org/us/grammar/british-grammar/content-or-contents) and got more confused, :smile:. I'll make the change.

**Comment by TomPed** [comment]
Updated.

**Comment by lilleyse** [comment]
Yeah I see your point about `contents` being ambiguous here, but it's okay for now. Merged.

**Pull request merged**
