### PR TITLE
Fix polyline update and removal bookkeeping

### LINKED ISSUE #4983: Batch Table 'instanceIndex is out of range' error when editing a polyline
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/gbBjAyFs1JQ

I've seen this a number of times when editing polyline positions, but haven't found a reliable way to reproduce the crash.  I asked the user from the forum if they had a code example to share.

### PR DESCRIPTION
**Pull request by markerikson**
Fixes #4983.

PolylineCollection stores a list of polylines that are waiting to be updated in the next render pass.  However, if a polyline is both updated _and_ removed in the same synchronous execution sequence, _and_ the polyline is near the end of the collection's internal `this._polylines` list, it's possible for the PolylineCollection to effectively read off the end of the array, causing an error "Batch Table instanceIndex out of range".

This is resolved by ensuring that removing a polyline from the collection also removes it from the list of polylines waiting to be updated.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @markerikson!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by markerikson** [comment]
CLA sent in, and updated CHANGES.md.

**Comment by hpinkos** [comment]
The fix looks good to me!  And we got your CLA email.  Can you please write a unit test for this?

**Comment by markerikson** [comment]
Yeah, lemme figure out how the unit testing setup works on this project and do so.

**Comment by markerikson** [comment]
Unit test added.

**Comment by pjcozzi** [comment]
We received @markerikson's CLA.

**Comment by markerikson** [comment]
Looks like there's some style complaints.  I'll fix those.

**Comment by markerikson** [comment]
And looks like the CI check is clean.

**Comment by hpinkos** [comment]
Great work @markerikson!  Thanks so much for digging into this, I wasn't able to figure out what the issue was last time I looked at it.

I just made a few minor styling changes.  As soon as CI passes I'll merge this in.

**Comment by hpinkos** [comment]
Great work @markerikson, thanks again!  And congrats on your first Cesium contribution!

**Pull request merged**
