### PR TITLE
Add support for using a velocity vector as the aligned axis of a billboard in CZML

### PR DESCRIPTION
**Pull request by shunter**
Introduce a new CZML property `velocityReference` which indicates that a value is determined by the velocity of an object's position, expressed using reference syntax.  The reference can be to any object.

additionally:
* I clarified in several places that aligned axis must be a unit vector.
* As discussed offline, I made the vector normalization done by `VelocityVectorProperty` optional (default remains as before).  

Specifically, consider whether this name is what we want.  Given that it becomes part of the CZML spec, decisions are fairly permanent here.

```json
"billboard" : {
    "alignedAxis" : {
        "velocityReference" : "#position"
    }
}
```

For this PR, there is a lot of churn in the validation document.  My initial simplistic approach to producing unique packet IDs and unique values etc. caused everything to get re-numbered throughout the document.  I have switched it to scope unique values a bit better from now on, so that adding a new property (e.g. `velocityReference`) won't affect quite as much of the document in the future.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Who is the right person to review this?

Perhaps @tfili?

**Comment by mramato** [comment]
@shunter please update CHANGES.md

**Comment by mramato** [comment]
Other than that, this is fine with me.  Can you merge in master, it looks like there are some changes part of this PR that I think should already be merged (czml validation stuff)

**Comment by shunter** [comment]
Updated.

**Comment by mramato** [comment]
Thanks.

**Pull request merged**
