### PR TITLE
Add Submitting an Issue section to CONTRIBUTING.md

### LINKED ISSUE #2744: Add submitting issues section to CONTRIBUTING.md
Given the increase in the number of questions we are getting in GitHub issues, perhaps adding a short section on submitting issues to the top of CONTRIBUTING.md that points users to the forum for questions would help.

@mramato please close if this is a duplicate, I know you suggested this at one point, but I couldn't find where.

### PR DESCRIPTION
**Pull request by pjcozzi**
Fixes #2744.

@slchow can you please review?  It is a balancing act of making the barrier-to-entry low, but also asking for enough information to help us find and fix the issue.  The overall tone should be "thanks for helping us, your awesome."

To submit changes, you'll want to make a branch from this `issue` branch into your fork, and then open a pull request back into this branch.

### CODE REVIEW

**Comment by pjcozzi** [comment]
This has been copyedited.

**Comment by mramato** [comment]
If it's a visual artifact, do we want a copy of their http://webglreport.com output?

**Comment by mramato** [comment]
I know it wasn't part of you changes, but the `Opening a Pull Request` section is pretty out of date and references `ant` and command lines that don't exist anymore.  Do you want to fix this now, or open another PR later?

**Comment by pjcozzi** [comment]
> If it's a visual artifact, do we want a copy of their http://webglreport.com output?

Yes, it's sometimes useful.  Added.

> I know it wasn't part of you changes, but the Opening a Pull Request section is pretty out of date and references ant and command lines that don't exist anymore. Do you want to fix this now, or open another PR later?

I fixed the old ant reference and will continue to improve this section as I finish the other guides.

**Pull request merged**
