### PR TITLE
Update ImageryProvider documentation

### PR DESCRIPTION
**Pull request by gberaudo**
The list is now up-to-date.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@gberaudo, thanks for the pull request! Maintainers, we have a signed CLA from @gberaudo, so you can review this at any time.

I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).



__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by ggetz** [comment]
Awesome, thanks @gberaudo!

@pjcozzi This is good to merge.

**Comment by pjcozzi** [comment]
Thanks @gberaudo @ggetz.

@lilleyse please merge before or after the 1.37 release.  This is just doc.

**Comment by pjcozzi** [comment]
Also despite the friendly @cesium-concierge's comment, this does not need an update to CHANGES.md so I removed it.

**Pull request merged**
