### PR TITLE
Fix morph crash from Columbus view to 3D

### LINKED ISSUE #5311: Render Error Switching from Columbus View to 3D view
Cesium 1.33, open sandcastle hello world (Chrome 51.0.2704.84), go to Columbus view, then go back to 3D view and I get a rendering error.
TypeError: Cannot read property 'clone' of undefined

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #5311.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @bagnell.  Please update README.md.  Is it also possible to add a reasonable unit test?

@cfairchi could you test this?

**Comment by bagnell** [comment]
@pjcozzi This is ready. There are no tests for `SceneTransitioner`.

**Comment by pjcozzi** [comment]
Am I doing something wrong?  If I run

http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/morph-crash/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases

Then morph to CV, I get:

image

**Comment by hpinkos** [comment]
Looks like it's running into the new `DeveloperError` I added in #5304

**Comment by bagnell** [comment]
Yes, it was from the latest merge. Fixed.

**Comment by pjcozzi** [comment]
Thanks, looks good!

**Pull request merged**
