### PR TITLE
Clamp to tileset example

### PR DESCRIPTION
**Pull request by ggetz**
Added an example for clamping to a position on the surface of a 3D tileset. 

There are some workarounds we need to do with the current API, so it's a little lengthy. We wait for the tileset to load in completely, place a "placeholder" frame as an image over the scene, move the camera overhead, render, and pick a position, then restore the camera values and remove the placeholder frame.

TODO:
 - [x] Thumbnail

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@ggetz, thanks for the pull request! Maintainers, we have a signed CLA from @ggetz, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
Given that clamping to a 3D Tileset https://github.com/AnalyticalGraphicsInc/cesium/issues/6080 is on the horizon, I don't think this should necessarily be merged, but it does serve as a good workaround until the functionality is built into Cesium.

**Comment by pjcozzi** [comment]
Customers have been asking about this.  I suggest merging it and then replacing it with a simple example as part of #6080.

**Comment by lilleyse** [comment]
Ok, sounds good. I'll do a closer review.

**Comment by lilleyse** [comment]
The demo has a lot going on but the code itself look good.

Given the complicated nature of this workaround, would it be ok to move this to the development folder instead?

**Comment by ggetz** [comment]
> Given the complicated nature of this workaround, would it be ok to move this to the development folder instead?

Since its a workaround, I'm good with that in theory. In practice however, it won't show up on the deployed Sandcastle, so we can't easily link from the forum, etc. Are we good with that?

**Comment by lilleyse** [comment]
The development demo can still be reached, though its hard to say what benefit it offers over passing around a Sandcastle link with the embedded code.

For example:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=development%2F3D%20Models%20Instancing.html&label=Development

This is the same dilemma as https://github.com/AnalyticalGraphicsInc/cesium/pull/6680#discussion_r195418892, whether workarounds should be included in Sandcastle demos. Maybe this is an exception since its short term, but I just want to make sure we're following Sandcastle best practices.

**Comment by ggetz** [comment]
@lilleyse Updated!

**Comment by lilleyse** [comment]
Thanks!

**Comment by VINOlive** [comment]
> Added an example for clamping to a position on the surface of a 3D tileset.
> 
> There are some workarounds we need to do with the current API, so it's a little lengthy. We wait for the tileset to load in completely, place a "placeholder" frame as an image over the scene, move the camera overhead, render, and pick a position, then restore the camera values and remove the placeholder frame.
> 
> TODO:
> 
> * [x]  Thumbnail

It doesn't work in cesium 1.64.   How to make it run correct, any help thank u

**Comment by OmarShehata** [comment]
@VINOlive is this the example you're testing?

https://sandcastle.cesium.com/index.html?src=Clamp%20to%203D%20Tiles.html

Is this producing an error for you?

**Comment by VINOlive** [comment]
> @VINOlive is this the example you're testing?
> 
> https://sandcastle.cesium.com/index.html?src=Clamp%20to%203D%20Tiles.html
> 
> Is this producing an error for you?

It work.  I want to get the height by lon and lat.  Through the demo  find the api.

Thank U and Cesium is realiy good in nicety

**Pull request merged**
