### PR TITLE
Fix KML ground overlay distortion bug

### LINKED ISSUE #5914: KML ground overlays appear distorted when rotated
PR incoming...

May or may not assist with the forum thread referenced in this ticket: https://github.com/AnalyticalGraphicsInc/cesium/issues/5025

Google Earth:
before

Cesium (before fix):
after

Cesium (after fix):
image

### PR DESCRIPTION
**Pull request by jburr-nc**
Fixes #5914

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Welcome to the Cesium community @jburr-nc!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?



__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by hpinkos** [comment]
Awesome!  Thanks for fixing this @jburr-nc!
Could you add a unit test? I imagine it will be similar to this one, just check that stRotation is also correct: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/DataSources/KmlDataSourceSpec.js#L794-L812

As soon as we receive your CLA we'll be able to merge this.

**Comment by jburr-nc** [comment]
@hpinkos The CLA for Novetta should be [submitted](https://github.com/AnalyticalGraphicsInc/cesium/pull/5860#issuecomment-333518063). I added an additional check to rotation test that was already there. Would you prefer a brand new test instead?

**Comment by hpinkos** [comment]
Thanks, I can confirm that we have your CLA.  And that test looks fine to me!

Thanks again @jburr-nc!

**Pull request merged**
