### PR TITLE
Remove handling of deprecated scene parameter in constructor

### PR DESCRIPTION
**Pull request by erikmaarten**
For issue #4385. @bagnell Does this look OK?

### CODE REVIEW

**Comment by mramato** [comment]
@erikmaarten this is exactly what was needed.  Can you add a line to CHANGES.md to mention this?  After that I'll merge.  Thanks.

**Comment by bagnell** [comment]
You can also update the code in `DataSourceDisplay._onDataSourceAdded` and `DataSourceDisplay._onDataSourceRemoved` that checks for clustering on the visualizers.

**Comment by erikmaarten** [comment]
@mramato Added to CHANGES.md now

**Comment by erikmaarten** [comment]
@bagnell I'm not quite sure about this, but it looks like the if statement could be removed, and 
```
cluster._initialize(scene);
scene.primitives.add(cluster);
```
could be run for every initializer, since these must now have a cluster, and will not have a scene. Is that right?
Such a change breaks a lot of tests, which seems to be related to a MockVisualizer in DataSourceDisplaySpec.js not yet being adapted to new the new Visualizer shape, but I'm not sure I should make too big changes to this code yet since I'm not very familiar with how the visualizers work.

**Comment by bagnell** [comment]
You should be able to remove the loop when the data source is added because 
```javascript
var visualizers = this._visualizersCallback(scene, entityCluster, dataSource);
dataSource._visualizers = visualizers;
``` 
should construct the visualizers with the cluster that was just initialized. The loop when a data source is remove only needs to destroy the visualizers. Yes, the tests in DataSourceDisplaySpec need to be updated, but I think the other tests should be fine.

**Comment by erikmaarten** [comment]
Thanks @bagnell. About the tests, they actually pass without changes. MockVisualizer should probably take an `entityCluster` instead of `scene` as the first argument, but `MockVisualizer` is never called with arguments so it shouldn't make a difference. Is this what's intended?

**Comment by fredj** [comment]
The `deprecationWarning` "include" in the file define (sorry, probably not the right term) can be removed in all the file where the `deprecationWarning` call where removed

**Comment by mramato** [comment]
Thanks @fredj I pushed a change to remove them.

@erikmaarten since they were unused, I just removed the two constructor parameters from MockVisualizer.  If we ever need the Mock to do more, we can add them back (my pipe dream is still to get webgl working on travis so we can actually mock less stuff, but that's a PR for another time).

This looks good to me.  Thanks @erikmaarten and @fredj!

**Pull request merged**
