### PR TITLE
Add a function for getting maximum level of detail in terrainProvider

### PR DESCRIPTION
**Pull request by nacho-carnicero**
This PR adds a method for getting the maximum level of detail for a specific zone of the globe from a terrainProvider instance. 

The reason for which I'm adding this is that it is very useful for getting the height of the terrain in a specific point. According to [this example](https://cesiumjs.org/Cesium/Build/Documentation/sampleTerrain.html) the following code can be used for sending a query to the terrain provider and getting back the height of the terrain:

```javascript
// Query the terrain height of two Cartographic positions
var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles'
});
var positions = [
    Cesium.Cartographic.fromDegrees(86.925145, 27.988257),
    Cesium.Cartographic.fromDegrees(87.0, 28.0)
];
var promise = Cesium.sampleTerrain(terrainProvider, 11, positions);
Cesium.when(promise, function(updatedPositions) {
    // positions[0].height and positions[1].height have been updated.
    // updatedPositions is just a reference to positions.
});
```

Now as it can be seen the call to `sampleTerrain` needs to specify the level-of-detail (LOD) to be used for the query. Since the LOD varies from one region to another, it is not possible (nor suitable) to hard-code the maximum LOD in one region and hope that it will work for another region.

Thus, this PR enables to call `terrainProvider.getMaxigetMaximumLevelAtPosition(position)` in order to get the maximal LOD in the region of interest and then query the terrainProvider to get the most precise height of the terrain.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Welcome to the Cesium community @nacho-carnicero!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).



__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by pjcozzi** [comment]
Thanks for the contribution, @nacho-carnicero!  We received your CLA.

@nacho-carnicero can you please update [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) and add a unit test to [CesiumTerrainProviderSpec.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Core/CesiumTerrainProviderSpec.js)?

@tfili can you please review?

**Comment by tfili** [comment]
Thanks @nacho-carnicero.

Since you added a method to the `TerrainProvider.js`, you need to add the method to all other `TerrainProviders`. This method can return `undefined` if its not implemented. This broke 3 tests
```
1) conforms to TerrainProvider interface
     Core/GoogleEarthEnterpriseTerrainProvider
     Expected function 'getMaximumLevelAtPosition' to exist on GoogleEarthEnterpriseTerrainProvider because it should implement interface TerrainProvider.
2) conforms to TerrainProvider interface
     Core/VRTheWorldTerrainProvider
     Expected function 'getMaximumLevelAtPosition' to exist on VRTheWorldTerrainProvider because it should implement interface TerrainProvider.
3) conforms to TerrainProvider interface
     Core/EllipsoidTerrainProvider
     Expected function 'getMaximumLevelAtPosition' to exist on EllipsoidTerrainProvider because it should implement interface TerrainProvider.
```

Also, you need to a few few tests. Probably need to verify a provider that hasn't been successfully loaded gracefully handles calling this function, along with a test that shows the function works correctly.

**Comment by kring** [comment]
Thanks for the PR, @nacho-carnicero, but I don't really think this change is needed.  `availability` is a public property, so users can access that directly.  The wrapper function in TerrainProvider doesn't really add much, IMO.  Also, we already have a function that directly addresses the stated use case: https://cesiumjs.org/Cesium/Build/Documentation/sampleTerrainMostDetailed.html

Perhaps there's something we can do to make that function more discoverable?

**Comment by nacho-carnicero** [comment]
I totally agree @kring, it does not add much but it enables to show this method on the terrain provider documentation so that someone that does not have the time to look at the code can have access to this information. 

Nevertheless the function `sampleTerrainMostDetailed` is exactly what I was looking for, I spent quite a time looking for something like this in the  documentation (but I guess I got obsessed with getting the maximum LOD instead). Perhaps a mention to this function in the `sampleTerrain` documentation would be useful. Indeed, when you type in Google "get terrain height cesium" the only function that shows up is `sampleTerrain`, so a link to `sampleTerrainMostDetailed ` in that documentation would certainly save a big amount of time to people interested in this.

As far as I'm concerned I don't see any other use case for this PR, so I'm going to close it. If you want me to add the link to `sampleTerrainMostDetailed ` in the documentation let me know.

**Comment by kring** [comment]
Glad to hear `sampleTerrainMostDetailed` is what you were looking for, @nacho-carnicero.  I think adding a link to that function from the `sampleTerrain` doc is a great idea.  If you don't mind opening that pull request (and add yourself to CONTRIBUTORS.md while you're at it), I'd be very happy to merge it.  Thanks again!

**Pull request closed without merging**
