### PR TITLE
Updated readme.md

### PR DESCRIPTION
**Pull request by Cwalsh88**
Worked on issue #5468, Updated all demos in README.md to match cesiumjs.org demos.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @Cwalsh88.  Congrats on your first Cesium pull request and first pull request ever!

@slchow could you please review this?

Also, anyone have any idea why the diff doesn't show cleanly?  E.g., line endings?

**Comment by mramato** [comment]
> Also, anyone have any idea why the diff doesn't show cleanly? E.g., line endings?

It's definitely whitespace/line endings changes.  If you add `?w=1` to the diff url, you'll see the changes all go away: https://github.com/AnalyticalGraphicsInc/cesium/pull/5581/files?w=1

We use `core.autocrlf` set to `true` on windows and left as the default on Unix/Mac, (which on new Git installations is the default I believe.)  If that setting is different, it can cause these types of diff issues.

**Comment by hpinkos** [comment]
@Cwalsh88 can you fix the whitespace issues and merge in master when you have a chance?  Thanks!

**Comment by slchow** [comment]
Actually, I'll work on this. With the recent improvements to cesiumjs.org, the links need to be updated, anyway.

**Comment by hpinkos** [comment]
Okay, thanks @slchow!

Thanks for making the initial effort at this @Cwalsh88!  I'm going to close this because there other chances we're waiting on from the website end.  We have tons of other open [beginner issues](https://github.com/AnalyticalGraphicsInc/cesium/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner) if you are interested in contributing.  We're always happy to review pull requests.  Thanks again!

**Pull request closed without merging**
