### PR TITLE
Change docs to say travis-ci.org

### PR DESCRIPTION
**Pull request by malaretv**
travis.org is a church website :smile:

### CODE REVIEW

**Comment by hpinkos** [comment]
Haha, thanks for catching that @malaretv! 

I know it's a tiny change, but can you send over a contributor license agreement (CLA) so we can merge this?  You can find instructions here: [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

**Comment by malaretv** [comment]
@hpinkos sent!

**Comment by pjcozzi** [comment]
Thanks @malaretv, we received your CLA.  Can you also please add yourself to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md in this pull request?

**Comment by malaretv** [comment]
@pjcozzi done.

**Comment by pjcozzi** [comment]
Thanks again @malaretv!

**Pull request merged**
