### PR TITLE
Closes issue #5691

### PR DESCRIPTION
**Pull request by avalan4e57**

### CODE REVIEW

**Comment by hpinkos** [comment]
@avalan4e57 can you please send us a Contributor's License Agreement so we can review and merge this?  See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by avalan4e57** [comment]
@hpinkos done!

**Comment by avalan4e57** [comment]
@hpinkos I’ve thought a little about it. And came to conclusion that I don’t want to contribute to AGI projects. Either I get paid for my code or I have my rights on it. Thank you for understanding and sorry for waisting your time.

**Comment by pjcozzi** [comment]
No worries @avalan4e57!  Thanks for considering to support the project, we hope you are having great success with your development.

**Pull request closed without merging**
