### PR TITLE
Handle undefined Primitives bounding spheres.

### PR DESCRIPTION
**Pull request by dwhipps**
I found that I would often get undefined bounding spheres here (with some KML data sets, if that helps).

I'm not actually sure whether it's better to not set these "batchedAttribute"(s) (as I do here) or to set them to some default value (zeros, for example.)

### CODE REVIEW

**Comment by hpinkos** [comment]
I don't know exactly what's going on, but I feel like it's a problem if the bounding sphere is undefined.  @bagnell do you have any idea?

@dwhipps, could you attach a KML that reproduces the problem?  Thanks!

**Comment by mramato** [comment]
Thanks @dwhipps, I agree with @hpinkos that this looks more like a symptom of a bigger problem.  If you can share one of the KML files or a simple test case, that would be a big help.

**Comment by bagnell** [comment]
The bounding sphere should always be defined. Unless the code doesn't handle invalid geometry correctly, for example, a degenerate polygon. I ran some tests, but I couldn't reproduce the crash.

**Comment by dwhipps** [comment]
Sorry, I've been on another project for a few days. Just getting bach to this now. I'll try to put together a Sandcastle showing the problem.

**Comment by mramato** [comment]
@dwhipps I'm assuming you are running into the same problem as #4431, which includes a KML that reproduces the issue.  We fixed the initial problem but now there are lots of undefined bounding spheres compared to 1.25 where everything works.

**Comment by mramato** [comment]
@dwhipps this was fixed with #4532

The only time you should have undefined bounding spheres is if the geometry failed to be created (for example polygons with invalid data or that fail to triangulate).  We handled these gracefully in the past, but a regression in 1.26 caused issues.  See the linked PR for details.  Thanks for helping bring the issue to our attention and if you're still having problems, let us know.

**Pull request closed without merging**
