### PR TITLE
Add support for touch and hold gesture

### PR DESCRIPTION
**Pull request by adridavid**
Currently, the only available event types in touch mode are LEFT_DOWN/LEFT_UP/LEFT_CLICK and LEFT_DOUBLE_CLICK. Since the touch and hold gesture is widely used on mobile devices, this is a pull request to add support for this event type.

Generally the touch and hold gesture is associated with the right click. For this reason, I linked it with the RIGHT_CLICK event type. But we may also think it as a new event type (for instance TOUCH_HOLD).

The amount of time before a touch becomes a touch and hold can be customized. It is set by default to 1,5 seconds.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @adridavid! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/touch-events/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the pull requests @adridavid!  Please send us a CLA so we can review this and  #7285 

We should be able to review this after the release next week

**Comment by pjcozzi** [comment]
Thanks again @adridavid, we received your CLA.

**Comment by hpinkos** [comment]
@adridavid please merge in master when you have a chance.  Thanks!

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @adridavid! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks @adridavid.  Can you merge in master again and move your CHANGES.md change under the 1.55 section?

@emackey can you review this?

**Comment by adridavid** [comment]
I just merged in master and updated CHANGES.md @hpinkos .

**Comment by emackey** [comment]
Overall this seems great, and I love that it's wired into the `RIGHT_CLICK` event because that's usually what touch-hold equates to on desktop.  Cesium doesn't make much use of that event, but our customers might.

One wrinkle I had while testing this is it was very tricky for me to hold my finger steady enough (on a Surface Pro 4 with a fairly large screen) such that I triggered the event rather than just panning the globe.  Is there a way to increase the robustness of that?  (Obviously without making the pan wait for it, but maybe by allowing the pan to travel some larger number of pixels without voiding it).  Just a suggestion.

Here's a Sandcastle I was using for testing.  It's the picking demo, modded to use right-clicking, which on this branch can be done with an actual mouse or by touch-hold.

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    selectionIndicator : false,
    infoBox : false
});

var scene = viewer.scene;
if (!scene.pickPositionSupported) {
    console.log('This browser does not support pickPosition.');
}

var handler;

Sandcastle.addDefaultToolbarButton('Show Cartographic Position on Right-click', function() {
    var entity = viewer.entities.add({
        label : {
            show : false,
            showBackground : true,
            font : '14px monospace',
            horizontalOrigin : Cesium.HorizontalOrigin.LEFT,
            verticalOrigin : Cesium.VerticalOrigin.TOP,
            pixelOffset : new Cesium.Cartesian2(15, 0)
        }
    });

    // Mouse over the globe to see the cartographic position
    handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
    handler.setInputAction(function(movement) {
        var cartesian = viewer.camera.pickEllipsoid(movement.position, scene.globe.ellipsoid);
        if (cartesian) {
            var cartographic = Cesium.Cartographic.fromCartesian(cartesian);
            var longitudeString = Cesium.Math.toDegrees(cartographic.longitude).toFixed(2);
            var latitudeString = Cesium.Math.toDegrees(cartographic.latitude).toFixed(2);

            entity.position = cartesian;
            entity.label.show = true;
            entity.label.text =
                'Lon: ' + ('   ' + longitudeString).slice(-7) + '\u00B0' +
                '\nLat: ' + ('   ' + latitudeString).slice(-7) + '\u00B0';
        } else {
            entity.label.show = false;
        }
    }, Cesium.ScreenSpaceEventType.RIGHT_CLICK);
});

Sandcastle.reset = function() {
    viewer.entities.removeAll();
    handler = handler && handler.destroy();
};
```

[localhost:8080 Sandcastle demo](http://localhost:8080/Apps/Sandcastle/index.html#c=lVVtb9MwEP4rph9IIoq7IRASayfYGGyiaIhWfIqEXOeSWHPtyHa6FdT/ztlpsjQrSESt5Je7516f84YZshFwD4bMiIJ7cglW1Gv6I5zFEQ/bS60cEwpMNCa/U0XwsyCBO6HVjcoEZ04b8o7kTFoYNwJC5fpCP7SnqdolZ6lK1QYtWg4K0GBjmYYtXoqcxM/ChlaC333TVngLi7qqtHGQJa1xrpXVEqjURRwtS2HJyuh7i0FkGixR2hHbKJE+EI28C7vWi5KpTIIJXi1wzZl1CMqy7CPkrJZuqbVcMXNRO6dVHC1KjflhxunCsKoUnLTABH/fRVG6l1yiPcxSXquQnbjz2VsE5YTbPgYe9gKstxnv5fwn2QokZq53FHLuHTjMcv/qgvG7wuhaZSjkTD2UybGKeBOdvq4eyForbSvGIRpIldqIX77e8taIQijU2PfE9eCGzq8+LQfaGzAO2+GJ7o+Dc7q8/TZQrMQDyNs8t+B97HWiTziumHoVn74Zk5PkUW/XLPeN5ZeTCfmqawtEoyPElUAKqVdAnMaGhXDA+wWs9gVstPcNcciEBTcAauFTdbXBgl03QnHTp5xhK1nvQA+AYhA3qqrdh6YHumZYo1trxEj6lfWNwdsgH3uDszUYFohwJaWorBZZB0Bbx8cNl2gIk0Ir2DoUiIis6vCTYU+11ruUzPqJb09pbvS6q0QP7uwpmtSqEK7OYOGMUMUj4FfmSur0RygwozbuW6WdUoISn7AXsvjVUXDm/h97rzOAPgRvqNnlFZG7IM+OSgaO0kDJWWDbv8QcPDgyOxTwXzTXChlJXpA48ltcDNKXUIsjBeKXbxO8jNK0Pjm5OEHBI2BpqubMDfEOMvYXuJ7vOwI4XoZtcizoMIfOntJx/DfqLLcV0O83n6+XPy/nN5dfwjROhvPXgJ8Bs2MjdDA1DXg+fJAyHhAQtdvV8+cdKzOwzuhtEN7hfzQeTa3bSjhvlN+LdXgyaiNjSicO1hUmD+xkVfM7cJTbQPTppFWaZmJDRDZLR4NnMh0RLpm1eJPXUi7EL0hH59MJyh+oSc0yLMotDivJtl6kPD2fN4eU0ukEt0+1XPMs9RD/AA)

**Comment by adridavid** [comment]
Thank you @emackey !

Concerning the number of pixels without voiding the event, I wanted it to be consistent with the simple click and I used the same behavior as for left click in touch mode :
https://github.com/AnalyticalGraphicsInc/cesium/blob/72cd1e799bc09cf24bbda2919b6a087fa2fbfad5/Source/Core/ScreenSpaceEventHandler.js#L136-L144

The pixel tolerance was previously set to 5, but there is a comment that suggests it should be revisited :
https://github.com/AnalyticalGraphicsInc/cesium/blob/72cd1e799bc09cf24bbda2919b6a087fa2fbfad5/Source/Core/ScreenSpaceEventHandler.js#L717-L719

Maybe we could use a second value which would be greater for the touch and hold event. However, I don't know which tolerance would be a good choice to handle correctly all screen sizes.

**Comment by emackey** [comment]
@adridavid Do you think it's worth adding a `this._touchPixelTolerance`, maybe set to 25 or some such, and using that just for the new touch-hold value here in this PR?  That way it can be tweaked and refined later.

**Comment by adridavid** [comment]
@emackey I did the change.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @adridavid! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@emackey what's the status of this?

**Comment by emackey** [comment]
Sorry, lost track of this, I have to test it at home because I don't have a touch screen at work.  I was pretty close to merging it before, so I think it's probably ready now, just want to test it on a touch screen once more.

**Pull request merged**
