### PR TITLE
Fixed additive refinement traversal bug

### LINKED ISSUE #5766: 3D Tiles selection bug?
Check out the NYC Sandcastle examples: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Picking.html&label=3D%20Tiles

If you just sit there and let everything load, some of the tiles that should be visible never get loaded even though they are definitely within the SSE (verified by waiting for the network tab to stop loading tiles).  If you move the camera around, these buildings get loaded pretty quickly, and if you go back to the home view, they stay loaded.  So I'm not sure where the bug is,, but it seems like a pretty significant one.

Initial view; 
image

After moving the camera around and back to the initial view:

image

CC @lilleyse @pjcozzi

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #5766 

This fixes an issue exclusive to additive refinement and with `skipLevelOfDetail` set to true (default).

Tiles with additive refinement were not getting loaded unless they were leaf tiles or they couldn't refine to their children due to SSE. Many interior tiles did not fit this condition and were never loaded. This fix forces additive tiles to always load during the traversal.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Code looks OK.  Could be worth adding a comment why additive always loads the tile.

@ggetz could you please test this?

**Comment by ggetz** [comment]
Yep, looks like it's working! We may want to also update the thumbnail for the example, since it shows the initial view where not all the building are loaded.

**Comment by lilleyse** [comment]
Updated thumbnail

**Comment by ggetz** [comment]
@pjcozzi This should be good to go.

**Comment by pjcozzi** [comment]
Thanks @lilleyse @ggetz!

**Pull request merged**
