### PR TITLE
Add max size query for SkyBox cubemaps.

### PR DESCRIPTION
**Pull request by emackey**
A case came up today with high-res SkyBox maps being unusable on certain systems, and @mramato suggested there should be a public way to query availability for this.

### CODE REVIEW

**Comment by mramato** [comment]
@pjcozzi any objections to this?  Seems pretty cut and dry to me, since you need to know the max cube size in order to create an appropriate SkyBox.  We added similar functionality to scene when we needed to start clamping line widths.

**Comment by emackey** [comment]
A more general question is, is this the strategy to take with all sorts of `gl.getParameter` type stuff?  I can imagine a user wanting to query any and all parameters from the GL context, possibly wanting to query even more than our own `Context` does.  At the very least the user should be able to get any values listed on [webglreport.com](http://webglreport.com).

**Comment by pjcozzi** [comment]
I'll look at this as soon as I can.  It will be a few days.

**Comment by pjcozzi** [comment]
This is OK.  I wouldn't worry about exposing anything else until we need it.  Update CHANGES.md in master if you want.  I'm not sure that it is needed.

**Pull request merged**
