### PR TITLE
Update Autolinker.js

### PR DESCRIPTION
**Pull request by ChristinaElaine**
Exception thrown when html is undefined which cancels the rest of the load on a KMLDataSource add.

### CODE REVIEW

**Comment by mramato** [comment]
Thanks for the contribution @ChristinaElaine.  Do you happen to have a snippet of KML (or a file) that causes this issue?  I would like to better understand what is going on.  I don't think this is a bug in AutoLinker.js itself but rather a problem with the KML code.  Thanks.

**Comment by ChristinaElaine** [comment]
Sure thing. Here is one of the placemarks that causes the error. It's just a point with a label:

<Placemark id="1bf12f6f-ec60-4bd2-bc4a-c70e4e62807e">
        <name>New Label</name>
        <styleUrl>#milsymbol-baloon-template</styleUrl>
        <Style>
          <IconStyle>
            <scale>1</scale>
            <Icon>
              <href />
            </Icon>
          </IconStyle>
          <LabelStyle>
            <color>FF000000</color>
            <labelSize>10</labelSize>
            <labelFont>Arial</labelFont>
          </LabelStyle>
        </Style>
        <ExtendedData>
          <SchemaData schemaUrl="ViperDataID">
            <SimpleData name="ViperType">MapPointText</SimpleData>
            <SimpleData name="ViperCoordinates">-114.85164691527,34.3866953464263</SimpleData>
          </SchemaData>
        </ExtendedData>
        <Point>
          <altitudeMode>clampToGround</altitudeMode>
          <coordinates>-114.85164691527,34.3866953464263</coordinates>
        </Point>
      </Placemark>

**Comment by mramato** [comment]
Thanks, but that snippet loads fine for me in Cesium and matches the output of Google Earth.  (It also generates some pop-up errors in Google Earth with error checking on).  What version of Cesium are you using?

**Comment by mramato** [comment]
Since we haven't heard back from you, we're going to close this PR.  Let us know if you are still having problems and can provide an example that we can reproduce with.  Thanks.

**Pull request closed without merging**
