### PR TITLE
Don't try to clone FormData

### PR DESCRIPTION
**Pull request by hpinkos**
For a `Resource`, `data` can be a `FormData` for something like uploading a file.  We shouldn't try to clone it into a generic object in this case.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hpinkos, thanks for the pull request! Maintainers, we have a signed CLA from @hpinkos, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
I don't think it makes sense to clone data at all, especially since it's not cloned in `clone`

**Comment by tfili** [comment]
I'm with @mramato that this shouldn't be cloned in the constructor or clone.

We may want to consider checking the `method` in the constructor and making `data` required if it is `POST` or `PATCH`. Then in `getDerivedResource` do we want to consider making data required in the same case. Is there a valid case where we would be sending the same data to multiple derived requests?

**Comment by mramato** [comment]
Maybe we just add post and patch functions similar to #6138 to `Resource` itself and pass the data into them instead of keeping it on the object?  Doesn't have to be this PR though, I would just remove the clone for now as the simple fix.

**Comment by tfili** [comment]
Fine with me.

**Comment by hpinkos** [comment]
@mramato ready

**Comment by mramato** [comment]
👍

**Pull request merged**
