### PR TITLE
Fix globe.pick for 2D/CV

### PR DESCRIPTION
**Pull request by hpinkos**
This makes `globe.pick` return a position in 3D coordinates instead of world coordinates based on the scene mode, which is what users are expecting.  We did a similar thing for `scene.pickPosition`.

This fixes imagery layer feature picking in 2D/Columbus View.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/globe-pick/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Another point of confusion:  The doc for `Globe.pick` says that `ray must be in world coordinates` but `Camera.getPickRay` does not create an array in world coordinates and is used to get a ray to pass to `Globe.pick` in a few places

**Comment by hpinkos** [comment]
@bagnell can you review please?

**Comment by bagnell** [comment]
The code looks good to me. Since this is a breaking change, are we sure we don't want to add a new function and deprecate the old one?

**Comment by hpinkos** [comment]
I think keeping it this way makes it consistent with what we did for `pickPosition` and I'm sure it's what users are expecting anyway.  I would guess pretty much anyone using `globe.pick` now thinks it's broken in 2D/CV instead of knowing it's in the wrong projection.  I can add a note to CHANGES though

**Comment by bagnell** [comment]
Since this has some of my code changes, someone else should review and merge. @mramato?

**Comment by hpinkos** [comment]
@bagnell this is ready

**Comment by mramato** [comment]
I'm only somewhat familiar with this code, but nothing jumped out as terrible to me.  If both @bagnell and @hpinkos are happy and this passes, one of you can just hit merge.

**Pull request merged**
