### PR TITLE
Master

### PR DESCRIPTION
**Pull request by vrittis**
Corrects issue #3588

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @vrittis!  Can you please send in a Contributor License Agreement as [described here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request) so we can review this?

**Comment by vrittis** [comment]
@pjcozzi Done

**Comment by pjcozzi** [comment]
Thanks @vrittis, we received it!

**Comment by mramato** [comment]
Thanks @vrittis.  I'm not sure why it was failing in IE to begin with, but I can definitely reproduce the problem and your fix is good.

**Comment by vrittis** [comment]
Nice! it took me a long time understanding why I couldn't get the test to fail under the chrome instance I was lauching jasmine in :crystal_ball:

**Comment by pjcozzi** [comment]
@vrittis can you please add yourself to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md?

**Comment by mramato** [comment]
Sorry, @pjcozzi, I already merged this and forgot to ask @vrittis to do that.  I'll add it myself in master.  Thanks again @vrittis

**Pull request merged**
