### PR TITLE
Enable four new ESLint rules

### PR DESCRIPTION
**Pull request by omh1280**
Add some rules that were likely lost during the transition from JSHint to ESLint. #5344 

These rules are the only of #5456 which do not require code changes in any way.

- [`guard-for-in`](http://eslint.org/docs/rules/guard-for-in)
- [`no-caller`](http://eslint.org/docs/rules/no-caller)
- [`no-floating-decimal`](http://eslint.org/docs/rules/no-floating-decimal)
- [`no-new`](http://eslint.org/docs/rules/no-new)

### CODE REVIEW

**Comment by omh1280** [comment]
@mramato I put these in Cesium's `.eslintrc.json`. Should they go in the shareable config instead?

**Comment by mramato** [comment]
Yes, they should go in the shareable config.  Also, create a 2.0.0 version in CHANGES.md for the shareable config and and add a line for each new rule.  Something like `Enabled guard-for-in.` where the rule links to esline like you did above.  When #5456 is done, we'll publish the new version.

**Comment by omh1280** [comment]
As it turns out, only one of these rules (`no-floating-decimal`) was not enabled by default.

**Comment by mramato** [comment]
Thanks.

**Pull request merged**
