### PR TITLE
fix large entities on terrain/GroundPrimitives crossing IDL in 3D

### PR DESCRIPTION
**Pull request by likangning93**
Part of #6951.

This doesn't fix the problem where ground primitives crossing the IDL are broken in columbus view and 2D, but that's going to be more complicated so I'll tackle that in a separate PR.

Give it a try [here](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fixGroundPrimitiveMaterialsIdl3D/Apps/Sandcastle/index.html#c=xVVtT9swEP4rVr80VYtbBmMblGqo6zY02CZA+1QJjHNNDI4d2U67MvHfd85Lm6YMCW3SXKmN7eeee3ku1zkzZC5gAYYcEwULMgYrsoT+yM+CNs+3Y60cEwpMu3M0VVM1RysD3DEVSZgoJ9wSzQseCn4vwFIWhsGvqSK4VuBDUp74xbU2oVDMgT2sHF9USDozOvkAkQGwwe6bAzrokb2B/96pdvt00Omt6RIkMoLJQ9KmtC8SFoHtF7TXZzrS12MttaF3adSuWXHJrBUzwZkTWl0tUyCrYMZbd/RqcnFxcvq1sH+cqsd1RXyoaiwMl/B8NVJthSdc+2EGayCY2tvIGhN95xN9PVgnqljiA2x/8s4IL7wxR2IQUezIQriY6MxJVKvKEqQUqfVWtdpbSMS5UNqc/BQWr/YGfqG3BoTdPQepSk7+V81jpkLZbN5L7otzmTIOkzkK8LkABaUknKGp9RylNbXgTlWauRPufQazTBUP4K07Vdm8P0Cl4u+lfmuVOapiGE0Fv5/k1dYiLKxpJbb351n6fXKzwXKDoklJboFkKoQZChcSMUMRDUl0hrph8ZV2RM8xTxcDiaS+BVqwITAosy5tgw3yTqcuus+A47WODEtjwTGBWgdWp3kPrlqywXe0ySZRJZeFsGY6Zy6mTlc9XHdHK/QWi1bRS2gqeJMH2xnb/3gdVZe8akAsvhwbkJ0tyAKs84hVUDtkvwEB1oB0NyBcK6txhEkdBTlbl7Tx083tiuatoF7AHDLEufZ2sCGXX2UwewcDNPebmptHfLV9fyBFHtCIPMVQxpr/7HiiOkM9lGcmVrWenuMvn+c+kV6hRS+PrFdoVx/nfzfW/8WoqVVp9Vi1nB9DvT8NnJzqbPLx6np8djr+Uo6rorwPWidXOmgUu3PU6rWG1i0ljAoH70WSYklIZmSAeTtIUukr27/N+D04ym0+wob9ymgYijkR4fG01fjTnraKKuDNLJPyUjzAtDUa9hG/YSY1Q/WibzhnJFt6SLw7OisOKaXDPm63rZzW8paZGuNv).

### CODE REVIEW

**Comment by hpinkos** [comment]
@likangning93 what's going on here?  This is from the example you posted.

image

**Comment by likangning93** [comment]
@hpinkos I think that's a result of `GeometryPipeline` splitting the shadow volume but still drawing both of them in the same call. Something similar happens in 1.45, which can be replicated in 1.48 by changing the classification type. [Here on 1.48](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVVtT9swEP4rVr80FcUtY4IBBQ1KB2gwJuj2qdIwzrXxcOzIdsrLxH/fOS9tkjImprlSG9vPPXf33OU6Z4bMBdyDIftEwT0ZghVpTL9nZ0GbZ9uhVo4JBabd2ZuoiZqjlQHumJpJGCkn3COa5zwU/F6ApSwMg18TRXAtwLukOPGLa21CoZgDu1s6viqRdGp0fAwzA2CDje0t2u+Szb7/Xi9372m/013SxUhkBJMLrqGW2tCj82+jCopLZq2YCs6c0Gr8mABZGqzc0aPL8Wlu/DxRz8v0fVxqKAyX8HrqibbCsy2dMIMJC6Y2ayliVjt0B7PaLnNSLPaxtU+8K8JzX8yRCMQscuReuIjo1EksTLswASlFYr1VRWYLsbgQSpvDB2HxarPvFyrYgLCfr0FKdUlD3pOr0ejL/9c3YiqUza685l6K64RxGM1R7NMcFBTyc4am1nMU1tSCO1NJ6g65dxhMU5U/gLfulCJ5f4BVib4WtVpWlGMNDKOJ4HejTFstwtyaloX1/jxLr0duaiw3WCIpyS2QVIUwxTKFREyxZIbEOsUqodRKO6LnmKeLgMykvgWasyEwKLIubIMaeadTLbHPgOO1nhmWRIJjApVuK0+zflu0X4Nvr84msUQuDWHJdMFcRJ0u+7XqjpboFRatZm+hKeFNHmxebPb9ZVRr5F0DYvFVqEHWVyD3YJ1HLIJaJ+8bEGANyFoNwrWyGmeT1LMgY1sjbfysZXZ585ZQX8AMMsCB9aFfK5dfRTCbW30095uKm2d8kX1/IEUW0AF5iaGINftZ90RVhmoor0yncr08oN8+qH0i3bwW3Syybl676pz+y7y+Gh2/AP7nsVJRZPFYtpcfOd0/DZeM53z0afxjeH42/FyMplzKJ63jsQ4awtYg8OBAheU7nB/mmzNlExRPmwvxILIXr9VtDax7lHCQx/VRxAmqRlIjA0p7DuJEevF7tym/A0e5zXwNeqXRIBRzIsL9Savxhz1p5crhzTSV8lo8waR1MOghvmYmNcMCzy5xFEn26CHRxsF5fkgpHfRwu2rltJa3zFQYfwM). It also doesn't happen when `scene3DOnly` is set to `true`.

Might need to discuss with @bagnell what we can do about this... adjusting the shadow volume height should help a bit in the meantime though.

**Comment by bagnell** [comment]
The problem with the screen shot is that the volumes are split but not closed. If you split the volume and close both on each side of the IDL, it should be fine.

@likangning93 Can you add this? In GeometryPipeline, the triangles are split. Can you keep track of the new vertices added. Then you can project the vertices onto the plane of the IDL and triangulate. Then, add the new indices to the split geometry.

**Comment by hpinkos** [comment]
@likangning93 here's the issue for seeing that seam when ground primitives cross the IDL: #4746

**Comment by bagnell** [comment]
This looks good. I'll merge. Don't forget about the other two PRs :smiley:

**Pull request merged**
