### PR TITLE
Allow datasources with billboards, labels, and/or points to be re-added

### LINKED ISSUE #4409: Unable to re-add datasource
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Yo_dyrt43B8

1. Click `add` to add the datasource
2. Click `remove` to remove it
3. Click `add` to add it again.  The app crashes with `cannot set property 'id' of undefined`

`DatasourceCollection.remove` has `destroy=false` by default, so I couldn't find any reason why you shouldn't be able to do this

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas
};
var kml = '../../SampleData/kml/facilities/facilities.kml';
var ds;

ds = new Cesium.KmlDataSource(options);
ds.load(kml, options).then(function() {
    console.log('loaded' + ds.entities.values.length + ' entities');
});

Sandcastle.addToolbarButton('add', function() {
    viewer.dataSources.add(ds);
});
Sandcastle.addToolbarButton('remove', function() {
    viewer.dataSources.remove(ds);
});
```

### PR DESCRIPTION
**Pull request by twpayne**
This is an attempt to fix #4409.

The underlying problem seems to be:

* When the data source is first added, a new `BillboardCollection` is created and a `_billboardIndex` property is added to each entity to store its index in the collection.
* When the data source is removed, the `BillboardCollection` is destroyed. However, the `_billboardIndex` properties are *not* cleared from the entities.
* When the data source is re-added, a new `BillboardCollection` is created for the first entity, but for the next entity its`_billboardIndex` property is read. This refers to a non-existent index. When we look up this non-existent index in the collection we get `undefined`.

The fix proposed here is to track the `BillboardCollection` in the entity as well as the entity's index in that `BillboardCollection`.

Similar code is required for the `EntityCluster`'s `LabelCollection` and `PointCollection`.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Are we sure we want the additional index checks in the primitives?  We don't do array bounds checks throughout Cesium, e.g.,

* https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/PrimitiveCollection.js#L343-L351
* https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ModelAnimationCollection.js#L303-L311

Perhaps consider this part of the PR later across all of Cesium (or even just all collection types) if we decide on that direction.

**Comment by twpayne** [comment]
> Are we sure we want the additional index checks in the primitives?

In this particular case, they would have caught this problem earlier, but I agree that they're probably overkill. I've reverted that commit.

**Comment by pjcozzi** [comment]
Sounds good.

Can you add unit tests and update CHANGES.md?

@mramato do you want to review?

**Comment by twpayne** [comment]
> Can you add unit tests and update CHANGES.md?

Done.

**Comment by mramato** [comment]
> @mramato do you want to review?

Yes, I'd like to look at this.  Will do so in a moment.

**Comment by twpayne** [comment]
I had a look at ways of removing `_pointIndex`, `_billboardIndex`, and `_labelIndex` from the entity when then data source was removed (and the underlying `BillboardCollection` consequently being destroyed), but I couldn't find a suitable hook point. Maybe I missed it. In any case, I think the extra protection offered by this PR is still worthwhile, but feel free to ignore it :)

**Comment by mramato** [comment]
In general, extra protection usually means that we end up hiding bugs rather than fixing them at the source, so the Cesium way is to fail as early as possible.

The hook point you might have overlooked is the `destroy` method on `BillboardVisualizer`, `LabelVisualizer`, and `PointVisualizer`.  In each, you would need to iterate over the `entityCollection.values` array and call `removeLabel`/`removePoint`/`removeBillboard` for each depending on the visualizer

**Comment by twpayne** [comment]
Thanks for the pointers! I'll close this PR and work on a new one.

**Pull request closed without merging**
