### PR TITLE
Geocoder lon lat bug

### PR DESCRIPTION
**Pull request by WilliamKHo**
For #4713. Extended our `CartographicGeocoderService` to evaluate queries for NSEW coordinates (i.e. "39N 75W" or "20.5E 60N"). This fixes the problem of replacing cartographic queries with incorrectly formatted coordinates in the geocoder. To review: code addition and new tests.

### CODE REVIEW

**Comment by hpinkos** [comment]
This looks great @WilliamKHo, thanks!  Can you just add a comment to `CHANGES.md`?

**Comment by lilleyse** [comment]
@WilliamKHo - just a reminder to update `CHANGED.md`

**Comment by WilliamKHo** [comment]
Hi please review. Sorry about that delay my email filter was not doing what it was supposed to.

**Comment by hpinkos** [comment]
Great @WilliamKHo, thanks!   Please make a comment on the forum post linked in #4713 that this has been fixed and will be included in the next release

**Pull request merged**
