### PR TITLE
Raise error event for network link failure

### LINKED ISSUE #5921: Better KML Network Link Error Handling
In #5871 we added a catch when a network link fails.  This makes it impossible to detect and handle errors programmatically.  We might want to consider adding support for a callback when a network link fails.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #5921

We raise the error event in other places, but we missed this one.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hpinkos, thanks for the pull request! Maintainers, we have a signed CLA from @hpinkos, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@thw0rted does this fix the problem you saw?

**Comment by thw0rted** [comment]
LGTM

**Comment by hpinkos** [comment]
@jburr-nc this change doesn't change anything about the way KML currently loads.  The only difference is that the error event will be raised in the event of a network link failure.  You would only see different behavior in your app if you are listening to the error event.

I thought we fixed the problem where a datasource wouldn't load when an image for a billboard failed.  I couldn't find the pull request related to that though.  If you have an example KML where that happens, let me know and I can write up a new issue.

**Pull request merged**
