### PR TITLE
Remove createLensFlarStage

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/6843

@hpinkos Can you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/remove-in-1.49/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@ggetz add a comment to breaking changes

**Comment by ggetz** [comment]
Thanks @hpinkos, updated.

**Comment by hpinkos** [comment]
👍

**Pull request merged**
