### PR TITLE
Fixed issue where we constantly fail to load the same image.

### LINKED ISSUE #6567: KML Image Overlays crash Cesium and Browser
Cesium version 1.44 and 1.45 crash when loading KML files with image overlays.  Files load fine, are displayed on map, then performance slows to a crawl ending with either WebGL crashing or the entire browser crashing. Crash typically happens around 10-30 seconds after file is displayed.

Tested Systems affected: 
Windows 7 64bit (6 core i7, 16GB RAM, SSD, NVIDIA Geforce 750GTX 2GB) on latest Google Chrome and Firefox - WebGL crash
Xubuntu 16.04 with Firefox - Browser crashes
Android with Firefox and Chrome (browser fully crashes)

EXAMPLE KML(s)
Cooperative Institute for Meteorological Satellite Studies (CIMSS) North Atlantic Infrared - NHC Enhancement **MULTIPLE IMAGE OVERLAY, ANIMATION**
[http://climateviewer.org/index.html?layersOn=cimss-irnhc](http://tropic.ssec.wisc.edu/real-time/atlantic/movies/kml/tiles/RT.atlantic.g8irn.tiles-8.kml)
live example:
[http://climateviewer.org/index.html?layersOn=cimss-irnhc](http://climateviewer.org/index.html?layersOn=cimss-irnhc)

Three Mile Island Meltdown **SINGLE IMAGE OVERLAY**
[http://climateviewer.org/layers/kml/pollution/nuclear/Three-Mile-Island-meltdown-Climate-Viewer-3D.kmz](http://climateviewer.org/layers/kml/pollution/nuclear/Three-Mile-Island-meltdown-Climate-Viewer-3D.kmz)
live example:
[http://climateviewer.org/index.html?layersOn=tmi-fallout](http://climateviewer.org/index.html?layersOn=tmi-fallout) 

ERROR:
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at f (http://climateviewer.org/lib/cesium/1.45/Cesium.js:20:432415)
    at y (http://climateviewer.org/lib/cesium/1.45/Cesium.js:20:435552)
    at d._bind (http://climateviewer.org/lib/cesium/1.45/Cesium.js:20:436567)
    at V (http://climateviewer.org/lib/cesium/1.45/Cesium.js:21:114519)
    at k.draw (http://climateviewer.org/lib/cesium/1.45/Cesium.js:21:118172)
    at n.execute (http://climateviewer.org/lib/cesium/1.45/Cesium.js:20:405485)
    at Ue (http://climateviewer.org/lib/cesium/1.45/Cesium.js:22:410268)
    at ze (http://climateviewer.org/lib/cesium/1.45/Cesium.js:22:411639)
    at We (http://climateviewer.org/lib/cesium/1.45/Cesium.js:22:415891)
    at Ke (http://climateviewer.org/lib/cesium/1.45/Cesium.js:22:420206)
x.showErrorPanel @ Cesium.js:23

PLEASE, either tell me what I am doing wrong or that this can be fixed ASAP.
I recently update my website from 1.39 to 1.44 and that is when this issue started. I rely on many meteorological KML files from government and universities and they use KML groundoverlays for this real-time data. 
 [ClimateViewer 3D](http://climateviewer.org/)
kml-overlay-crash

### PR DESCRIPTION
**Pull request by tfili**
Fixes #6567 

Can easily be tested with the following. Before this fix it tries to load `etna.jpg` hundreds of times.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas
};

viewer.dataSources.add(Cesium.KmlDataSource.load('https://gist.githubusercontent.com/shunter/03d24977213616ae9992f443d3c051ea/raw/6d2aeffc8e667b9100a2875388d19e9c64b945fd/KML_Samples.kml', options));
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@tfili, thanks for the pull request! Maintainers, we have a signed CLA from @tfili, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@tfili is there a good way write a unit test to make sure the material only tries to load the resource once?

Other than that this change looks fine to me

**Comment by tfili** [comment]
> @tfili is there a good way write a unit test to make sure the material only tries to load the resource once?

It doesn't look like it. It'll be pretty difficult and a ton of mocking to test this. I don't think it's worth the time it'll take.

**Comment by hpinkos** [comment]
Thanks @tfili

**Pull request merged**
