### PR TITLE
#6768 adding a Plane geometry spec

### PR DESCRIPTION
**Pull request by baloola**
Hi there, I added a unit test for planeGeometry base on @hpinkos instructions #6768.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @baloola! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/planeGeometry_spec/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks @baloola!  We've received your CLA.  This looks good to me, but I'll wait to merge until after the release goes out today.

**Comment by hpinkos** [comment]
Looks great, thanks @baloola!

**Comment by baloola** [comment]
Thank you Hannah, I'm glad to do a tiny help :)

**Comment by hpinkos** [comment]
Yes! All contributions are greatly appreciated.  Having more complete unit tests is always a win!  Hope to see more contributions from you in the future =)

**Pull request merged**
