### PR TITLE
Moon Z fix

### PR DESCRIPTION
**Pull request by kainino0x**
For issue #1964.

The `// XXX` parts need work because I don't know how to do things correctly. @pjcozzi

### CODE REVIEW

**Comment by pjcozzi** [comment]
@fstoner @bagnell this may create a minor merge conflict when merged into your branches.

**Comment by pjcozzi** [comment]
For future reference, if you are trying to find the moon, put this code at the top of the Sandcastle example:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer' ,{
    sceneModePicker : false
});
var globe = viewer.scene.globe;
globe.enableLighting = true;

var clock = viewer.clock;
clock.multiplier = 3 * 60 * 60;

var position = Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883);
var primitives = viewer.scene.primitives;
var collection = primitives.add(new Cesium.PolylineCollection());
var polyline = collection.add();

var transformMatrix = new Cesium.Matrix4();
var toMoon = new Cesium.Cartesian3();

clock.onTick.addEventListener(function() {
    var time = clock.currentTime;
    Cesium.Transforms.computeTemeToPseudoFixedMatrix(time, transformMatrix);
    Cesium.Simon1994PlanetaryPositions.computeMoonPositionInEarthInertialFrame(time, toMoon);
    Cesium.Matrix3.multiplyByVector(transformMatrix, toMoon, toMoon);
    polyline.positions = [position, toMoon];
});
```

**Comment by emackey** [comment]
I suggest adding one line to the bottom of the above example:

```
viewer.scene.camera.frustum.far = 1e10;
```

**Comment by pjcozzi** [comment]
@kainino0x can you merge in master from the main Cesium repo so github can auto merge this?

Please comment in this PR when it is ready.

**Comment by kainino0x** [comment]
I rebased rather than merging, is that okay? (Didn't think about it - easy to revert though.) It can be auto merged now.

**Comment by pjcozzi** [comment]
Yes, thanks!

Congrats on your first pull request.

**Comment by pjcozzi** [comment]
Also, we pretty much always delete branches once we merge a pull request using the GitHub option in the pull request.

**Pull request merged**
