### PR TITLE
Update PerformanceDisplay MS reading less frequently

### PR DESCRIPTION
**Pull request by hpinkos**
To make the millisecond print out a little easier to read, I changed it so that it updates every 200ms instead of every frame

### CODE REVIEW

**Comment by emackey** [comment]
This just shows the most recent ms reading every so often.  Can you instead show the average ms/frame over the timespan, like fps does?

**Comment by emackey** [comment]
But otherwise :+1: for fixing this, it was bugging me just today.

**Comment by hpinkos** [comment]
@emackey ready!

**Comment by emackey** [comment]
Apologies for bikeshedding, but the differing rates don't work for me at all.  Let's just use a single 500ms timeout instead of dual timeouts.  It will make the logic a bit lighter and the updates can happen in unison so they are less distracting.

**Comment by hpinkos** [comment]
The current implementation has different rates. 
I think keeping fps updating every second makes sense.  I initially started out having the ms update at that rate as well, but I thought it made more sense to have it update more frequently since it's measuring milliseconds.

**Comment by hpinkos** [comment]
I'll also note that I like the 'feel' of the number changing quickly.  It makes it seem like it's working better or something.  I purposely went for a rate so the number updated quickly but not too quick to actually read the value.

**Comment by emackey** [comment]
OK

**Pull request merged**
