### PR TITLE
Add karma edge launcher. Allows --browsers Edge now

### PR DESCRIPTION
**Pull request by shehzan10**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Could you update https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide#run-tests-with-a-specific-browser-or-browsers with the available browsers?

**Comment by pjcozzi** [comment]
@mramato do you want to look at this?

**Comment by shehzan10** [comment]
> Could you update https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide#run-tests-with-a-specific-browser-or-browsers with the available browsers?

Thanks for the suggestion. Just did.

**Comment by mramato** [comment]
Thanks.  Last time I looked the Edge launcher wasn't quite ready but it looks like they've made a lot of progress.

**Pull request merged**
