### PR TITLE
Display x y tiles on separate lines

### PR DESCRIPTION
**Pull request by chriswingler**
This is a fix for https://github.com/AnalyticalGraphicsInc/cesium/issues/8058 

@OmarShehata approved this change here:
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/1rCMQGuwM-I

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @chriswingler!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/8058-display-x-y-tiles-on-separate-lines/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by chriswingler** [comment]
Update: Looks like it's not working with IE11.  I'm going to do a little investigating.

**Comment by OmarShehata** [comment]
Thanks for this fix @chriswingler ! I haven't tested it out yet - what does it look like in IE11? Or does it not display at all?

**Comment by chriswingler** [comment]
> Thanks for this fix @chriswingler ! I haven't tested it out yet - what does it look like in IE11? Or does it not display at all?

@OmarShehata maybe I forgot to save, but it's working now in IE11.  This PR is ready for review.

**Comment by hpinkos** [comment]
Looks great @chriswingler, thanks!

image

I'll merge as soon as CI passes

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/1rCMQGuwM-I

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/8131 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by chriswingler** [comment]
Thank you @hpinkos !

**Pull request merged**
