### PR TITLE
Optional result parameter to Color.fromHsl and Color.fromCssColorString

### PR DESCRIPTION
**Pull request by ggetz**
Added optional `result` parameter to `Color.fromHsl` and `Color.fromCssColorString` and added tests to check the result is modified.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Could you also update `Color.fromRgba`?  For an example of how to test these, see https://github.com/ggetz/cesium/blob/color-result-parameters/Specs/Core/Cartesian3Spec.js#L50-L55

**Comment by ggetz** [comment]
Updated.

**Comment by pjcozzi** [comment]
@lilleyse do you want us to wait until after the 1.19 release to merge this?  Doesn't matter to me, there is no rush here.

**Comment by lilleyse** [comment]
It's fine to merge this.

**Comment by pjcozzi** [comment]
:+1:

**Pull request merged**
