### PR TITLE
Update CLA instructions

### PR DESCRIPTION
**Pull request by OmarShehata**
I think we're ready to debut the new CLA system. Instead of having to fill out and email us a PDF, new contributors can now just fill out a Google Form. This is also going to be significantly easier for us to maintain since it's much more automated now.

@pjcozzi let me know what you think of the wording. Feel free to test fill-out the form(s) too. I will merge this Monday morning if all looks good to coordinate the Concierge deploy to switch over to this. Any contributors that are waiting to sign a CLA can go ahead and fill out this new form now.

TODO:

* [x] Update the links on [Contributors.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md)
* [x] Remove the cla.txt currently linked there ^ 
  * Each signer automatically gets a copy of what they signed in their email, and we do keep a PDF copy of each version of the form in case we update it in the future for any reason, so I think this is OK.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/new-cla/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by pjcozzi** [comment]
I didn't test the forms but this all looks OK to me.  Please confirm that there was no material changes to the CLAs.

Also, perhaps consider making this in the corporate agreement two separate forms:

> Point of contact name & title

Perhaps someone else should test and merge?

**Comment by OmarShehata** [comment]
> Please confirm that there was no material changes to the CLAs.

I can confirm a diff shows the only changes are `AGI` -> `Cesium` (it's defined at the top that Cesium refers to Cesium GS), and `You` & `Your` becoming `you` & `your` when not at the beginning of a sentence). 

> Also, perhaps consider making this in the corporate agreement two separate forms:

Done.

> Perhaps someone else should test and merge?

@mramato since you're familiar with the details of the new system, do you mind filling out both forms and merging? I should get an email notification when you do. 

* [individuals](https://docs.google.com/forms/d/e/1FAIpQLScU-yvQdcdjCFHkNXwdNeEXx5Qhu45QXuWX_uF5qiLGFSEwlA/viewform)
* [corporations](https://docs.google.com/forms/d/e/1FAIpQLSeYEaWlBl1tQEiegfHMuqnH9VxyfgXGyIw13C2sN7Fj3J3GVA/viewform)

**Comment by mramato** [comment]
@OmarShehata I filled out both forms, please let me know if you are happy the the results. (I assume you also want to undo whatever extra changes filling everything out did).

**Comment by OmarShehata** [comment]
Yes, all looks good! I undid it for both forms. Please merge if you're happy with the wording on everything. @mramato

**Comment by mramato** [comment]
> `You` & `Your` becoming `you` & `your` when not at the beginning of a sentence

Is this okay, legally speaking?  I assume they were capitalized before for a reason?

**Comment by mramato** [comment]
Once the form is done we say something like "You an go ahead and notify".  Perhaps make this more specific/direct.  Something like:

> Leave a comment on any pending pull requests notifying us that you have signed the CLA

It shouldn't be optional.

**Comment by mramato** [comment]
That's the only comment/questions I have.

**Comment by OmarShehata** [comment]
> Once the form is done we say something like "You an go ahead and notify". Perhaps make this more specific/direct. Something like:

Updated!

> Is this okay, legally speaking? I assume they were capitalized before for a reason?

I was wrong, looks like it is still capital in all cases when it's used as the legal definition at the top. I'm having someone on the contracts team double check this now and will merge.

**Pull request merged**
