### PR TITLE
Remove model update height callback on destroy

### PR DESCRIPTION
**Pull request by hpinkos**

### CODE REVIEW

**Comment by ggetz** [comment]
@hpinkos Looks good to me, does this warrant a change to CHANGES.md?

**Comment by hpinkos** [comment]
I didn't think it needed a line in CHANGES because there wasn't a user reporting the problem and I'm not sure this was causing issues for anyone, I just noticed this needed to be cleaned up.

**Comment by ggetz** [comment]
OK, sounds good. 👍

**Comment by pjcozzi** [comment]
Thanks!

**Pull request merged**
