### PR TITLE
Added useDepthPicking flag from 3d-tiles

### PR DESCRIPTION
**Pull request by lilleyse**
Cherry-picked 312fecca4f67805dd482b6370733d5a6d102561c and 66a9da108f8b48a64f0f538eeac7bbb8fc1ba198 into master, allowing you to set a `useDepthPicking` flag in `Scene`.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Update CHANGES.md.

Remind me what the use case - pick mouse over picking for point clouds was slow?

**Comment by lilleyse** [comment]
Yes it seems like that was the reason.

**Comment by pjcozzi** [comment]
OK, update CHANGES.md and we'll merge.

**Comment by lilleyse** [comment]
Updated.

**Pull request merged**
