### PR TITLE
uniformState.inverseTranposeModel -> uniformState.inverseTransposeModel

### PR DESCRIPTION
**Pull request by imsoalan**
Fixed return on line 2132 - uniformState.inverseTranposeModel to 'TransposeModel'

### CODE REVIEW

**Comment by lilleyse** [comment]
For #3942

**Comment by lilleyse** [comment]
Hi @imsoalan 

Make sure you also change the spelling error in `UniformState`.

**Comment by pjcozzi** [comment]
Thanks for this contribution, @imsoalan.  Can you please submit a [Contributor License Agreement (CLA)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can merge this when ready?  Let me know if you have any questions.

**Comment by pjcozzi** [comment]
@imsoalan can you please submit a [Contributor License Agreement (CLA)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can finish reviewing this?

**Comment by imsoalan** [comment]
I filled that out quite a bit ago.

**Comment by pjcozzi** [comment]
Ah, yes, thanks I see that we received it.

Did you do a global search for the misspelling and see @lilleyse's comment, https://github.com/AnalyticalGraphicsInc/cesium/pull/3943#issuecomment-221267974?

**Comment by lasalvavida** [comment]
I think this was fixed by @andyfry01 in #4115, so this should be safe to close.

**Pull request closed without merging**
