### PR TITLE
Update KmlDataSource.js (processLookAt)

### PR DESCRIPTION
**Pull request by jaforom**
The `tilt` variable is in radians, so `90.0` must be `Cesium.Math.PI / 2`

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@jaforom, thanks for the pull request! Maintainers, we have a signed CLA from @jaforom, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by ggetz** [comment]
Thanks @jaforom! It looks like you have some build errors, see the [log](https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/306288263?utm_source=github_status&utm_medium=notification). We need to get those fixed and the build passing before we can merge,

**Comment by hpinkos** [comment]
Thanks @jaforom!  This change looks good.

Can you update this unit test to confirm that `entity.kml.lookAt` has the correct values for `position` and `headingPitchRange`? https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/DataSources/KmlDataSourceSpec.js#L4254-L4274

Also, please add a comment to `CHANGES.md` about your bug fix. Thanks again!

**Comment by hpinkos** [comment]
In the interest of getting this merged in before the next release, I went ahead and added the unit test.

Thanks for the contribution @jaforom! 

Fixes #5992

**Pull request merged**
