### PR TITLE
TerrainOffsetProperty was not being cleaned up

### PR DESCRIPTION
**Pull request by tfili**
`GroundGeometryUpdater` didn't have it's own destroy method, it's `_terrainOffsetProperty` was never getting destroyed. This would leave a bunch of listeners for `scene.terrainProviderChanged` and `scene.morphComplete`.

This change adds a `GroundGeometryUpdater.destroy` method that destroys `_terrainOffsetProperty` and then calls `GeometryUpdater.destroy` like it used to.

Added a test to make sure it's all wired up correctly.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @tfili!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/cleanup-terrainOffsetProperty/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by tfili** [comment]
Also discovered the `GeometryVisualizer` wasn't calling destroy on it's updaters, so entities from Datasources weren't getting cleaned up at all.

**Comment by mramato** [comment]
@tfili update Changes and be sure to specifically mention fixing memory leaks when removing entity geometry (or whatever else caused it).

**Comment by mramato** [comment]
Perhaps fixes #5662?

**Comment by tfili** [comment]
@mramato Updated

**Comment by mramato** [comment]
Thanks @tfili!

**Pull request merged**
