### PR TITLE
Update to knockout 3.4.2

### PR DESCRIPTION
**Pull request by hpinkos**
Knockout fixed some bugs and performance issues.  I tested all of our widgets and nothing seems like it needed to be changed.

### CODE REVIEW

**Comment by mramato** [comment]
We usually update CHANGES for this kind of stuff (not sure why the concierge hasn't kicked in yet).

**Comment by mramato** [comment]
Also update LICENSE because the copyright has changed.

**Comment by hpinkos** [comment]
@mramato ready

**Comment by mramato** [comment]
👍 Thanks.

@ggetz if the concierge doesn't post to this PR by the time you read this, it might be a good idea to try and figure out why.  (This is the first time I've seen it not post to a PR).

**Comment by mramato** [comment]
I'll merge this as soon as the tests pass.

**Pull request merged**
