### PR TITLE
prevent colorToAlpha from carrying over from one imagery layer to its replacement

### PR DESCRIPTION
**Pull request by likangning93**
https://github.com/AnalyticalGraphicsInc/cesium/pull/7727 had a funny bug where switching an imagery layer with color-to-alpha out and _not_ setting color-to-alpha on the new layer would retain the color-to-alpha settings from the previous layer.

This PR always sets the value in the color-to-alpha uniform to a value that won't cause any change, regardless of whether it's used or not.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @likangning93!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/colorToAlpha/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by likangning93** [comment]
Bug introduced in this release, so no CHANGES update.

**Comment by likangning93** [comment]
@bagnell there might be one more thing, will bump when ready.

**Comment by likangning93** [comment]
@bagnell ready!

**Comment by bagnell** [comment]
Thanks for catching these.

**Pull request merged**
