### PR TITLE
Update docs: `PerInstanceColorAppearance` vertex format and other primitive API stuff

### PR DESCRIPTION
**Pull request by nmschulte-aviture**
I believe `FLAT_VERTEX_FORMAT`'s documentation is supposed to read "when `true`", not "`false`".

---
As well, the documentation for `VERTEX_FORMAT` mis-matches the code; I've included a documentation change to make them match.

See also #8045; a bug moved from this PR.

---
CLA is signed and `CONTRIBUTORS.md` is already updated:
https://github.com/Aviture/cesium/blame/fix-perinstancecolorappearance-doc/CONTRIBUTORS.md#L69

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @nmschulte-aviture! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Aviture/cesium/blob/fix-perinstancecolorappearance-doc/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-perinstancecolorappearance-doc/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte-aviture! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte-aviture! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks @nmschulte-aviture!

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @nmschulte-aviture! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request merged**
