### PR TITLE
Renamed dataSource to dataSourcePromise

### PR DESCRIPTION
**Pull request by kilarusravankumar**
renamed dataSource a promise to dataSourcePromise

### CODE REVIEW

**Comment by emackey** [comment]
Hey, thanks @kilarusravankumar!  If you haven't already, can you [email us a CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)?

Also, I notice that the modified HTML has been through what looks like auto-formatting.  These examples all load and re-save from our "Sandcastle" web application, which can be a little twitchy about loading HTML that has been formatted differently from what the app itself saves out.  So, I recommend against external changes to formatting in Sandcastle gallery examples.  One thing you can try is to load each of these into your local copy of Sandcastle (under Apps), and use the "Save as" button from inside the app to save a new copy of the file, this will guarantee the correct formatting.

**Comment by pjcozzi** [comment]
We now have a CLA from @kilarusravankumar, thanks again for the contribution!

**Comment by emackey** [comment]
Great, thanks @kilarusravankumar!  Two last things:

* There's still a lot of whitespace noise in `CZML Box.html`, can that be fixed?  The other files are perfect.

* Please add yourself to the end of `CONTRIBUTORS.md` in the root folder (it's in chronological order).

Thanks!

**Comment by kilarusravankumar** [comment]
Fixed white space. sorry, about that. Please, check now.

**Comment by emackey** [comment]
It looks like `CONTRIBUTORS.md` was checked in but the whitespace fix didn't get submitted, can you check again?  Thanks!

**Comment by kilarusravankumar** [comment]
fixedwhite spaces in CZML box.html

**Comment by emackey** [comment]
Thanks @kilarusravankumar!

**Pull request merged**
