### PR TITLE
Fix translucent picking

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/7032

This was a regression from https://github.com/AnalyticalGraphicsInc/cesium/pull/6957 at this commit https://github.com/AnalyticalGraphicsInc/cesium/pull/6957/commits/259c314ea47654309433b979339396bd72032179. That turned off translucent object sorting during the pick pass. I must have been thinking pick commands wrote depth but they currently don't.

One fix is to revert that commit, the other is to write depth for pick commands. This PR does the second. I like the second way because it makes the pick pass more accurate for overlapping primitives, and allows pick functions to get a pick id and the pick position in the same pass, which I'm trying to do to optimize the pick-from-ray functions. It does break some `PrimitiveCollection` tests where it expects primitives added at the same spot to be picked based on the order they were added. I'm not sure if this is the test being too strict or actually important behavior to preserve. @bagnell do you know?

~~Only broken in master so no CHANGES.md update needed.~~
Edit: does happen in earlier versions of Cesium. Needs CHANGES.md update.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/translucent-pick-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
To add to above, this will probably create a lot of z-fighting while picking overlapping primitives on the surface which will lead to inconsistent pick results. I might have to rethink this approach.

**Comment by lilleyse** [comment]
Actually ruled out z-fighting as a problem. However I still need to figure out why picking and rendering produce different results as to the primitive in front, since both passes write depth now.

[Debugging demo](http://localhost:8080/Apps/Sandcastle/index.html#c=lVXfb9owEP5XPF5IJGpge9jU0mqIwYbG1KpF1aQxVSY5wJtjR7aTjk387zs7PwgZfVgeTOK7++78fXcmZ5rkHJ5Bk2si4ZlMwPAsoY9+L+hG/nOipGVcgu72yJ+VJPgoHYOeyxhSwEXapWbSiCwCGe3JJdkwYQDdVvIQXq1kjmkM2gCzFOmo/yxNqeYJtzwHg3ZvoMct9Cm8NESWya1wIGWZ99UW3WiVfICtBjDBxbsBHfTIa79evPU/b3ANPdQmk5HlSpJIA7NQQwQa4h5xCLJHdsC3OxtWpy3Sx7XvXBp8ieCUtI+gErB6X1mDMto929KG3DQiasAqtBninuOZL4/vvVOfHLSFXzOlE2bRrYS+c/IUdUyUUHqcpsC0+6SP0/vl9OvT7Pb+y3h5xDqEDWBmrebrzIK5JK2aIgdX5/Hg7ZOPq2ivi3cJGscuNpp8e42GKFHYqKd4PRSyFWzYTMtGu1AWx03gu8pyjvqqOIMkfTun5vfm+Wu6ThV7mda2dLaeCKeK1Vlbt0goA3Fpe0kGs5fRTiupMlONVUWL4+VQDUc6wF5sd/TQsVo2vncannGqqUendEAlS1xbd+949BOrQ4Jx3XBtLHGKhV3nNjzvZiBSMiaBF9V7Yt5q3N3eQ8oimOZIyScmY+H2wc5lmtmxn8mgHk4lF7CxE4HwQaJySDCmHkc/j6nPPMPDZLp9r9C0GUdTZbhDdUf08XxDglelojFs8GqLgxO8MDzp+n6fSGV3XG7LtA1b0ZQV8qGqsFmNdnekDur0rny1/oES/F/dyK5ReNkJtQ2K+OM96RXxLdGrevWhxflynwJdTGfLp8liPvkcXnV6nZGxewE3Bf57nqRKW5JpEVDat5CkAnvF9NcZHtrSyBiXYdSvgkYxzwmPr1ed1h/FqoPtzYxByyYT4oH/hlXnZtRH/5MwoViMrN7iHSbY3rnshjeLYpNSOurj579RVimxZrqB+Bc)

**Comment by lilleyse** [comment]
Ignoring the case where the primitives completely overlap, which has it's own sort of behavior, this is the problem with turning depth mask on for translucent primitives in the pick pass. Drawn as opaque rectangles, but image this is the pick pass:

picking-z-fighting

So the best change is to revert to the old behavior. I'll need to think of ways to work around this in https://github.com/AnalyticalGraphicsInc/cesium/pull/6934.

**Comment by lilleyse** [comment]
But then again master has it's own set of bugs because it doesn't write depth in the pick pass.

The green rectangle is 10000 meters above the red rectangle but the red gets picked if the red primitive's bounding sphere is closer to the camera. That almost seems worse than the z-fighting which can be remedied fairly easily by setting one rectangle's height slightly higher than the other.

pick


[Demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=hVVtb9MwEP4rVr80kYL7gibQ1k2UssFE0aatmpAomrzk2lo4drCdjoL63znHSZpkG+SDm/junrt7nrO7ZZpsOTyCJqdEwiOZgeF5Su+KvaAfF58zJS3jEnQ/In+WkuAzGCidgL6UCWSAi7QLzaQReQwy3pFjsmLCwFLuw5Ol3GIWgwbAJD4bLT5LU6Z5yi3fgkF7YaCHLfTxXhpiy+RawAi9yjJvqj260ir9AGsNYIJXb4d0GJFxsb56U/y8xrUqpUYa/x/pyAWPjjxS8TM+8khLucplbLmSJNbALNQQQZ0gwlxJRByYjMiDyHHH1jzZiGyArzc2rFj11SU10qU0+BJDW5yPoFKweldZgzLaPevShgo0ImrAKrQZ4p66Yow7VN/22YK28OtC6ZRZdCuhr90Q+DpmSig9zTJg2n3Su/ObxfnX+4urmy/TRQfMN44w/uVg3IcNT2at5g+5BXNMOhXHLlldRZG6y8u0ii40LVyCBil+46lAI9Q3bBTkX/dec0+WzbVsjC1lSdJEvq4szylTVWew+W/Pif29SUDNZlvQl1nvKtsYN4RoDl+HT6EMJIeD+7weZifjjVZS5abtug8dP3tH0VLeMpnEzFg8TcjMQinxwPT73Folg/40SYjK2M8ciCOf2A1IL0CI10t1poLWmciGeAJePGWjQrOIDOvF6kLIIT6urBpm9C+YcRk86sCMmzDZkEqWugPZv+bxD6wfO8R1xbWxRUNhv3IdPe9qIFYyIUHZ80l5SeLdVF2NznCbsRjOtyjUJ2RTuH2wlzLL7dQTVN8+Ss5hZWcCcwSp2kKKMW32iuwX2Hauu1cwzZphNFOGO9CqXb4iQTlyCazwLyAJWmhh2DyX2JdRKLpQ67bb4T4vKKnQcVz2UTXSt522F7sM6Pz8YnE/m1/OPocnvag3MXYn4MxHv+NpprQluRYBpQMLaSZQWTN4yDG1pbExLtFkUAVNEr4lPDld9jp/a8sejj8zBi2rXIhb/huWvbPJAP1bYUKxhMv1Fd6Egu2cy2Z0NveblNLJAD+fRlk//w3Evw)

**Comment by lilleyse** [comment]
@bagnell Updated CHANGES.md

**Pull request merged**
