### PR TITLE
Fix KML example error

### LINKED ISSUE #4063: KML Sandcastle example throws exception
@tfili can you look at this before the 1.23 release on Friday?

Open `http://localhost:8080/Apps/Sandcastle/index.html?src=KML.html&label=All` and select `KMZ with embedded data - GDP per capita` from the dropdown.

image

### PR DESCRIPTION
**Pull request by tfili**
Fixes #4063.

### CODE REVIEW

**Comment by mramato** [comment]
Unit test?

**Comment by pjcozzi** [comment]
@mramato please merge when ready.

**Comment by tfili** [comment]
@mramato My bad. I was rushing. Should be good now.

**Comment by mramato** [comment]
Thanks.

**Pull request merged**
