### PR TITLE
EllipsoidalOccluder updated with check

### PR DESCRIPTION
**Pull request by Rudraksha20**
Worked on issue #4794. updated EllipsoidalOccluder with Check.

### CODE REVIEW

**Comment by omh1280** [comment]
Same problem as #5557. Once #5555 goes into master, you will want to rebase!

**Comment by omh1280** [comment]
Can you make the checks more specific? For example, if a variable is expected to be a number use `Check.typeOf.number`. It implicitly checks if the variable is defined.

**Comment by Rudraksha20** [comment]
@omh1280 updated EllipsoidOccluder.js with the recommended changes.

**Comment by omh1280** [comment]
Looks good! Thanks

**Comment by pjcozzi** [comment]
Thanks again @Rudraksha20 @omh1280!

**Pull request merged**
