### PR TITLE
Reduce amount of Sun bloom post-process effect

### LINKED ISSUE #5381: Sun atmosphere artifact
@emackey as discussed offline.  Perhaps a render order / framebuffer / scissor issue.

ok2

### PR DESCRIPTION
**Pull request by emackey**
After triaging with @klingerj.

Fixes #5381.

### CODE REVIEW

**Comment by emackey** [comment]
Master: [Demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=56db1621a7b124fdb6651d727e795561)

This branch:  [Demo](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/less-sun-bloom/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=56db1621a7b124fdb6651d727e795561)

**Comment by emackey** [comment]
@klingerj when you get a chance can you add this to `CHANGES.md`?  Merge master in here first.  Thanks!

**Comment by emackey** [comment]
Updated.

**Comment by pjcozzi** [comment]
Thanks all!

**Pull request merged**
