### PR TITLE
Document inheritance hierarchy 

### PR DESCRIPTION
**Pull request by icholy**
You're currently using `@see` tags to [point from the parent to the child](https://github.com/AnalyticalGraphicsInc/cesium/blob/d3eb3015881fcc0071d64d0f97ea8f83a7d9f0ba/Source/Scene/Appearance.js#L36-L41) but not linking the child to the parent in any way.

This is problem for me while generating TypeScript definition files.

``` ts
class Appearance {
    material: Material;
    translucent: boolean;
    vertexShaderSource: string;
    fragmentShaderSource: string;
    renderState: any;
    closed: boolean;
    constructor(options?: { translucent?: boolean; closed?: boolean; material?: Material; vertexShaderSource?: string; fragmentShaderSource?: string; renderState?: RenderState });
    getFragmentShaderSource(): string;
    isTranslucent(): boolean;
    getRenderState(): any;
}

class MaterialAppearance {
    material: Material;
    translucent: boolean;
    vertexShaderSource: string;
    fragmentShaderSource: string;
    renderState: any;
    closed: boolean;
    materialSupport: MaterialAppearance.MaterialSupport;
    vertexFormat: VertexFormat;
    flat: boolean;
    faceForward: boolean;
    constructor(options?: { flat?: boolean; faceForward?: boolean; translucent?: boolean; closed?: boolean; materialSupport?: MaterialAppearance.MaterialSupport; material?: Material; vertexShaderSource?: string; fragmentShaderSource?: string; renderState?: RenderState });
    getFragmentShaderSource();
    isTranslucent(): boolean;
    getRenderState(): any;
}
```

`MaterialAppearance` should `extend` `Appearance` but I have no way of figuring that out from the annotations in your source.

jsdoc has a an [@extends](http://usejsdoc.org/tags-augments.html) tag which can be used to document the relationship between a parent and child class. 

Here's what I looks like in the docs 
pic

Would you consider accepting a change like this?

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @icholy.

Anyone have thoughts here?

This is fine with me, but there are a lot more places we would want it, e.g., `TerrainProvider`, `ImageryProvider`, etc.  Is there also an `@implements`?

**Comment by icholy** [comment]
@pjcozzi if I get the the thumbs up, I'll go and update all of them. I just didn't want to waste my time in case it wasn't something that was going to get accepted.

Yeah, there are `@interface` and `@implements` tags http://usejsdoc.org/tags-implements.html

**Comment by pjcozzi** [comment]
I'm OK with this.  @mramato @kring any thoughts?

**Comment by mramato** [comment]
This is something I've actually been meaning to look into, so thanks @icholy for getting the ball rolling.  

Since Cesium doesn't use actual inheritance, I think `@interface` and `@implements` is the right thing to use in our code base.  It also looks like jsDoc will automatically use the default documentation on the `interface` object if it's not overridden on the implementor.  This should let us delete a bunch of duplicate documentation littered throughout the code base.

I think making this change one set of classes at a time would be the way to do it, so if you want to change Appearance to `@interface` and `@implements` as well as see if there is duplicate doc that can be removed, that would be a good test case.  Once we're happy with that, we can identify the other interfaces and update them and their implementations as well.

**Comment by icholy** [comment]
@mramato at first I was thinking the same thing. But take a look at [this](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.11/Source/Scene/MaterialAppearance.js#L250-L279). Looks a lot like inheritance to me.

**Comment by mramato** [comment]
> @mramato at first I was thinking the same thing. But take a look at this. Looks a lot like inheritance to me.

That is not actually inheritance, it's just code sharing.  Inheritance would mean that `Appearance` would actually be in the prototype chain for `MaterialAppearance`, but it's not.  All that code is doing is reusing the function already written in `Appearance`.

**Comment by icholy** [comment]
Meh, tomato, tomato. You're not using the standard mechanism, but the end result is pretty similar. I agree that it's not a perfect fit, but I think `Appearance` is much closer to a base class than an interface (interfaces don't define behaviour).

However, I won't really matter if it's an interface or class in the typescript definitions. I'll update it to use interfaces.

**Comment by icholy** [comment]
@mramato seems like your jsdoc template doesn't support interfaces. I stripped down `Appearance` to the bare minimum and nothing is getting generated.

**Comment by mramato** [comment]
> Meh, tomato, tomato. You're not using the standard mechanism, but the end result is pretty similar.

No, the result is very different, it's only superficial on the surface.  If this was really inheritance, the functions would not need to be defined at all in the object implementing them because they would get them automatically.

> seems like your jsdoc template doesn't support interfaces

This may be true, but I also noticed you deleted a bunch of code in the `Appearance` class, the only thing you should have had to to was add the `@interface` attribute, everything else needs to stay.  Does that still result in it not showing up?

**Comment by icholy** [comment]
Yeah that's what I tried first. After that didn't work I deleted everything in Appearance to see if that would work.

**Comment by mramato** [comment]
Okay, I'll take a look at this if I get a chance.  Modifying our template is definitely an option, but I won't know how easy/hard it is without looking more into it.

**Comment by icholy** [comment]
@mramato are the templates a modified version of a publicly available theme? Or is it written from scratch for caesium?

**Comment by mramato** [comment]
> @mramato are the templates a modified version of a publicly available theme? Or is it written from scratch for caesium?

I'm honestly not sure.  I think it was at some point, but it was a 2.x version of jsDoc.  It's in `Tools\jsdoc\cesium_template` if you want to take a look or play with it.

**Comment by shunter** [comment]
I created the current template when we upgraded to jsDoc 3 which was PR #1745

The template was based on the default at the time, but I ended up making huge changes to make it match our desired output.

**Comment by icholy** [comment]
@shunter I've made several attempts at this but I'm not getting anywhere. What are the odds you could update the template with support for interfaces?

**Comment by icholy** [comment]
@mramato soo uhh, can I just do them as base classes instead of interfaces? Better than nothing.

**Comment by icholy** [comment]
@mramato this has been a blocker for generating typescript definitions for almost a year now. I want to get this conversation going again.

**Comment by pjcozzi** [comment]
@mramato can @icholy move forward with this, https://github.com/AnalyticalGraphicsInc/cesium/pull/2879#issuecomment-149914796?

> @mramato soo uhh, can I just do them as base classes instead of interfaces? Better than nothing.

**Comment by thinkpadder1** [comment]
@mramato Can we please get this merged... I need typescript definitions... :cry:

**Comment by icholy** [comment]
Wow fuck this, I give up. BTW, `Appearance` is not an interface.

**Pull request closed without merging**
