### PR TITLE
Ungzip geom tile

### PR DESCRIPTION
**Pull request by lilleyse**
This will hopefully fix https://github.com/AnalyticalGraphicsInc/cesium/issues/7731, and in general it's good practice to have sample data be ungzipped.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/geom-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
This will fix the issue, but there are bigger problems here, I have a PR incoming to fix the real problem.

**Comment by mramato** [comment]
We should still take this if we want the geom file to be ungzipped.

**Comment by mramato** [comment]
I'll test the deployed version once CI finishes and then merge

**Comment by mramato** [comment]
Thanks, @lilleyse

**Pull request merged**
