### PR TITLE
Classification primitives become ready when show is false

### PR DESCRIPTION
**Pull request by bagnell**
Ground and classification primitives will become ready when show is false. For #6413.

CC @mramato @hpinkos The tests fail in master from timing out. Is there a better test?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@bagnell, thanks for the pull request! Maintainers, we have a signed CLA from @bagnell, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
This looks good to me!  And this should allow @roderickgreen to finish his flickering polygons pull request.

@mramato did you want to take a quick look at this?

**Comment by mramato** [comment]
This is fine with me, I merged in master so as soon as this is green someone can hit merge.

**Comment by mramato** [comment]
Thanks @bagnell

**Pull request merged**
