### PR TITLE
Deprecate all the things!

### LINKED ISSUE #6119: Remove deprecated properties from the adding of the Resource class
Remove functions:
- [ ] `loadImage`
- [ ] `loadArrayBuffer`
- [ ] `loadblob`
- [ ] `loadImageViaBlob`
- [ ] `loadJson`
- [ ] `loadJsonp`
- [ ] `loadText`
- [ ] `loadWithXhr`
- [ ] `loadXML`

Removed deprecation of parameters:
- [ ] `loadCRN`
- [ ] `loadKTX`
- [ ] `ArcGisMapServerImageryProvider`
- [ ] `BingMapsImageryProvider`
- [ ] `GoogleEarthEnterpriseMapsProvider`
- [ ] `GoogleEarthEnterpriseImageryProvider`
- [ ] `MapboxImageryProvider`
- [ ] `SingleTileImageryProvider`
- [ ] `UrlTemplateImageryProvider`
- [ ] `WebMapServiceImageryProvider`
- [ ] `WebMapTileServiceImageryProvider`
- [ ] `createOpenStreetMapImageryProvider`
- [ ] `createTileMapServiceImageryProvider`
- [ ] `ImageryProvider`
- [ ] `CesiumTerrainProvider`
- [ ] `GoogleEarthEnterpriseTerrainProvider`
- [ ] `GoogleEarthEnterpriseMetadata`
- [ ] `Model`
- [ ] `Cesium3DTileset`
- [ ] `CzmlDataSource`
- [ ] `KmlDataSource`

`Resource` class cleanup
- [ ] `loadImage` method - `allowCrossOrigin` parameter.
- [ ] `createIfNeeded` method can probably have the options parameter removed. It was there to more easily handle URL strings with a bunch of options specified to the parent classes instead of the to the `Resource`. Removing all these deprecated properties should remove the need for it.
- [ ] Move all the specs for the `load*` functions to the specs for the `Resource` class.

### PR DESCRIPTION
**Pull request by mramato**
Didn't see anyone tackling this and the release is a week away (plus I know how to party on a Friday night).

* Remove `loadArrayBuffer`, `loadBlob`, `loadImage`, `loadJson`, `loadJsonp`, `loadText`, `loadXML` and `loadWithXhr` have been removed.
* Remove `proxy`, `headers` and `query` parameters from all the fuctions that take a `Resource`.

Fixes #6119

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@mramato, thanks for the pull request! Maintainers, we have a signed CLA from @mramato, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Just realized that none of the tests were moved into Resource, @tfili am I right that I need to move all of the `loadXXXSpec.js` tests into Resource.js and update them? (Not sure why we didn't do that initially)

**Comment by mramato** [comment]
Okay, I added back the relevant tests and this is ready. (Still ~2700 lines down!)  Not all the tests needed to be moved because they were duplicating stuff that was already tested.

In the future we can definitely streamline the Resource tests further, but  that's purely for cleanup purposes.

**Comment by tfili** [comment]
It looks like you got everything outlined in the issue. Thanks @mramato.

**Pull request merged**
