### PR TITLE
Feature/kml update

### PR DESCRIPTION
**Pull request by dwhipps**
This pull request includes one "breaking" change: the parameters passed to `unsupportedNode` Event listeners has changed. (I needed all of them, and thought that long-term it was better to maintain the parameter ordering from the parent calls.) Happy to discuss this one.

I renamed the `processUnsupported` method to `processUnsupportedFeature` to better distinguish it from similarly named `processUnsupportedGeometry`.

Finally, I implemented logic that ensures only nodes whose _entire ancestry_ is visible will produce Entities with show === true. See helper function `ancestryIsVisible()`. (Per the KML spec here: https://developers.google.com/kml/documentation/kmlreference#folder).

> A Feature is visible only if it and all its ancestors are visible.

I couldn't find this logic anywhere else. Please let me know if I've missed something.

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @dwhipps!  We'll try to review this soon

By the way, it looks like there are a few test failures

**Comment by dwhipps** [comment]
Fixing tests now.

**Comment by dwhipps** [comment]
That looks better.

**Comment by pjcozzi** [comment]
Thanks again for the contribution, @dwhipps.  Can you please also update CHANGES.md?

@tfili can you review this when you are back in town?

**Comment by tfili** [comment]
Thanks @dwhipps.

**Pull request merged**
