### PR TITLE
Fix updateBatchTableBoundingSpheres

### LINKED ISSUE #4431: Kml file loading regression: works in 1.25, not 1.26 "Cannot read property 'center' of undefined"
The attached kml file loads correctly in 1.25, but fails with the following error message in 1.26:

> An error occurred while rendering. Rendering has stopped.
> TypeError: Cannot read property 'center' of undefined
> TypeError: Cannot read property 'center' of undefined
>     at updateBatchTableBoundingSpheres (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:93495:40)
>     at Primitive.update (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:93890:13)
>     at GroundPrimitive.update (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:98060:25)
>     at PrimitiveCollection.update (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:157993:27)
>     at updatePrimitives (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166211:33)
>     at executeCommandsInViewport (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166122:9)
>     at updateAndExecuteCommands (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:165990:17)
>     at render (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166420:9)
>     at Scene.render (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:166458:13)
>     at CesiumWidget.render (http://localhost/geosportardeche/DesktopModules/CG.EarthMapMaker/js/Cesium/Cesium.js?v1:175280:25)

I wasn't able to determine if it was a problem with the quantity of geometries in the file or the mix between polygon and multigeometries. I stripped down the kml file for the issue, the polygons are much more complex usually. However the error happens even with four points polygons. There are 3423 placemarks in the file. 

[Fail1.26.kml.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/529713/Fail1.26.kml.zip)

### PR DESCRIPTION
**Pull request by mramato**
updateBatchTableBoundingSpheres was using the BoundingSphere center without applying the modelMatrix to the sphere first.

Fixes #4431 and #4428

@bagnell as discussed offline, this may not be the most correct fix, but let me know what you think.  We probably want a unit test for this as well.

### CODE REVIEW

**Comment by hpinkos** [comment]
Just waiting on unit tests.  @mramato let me know when this is ready =)

**Comment by hpinkos** [comment]
#4428 is fixed, but I'm still getting a crash with the KML file included in #4431

```
DeveloperError: sphere is required.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at Function.BoundingSphere.transform (http://localhost:8080/Source/Core/BoundingSphere.js:1003:19)
    at updateBatchTableBoundingSpheres (http://localhost:8080/Source/Scene/Primitive.js:1197:45)
```

**Comment by mramato** [comment]
I'm still working on this, so there's a chance that I'll fix it or it's a completely different unrelated crash.

**Comment by hpinkos** [comment]
alright, let me know when this is ready then

**Comment by mramato** [comment]
This is ready.  I'm going to open a PR for #4431 separately since fixing the first issue exposes a new one.

**Comment by hpinkos** [comment]
@pjcozzi can you take a quick look at this and merge it?  It fixes the problem, I'm just not 100% sure on the code changes.

**Comment by mramato** [comment]
Thanks @pjcozzi, good call.  Both are done.

**Comment by pjcozzi** [comment]
#4428 is fixed.

With #4431, I get this on drag and drop:

image

**Comment by mramato** [comment]
> With #4431, I get this on drag and drop:

Yes, we discussed this earlier in the PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/4461#issuecomment-255404146

**Comment by pjcozzi** [comment]
Sounds good.

**Pull request merged**
