### PR TITLE
Replaced error checking with Check

### PR DESCRIPTION
**Pull request by hulyayurtman**
Replaced DeveloperErrors with Checks in CorridorOutlineGeometry

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @hulyayurtman, congrats on your first Cesium pull request!

@omh1280 do you want to review and test this?

Note that `DeveloperError` no longer needs to be included in CorridorOutlineGeometry.js.

**Comment by omh1280** [comment]
Code looks great. My only comment is to include a description in the PR so that other users can know what this is for (you can even link issues like #4794!)

Thanks!

**Comment by omh1280** [comment]
One thing, actually: can you remove `DeveloperError` and `'./DeveloperError'` from the `define` statement please? When you've done this, bump this thread and I can review again :)

**Comment by omh1280** [comment]
Thank you @hulyayurtman. Looks great!

**Comment by hulyayurtman** [comment]
All done :)

**Comment by pjcozzi** [comment]
Thanks for the quick review, @omh1280!

@hulyayurtman once again, nice job and welcome!  We look forward to your future contributions! 😀

**Pull request merged**
