### PR TITLE
Make dynamic polyline create the given arcType

### PR DESCRIPTION
**Pull request by OmarShehata**
This is a fix for an issue that [came up on the forum](https://groups.google.com/d/msg/cesium-dev/AmbEbLMKAAs/1OooENSyBgAJ). It's easy to see [in this Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=5Vddb9s2FP0rrF8sAy5dLcs2JG6wxNFSY04dxElf6qJgpGubKCUKJOXUa/3fd6lvyY7rPuxpeghC8tyvc3mu5DVTZM3hGRR5SyJ4JiPQPAnph3TP6frpciQjw3gEqtsn3+YRwYeHbAlqc6fkmgegzurGYxmNm8fON8K0BjMOzsjJH7+ekm1vHm175/MoC061rwCiWcx88NYQmXcsCgTuKwjlGsZRnJhL33AZOXmMWcvgYRMDnXh/PXweTcajv/8b19fTx6uJV0XAGMif9iECpK+Mh8vz7MhnIShWnWXr/DCWYiN4iQ0Ue+bREsELJjSUIM1tchr3P37KNxdcaTMS3P9iu5YIUeayyoprNnO2nwGnTApNdVZPbk9tr2rMZD1fJFG6JI5vY/eKu2CftFq7e5cn3C6axnjoCcFjLXmQeaBFdeT798yaQhQUHvoNRulSyCegUHiw+RbB+YI4rypSGomlidf5amR53gSWbNM40SunAa0H3DZj5607HDfv095wRXP3+K+uxav83xy37ZPjtXB0Z60mQvSx09xQJhqObG7hpNHfcvOnWnwc0YMByeRMYgVrjqkSq6wmKA+FKWBs0PkAcAoZ9o5tzp6LUrt7h4ENFttYW51TGjTuW/q3Wh91A26njzPv8+30g5cRWTY5jeMnSiHyrgxXcFrwUfW4ZIwFgVNjvkSetftRcdd4MYyYEE8MJaVkDMpsnCIlZ6ej9lFgEhWRdqYt1pCFdGD2+s39kBlQnAlMoQgvhVT0avLotaDPPDArxJ229pnyLZOVh8tsg96/e7y92pFr+kLbWqrxPiJXVrYrEDEx8NXk45wptlQsXr1BegPpJ6kisHuYrCdSfTjduGsdVVDKA0R3ras33fwVEMkA9vh4wEjv8ciZdx4k0YYpU0yQPhGwMNn4IzgMUkFmsqZk3mmFZHGMOh2tuAicNFb1vitR7vE1uLUa3HoN7sEaJrWMl/gFQowtSsZFTTuJuzuJu1XikCVXj7gEk6d8tRkHTtdIiTdUpcnn8IbHiqEfItLALwbKmtmj2mwE0AV+YM34P1ZzXfe3+Gv3R6buQdOsXAXBDSADmvuHtbxfx3UNl/pVBv9j0QldKBlewxLHjr5Uim2cj69/P+2Tk7aEfuZ57f6SuvhUl/I+bb6oyxtveu3NxqMa9qUxcO9d56ht/imasWZLiu5XSfj0fyEtHWZHMHZz73nvm5R1+p1heg0vsv0/eRhLHDmJEg6lAwNhLNCbHjwl/hdAgev0tTYcFEbDgK8JD97OO61fGvMO6h5/M+DJAj+c7A2fdy6GA8Q3zIRkds5O16AE21jIyr2YZJuU0uEAl7tWucxrHv8F).

The red line is a geodesic. The green is a rhumb. The dynamic blue line is supposed to be a rhumb line, but is always drawn as a geodesic no matter what you pass as an `arcType`.

bad_rhumb

This is because the dynamic polyline geometry does not take into account the arcType when generating the positions. I added a test to ensure this runs, which should fail in master and pass here.

@shehzan10

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by shehzan10** [comment]
Seems fine to me. A maintainer should look at this and merge.

**Comment by OmarShehata** [comment]
Thanks Shezhan! @hpinkos would you like to merge?

**Comment by hpinkos** [comment]
Reviewing this now

**Comment by hpinkos** [comment]
Works great @OmarShehata, thanks!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/AmbEbLMKAAs/1OooENSyBgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/8191 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Pull request merged**
