### PR TITLE
Fix GroundPrimitive clipping issue

### LINKED ISSUE #3706: Ground primitive clipping issue
@bagnell here's the bug we were talking about yesterday, not sure if you have a better test case (this one requires @tfili's `entity-terrain` branch.

Run the below code in Sandcastle and then hit the "Bug" button.  Right-click zoom in and out of the rectangle (without rotating) and you will see obvious visual artifacts as the ground primitive seemingly changes size/shape as you zoom.  I believe @bagnell said this is a multi-frustum related issue.

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    baseLayerPicker: false,
    terrainProvider: new Cesium.CesiumTerrainProvider({
        url: '//assets.agi.com/stk-terrain/world'
    })
});


var rect = Cesium.Rectangle.fromDegrees(-85.0, 35.99, -84.99, 36.0);
Sandcastle.addToolbarButton('Bug', function () {
    viewer.entities.add({
        rectangle: {
            coordinates: rect
        }
    });

    viewer.camera.setView({destination: rect});
});
```

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #3706.

Removes the OBB optimization for better culling. The bounding volume was
pulling the far plane closer to the camera and causing the shadow volume
to be clipped.

### CODE REVIEW

**Comment by mramato** [comment]
I can confirm the issue is fixed.  I also wrote up #3710, which is most likely unrelated.

**Comment by pjcozzi** [comment]
@bagnell if I'm following you correctly, the bounding volume was smaller than the shadow volume so the shadow volume was getting clipped, right?

I'm fine with this change for now since we have bigger fillrate improvements to make here, but two questions:
* Why doesn't depth clamping clamp the clipped volume to the near/far plane?
* Wouldn't it be more efficient to just also make the shadow volume smaller instead of making the bounding volume big?  Is that just too ugly?

**Comment by bagnell** [comment]
>Why doesn't depth clamping clamp the clipped volume to the near/far plane?

I forgot about the near/far plane clipping. The volume doesn't need to be clipped to the near plane. It should be getting clipped to the far plane though so I'll look into it.

>Wouldn't it be more efficient to just also make the shadow volume smaller instead of making the bounding volume big?

Yes, I wish we could. Most likely, we would need support from the terrain server to get the max/min height of the terrain over an area.

**Comment by pjcozzi** [comment]
>> Wouldn't it be more efficient to just also make the shadow volume smaller instead of making the bounding volume big?
> 
> Yes, I wish we could. Most likely, we would need support from the terrain server to get the max/min height of the terrain over an area.

In the general case, I agree.  In this case, don't we know the max height of the smaller OBB?  Couldn't we use that?

**Comment by bagnell** [comment]
>In this case, don't we know the max height of the smaller OBB?

Which OBB? We compute the one for the primitive based on the volume. For the terrain tile, we would have to go through the quadtree. The volume might overlap more than one tile. We can't use the parent tiles either. The min and max height of the tiles are for the quantized mesh so the min/ max heights of the parent aren't guaranteed to bound those of the children.

**Comment by kring** [comment]
In the quantized mesh format, at least the one produced by STK Terrain Server and at least when I wrote it, the min/max heights of a tile very intentionally represent the the min/max height of that tile _and all its descendants_.

**Comment by bagnell** [comment]
That would be great. We might be able to do something client side in the short term to shrink the volumes. I had an offline discussion with Alex where he said that was not the case. Maybe something changed? CC @abwood

**Comment by abwood** [comment]
Looking at the code, this is not the case (I can see how maybe it was intended).  From what I see, min height and max height are set during refinement, meaning only vertices that are INSERTED into the tile contribute to minheight and max height.  What that means is that if you have a tileset with leaf nodes at level 9, and then add a higher resolution raster data to that tileset into level 12, simplification could cull out the minimum and maximum values that are defined in level 12 by the time those vertices are propagated up to level 9.

I'm not sure how common that case is, but looking at the code we can just make it behave as kevin says (I've been thinking of this since Dan and I spoke).  The only thing that could be impacted would be the precision we have to work with when quantizing the heights, but it shouldn't be that big of a deal.  Will backup with unit tests.

**Comment by pjcozzi** [comment]
@bagnell is there anything you want to do in the short-term or should we merge this?

**Comment by bagnell** [comment]
@pjcozzi I think we should merge this.

**Pull request merged**
