### PR TITLE
Directly passing texture objects to fabric material shaders

### PR DESCRIPTION
**Pull request by LukasdeBoer**
For my master thesis, I required direct access to the fragment shader in order to do Volume Raycasting. In Cesium, this can be done using the Fabric approach. However, there was no way to directly pass a texture containing my volume data. A slight alteration to the Material code, allowing me to directly pass a Texture object to the shader was enough to access the sampler in the fragment shader. Example, starting with creating the texture:

```
var pointcloud = new Uint8Array(length * width * height);

/* fill the pointcloud here */

var source:any = new Object();
source.arrayBufferView = pointcloud;

var texture = new Cesium.Texture({
    context : this.scene.context,
    width : width,
    height : length * height,
    pixelFormat : Cesium.PixelFormat.LUMINANCE,
    pixelDatatype : Cesium.PixelDatatype.UNSIGNED_BYTE,
    source: source,
    sampler: new Cesium.Sampler({
        wrapS : Cesium.TextureWrap.CLAMP_TO_EDGE,
        wrapT : Cesium.TextureWrap.CLAMP_TO_EDGE,
        minificationFilter : Cesium.TextureMinificationFilter.LINEAR,
        magnificationFilter : Cesium.TextureMagnificationFilter.LINEAR
    })                
}); 
```

Creating Shader Source:

```
var shader_source = ` 
    czm_material czm_getMaterial(czm_materialInput materialInput)
    {   
        czm_material m = czm_getDefaultMaterial(materialInput);
        float x = sampler2D(pointcloud, materialInput.st) / 256.0;
        m.diffuse = (x, x, x);
        return m;
    }
`;
```

And then passing it to the primitive:

```
var instance = new Cesium.Primitive({
    asynchronous: false,
    geometryInstances: new Cesium.GeometryInstance({
        geometry: polygonGeometry
    }),
    appearance : new Cesium.MaterialAppearance({
        material : new Cesium.Material({
            fabric : {
                uniforms : {
                    pointcloud: texture,   
                },
                source : shader_source
            }
        })
    })
});
```

My code example is in Typescript, please excuse me if this does not directly convert to JavaScript.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Cool, thanks @LukasdeBoer!  Can you please add a unit test to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Scene/MaterialSpec.js?

Also, just a heads up that `Cesium.Texture` is not part of the public API so its interface may change from release to release, e.g., when we upgrade to WebGL 2.

**Comment by thinkpadder1** [comment]
Off topic: Are you using typescript with Cesium? Can I get some details, please (type definitions, etc)? Thank you.

**Comment by LukasdeBoer** [comment]
@thinkpadder1 Unfortunately, nothing special. I use Cesium from our visualization framework [CommonSense](https://github.com/TNOCS/csWeb). There are some definition files circling around the internet, but I don't use them at the moment.

**Comment by pjcozzi** [comment]
Closing given that `Texture` isn't yet part of the public Cesium API.  We can revisit when we make `Renderer` changes, which are imminent-ish given WebGL 2 progress.  Thanks for supporting Cesium, @LukasdeBoer!

**Pull request closed without merging**
