### PR TITLE
Fix allow local-running Cesium to load its resources for Chromium

### PR DESCRIPTION
**Pull request by hpinkos**
See https://github.com/AnalyticalGraphicsInc/cesium/pull/5892#issuecomment-364110404

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hpinkos, thanks for the pull request! Maintainers, we have a signed CLA from @hpinkos, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@thw0rted this should fix your issue, right?

Hope you get your CLA issues figured out.  It would be great to have you as a contributor!

**Comment by thw0rted** [comment]
I have tested the change and it does resolve the issue for my specific use case (in Chrome/Chromium, with `--allow-file-access-from-files` switch).  I'll address other local-load issues in other threads.

**Comment by thw0rted** [comment]
Trackback to #5830

**Comment by hpinkos** [comment]
Can someone review this? @emackey?

**Comment by emackey** [comment]
I've been meaning to test the new resource stuff in VSCode, haven't gotten there yet.

In the meantime, this change seems fine for Chromium.  The same behavior is not present in Firefox (origin is null for local files) but presumably one wouldn't run Cesium in a stand-alone Firefox engine the way one does for Electron/Chromium.

@hpinkos If you like I can build Cesium locally with and without this change and test the behavior out inside a VSCode plugin.  Or you could just merge this, it looks fine.

**Comment by thw0rted** [comment]
Just as a data point, I think our customers are more likely to run our product offline in Firefox than Chrome, just based on how the software baseline is set up, but I wouldn't expect it to be *common.  I'm also fairly certain that the above change wouldn't affect Firefox because I don't think it returns `status=0` for local XHRs.

**Comment by hpinkos** [comment]
Thanks @emackey!  I think I'm just going to merge this now

**Comment by hpinkos** [comment]
Thanks @thw0rted, this is merged and will be included in Cesium 1.43

**Comment by pjcozzi** [comment]
Does this warrant an update to CHANGES.md?

**Pull request merged**
