### PR TITLE
ScreenSpaceCameraController.maximumZoomDistance doc fixed #4660

### LINKED ISSUE #4660: ScreenSpaceCameraController.minimumZoomDistance default is incorrect
If you look at the code you'll see the actual default and the default in the doc are different. We should make them match.

I'm not sure what the correct value is. I've noticed that the value of `1.0` causes issues when you can zoom through terrain if you are zooming in to a mountain.

```javascript
        /**
         * The minimum magnitude, in meters, of the camera position when zooming. Defaults to 20.0.
         * @type {Number}
         * @default 20.0
         */
        this.minimumZoomDistance = 1.0;
```

### PR DESCRIPTION
**Pull request by ateshuseyin**
issue fixed

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @ateshuseyin!

Even though this is a really small fix, could you please send us a Contributor License Agreement?  We need to have that signed before we can merge your commit.  You can find directions here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by hpinkos** [comment]
Thanks @ateshuseyin, we received your CLA.  Can you please add yourself to [CONTRIBUTORS.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md)?  As soon as you do I'll merge this.

**Comment by pjcozzi** [comment]
Thanks @ateshuseyin

**Comment by pjcozzi** [comment]
@ateshuseyin after you make commits based on a review, please comment in the GitHub issue so we get notified.

**Comment by ateshuseyin** [comment]
I added myself to contributors.md

Thanks

23 Ara 2016 ÖS 7:19 tarihinde "Hannah" <notifications@github.com> yazdı:

Thanks @ateshuseyin <https://github.com/ateshuseyin>, we received your CLA.
Can you please add yourself to CONTRIBUTORS.md
<https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md>?
As soon as you do I'll merge this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AnalyticalGraphicsInc/cesium/pull/4778#issuecomment-269012872>,
or mute the thread

**Pull request merged**
