### PR TITLE
Primitive fixes; docs, dev checks, cleanup; depth fail, rtc, hardware resources

### PR DESCRIPTION
**Pull request by nmschulte-aviture**
Some cleanup to `Primitive.js`.

---
CLA is signed and `CONTRIBUTORS.md` is already updated:
https://github.com/Aviture/cesium/blame/primitive-fixes/CONTRIBUTORS.md#L69

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @nmschulte-aviture! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Aviture/cesium/blob/primitive-fixes/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/primitive-fixes/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by nmschulte-aviture** [comment]
Please see also #7947 (doc updates).

**Comment by OmarShehata** [comment]
We have a signed CLA from Aviture for username `nmschulte`. Did you have your GitHub username changed?

Was there an open issue for this bug? If so, can you link it? If not, can you provide a Sandcastle example of the bug this PR fixes, to make this easier to review?

**Comment by nmschulte-aviture** [comment]
> We have a signed CLA from Aviture for username `nmschulte`. Did you have your GitHub username changed?

I operate both usernames, @nmschulte and @nmschulte-aviture.  If I need to amend the CLA somehow that is fine; if I simply need to voice approval as @nmschulte I can do that as well.

> Was there an open issue for this bug? If so, can you link it? If not, can you provide a Sandcastle example of the bug this PR fixes, to make this easier to review?

I do not know of any open issues addressing these concerns.  I can create a test/example case for the rtc `Array` `length` logic bug but it'd be contrived.  As well, I can create a test/example case for the resource freeing, but again they'll be contrived.

This command should show that the `_pickSP` code in `Primitive` isn't necessary:
`git show -s HEAD && git grep _pickSP`
2019_08_08-14_31_03-1276x288

**Comment by nmschulte-aviture** [comment]
Sandcastle example showing issue with depth-fail's shader program not cleaning up:
https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=vVZtb9s2EP4rRD40NKLSkiVZUuIEM5I0CNY6QWOsGOpiYCTaJkqLAkk78wb/951eIytOCgxF88ERj/c8d/foeNSGKrTh7IkpdI5S9oQumebrFfmjsOHjuFheytRQnjJ1bKF/ZymCP8OUAtO9khueMHVaA2PFqGFfpBLJtHTBvVm6653N0g3E0jFLGYQqY5JiCVuztHgiCyEfGUlYZpZTps14AXhtKiKAGbUu3XOuTIqt4OmzQbB0YZbg5ti23Vi1ocp8lDm8yvETNUti5GeacJpqHA5J5LtB5NZJsjT5gX8YDb0o6D1HpuZV90FAojAc+C33SrwHusoEu5eaGy5TDQxfv4HPXCqEczcOFvsM/o2q0s7QyQnv1a+gCPwiT8FUhssKrKZ2C0j6CFcCvUdOL0+mJsmqDPZb4BKgcqFotuQxFjkHVFnDDldAsrVe4pou993lJVeET0uW4upZF8DqxX6S2lwx6DDBElx1Rqe/rFci9iw0X6dx/oxLTr2nj5zPNTNFSxC7yv2QvhWWHNI5/6v2v/JvZMn4YmnQyXlFXrEWleYPdVvuq3mv+ApS3jDcYl0wuWJGbW+hyWkKZ+20Dbnp7LaRbfQe6L6KXoO7oDLDSr3m1F4LwTMteUK+3DyEHolb734Mum+nMm8HcKZpsW7Etl7SUxVPtxlryMflmkzuJtcH3J94YpanyO9s7brUPDlFx7W4x51Naozij2uTS3ig4lgKqfZ0uswtXYXHNQuZK7kqXHDbn9x9Hk9urg8VXcysD9DClz8p1P3t5PduoF1rvacPzTJGVc57sBkKxnHj0+0JA1Yt1jCBzSmaU6HZa3GaKse/IOCuHJjF8Stuh6w+Q5rQJMF1Lzy7FbOVqkVx4jujrOhdF7u2HQQ28e0wGLhh5Iaehfyh60XOgDiu40aeH/oWGkRB6PgDMgiHvu/5jjOsJ18zUQ7zA5VHosCzo3AYhP5wYKH3cLUQ13OiIArt0Ak8B/i9KIJbxw7DoR0MXWc4aAZyOf9iumKKEiHl97HBZVFWFfwt12kuLUy4FX6+FBT/2yO3V9eT6e30zxpc/rZHc60ngSs82cLkXXF4Mc18RXh/IjIz5Ssm1wa/4lEevFRLwSC5BS4OL/DDMUYnzZgkXF/BVa/kFoZ/cy29ii8gf+msQwKW/0l0Vbf0S8Zm623qF82p2ErCoG/35w9T+Ymi4LYJvXv3lkq/SKYddDx8k9Wm4mTDz5F1NNJmK9hFaf+NrzKpDForgQnpGwZ3DHxN6v7jOv7ODIm1zpGjfg0aJXwDF8P57KjzoTo7QrGgWsPOfC3EA/+HzY4uRn3w34MJCV9p6eJuw5Sg29xl6Vx8LI2EkFEfli9RRkrxSFWL8T8

The above example also seems to show a problem with `ShaderProgram`'s `destroy`; it also has a `finalDestroy` method which seems like what I'd expect `destroy` to be, so I'm sure I'm missing something here.

**Comment by nmschulte-aviture** [comment]
Sandcastle example showing issue with relative-to-eye coordinate rendering check:
https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=ZY5NS8QwEIb/SsiphSXB6262CD2IICh4NB6y6bgbzEeZTCp12f9utBRWndu87/MMMxlkI7rgyE3A9izCB+shuxLE0xo3Zx1ZnSOkAITzfcxkooW8ZS9X/N2fujmvwpYRFri0r5vlEJLtIRLgUtT00u74hqtMs4dugW5dGBMSK+gbISRBGL0hyPJQ7DuQsDm3Ox2VXCU1uIm5Ya+5/XmoT5GMi4CaM+tNzrV5K94/u0/QvFOy8r80n8zg4vFxAvRm/kZON93DEgohlKzrf4tS8geDVxe/AA

**Comment by hpinkos** [comment]
Thanks @nmschulte-aviture!  This looks good.  I'll merge as soon as CI passes

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @nmschulte-aviture! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request merged**
