### PR TITLE
Remove unused import

### LINKED ISSUE #6456: Necessary import?
I noticed [Source/Scene/Globe.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Globe.js) is importing Material.js but isn't using it in the code aside from referring to it in the doc comments. This is causing lots of code to be included in my builds unnecessarily...

Would a pull request removing this import be welcome?

### PR DESCRIPTION
**Pull request by puckey**
Closes #6456.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @puckey!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by puckey** [comment]
Just mailed you the CLA

**Comment by pjcozzi** [comment]
Thanks @puckey, we received the CLA.

**Comment by hpinkos** [comment]
👍

**Comment by hpinkos** [comment]
Whoops, forgot to have you add yourself to `CONTRIBUTORS.md`.
I added it here: https://github.com/AnalyticalGraphicsInc/cesium/commit/855f849b8f4e730cc2bc479870cad5ea45d1aefa

Thanks for the contribution!

**Pull request merged**
