### PR TITLE
Registering Cesium on node.js npm

### PR DESCRIPTION
**Pull request by chris-cooper**
This PR is to start a discussion about registering a subset of Cesium on npm so it can be brought in with a simple...

    var Cesium = require('cesium');

This could be useful for e.g. writing simple node.js scripts that generate CZML.  You should be able to test this by running the following commands from the Cesium root dir...

    npm install
    node node-test.js

Having node support for Cesium in this form would require ongoing maintenance of index.js and package.json along with updating npm on each Cesium release.  Presumably this would become part of the Cesium release procedure.  The current index.js supports pretty much all of Cesium Core with a few modules removed that depend on window.

### CODE REVIEW

**Comment by chris-cooper** [comment]
@pjcozzi It should work now from a fresh clone.

**Comment by pjcozzi** [comment]
Thanks @chris-cooper.  I updated this to master in the [node-npm-2 branch](https://github.com/AnalyticalGraphicsInc/cesium/compare/node-npm-2).  The CZML your example generates is now wrong, but I haven't looked into it.

I'm really just toying with this.  Will let you know if anything comes of it.

**Comment by adius** [comment]
Just wanted to let you know that I publish cesium with the name cesiumjs on npm.
I'm happy to hand over the url to you when you have figured out a build chain and are ready to publish.

**Comment by pjcozzi** [comment]
Thanks for the offer, @adius.  @kring and I have discussed a bit, and I suspect we would see several modules, not just the top-level `cesiumjs`.  We'll let you know when the time comes.

**Comment by pjcozzi** [comment]
@chris-cooper are you using the `node-npm-2` branch?  I was planning on deleting it since I am not using it.

**Comment by chris-cooper** [comment]
@pjcozzi I did have a quick look at node-npm-2, but I can now do what I need via [terriajs-cesium](https://www.npmjs.com/package/terriajs-cesium).  Shall we delete this branch too?

**Comment by pjcozzi** [comment]
Excellent.  I'll delete both branches.

**Pull request closed without merging**
