### PR TITLE
Add ISSUE_TEMPLATE.md

### LINKED ISSUE #4443: Issue template to point users to the forum
Although we did not move forward with #3637, I encourage us to create a one- or two-sentence [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) to let users know to use the forum for questions and GitHub issues for bugs/features as we have had to point several users to the forum recently.

See [Submitting an Issue](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#submitting-an-issue).

### PR DESCRIPTION
**Pull request by pjcozzi**
Let's see if this issue template helps.  If not, we can change or remove it in a few weeks.

There's lots more it could say, but I want to keep it concise.

Fixes #4443

### CODE REVIEW

**Comment by hpinkos** [comment]
:+1:  thanks @pjcozzi!  I think this will make a difference

**Comment by mramato** [comment]
@pjcozzi please add a separate pull request that ignores this file from both the release zip and adds it to npmignore.  Thanks.

**Comment by mramato** [comment]
Looks like it is not part of the zip, but it does need to be in npmignore.

**Comment by pjcozzi** [comment]
See #4478 for npmignore

**Pull request merged**
