### PR TITLE
Option to turn off normal shading

### PR DESCRIPTION
**Pull request by Vineg**
Small fixes.
#5152

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @Vineg!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/point-cloud-scale-fixes/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Thanks for the PR @Vineg!  @lilleyse can you take a look a this?

**Comment by lilleyse** [comment]
Thanks @Vineg. Would you mind opening a separate PR for the point cloud changes so that we can focus on the geometric error fix exclusively?

**Comment by Vineg** [comment]
Ok, tomorrow

**Comment by hpinkos** [comment]
@Vineg is this ready for review now?  Next time, make a comment when it's ready so we get notified.  We don't get notified when you push new commits.  Thanks!

**Comment by Vineg** [comment]
@lilleyse @hpinkos this one is ready

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Vineg! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@lilleyse can you review this?

**Comment by hpinkos** [comment]
@lilleyse I think this is ready.

@Vineg @geoscan-builder next time you push commits after a review, post a comment when the PR is ready for another look.  We don't get notifications when commits are pushed up so we missed that you were working on this.  Thanks!

**Comment by lilleyse** [comment]
Thanks for the updates @Vineg. I just tweaked a few things and updated documentation and `CHANGES.md`.

**Pull request merged**
