### PR TITLE
Fix generating model shaders for case where material is not used by a primitve

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://groups.google.com/forum/#!topic/cesium-dev/xat4Uy4sabQ

CC https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/351

`extras._pipeline.primitive` is only created if a primitive uses the material. The model linked in the forum post had a material that wasn't being used by any primitives which triggered an edge case in the shader generation code.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@lilleyse, thanks for the pull request! Maintainers, we have a signed CLA from @lilleyse, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

:warning: I noticed that a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version. Once you do, please confirm by commenting on this pull request.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
@shehzan10 could you please look at this?

@lilleyse do you need to update CHANGES.md or add any tests?

**Comment by shehzan10** [comment]
This looks fine to me (pending any update to CHANGES.md or tests).

I do not have commit access to Cesium, so I won't be able to merge this.

**Comment by pjcozzi** [comment]
Thanks @shehzan10.

Waiting on

> @lilleyse do you need to update CHANGES.md or add any tests?

**Comment by lilleyse** [comment]
Updated `CHANGES.md`. I'll add a test to `gltf-pipeline`.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/xat4Uy4sabQ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/6315 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
@lilleyse please update the forum.

**Pull request merged**
