### PR TITLE
Remove getBasePath

### PR DESCRIPTION
**Pull request by lilleyse**
Quick update to 3d-tiles.

I noticed that we already have a file called [getFilenameFromUri](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/getFilenameFromUri.js) that does the same thing, so I removed `getBasePath`.

### CODE REVIEW

**Comment by pjcozzi** [comment]
There are `Scene/Model` test failures.

Also, once we merge this, can you also open up a PR into master that removes the private `getBasePath` in Model.js?

**Comment by lilleyse** [comment]
I mistook `basePath` for `baseName`. So in reality `getFilenameFromUri` and `getBasePath` do opposite things. I'm closing this PR and making the original PR into master. Maybe we can name it `getDirectoryFromUri`?

**Comment by mramato** [comment]
`getDirectoryFromUri` is not a good name, Uri's don't have directories (people often confuse Uri and file paths as being interchangeable but they are not).  `getBaseUri` is probably the best name here.

**Comment by lilleyse** [comment]
I realized that too. I named it `getBasePathFromUri`, but `getBaseUri` is better.

**Pull request closed without merging**
