### PR TITLE
Fixed brightness levels for procedural Image Based Lighting

### LINKED ISSUE #7803: Tweak IBL parameters
Our default PBR/IBL setup is too strong and makes things look washed out. It might be a matter of tweaking the procedural environment lighting since normal environment maps looks good.

Some examples of the washed out look:

57018037-b9331800-6bef-11e9-9baa-54dea87f22fb
Selection_101
Selection_102

### PR DESCRIPTION
**Pull request by IanLilleyT**
Fixes #7803

It came down to changing the default zenith luminance from 0.5 to 0.1

Old:
milktruck_procedural_old
New:
milktruck_procedural_new
Compare to non-procedural IBL:
milktruck_envmap

Old:
pawns_procedural_old
New:
pawns_procedural_new
Compare to non-procedural IBL:
pawns_envmap

Old:
city_procedural_old
New (still ugly):
city_procedural_new

### CODE REVIEW

**Comment by mramato** [comment]
> New (still ugly):

But not washed out, so I think it's a net win.

**Comment by mramato** [comment]
I know I'm a broken record at this point, but any kind of parameter tweaking like this really needs to be done on a calibrated monitor, I assume that's not the case here?

**Comment by IanLilleyT** [comment]
Yeah, my monitor is not specially calibrated. But the result is similar brightness to the non-procedural environment map so it seems like a safe tweak. 

In the future I hope to have a more holistic understanding of the lighting (including skybox, atmosphere, models, etc), and that's when working on a calibrated monitor would be useful.

**Comment by IanLilleyT** [comment]
Before merging this I'm going to take a look at brightness levels of environment maps in cesium vs other viewers. Hopefully today or tomorrow.

**Comment by IanLilleyT** [comment]
Discovered a bug where the brdf look-up-table was flipping the NdotV channel, which made all PBR materials look a bit off, especially more reflective objects. Also, I'm still ok with the default 0.1 luminanceAtZenith value. This is ready to review @lilleyse 

**Before (with tonemapping)**
pawn_cesium_group_before

**After (with tonemapping)**
pawn_cesium_group_after

**After (no tonemapping)**
pawn_cesium_fixed

**Blender (no tonemapping)**
pawn_blender

There might be minor gamma differences between blender and cesium

**Comment by lilleyse** [comment]
Nice catch!

Maybe increase the luminance to 0.2 or 0.25? The NYC buildings are `{"baseColorFactor":[1,1,1,1],"metallicFactor":0.1,"roughnessFactor":0.25}` and they seem too dark.

0.5
city_procedural_old
0.1
city_procedural_new
0.25
lighting

**Comment by IanLilleyT** [comment]
Found a happy medium at 0.2

city_final

**Comment by lilleyse** [comment]
:+1:

**Pull request merged**
