### PR TITLE
Lower epsilon for comparison in computeWallGeometry for extruded polygons

### PR DESCRIPTION
**Pull request by shehzan10**
When using ground polygons with rhumb lines, the polygon was being rendered like 
image

For a small polygon like the one in the sandcastle below, while debugging @likangning93 found that the indices for geodesic vs rhumb line polygons were not the same. Upon further digging, we found that the check to see if the points are too close was resulting in equality for geodesic, but not for rhumb line polygon (rhumb line was equal upto 1e-8).

The fix, changing the epsilon to 6 will allow this and other such equalities to pass, and in my opinion is precise enough in Cartesian coordinates.

@bagnell Can you review this since you were the original author of this code and both @likangning93 and I worked on this.

Sandcastle to reproduce:
```
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: Cesium.createWorldTerrain()
});
var scene = viewer.scene;
viewer.extend(Cesium.viewerCesiumInspectorMixin);

var handler;

var points = [
    Cesium.Cartesian3.fromRadians(-0.004009249759272205, 0.3943878335588929),
    Cesium.Cartesian3.fromRadians(-0.004163539060811744, 0.3881044459031214),
    Cesium.Cartesian3.fromRadians(0.005080091230656227, 0.3880980356196967),
    Cesium.Cartesian3.fromRadians(0.0047191879663033304, 0.3945808943589415)
];

Sandcastle.addDefaultToolbarButton('Rhumb polygon', function() {
    // Rhumb line polygon geometry
    scene.groundPrimitives.add(new Cesium.GroundPrimitive({
        geometryInstances : new Cesium.GeometryInstance({
            geometry : new Cesium.PolygonGeometry({
                polygonHierarchy: new Cesium.PolygonHierarchy(points),
                arcType : Cesium.ArcType.RHUMB
            }),
            attributes: {
                color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 1.0, 0.0, 0.5))
            },
            id : 'rhumbPolygon'
        }),
        classificationType : Cesium.ClassificationType.TERRAIN,
        //debugShowBoundingVolume: true,
        //debugShowShadowVolume: true
    }));
});
Sandcastle.addToolbarButton('Geodesic polygon', function() {
    scene.groundPrimitives.add(new Cesium.GroundPrimitive({
        geometryInstances : new Cesium.GeometryInstance({
            geometry : new Cesium.PolygonGeometry({
                polygonHierarchy: new Cesium.PolygonHierarchy(points),
            }),
            attributes: {
                color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 0.0, 0.0, 0.5))
            },
            id : 'geodesicPolygon'
        }),
        classificationType : Cesium.ClassificationType.TERRAIN
    }));
});

Sandcastle.reset = function() {
    scene.groundPrimitives.removeAll();
    handler = handler && handler.destroy();

    viewer.camera.lookAt(Cesium.Cartesian3.fromDegrees(0.0, 22.5), new Cesium.Cartesian3(0.0, 0.0, 200000.0));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
};
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @shehzan10!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-rhumb-polygon-on-terrain/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by shehzan10** [comment]
I'm not completely sure if this fixes other cases, but I wanted to get feedback on this as I'm doing some more testing.

**Comment by hpinkos** [comment]
@shehzan10 The points should be exactly equal for this check, and `EPSILON6` is not good enough for very small polygons.  You could probably push it to `EPSILON10`, but this seems like there's something else going wrong.  This check is to find the corner points of the polygon, and each corner point is duplicated so each face of the wall can have a normal pointing in the correct direction, so the values at these corners should be a lot closer

**Comment by shehzan10** [comment]
> @shehzan10 The points should be exactly equal for this check, and `EPSILON6` is not good enough for very small polygons. You could probably push it to `EPSILON10`, but this seems like there's something else going wrong.

@hpinkos while dropping it to `EPSILON10` is fixing the sample code I added above I wonder if the problem will show up and require revisiting.

On a side note, `EPSILON6` is checking for points within a micro-meter of each other, right? So isn't that close enough to be considered the same point?

**Comment by hpinkos** [comment]
> On a side note, EPSILON6 is checking for points within a micro-meter of each other, right? So isn't that close enough to be considered the same point?

Not exactly, because our equality check has this relativeEpsilon vs absoluteEpsilon thing: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Math.js#L569

We've opened a number of PRs in the past where `EPSILON6` wasn't good enough for really small geometry

**Comment by bagnell** [comment]
> > So would it be better to use different relative and absolute epsilons then?
> 
> That's a question for @bagnell

The fix here should be to keep the relative epsilon and add EPSILON6 as the absolute epsilon.

**Comment by shehzan10** [comment]
Fixed as @bagnell suggested.

**Comment by hpinkos** [comment]
@shehzan10 did you check if `EPSILON8` or `EPSILON10` fix your case? We should use a smaller value if possible and not pick `EPSILON6` just because

**Comment by shehzan10** [comment]
> @shehzan10 did you check if `EPSILON8` or `EPSILON10` fix your case? We should use a smaller value if possible and not pick `EPSILON6` just because

In the test case I posted above, `EPSILON8` does fix it, but I don't think there is a guarantee that it will fix other polygons that may need `EPSILON6`. I think it's better to keep it at `EPSILON6`.

**Comment by shehzan10** [comment]
Bump. Let me know if the consensus is to decrease the epsilon, otherwise ready to merge.

**Comment by hpinkos** [comment]
Tested it out as is, and it looks good =)

I used [this demo](http://localhost:8080/Apps/Sandcastle/index.html#c=nVRbb9MwFP4rpi9NpMjdHnhpu4mtC2wiqGjtQIgi5DmniTXXjmwnJaD+d5y4uXXchJ9yLt93zvnOUQqiUMFgDwpdIAF7tADN8h3+UPu8Ma3NhRSGMAFq7M82orAYTUGAhTgsrk0bcsFMahv6/GXWmswwKfSwxIJw/kjo03slM1Cm9La5oFWe56MfG4HsU2ByJSoCS3UI0JZwDX5Ly4RpCzkfCMNM2fVV2ww0JnHsHUkzyctECjRtqlQvZaCIomk57doNuvCOGFCM8GnbvORS4fvwBu+ZSa94lhLvDL/0HeRgu/XbphKQsUVR25ZReSXTioiYEm04VI2tpbRCqOvcGDv8eC2ThAOKrN5jO/IzUXp0L5rvmQuxLfIal98fz+mCj6NjO+m6zKr9Hce5cg78JlzehKu7xZHvgMAK/j9E97cP765nv1IjtbPz03NbUQUgVhmhEBa2xq1L8uq7wpRYpK4ojmCswdyJLDdXTptWJMoZfWonr8pRooytQUR3FJTs7LJxZlNDzlmmJYsdEje7D9yB44TLR8DQZPk9nVvigdCWAGe5TnvhWT9anaxL+MOF9sjqbqbdFMFphiUcHHLzaHWgJ+f6KYyi5cfgeXLGvgFfse8wRednw/ChMw++39to8Lvd1fuPwtfrr4vobvHWbf5vi2tFrATkIBKT2oWdzRpnrdtWqpDQtEPV/oH+p6oq2MkCjolN9/6QdlDuX+a6WT5cR2Ez3igYzbUpOVw61ldsl0llUK64h/HEwC7j9vehJ485fQKDqa5PeT5pQPOYFYjFF5vRyd92M0KUE61tZJvzekGb0eV8YvMHMC5JzESyLEBxUlYp6fll5JwY4/nEms9Rxv12eow/AQ) to click out some tiny tiny polygons and they all worked better in this branch than in master.

Thanks @shehzan10 !

**Pull request merged**
