### PR TITLE
Instancing billboards

### PR DESCRIPTION
**Pull request by lilleyse**
This is merged with the billboard size-in-meters changes.

For #3001

### CODE REVIEW

**Comment by pjcozzi** [comment]
In Firefox, I get six test failures in master, and 22 in this branch.  The new ones are `BillboardCollection` and friends.

**Comment by pjcozzi** [comment]
The vast majority of this code has already been reviewed and is in the `instancing-ready-for-master` branch (merged in #3048).  This pull request is to bring those changes into master along with fixing merge conflicts from #3043 (billboard size in meters).

**Comment by pjcozzi** [comment]
@lilleyse please update the task list in #3001 when this is merged (and in general as needed).

**Comment by pjcozzi** [comment]
This is ready to merge once the test failures in Firefox are fixed.

**Comment by lilleyse** [comment]
This should fix the errors.

**Comment by pjcozzi** [comment]
Looks good, thanks!

**Pull request merged**
