### PR TITLE
Optimize approximateTerrainHeights file for quicker page loads (Solves #6557)

### PR DESCRIPTION
**Pull request by tinco**
This solves #6557, it rounds the numbers in `approximateTerrainHeights.json`, I also added a script that performs this rounding in the Gulpfile, and left the original in `approximateTerrainHeightsPrecise.json` so if it ever needs updating or some other resolution that would be a simple change to the script.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @tinco! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/tinco/cesium/blob/optimize-approx-terrain-heights/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/optimize-approx-terrain-heights/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by tinco** [comment]
I forgot to run the test suite, it actually tests some values with EPSILON10 which is a bit strict, but I updated the values.

Now one integration test fails that seems like I really did break something. I'm not sure what I should do to figure out what's wrong.

**Comment by tinco** [comment]
I tried increasing the resolution to 10cm instead of 1m, but it didn't fix it. Maybe someone could explain to me what this integration test does and we can figure it out from there.

**Comment by tinco** [comment]
Eh.. ok so apparently it only fails on my machine? Forget I said anything ;)

**Comment by OmarShehata** [comment]
Thanks for doing this much needed cleanup @tinco ! We're in the middle of updating our CLA process - I'll get that sorted out in the next few days and then take a look at this.

**Comment by OmarShehata** [comment]
Thanks for submitting a CLA @tinco ! You are officially the first person to sign using the new system 🎉

I'll try to get this reviewed sometime next week.

**Comment by OmarShehata** [comment]
Thanks again @tinco ! A few thoughts:

* I'm not sure if any other gulp task does not have a mirror `package.json` task, so perhaps add one for `optimizeApproximateTerrainHeights` so it can be run in the same way?
* It might be worth adding a `precision` option so it can be easy to change (or that it's at least clear from a glance what it's using). Something like:

```
const precision = 1;
    return gulp.src('Source/Assets/approximateTerrainHeightsPrecise.json')
        .pipe(gulpJsonTransform(function(data, file) {
            Object.entries(data).forEach(function(entry) {
                var values = entry[1];
                data[entry[0]] = [Math.floor(values[0] * precision) / precision, Math.ceil(values[1] * precision) / precision ];
            });
            return data;
        }))
        .pipe(gulpRename('approximateTerrainHeights.json'))
        .pipe(gulp.dest('Source/Assets/'));
```

* Perhaps add a comment in the code above the task to explain that this can be used if this file needs to be regenerated, and that this is an approximation that's used only when the terrain provider doesn't have this information etc. for context?
* Can you fix the contributors.md merge conflict, and move CHANGES.md up to the right place? I did it in this commit https://github.com/AnalyticalGraphicsInc/cesium/commit/b32e48913a871a25219d989ab0a192a854aef154 but I can't seem to push directly to this PR.

Otherwise, this looks like a pretty straightforward change that shaves off a good ~300 kb. @mramato when you get a chance, sometime before the next release, can you take a second look here? The extra dependency is only a dev dependency so I think it should be OK here.

**Comment by tinco** [comment]
Thanks, applied all the changes you suggested :) hadn't seen the `package.json` commands

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @tinco! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Works great @tinco, thanks!  I executed your script to change `approximateTerrainHeights.json` to use 2 degrees of precision.  This keeps it at millimeter precision but reduces the file size from 517KB to 268KB

**Pull request merged**
