### PR TITLE
GlobeSurfaceTile uses TileBoundingBox

### PR DESCRIPTION
**Pull request by lilleyse**
For #3177 

Using `TileBoundingBox` inside `GlobeSurfaceTile` and `GlobeSurfaceTileProvider`.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Everything looks good.

Just a heads up that the following test passes in master but fails in this branch and `3d-tiles`:

image

**Comment by lilleyse** [comment]
I think that's because `viewRectangle` was removed in 1.17, and this test is not in master for some reason.

**Comment by pjcozzi** [comment]
Can you look into it?  It might have been removed from master, but then kept in `3d-tiles` because of a bad (auto-)merge.

**Comment by pjcozzi** [comment]
Also, can you please cherry pick commits for a pull request into master?  We could do this in one PR into master, and then the request scheduler in a separate PR into master.

**Pull request merged**
