### PR TITLE
fix drawing on point clouds with eye dome lighting

### LINKED ISSUE #6850: Tile debug bounding volumes clipped when EDL is enabled
The failing commit is https://github.com/AnalyticalGraphicsInc/cesium/commit/97074e5c968de24a6a1cce57ef010c2188d34af4 part of the EDL updates in https://github.com/AnalyticalGraphicsInc/cesium/pull/6801.

Not critical for the release but it would be good to fix since it's a regression since 1.47.

`1.47`

before

`master`

after

### PR DESCRIPTION
**Pull request by likangning93**
Fixes #6850.

[Sandcastle showing bug in `master`](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/Sandcastle/index.html#c=fVVtb+I4EP4rUb80SKxJSCCB7VbXFrqHtH0RZVd3J6STSQawzrEj22HhVv3vOzGEBNrdfMDEnpdnnmfG2VDlbBh8B+V8cgR8d+5AsyIj3+yee5nY1zspDGUC1GXb+TEXDj4soytQu2clNyxF72HlmSigBmaMwwPNX0BtWAKTU2P3EKN8CsVr30XBePog04LDV8XdyxutwejODLamUKA7jxRXysdUmfVkctnah3lttefitfVxLuZig/UwwQyj/FlqXKXAwg7h79AP/1ERkKWS2ZSm+F+7H7rED8IwjgI/DqLYC+Ow7Xgk9iI/iL1uFAWRF0W414vCgASDMBxEg7jr97tlzkbGJ8UAiTokbbD5J2AqsXpmJllPJec2/QhWCkC7vt8lg0Fv0O9Hftf3gl7cdj50fRKEwcDr9bw46oZ9v0SEgPqDnj/w43gQh37PprdCEZ2AAJLQDBQlSFqpX0VzCtowYWENz8lp701kjXz4TjUHKxDpTCFjS6myo2YP1Ci2DclkNH6cTWZ/11I0kXG5ooqZdcaSEeRmfVssl7bnlpRrOEpnsG0Q/Sl7+yUYzfaH7o+yaY75J1JMQctCJWBptT0zSd0gDsOW8/qGo1yxDOvbgCY0Td1Dxj3kwwvJJRPmjssifVlb5Qg1BkRRSWtUUWL+tTnsYCQz+MJWa6R+VbvUTjgmaTkRGdNAzBqEuyxEUiZwW9WQlZQgaGOZqhwXshBlkpd8DQo1t+c2dOWykFscIuB7aer+r6TKCm5Yzne3Oysnt2W59UwezI9aawJUm0eJU/c1n8l7toX0XmGvufvkrfYb38ao/TOePrWbeh5guK3WOerPgKQZtash39ab+6FhGQiNcHXzEtkAZtveI1Rq6tvkGdREaENFAneSS3WT50BV+Uq+jaez8V//3j9NH25mDfTpMTyGabbgsRw39DycxLYTHNaeXY9X0cd3C6pwnDb2+WmzpFVFxbAZpwE1ayg8PJO8YYaNq9iiQPRo1YhfPknJSs2XJekc003lb+m3Jm6TGLvhl0R4jZ9eq1Wnej3n5jfj2Aj9XJ28R0sFT5/yU203CTiqfirpr7vDPaeJSw3p0I5wo6qj5GVdtriL9sWVNjsO1/ujP1iW49CU15VLSMdAluOs4XdsUST/4SQnWpduV53K6SplG4eln+YXZ9/d+QWioFrjybLg/IX9D/OL66sO2p+4cWnvnyccCE53pcnav/6y3ySEXHXw9a2XkZIvqGpE/Ak)

[Sandcastle showing bugfix on deployed branch](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fixDrawOnEdl/Apps/Sandcastle/index.html#c=fVVtb+I4EP4rUb80SKxJSCCB7VbXFrqHtH0RZVd3J6STSQawzrEj22HhVv3vOzGEBNrdfMDEnpdnnmfG2VDlbBh8B+V8cgR8d+5AsyIj3+yee5nY1zspDGUC1GXb+TEXDj4soytQu2clNyxF72HlmSigBmaMwwPNX0BtWAKTU2P3EKN8CsVr30XBePog04LDV8XdyxutwejODLamUKA7jxRXysdUmfVkctnah3lttefitfVxLuZig/UwwQyj/FlqXKXAwg7h79AP/1ERkKWS2ZSm+F+7H7rED8IwjgI/DqLYC+Ow7Xgk9iI/iL1uFAWRF0W414vCgASDMBxEg7jr97tlzkbGJ8UAiTokbbD5J2AqsXpmJllPJec2/QhWCkC7vt8lg0Fv0O9Hftf3gl7cdj50fRKEwcDr9bw46oZ9v0SEgPqDnj/w43gQh37PprdCEZ2AAJLQDBQlSFqpX0VzCtowYWENz8lp701kjXz4TjUHKxDpTCFjS6myo2YP1Ci2DclkNH6cTWZ/11I0kXG5ooqZdcaSEeRmfVssl7bnlpRrOEpnsG0Q/Sl7+yUYzfaH7o+yaY75J1JMQctCJWBptT0zSd0gDsOW8/qGo1yxDOvbgCY0Td1Dxj3kwwvJJRPmjssifVlb5Qg1BkRRSWtUUWL+tTnsYCQz+MJWa6R+VbvUTjgmaTkRGdNAzBqEuyxEUiZwW9WQlZQgaGOZqhwXshBlkpd8DQo1t+c2dOWykFscIuB7aer+r6TKCm5Yzne3Oysnt2W59UwezI9aawJUm0eJU/c1n8l7toX0XmGvufvkrfYb38ao/TOePrWbeh5guK3WOerPgKQZtash39ab+6FhGQiNcHXzEtkAZtveI1Rq6tvkGdREaENFAneSS3WT50BV+Uq+jaez8V//3j9NH25mDfTpMTyGabbgsRw39DycxLYTHNaeXY9X0cd3C6pwnDb2+WmzpFVFxbAZpwE1ayg8PJO8YYaNq9iiQPRo1YhfPknJSs2XJekc003lb+m3Jm6TGLvhl0R4jZ9eq1Wnej3n5jfj2Aj9XJ28R0sFT5/yU203CTiqfirpr7vDPaeJSw3p0I5wo6qj5GVdtriL9sWVNjsO1/ujP1iW49CU15VLSMdAluOs4XdsUST/4SQnWpduV53K6SplG4eln+YXZ9/d+QWioFrjybLg/IX9D/OL66sO2p+4cWnvnyccCE53pcnav/6y3ySEXHXw9a2XkZIvqGpE/Ak)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @likangning93!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fixDrawOnEdl/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by likangning93** [comment]
2D/CV - as well as it did before.

**Comment by hpinkos** [comment]
Awesome, thanks @likangning93!

@lilleyse can you review and merge?

**Comment by lilleyse** [comment]
Looks good.

**Pull request merged**
