### PR TITLE
Fix Polylines in a PolylineCollection that cross the IDL

### PR DESCRIPTION
**Pull request by bagnell**
Fix adjacency information for lines in a `PolylineCollection` that cross the IDL. Similar to #3714.

Here's an example for a simple polyline and one that is subdivided to fit the ellipsoid:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', { sceneMode : Cesium.SceneMode.SCENE2D });

var polylines = viewer.scene.primitives.add(new Cesium.PolylineCollection());
polylines.add({
    positions : Cesium.Cartesian3.fromDegreesArray([-170.0, 30.0, 170.0, 30.0]),
    material : Cesium.Material.fromType('Color', {
        color : new Cesium.Color(1.0, 1.0, 0.0, 1.0)
    }),
    width : 10.0
});

polylines.add({
    positions : Cesium.PolylinePipeline.generateCartesianArc({
        positions : Cesium.Cartesian3.fromDegreesArray([170.0, -40.0, -170.0, -30.0])
    }),
    material : Cesium.Material.fromType('Color', {
        color : new Cesium.Color(0.0, 1.0, 1.0, 1.0)
    }),
    width : 10.0
});
```

### CODE REVIEW

**Comment by hpinkos** [comment]
The polyline looks bad during the transition from 2D to 3D.  Is that something we care about?

**Comment by hpinkos** [comment]
That's my only comment. This looks good!

**Comment by bagnell** [comment]
>The polyline looks bad during the transition from 2D to 3D. Is that something we care about?

Yeah, I'll take a look. It looks really bad for really wide lines.

**Comment by bagnell** [comment]
@hpinkos This is ready for another review.

I also fixed dynamic lines. Checkout the CZML Sandcastle example in 2D. Its easier to see if the polyline width is hardcoded to a large number.

**Comment by hpinkos** [comment]
Well, there's still some weirdness in the CZML example when transition from 2D to 3D, but it's not related to the IDL and it's the same in master.  I'll write up a separate issue for that.

This looks good to me!

**Comment by mramato** [comment]
@hpinkos if you're talking about the orbit lines, you are most likely seeing the ICRF to fixed transition that is not part of the morph and instead snaps the line.  There's a long standing issue for that (or at least used to be).  It's fixable but has never been a priority.

**Pull request merged**
