### PR TITLE
Fix problems with joinUrls and absolute URLs.

### LINKED ISSUE #3142: Regression layer.json with absolute URLs due to #3133
The layer.json of my Cesium terrain server defines an array of absolute URL
templates in order to allow parallel queries to subdomains.

Before #3133, the URLs were used as-is. Now, they are scrumbled:
- URL to layer.json: https://3d.geo.admin.ch/prefix/layer.json
- URL in layer.json: //terrain3.geo.admin.ch/prefix/{z}/{x}/{y}.terrain?v={version}
- generated terrain URL: https://3d.geo.admin.ch/prefix/prefix/0/1/0.terrain?v=1.0.0

The domain is incorrect and the prefix appears twice.

### PR DESCRIPTION
**Pull request by kring**
This is a bit... fiddly... but much better at least.
Fixes #3142

### CODE REVIEW

**Comment by gberaudo** [comment]
Thank you @kring, I confirm this fixes #3142.

**Comment by pjcozzi** [comment]
@mramato do you want to review this?  I'd like to merge it as soon as we can.

**Comment by mramato** [comment]
Thanks for testing @gberaudo and thanks for the fix @kring.

**Comment by gberaudo** [comment]
Thank you for the quick fix and merge.

**Pull request merged**
