### PR TITLE
Not sure how to repro this, but occasionally get undefined geometries…

### PR DESCRIPTION
**Pull request by dwhipps**
… and need to guard against undefined.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@dwhipps thanks for looking into this.  If you're able to create a test case to reproduce this, we can consider this fix; otherwise, this could be covering up a problem elsewhere that we do not want to cover up here.

**Comment by dwhipps** [comment]
Yeah, that just makes it tough to run my app, because I'm getting these crashes. Creating a test case is also tough, because the drawing is asynchronous, and so the stack I get is all inside Cesium code, with no obvious reference back to my own. I'll see what I can do.

**Comment by pjcozzi** [comment]
@dwhipps I'm going to close this but please re-open if/when appropriate.  As always, thanks for your support.

**Comment by mramato** [comment]
@dwhipps around line 264 of Primitive.js you can hard-code asynchronous to false and that will force all geometry to happen synchronously, which may give you a better callstack and shot at debugging this.

@pjcozzi I'm actually going to re-open this because I think I might know how to reproduce, (basically create an invalid geometry and then toggle it's show setting).

**Comment by pjcozzi** [comment]
Sounds good.

**Comment by dwhipps** [comment]
Not sure if this is it, but I'm getting a repeatable crash opening this KML file (with the latest release.) This is definitely a regression, because this file used to open for me just fine:

[Sandcastle](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=1d0975ebe0da022a89b5593e4de48fb5)

Here's a direct link to my KMZ file:
[https://earthdata.layeredearth.com/Layers/Earth/Climate/default%20cloud%20pattern.kmz](https://earthdata.layeredearth.com/Layers/Earth/Climate/default%20cloud%20pattern.kmz)

**Comment by dwhipps** [comment]
@pjcozzi @mramato are either of you able to repro this? I'm happy to take a stab at fixing it, but even with async=false, I don't get a decent stack.

**Comment by mramato** [comment]
Yes, I can reproduce this as well, thanks for the KMZ.  I got a decent stack from your example by turning "Pause on all exceptions" in the Chrome debugger (which will also break inside the web worker). At first glance, it looks like an exception deep in the geometry pipeline when combining instances, but it's possible that the real cause is simply a bad geometry computed earlier in the pipeline.  The good news is we should be able to isolate which geometry that is by looking at the state of some variables when the exception is thrown.  Since this crash was in geometry splitting code for 2D, I was able to isolate it further by changing the first line of your example to `var viewer = new Cesium.Viewer('cesiumContainer', {scene3DOnly: true});` adding scene3DOnly causes this to crash in the main thread in a different spot and points further to bad geometry (because the bounding sphere is huge).


I'm at a conference until Friday, so I can't look at this in more detail until I get back.  I'd be grateful if you took a shot at this if you can spare the time.  @bagnell or @hpinkos might have some thoughts as well, now that we have an easy to reproduce case.

If you can't get to it, I'll try and look at it as soon as I get back, since this is now a cut and dry test case.

**Comment by dwhipps** [comment]
For convenience, I'm adding the KML right here. Note how simple it is (Sorry for the formatting, MD doesn't love KML I guess):
`<GroundOverlay>`
	`<name>default cloud pattern</name>`
	`<Icon>`
		`<href>files/cloudimage.png</href>`
		`<viewBoundScale>0.75</viewBoundScale>`
	`</Icon>`
	`<LatLonBox>`
		`<north>90</north>`
		`<south>-90</south>`
		`<east>180</east>`
		`<west>-180</west>`
	`</LatLonBox>`
`</GroundOverlay>`

**Comment by dwhipps** [comment]
@mramato This last commit check for `undefined` cartographic positions of a BoundingSphere. In this instance, the RectangleGeometry covers the entire globe, and so the BoundingSphere has a centre of (0,0,0) and a radius equal to the radius of the Earth (which to me seems valid).

There is however no way to create a valid Cartesian representation of the BoundingSphere centre, and so we must check for that.

Note that this does NOT yet fix all the bugs. We still need to deal with the 2D case.

**Comment by dwhipps** [comment]
@mramato Any thoughts on this? Especially the last commit, ce28e99.

**Comment by pjcozzi** [comment]
@shehzan10 can you please review this?

**Comment by shehzan10** [comment]
@dwhipps Can you please update the source branch to `master`? Git doesn't seem to be playing too well when I'm trying to merge it locally.

In fact, since these are just a handful of changes, I would recommend that you start off with a clean `master`, add your changes to that and then force push to the branch `feature/undefined-geometries`.

**Comment by shehzan10** [comment]
The code is a fair solution to the problems put forth. The tests pass. Looks good to me (other than cleaning up the PR commits).

**Comment by dwhipps** [comment]
@shehzan10 I tried a rebase off master instead of a merge and it seemed to work. Let me know what you think.

**Comment by shehzan10** [comment]
Yeah, I don't think that worked (it's the same thing that was happening to me). It went from 4 commits to >250, so something wrong.

I would recommend started afresh with the latest master, adding the commits one at a time and then force push. It's just a few lines of code so shouldn't take long at all.

**Comment by shehzan10** [comment]
@dwhipps I have cleaned up the commits and opened #4912.

@pjcozzi We can close this PR and use #4912 to merge the commits.

**Comment by hpinkos** [comment]
replaced by #4912

**Pull request closed without merging**
