### PR TITLE
Fixed selection filtering for bloom

### PR DESCRIPTION
**Pull request by ProjectBarks**
Right now you can apply certain post process effects to just one feature. The bloom shader doesn't do any check to allow you to apply it to just to the selected feature as you would expect. Bloom post-processing is fixed by adding in the proper selection checks.

This is in reference to https://github.com/AnalyticalGraphicsInc/cesium/issues/7984

I was able to test using [this sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=vVZtb9M6FP4rph9oKhW3YwMEdBNjVLpIqzYpu/CBIuTGp63BsSPb6W7v1f77PXbcNGmLKkBQ9UNsn/Ocx895SVbMkJWAezDknCi4J1dgRZnTD2Ev6WZheaWVY0KB6fbJf1NF8GeXupT8UomcOSCviDMlTNVD7/VUTdUKUQtthRNaIW7EvGLG4RNTp3RudP4OFgbAJk9Onp7S4Yuzs+cnL/vk7IwOnw1PXwyfeygPVBqJGF1KB/hPWV5IeMccG+Sag7SDCnzCVHz6go90IWdd7x5uQZ1h2TfgY+WEWyNW3Aa/FmAp4zyJ11Is97fBmP1qo77Gq/oxnoT4uB09/a80onKuth5qQcScJI+iDLfaulujUVmbOraAazEzzKypsKmQqCo4B2lZFBrV4knkajNQ0OttgmVaWS2BSr1IundLYcnM6HuLWeQaLFHaEVtBELcEYmtgfwlHiio87Xp2D5uMWc/GbvUJMWmxQ9fGtDQwz6NrEPLILTMDWDCNm/rDpOeJbBFpiYppk1uaaalNo4T8kl6/n4wji5nE1F4q/nEpforI26Z/g0sLd0tnYRhnvga8TM/osGahdb6NHpZ1IyyZ4hIMruelykItIb2JLi3crLDHglOd2Wjd7sYUyYJKC5bBeIVl+1dl1CoOmjEMZz35Bg614N6ronSXIXKyoZDkegU5QvWa9Rv6VvheuZl9hczt1QKe1Z7YP/w2tsQmqv/5Wo+8OcxxavCkidlrRQyjxAuARCWeAseYn5r2tDAixyAr+NwI8kCw9+E4UssndmX/e7LerQugk5u/0/GXyc2Hcd0cdd4M+MsfT93m6fHjOg8crDN6nWyUOkw1hEvRJWPWYX9jodxpLWfMTECVyacYycE/DgdNNzB5gpQMCYVM0JOEku3GIYWVGkKgdZ36VgLahQ6KzWSg4+d5Q7tGb25t5gxz8LqJhXV/4HxrsStg8GgWz57CddymVat/WjfYWPnRW7+rDsi1HUC/rNSuCgel2pHzNyh1UIY9sfb1PKbUWx/4z4h0rJ6iiD9aLT+nVEtwL9Jnv+j0OyPr1hIuqoM3Ig9vWXznJ/h54gA/T/C1YgezEkeYo5kNE3k02DiNuFgRwc+nnZ1Pq2mHZJJZiyfzUspU/AvTzsVogPYtN6kZF2rhOUq29ibLk4vrapNSOhrgct/LVVOkgfg/)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ProjectBarks!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@OmarShehata or @lilleyse is this good with you?

**Comment by OmarShehata** [comment]
This looks good at first glance. It still won't allow you to select entities as features to apply the post processing to (as Brandon notes here https://github.com/AnalyticalGraphicsInc/cesium/issues/7984#issuecomment-520919370) but it's still a useful fix.

@ProjectBarks can you:

1. Check if any of the other post processing effects are missing a selected snippet like this? Would be good for consistency if it's easy to have them all respect this array.
2. Post more details about what you've found about why "only some entities/primitives" can be selected? You can put that in the linked issue. I thought it was just that you had to supply a primitive but it sounds like it's not that simple?

**Comment by ProjectBarks** [comment]
Responded in github issue.

**Comment by mramato** [comment]
@ProjectBarks please merge in master.

Where are we with this, is it just waiting for review?  @lilleyse need to take a look at this or is @OmarShehata comfortable with these changes?

**Comment by OmarShehata** [comment]
This looks good to me.

**Pull request merged**
