### PR TITLE
NoSleep library doesn't check if navigator is undefined

### PR DESCRIPTION
**Pull request by hpinkos**
This causes a `ReferenceError` when using cesium in node since navigator isn't defined

I'm going to submit a fix to the NoSleep repo too, to see if he'll take it.

### CODE REVIEW

**Comment by mramato** [comment]
Does this mean 1.18 is completely broken in Node?  If so, we should consider releasing a node-only 1.18.1

**Comment by hpinkos** [comment]
No, everything still runs.  There's just an error message in the console

**Comment by mramato** [comment]
Okay, update CHANGES to mention this since we shipped it with the problem.

**Comment by hpinkos** [comment]
@mramato ready

**Comment by mramato** [comment]
Thanks @hpinkos please write up a new issue that mentions the changes you made to NoSleep and a link to the pull request you open into their repository.  This way we can get back to the official release sooner rather than later.

**Pull request merged**
