### PR TITLE
Fix KML random colorMode returning the same color

### PR DESCRIPTION
**Pull request by jburr-nc**
Sometimes KMLs using the `<colorMode>random</colorMode>` property can return the exact same color for shapes in Cesium. In Google Earth they appear as having different colors.

The issue occurs when R, G, or B are 0 on one of the initial calls to `parseColorString`, in which case `colorOptions.red`, `colorOptions.blue`, or `colorOptions.green` can get set to 0.

On the next call to `parseColorString`, assuming R, G, and B are no longer 0, `colorOptions.maximumRed`, `colorOptions.maximumGreen`, and `colorOptions.maximumBlue` get set.  

When `Color.fromRandom()` gets called again, however, `red` still exists in the object, which ends up getting used instead of `maximumRed`:
https://github.com/AnalyticalGraphicsInc/cesium/blob/337ad9d7ebdc85172deb90cf2c21f9ca12844146/Source/Core/Color.js#L278

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @jburr-nc!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Awesome, thanks @jburr-nc!  Is there an easy way to add a unit test for this?  If not, could you send over a sample KML that so I can reproduce the bug this is fixing?  Thanks!

**Comment by jburr-nc** [comment]
[random3.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2055668/random3.zip)

**Comment by hpinkos** [comment]
Works great @jburr-nc!  Could you please add a unit test when you have a chance?

It could be something like this:
```js
CesiumMath.setRandomNumberSeed(0);
var kml = '<copy/paste two polygons from the kml you attached>';
return KmlDataSource.load(parser.parseFromString(kml, "text/xml"), options).then(function(dataSource) {
    expect(source.entities.values.length).toEqual(2);
    expect(source.entities.values[0].polygon.material.color.getValue()).not.toEqual(source.entities.values[1].polygon.material.color.getValue());
});
```

**Comment by hpinkos** [comment]
In the interest of getting this merged, I finished up adding a test for this.  Thanks for the fix @jburr-nc!

**Pull request merged**
