### PR TITLE
Normalize cross product result for up vector to fix #6640

### LINKED ISSUE #6640: rotationMatrixFromPositionVelocity not normalized cross product leads to rendering artefacts
Method  Cesium.Transforms.rotationMatrixFromPositionVelocity does not normalize the result of several cross product operations.

This leads to rendering artefacts similar to some observed in a different scenario (#3178) when a VelocityOrientationProperty is being used to generate a camera lookAt transform.

### PR DESCRIPTION
**Pull request by xtassin**
At minima, normalizing the up vector obtained from cross product resolves issue #6640

Other cross product results in this function could also be normalized but only the up vector was causing the effect noticed in the mentioned issue.

This is my first pull request to Cesium, let me know if anything wrong.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @xtassin!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Thanks @xtassin, we received your CLA, someone will review soon!

**Comment by hpinkos** [comment]
Thanks @xtassin!  I think we do also want to normalize the `right` vector.

And can you update `CONTRIBUTORS.md` in this pull request?  You can edit the file right on GitHub here: https://github.com/xtassin/cesium/blob/patch-1/CONTRIBUTORS.md

**Comment by hpinkos** [comment]
@xtassin do you have time to finish up this pull request?  We also want to normalize the `right` vector, then you should add yoursefl to the list in `CONTRIBUTORS.md`.  Thanks!

**Comment by hpinkos** [comment]
Sorry for the delay on this @xtassin, I didn't realize you had committed those changes.  Thanks for the contribution!

**Pull request merged**
