### PR TITLE
Initial WebStorm project

### PR DESCRIPTION
**Pull request by mramato**
This adds a basic WebStorm project for devs that want to use WebStorm. It's not as robust as the Eclipse set up yet, but I'll remedy that in a future PR.  For now:

1. Configure code formatters to mimic Eclipse formatting.  It's not 100% but it's close
2. Add a File Watch that triggers `ant build` whenever a glsl file is modified.
3. Mark `Build` directory as ignored, the root directory as resource root, and the `Specs` directory as test root.

`ant` is running the windows command right now, as there doesn't seem to be a good way to configure it cross platform, from what I can tell.

As an aside, I'm going create a roadmap to start to move us to `gulp` for any low hanging fruit, with the overall goal of moving away from ant completely.

### CODE REVIEW

**Comment by mramato** [comment]
Can someone please take this for a spin?

**Comment by emackey** [comment]
I think @jkrrv did some testing with this when he was here.  James are you still interested in testing a webstorm pull request?

**Comment by jkrrv** [comment]
@emackey: I'd be happy to.  It'll take me a couple days, to get to it, though.

**Comment by hpinkos** [comment]
This looks good to me! 
@mramato is this all set to be merged in?  Should we add documentation to the wiki somewhere?

**Comment by mramato** [comment]
There's a separate issue to update the wiki and I plan on opening some additional pull requests this week to further advance webstorm integration (and our build process), so I'll probably do one big update at the end of the week.

**Comment by jkrrv** [comment]
.gitignore should also have .idea/tasks.xml

Otherwise, looks good.

**Comment by mramato** [comment]
Thanks, I was unaware of `tasks.xml` but after double checking, I agree it should be ignored.

This is ready.

**Pull request merged**
