### PR TITLE
Ground atmosphere/fog hue, saturation and brightness shifts

### LINKED ISSUE #4195: Make fog color correspond to atmosphere color
So instead of this:
image

We could have something like this:
capture copy

This is just a simple PhotoShop so not at all physically correct. Perhaps that can be improved by the shader computations.

If this specific feature is not feasible then it would be nice to get a `color` property on the `Fog` class, so we can set it manually.

### PR DESCRIPTION
**Pull request by bagnell**
Added `atmosphereHueShift`, `atmosphereSaturationShift`, and `atmosphereBrightnessShift` properties to `Globe` which shift the color of the ground atmosphere to match the hue, saturation, and brightness shifts of the sky atmosphere.

Fixes #4195.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @bagnell!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
@OmarShehata would you like to review?

**Comment by OmarShehata** [comment]
@bagnell this looks good to me! I like the updated Sandcastle example.

The only failing test is a color test in ModelSpec `loads a glTF 2.0 model`. It might just need a bigger epsilon?

**Comment by bagnell** [comment]
> The only failing test is a color test in ModelSpec `loads a glTF 2.0 model`. It might just need a bigger epsilon?

These code changes don't affect anything in model so something else is causing that to fail.

**Comment by bagnell** [comment]
> I'm still seeing a failure on that test. It seems like the epsilon was changed from 5 to 10 here:

Right, so it shouldn't impact this PR and perhaps @lilleyse can take a look at it.

**Comment by OmarShehata** [comment]
I think we merge this then since that failing test is unrelated and everything else looks good (I don't have commit access so I can't merge).

**Comment by lilleyse** [comment]
Thanks @OmarShehata for the review. I had fun trying out the updated demo. Once CI passes I'll merge.

**Pull request merged**
