### PR TITLE
Align plane entities with ellipsoid surface

### PR DESCRIPTION
**Pull request by hpinkos**
Before: 
image

After: 
image

Thanks @bagnell for figuring out the math for this =)

@ggetz can you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by ggetz** [comment]
Thanks @hpinkos, will look at this soon.

**Comment by ggetz** [comment]
Everything looks good, thanks @hpinkos. It is worth re-snapping the Sandcastle thumbnail ?

**Comment by hpinkos** [comment]
@ggetz updated

**Comment by ggetz** [comment]
Thanks!

**Pull request merged**
