### PR TITLE
Added new Color operations

### PR DESCRIPTION
**Pull request by ggetz**
Added new functions to `Color`, including:
  - `add` - Adds two colors componentwise
  - `subtract` - Subtracts two colors componentwise
  - `multiply` - Multiplies two colors componentwise
  - `divide` - Divide two colors componentwise
  - `mod` - Mod two colors componentwise
  - `multiplyByScalar` - Multiply a color by a scalar componentwise
  - `divideByScalar` - Divide a color by a scalar componentwise

And updated `ColorSpec` for each of these new functions

### CODE REVIEW

**Comment by emackey** [comment]
I don't normally hear of `divide` or `mod` in regards to color.  Is there a use case in mind for color division?

More commonly, the opposite (or negative) of a `multiply` type color operation is called `screen` or some such, and the formula looks like this:

```
vec3 result_color = 1.0 - ( (1.0 - color_A) * (1.0 - color_B) );
```

This is kind of the photo-negative effect of `multiply`, and is useful for superimposing brighter things on darker things etc.

Also, `diff` is sometimes useful, it's essentially an absolute-value version of `subtract`.

Just my $0.02, not saying anyone needs to change the design here, just something to consider.

**Comment by pjcozzi** [comment]
@emackey this is for the 3D Tiles styling language where `Color` is a first-class type just like `Number`, `String`, etc.  I think it is important that we implement all the sane operators for completeness even if they wouldn't be widely used; think of this like a color that is a `vec4` in GLSL.

As for interesting color ideas, feel free post them here: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2

**Comment by pjcozzi** [comment]
P.S. it would be a killer code sprint project to extend 3D Tiles styling with new color operations...gamma correction...lighten...darken...whatever.  We could only put the pragmatic ones in the spec though.

**Comment by pjcozzi** [comment]
@ggetz code looks good.  Update CHANGES.md.

**Comment by ggetz** [comment]
Updated.

**Comment by pjcozzi** [comment]
Thanks @ggetz!

**Pull request merged**
