### PR TITLE
Add rollup plugin to strip pragmas

### PR DESCRIPTION
**Pull request by shehzan10**
Add a rollup plugin that removes pragmas from files.

The plugin takes include/exclude files as input along with an array of pragmas to remove, then removes them.

@mramato

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @shehzan10!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Thanks @shehzan10.  Sorry for all the conflicts  but I'm trying to clean up the git history for the ES6 work.  Can you reset this branch against `es6-modules` and retarget the PR?  Thanks!

**Comment by shehzan10** [comment]
@mramato updated to target es6-viewer and rebased of it.

**Comment by mramato** [comment]
Thanks.  I was thinking we may want to put this in its own subdirectory so that we can release it as it's own package later on, but that can happen when actually needed by our users (or ourselves for other repositories)

**Pull request merged**
