### PR TITLE
Code Review Guide

### PR DESCRIPTION
**Pull request by pjcozzi**
Please make edits and comments by end of Thursday:

* [Code Review Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/review-guide/Documentation/Contributors/CodeReviewGuide/README.md)

This is largely an reorganization of the [old guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Code-Review-Tips) with some new content.

**TODO**
* [x] Resize images
* [x] Remove old guide

### CODE REVIEW

**Comment by pjcozzi** [comment]
Also, not all the links will work until the branches for the other guides are merged.

**Comment by mramato** [comment]
This all sounds find to me.

Just a note that since we are maintaining our wiki as part of the code base now, we need to be really careful about submitting (or churn on) images in general, because anytime we resize or update them, the old binary stays around and bloats the size of the initial close.

**Comment by pjcozzi** [comment]
Ah yes, good call.

This is ready.

**Comment by pjcozzi** [comment]
This is ready.

**Comment by hpinkos** [comment]
@pjcozzi looks good! thanks

**Pull request merged**
