### PR TITLE
Added withCredentials to force sending PKI certificates

### PR DESCRIPTION
**Pull request by TJKoury**
Under certain versions of Firefox, cross domain requests will fail to send PKI credentials if the 'withCredentials' property is not set.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @TJKoury.  I don't think we have a Contributor License Agreement (CLA) from you.  Can you send one in?  See [CONTRIBUTING.md)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).

**Comment by TJKoury** [comment]
Sent, and I'll modify the CONTRIBUTORS.md.

**Comment by mramato** [comment]
Thanks @TJKoury. While I'm only slightly familiar with `withCredentials`, if I'm reading [MDN's page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) correctly, I think we may need to make this an option rather than always setting it to true.  I think there are also security implications since normally cookies are not sent with requests (but are when `withCredentials` is true.

From MDN:
> Line 7 shows the flag on XMLHttpRequest that has to be set in order to make the invocation with Cookies, namely the withCredentials boolean value.  By default, the invocation is made without Cookies.  Since this is a simple GET request, it is not preflighted, but the browser will reject any response that does not have the Access-Control-Allow-Credentials: true header, and not make the response available to the invoking web content.

I think having the ability to specify `withCredentials` is a good idea, we just need to understand the implications.

@shunter, any thoughts here?

**Comment by pjcozzi** [comment]
We received @TJKoury's CLA.

**Comment by TJKoury** [comment]
Keep this open, having an issue with non-PKI imagery.

**Comment by TJKoury** [comment]
@mramato You're absolutely right, setting it to 'always true' causes:
```javascript
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin'
```
When used with a provider that doesn't send back the requesting domain in the header.

**Comment by TJKoury** [comment]
@mramato @shunter Ok, so I've gotten to the point where it looks like I'm going to have to add an 'options' property to each element in the throttleRequestByServer.js -> activeRequests hash, so that it can be passed along with the url to the callback, then get every instance of the loadWithXhr method and extend it with a 'withCredentials' argument.  The only  other way I can see doing a 'cheat' is by adding a header and checking for the value during loadWithXhr then deleting it before the headers get assigned for the request, but that's not really a good way to do this, kind of hacky.

Anything obvious I'm missing here?

**Comment by mramato** [comment]
I'm not very familiar with the throttleRequestByServer code, so @shunter or @kring may be able to provide a better answer; but I'm pretty sure threading an extra options object through the system and down into `loadWithXhr` and related request is probably the way to go.

The (simpler) alternative you could try would be to add a global hook into `loadWithXhr` that calls a callback before `xhr.send` for every request that gets made.  This hook could take all of the options originally passed in as well as the xhr object itself.  That would give you a chance to look at the url and selectively set other options before the request is submitted.  The nice thing about this approach is that it would expose all xhr options for customization and is way easier to implement.  The downside is that it puts the onus on the user to detect the url each request and add the option, as opposed to setting it once for each instance at a high level, but the implementation is so much simpler that it might be the better way to go.

I think @shunter had some additional downsides to my xhr "hijacking" strategy, maybe he can chime in with some thoughts.

**Comment by TJKoury** [comment]
@mramato I think, if we go the hook route, we could just use the built-in Event class.  

After playing with it a few days, I'm more in favor of the extra options object for this particular use, as it should be easier to track xhr standards changes and create sane defaults in core Cesium that way.  It also leaves the option to have the same provider loaded with different options objects dynamically based on the network environment.

**Comment by pjcozzi** [comment]
If we want this in 1.15, please merge this tomorrow.  No rush, of course.

**Comment by TJKoury** [comment]
It's not going to make it, haven't had time to make all the changes
required.  Will get to it this weekend.

**Comment by TJKoury** [comment]
Closing this pull and reopening with newer version.

**Pull request closed without merging**
