### PR TITLE
Fix geocoder: true

### LINKED ISSUE #6826: Geocoder is not working if I provide true value explicitly
Geocoder is not working if I provide true value explicitly.

Please take a look on the following code:

Not working example:
`var viewer = new Cesium.Viewer('cesiumContainer',{
    geocoder: true,
});`

Working example:
`var viewer = new Cesium.Viewer('cesiumContainer',{
    /*geocoder: true,*/
});`

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #6826

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-geocoder/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Do all of the other widgets already handle this case?

**Comment by hpinkos** [comment]
@mramato yes, `geocoder` was the only one we were overloading this option for

**Comment by mramato** [comment]
Thanks @hpinkos!

**Pull request merged**
