### PR TITLE
remove useless argument of ScreenSpaceEventHandler

### PR DESCRIPTION
**Pull request by bbbbx**
see [https://groups.google.com/forum/?hl=en#!topic/cesium-dev/huOer7E71Iw](https://groups.google.com/forum/?hl=en#!topic/cesium-dev/huOer7E71Iw) for details

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @bbbbx! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/bbbbx/cesium/blob/fix-ScreenSpaceEventHandler/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-ScreenSpaceEventHandler/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by bbbbx** [comment]
I have signed the CLA.

**Comment by hpinkos** [comment]
@OmarShehata have we received a CLA?

**Comment by OmarShehata** [comment]
@hpinkos  yes, CLA is signed!

**Comment by hpinkos** [comment]
Thanks for the contribution @bbbbx !

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/huOer7E71Iw](https

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/8160 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Pull request merged**
