### PR TITLE
Added back in setting of ray origin to IntersectionTests.lineSegmentS…

### PR DESCRIPTION
**Pull request by jasonbeverage**
Fix for IntersectionTests.lineSegmentSphere where the ray origin wasn't set.

Adds back in line that was removed here
https://github.com/AnalyticalGraphicsInc/cesium/commit/86b7a495687c33b3b497e0e728b9e1e7a9ae663b#diff-455bf7b88a31361988ed51ee3e4683a1L347

### CODE REVIEW

**Comment by pjcozzi** [comment]
Hi @jasonbeverage, thanks for the fix!  Can you send in a Contributor License Agreement ([described here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request)) so we can review this?

**Comment by jasonbeverage** [comment]
Just sent it out.

**Comment by pjcozzi** [comment]
Thanks, we received it.  Can you update CHANGES.md in the root directory?

@bagnell can you review this?

**Comment by jasonbeverage** [comment]
I added two new changes.  One updating the CHANGES.MD and another removing the var origin since it is never used and causes jshint to fail.  That was probably the original reasoning for removing the line in the first place :)

**Comment by bagnell** [comment]
Can you merge master? There's probably a trivial conflict in `CHANGES.md`.

**Comment by jasonbeverage** [comment]
Just merged, sorry about that.

**Comment by bagnell** [comment]
Looks good. Thanks!

**Pull request merged**
