### PR TITLE
DeviceOrientationCamera 

### PR DESCRIPTION
**Pull request by malaretv**
WIP

An attempt to address the device orientation issues laid out in #4135

Instead of repeatedly applying deltas of the device orientation to current camera orientation this approach maps it directly to the scene (taking into account device orientation).

The overall behavior is improved as far as responding to orientation changes. Now need to look into better orientation on intializing -- shouldn't have to know where true north is to find the globe :)

Other potential issues:
- iOS does not support screen orientation API. We could probably safely default to primary-landscape (90deg) as was done before.

### CODE REVIEW

**Comment by hpinkos** [comment]
Great, thanks for the pull request @malaretv!  @bagnell can you take a look at this when you have a chance?

**Comment by pjcozzi** [comment]
@emackey are you familiar with this code?  Would you be able to review this?

**Comment by emackey** [comment]
@pjcozzi I'm not, unfortunately.  It's on my list of things to investigate when I get back into VR stuff.

**Comment by pjcozzi** [comment]
@bagnell could you review this then?

**Comment by hpinkos** [comment]
@bagnell can you review this when you get a chance?

**Comment by malaretv** [comment]
Any word on this? I'll have some downtime soon and wiling to revisit and work with y'all to get a fix in.

If the pull request is unacceptable as-is I'm open to feedback as to approaches that could work better!

There's also https://github.com/dorukeker/gyronorm.js if willing to offload getting consistent gyroscope values across devices to a third-party lib.

**Comment by hpinkos** [comment]
Sorry it's taken so long for us to get to this @malaretv.  We'll try to carve out some time to review it soon.  Thanks!

**Comment by pjcozzi** [comment]
Also added to #3422.  There's potential for VR work to pick up soon.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @malaretv! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @malaretv! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
I'm going to close this PR because no commits have been made in over 2 years and I'm sure it needs a lot of updating before we can review it again.

Thanks for putting the time into this @malaretv!  We're hoping to make some WebXR improvements this year and will certainly use the changes in this PR as a reference.

**Pull request closed without merging**
