### PR TITLE
Enable webgl2 by default

### PR DESCRIPTION
**Pull request by lilleyse**
Uses a WebGL2 context by default if it's available.

Not ready to merge. However because of #5623 we are fairly far along and a lot of the Sandcastle demos I've tried do run. Way more testing is needed though.

TODO:
* [ ] Update CHANGES.md
* [ ] Testing and bug fixes

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@lilleyse, thanks for the pull request! Maintainers, we have a signed CLA from @lilleyse, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
An error I pretty much always see if the globe is enabled:
capture

**Comment by lilleyse** [comment]
In http://localhost:8080/Apps/Sandcastle/index.html?src=Polygon.html&label=Geometries

polygon

**Comment by mramato** [comment]
FYI, Firefox gives a similar (and perhaps more helpful) error:

> Error: WebGL warning: drawElements: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: Because minification or magnification filtering is not NEAREST or NEAREST_MIPMAP_NEAREST, and the texture's format must be "texture-filterable".
> 
> Context.js:973:17

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Something changed for terrain loading using WebGL 2 between the 1.46 and 1.47 release.  We'll have to make sure that's fixed before this gets merged.  See this issue: #6756

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
Closing due to inactivity.

**Pull request closed without merging**
