### PR TITLE
Update third party library contributing advice

### PR DESCRIPTION
**Pull request by OmarShehata**
The contributing guide currently tells you to start a new forum thread if you're thinking about adding a third party library:

> If you added third-party libraries, including new version of existing libraries, update [LICENSE.md](LICENSE.md).  Mention it in [CHANGES.md](CHANGES.md).  If you plan to add a third-party library, start a new thread on the [Cesium forum](http://cesiumjs.org/forum.html) first.

Based on what I've seen, technical discussions are more productive in GitHub issues. In this case, I think it would make sense to open a PR for feedback and have that discussion there instead of a forum thread.

Thoughts?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/patch-5/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by OmarShehata** [comment]
@mramato what do you think?

**Comment by pjcozzi** [comment]
Please don't remove the whole sentence, just tell them to submit an issue to discuss it; we generally don't want large third-party libraries and definitely do not want ones with incompatible licenses so we want these discussed in advance before a contributor puts in too much effort.

**Comment by OmarShehata** [comment]
@lilleyse since Patrick's out this week, do you want to merge this?

**Comment by lilleyse** [comment]
Looks good based on the feedback already in here.

**Pull request merged**
