### PR TITLE
Add tapered glowing lines as an option on PolylineGlowMaterial.

### PR DESCRIPTION
**Pull request by emackey**
This adds a new `uniform` parameter to `PolylineGlowMaterial` called `taperPower`, to go alongside the existing `glowPower` parameter.

When set, this parameter will taper off the glowing line, using a strength falloff profile that matches the `glowPower` falloff for the equivalent number.

The default value is `1.0`.  Numbers `1.0` and higher produce no tapering effect, so, the default behavior will exactly replicate the look of `PolylineGlowMaterial` prior to the introduction of this new parameter.

The core of what actually changed here is in the file `PolylineGlowMaterial.glsl`.

The best sample usage of this new parameter is in the [**HeadingPitchRoll** demo](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/polyline-glow-taper/Apps/Sandcastle/index.html?src=HeadingPitchRoll.html), where the aircraft now leaves behind a tapered glowing line, simply by adding the new parameter to its code.  Use the arrow keys to steer the aircraft.

taperlinedemo

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/polyline-glow-taper/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by emackey** [comment]
More [demo fun](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/polyline-glow-taper/Apps/Sandcastle/index.html#c=pVZbb9s2FP4rRF5qLwot59KkthvMcLuhQxobidG9GBgY6djmSpECSdnxivz3HlIXU06ALJsebPHcz3c+ktowTTYctqDJRyJhSyZgeJHRb17WeZf45URJy7gE/S4iPxaS4GPWqhDpWPKMWSADYnUBC/nUHS7kQm4wqiyyB9DT5VgnBmNfxMNSbizT9kZJlJ1cnreEzKLw7EMZwhdAE6GS7+XvHZMrQIOqwkkjozfT6eyv+/l0NjzwywpheS64765/FcdNdT7hnGcuYMulUVSVZTytzKq8fxSCM/kJu6YsTe8hUTI1ncYtIudnp3EchWDuXTrdbtOxyt8Y+Or9+SuBF3KpNOm4+BwDx0P8G7UmMSTHx7xbD9EZJkooHcDqlnSpVYbYpirrVKbuYSJfM5x1n8al0I+7DuQ6KudahfrK7JpKeLRlpFtfRqdLfiFnF1fkhPQvPxy6ewa86t6/dO5XJVGcf69HJhocERnG0Yyv1vZEIGFJ7oLsk+Ra5aDtrk32e5blAtKZMtxyJWeVUafdHc6htgjgQim+MXnmMfsEKw1QTQ3BiBpmRySuw9VF+DH71OGUW4kO8X1DAX4YUQ3ra+lLMkatJN0Q39+4TIldg9sQueLSErX06xpvD3VEcFYEBQYItwYZY7ktUghGgP4z799qQa00y9c88U00PXWaWldgvzFRQKfaj926mzocXYOv4l/Q5yJ2Dzkmp+Xb8KC4BuLqYDAJSKAroR6AghA8N4qnNAmqnqt9yfvtUpfW2rL7edVbtgL4DlLlAXU4EqvIA/il82U6oe3hvY3A/4FxL7hU0EchSv+PVPWmleSzRKLsXNt4sWx94/um3WRwVdk0cwG35mBczvCYyusJDpqyor0W084dyp6D3BCVO1smIvKF/F0YS7ZMWkh9KeBYTMPIzmlAgmRezB9B3PN/3D14FbV15fE6aB+v87vx7f1sfPf5dn5grgrrzq1J5eW9Xzb5k6fIkwE522ufAkvPomeVajBKFBU4fXdPtfXuMtecCdQG9JopsXMpfxdq+7WyaDh2kME9uFW2M+W+KQYkpv330XMTy9B7b3N68YJNEoLQVj91D+y3FRr9w44EMM9azHKgceeWKFV96McBjMHlVr425KM1t6gB+wV5onMlmBNMPY1MCAcP9eXBjBWGnbYsxmKlNLfrbM+WG4YHDH7huAFIlSHs4xwp/eg+utAjqBNrPoqORsbuBFyX8l95littSaFFh9KeBdyVODzTeyiS72BpYozzHPVqp1HKN4SnHxdHB199iyOSCGYMapaF8ExfHF2PemjfchOKpVyuphvQgu2cybp/fVMKKaWjHi6fe1mlxAPTQcSf).

TaperExplosion

**Comment by emackey** [comment]
I merged master in here, but the tests failed.  The failures look like they might be related to #7579, createImageBitmap.

**Comment by emackey** [comment]
Merged master again, nothing test-related there, but tests pass this time.

**Comment by emackey** [comment]
This is ready.

**Comment by bagnell** [comment]
👍  Thanks @emackey.

**Comment by iamsee** [comment]
@emackey  the demo page is 404

**Comment by OmarShehata** [comment]
@iamsee you can get the updated demo URL by taking the same query parameters with the `sandcastle.cesium.com` domain. [Here's a working link](https://sandcastle.cesium.com/index.html#c=pVZbb9s2FP4rRF5qLwot59KkthvMcLuhQxobidG9GBgY6djmSpECSdnxivz3HlIXU06ALJsebPHcz3c+ktowTTYctqDJRyJhSyZgeJHRb17WeZf45URJy7gE/S4iPxaS4GPWqhDpWPKMWSADYnUBC/nUHS7kQm4wqiyyB9DT5VgnBmNfxMNSbizT9kZJlJ1cnreEzKLw7EMZwhdAE6GS7+XvHZMrQIOqwkkjozfT6eyv+/l0NjzwywpheS64765/FcdNdT7hnGcuYMulUVSVZTytzKq8fxSCM/kJu6YsTe8hUTI1ncYtIudnp3EchWDuXTrdbtOxyt8Y+Or9+SuBF3KpNOm4+BwDx0P8G7UmMSTHx7xbD9EZJkooHcDqlnSpVYbYpirrVKbuYSJfM5x1n8al0I+7DuQ6KudahfrK7JpKeLRlpFtfRqdLfiFnF1fkhPQvPxy6ewa86t6/dO5XJVGcf69HJhocERnG0Yyv1vZEIGFJ7oLsk+Ra5aDtrk32e5blAtKZMtxyJWeVUafdHc6htgjgQim+MXnmMfsEKw1QTQ3BiBpmRySuw9VF+DH71OGUW4kO8X1DAX4YUQ3ra+lLMkatJN0Q39+4TIldg9sQueLSErX06xpvD3VEcFYEBQYItwYZY7ktUghGgP4z799qQa00y9c88U00PXWaWldgvzFRQKfaj926mzocXYOv4l/Q5yJ2Dzkmp+Xb8KC4BuLqYDAJSKAroR6AghA8N4qnNAmqnqt9yfvtUpfW2rL7edVbtgL4DlLlAXU4EqvIA/il82U6oe3hvY3A/4FxL7hU0EchSv+PVPWmleSzRKLsXNt4sWx94/um3WRwVdk0cwG35mBczvCYyusJDpqyor0W084dyp6D3BCVO1smIvKF/F0YS7ZMWkh9KeBYTMPIzmlAgmRezB9B3PN/3D14FbV15fE6aB+v87vx7f1sfPf5dn5grgrrzq1J5eW9Xzb5k6fIkwE522ufAkvPomeVajBKFBU4fXdPtfXuMtecCdQG9JopsXMpfxdq+7WyaDh2kME9uFW2M+W+KQYkpv330XMTy9B7b3N68YJNEoLQVj91D+y3FRr9w44EMM9azHKgceeWKFV96McBjMHlVr425KM1t6gB+wV5onMlmBNMPY1MCAcP9eXBjBWGnbYsxmKlNLfrbM+WG4YHDH7huAFIlSHs4xwp/eg+utAjqBNrPoqORsbuBFyX8l95littSaFFh9KeBdyVODzTeyiS72BpYozzHPVqp1HKN4SnHxdHB199iyOSCGYMapaF8ExfHF2PemjfchOKpVyuphvQgu2cybp/fVMKKaWjHi6fe1mlxAPTQcSf).

**Comment by iamsee** [comment]
@OmarShehata  thx

**Pull request merged**
