### PR TITLE
Billboard depth testing performance improvements

### LINKED ISSUE #6699: Billboard depth testing performance improvements
Leftover from #6621 

Right now we're doing the depth testing checks in the fragment shader.  We can move most of this to the vertex shader (when texture reading in the vertex shader is supported), but the math will be slightly different for computing the screen coordinates.

See this comment: https://github.com/AnalyticalGraphicsInc/cesium/pull/6621#discussion_r195212797

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #6699

Moves the billboard depth test logic to the vertex shader when texture reads from the vertex shader are supported.  Otherwise it falls back to doing the depth test in the fragment shader.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/billboard-depth-vs/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@bagnell can you review?

**Comment by hpinkos** [comment]
Here's the sample code from my last PR:

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: Cesium.createWorldTerrain()
});
viewer.scene.globe.depthTestAgainstTerrain = true;

var e = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
    billboard : {
        image : '../images/Cesium_Logo_overlay.png',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM
    }
});

viewer.trackedEntity = e;
```

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: Cesium.createWorldTerrain()
});
viewer.scene.globe.depthTestAgainstTerrain = true;

var e = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
     label : {
        text : 'Clamped to ground',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
        horizontalOrigin : Cesium.HorizontalOrigin.CENTER,
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM,
        fillColor : Cesium.Color.BLACK,
        showBackground : true,
        backgroundColor : new Cesium.Color(1, 1, 1, 0.7),
        backgroundPadding : new Cesium.Cartesian2(8, 4)
    }
});

viewer.trackedEntity = e;
```

**Comment by bagnell** [comment]
When the origin is the top right, it seems like it is only depth testing that point. You can see that the top left is not behind any terrain.
billboard_depth_test_top_right

**Comment by hpinkos** [comment]
Thanks @bagnell, I think this is ready now

**Comment by bagnell** [comment]
@hpinkos Just had some formatting changes in ce49ae9. Everything else looks good. Thanks!

**Pull request merged**
