### PR TITLE
Vanishing atmosphere when looking up #3347

### LINKED ISSUE #3347: Atmosphere disappears as you look up
Reported on the forum https://groups.google.com/forum/?hl=en#!topic/cesium-dev/su5kb_cNN7Y

This seems to have been introduced in 1.16.

* Zoom into the globe and tilt
* Middle mouse drag on the sky to keep tilting up
* The atmosphere flickers then disappears completely when the globe leaves the bottom of the screen

### PR DESCRIPTION
**Pull request by likangning93**
Fixed #3347 

It seems like this problem was caused by commit 4cccade8135aea8070c1daba84fcec43fb892ec1. I think this was to prevent the atmosphere from rendering before tiles were ready, but the way it was handled caused the atmosphere to vanish if no tiles were being rendered (fully skyward view).

Also updated CHANGES.md.
disappearing atmosphere snip

### CODE REVIEW

**Comment by likangning93** [comment]
Now we can view the solar eclipse on September 1st of this year! As seen from Madagascar:

eclipse sept 1 2016 madagascar

**Comment by lilleyse** [comment]
Nice fix!

**Comment by pjcozzi** [comment]
Wow great fix, thanks @likangning93!

Can you please post to [this thread](https://groups.google.com/forum/?hl=en#!topic/cesium-dev/su5kb_cNN7Y) (linked from #3347) and let them know that this is fixed and will be in Cesium 1.22 next Wednesday?

Also, if you are interested in solar eclipse, see http://cesiumjs.org/2015/03/19/EclipseTracks-Interactive-Solar-Eclipses-with-Cesium/

**Comment by mramato** [comment]
Now you just need to make the sky goes dark and the moon casts a shadow on the Earth :)

**Pull request merged**
