### PR TITLE
Update dojo 1.9.3 -> 1.10.4

### PR DESCRIPTION
**Pull request by mramato**
The version we have is old and until Sandcastle gets its much needed makeover, we should stay current with dependencies.  No changes were needed on our end.

@emackey I'm pretty sure everything still works, can you run Sandcastle thru its paces too just to be sure.  Thanks.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Worth an update to CHANGES.md?  Maybe not since it is just used in Sandcastle, not Cesium.

Any update to LICENSE.md?  Again, probably not, but just want to be sure.

**Comment by mramato** [comment]
> Maybe not since it is just used in Sandcastle, not Cesium.

Exactly, we had problems in the past with people thinking Cesium itself used Dojo.

> Any update to LICENSE.md?

No changes, unless you count the Copyright year, the license now says `2005-2015` instead of `2005-2011`  Not sure it matters and I'm guessing a lot of our libraries are out of date if you consider it does.

**Comment by pjcozzi** [comment]
> No changes, unless you count the Copyright year, the license now says 2005-2015 instead of 2005-2011 Not sure it matters and I'm guessing a lot of our libraries are out of date if you consider it does.

Perhaps submit an issue for us to update all of them.  It would be good for someones first commit.

**Comment by mramato** [comment]
#3234

**Comment by emackey** [comment]
Seems to work fine.

**Pull request merged**
