### PR TITLE
Expose DEFAULT_OFFSET from Camera

### LINKED ISSUE #2599: Ability to set home offset
We currently expose `Camera.DEFAULT_VIEW_RECTANGLE` and `Camera.DEFAULT_VIEW_FACTOR` but we don't expose anything like `Camera.DEFAULT_OFFSET`, which I imagine would be an HPR.  We should expose such a value and use it in the `HomeButton` widget.

### PR DESCRIPTION
**Pull request by bampakoa**
Closes #2599

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks for the pull request @bampakoa!  We got your CLA emails and we'll try to review this next week.

**Comment by emackey** [comment]
Can we easily explain to users the difference between this and `Camera.DEFAULT_VIEW_FACTOR`?  How does a user decide which one to use?

**Comment by bampakoa** [comment]
@hpinkos Do I need to elaborate further more on the documentation, as @emackey refers, in order for the PR to be reviewed?

**Comment by emackey** [comment]
@bagnell When you get a minute, what do you think of this?

**Comment by bagnell** [comment]
@bampakoa I think this is great. 
@emackey You can merge this whenever its ready.

**Comment by emackey** [comment]
Thanks @bampakoa.  I'll add a note in CHANGES.md in master.

**Pull request merged**
