### PR TITLE
Added (lon, lat, height) to Geocoder

### PR DESCRIPTION
**Pull request by pjcozzi**
Awesome for testing.  Totally understand if we don't want to advertise it.

Part of #1262.

### CODE REVIEW

**Comment by mramato** [comment]
I'll take a look at this as soon as I have a chance, thanks for getting the ball rolling on this.

I think there are some good coordinate parsing functions out there on the web that can handle multiple formats (degrees/minutes/seconds/lla/utm/etc...).  If I can find a good one it would definitely make this a feature to advertise.

**Comment by pjcozzi** [comment]
I'm trying to consolidate the number of branches I am maintaining.   Can we merge this (now or after #2495)?  I'm totally cool with not documenting it if that would make us more comfortable.

**Comment by mramato** [comment]
I'll look at this soon.  Just assume I'll maintain this branch from now on.

**Comment by mramato** [comment]
I made some tweaks, mostly to be more tolerant of whitespace.  Other than that, this looks good.  Eventually we'll add more control over the geocoding process in general, but this is a good interim step that won't cause issues down the line.

**Comment by pjcozzi** [comment]
Cool, thanks.

**Pull request merged**
