### PR TITLE
The depth plane should only be rendered in 3D.

### LINKED ISSUE #3748: Large missing section of primitive when switching from 3D to Columbus View
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/5A1-br_4iu4

The first example is 3D -> CV
artifact

The second example is 2D -> 3D -> CV
artifact2

As far as I can tell, this was introduced in 1.17
Run this example, and change the scene mode to 3D and then to CV.  Then tilt the map to see the artifact.
```
var viewer = new Cesium.Viewer('cesiumContainer', {sceneMode: Cesium.SceneMode.SCENE2D});

viewer.entities.add({
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-170.0, -80.0, 170.0, 90.0),
        material : Cesium.Color.YELLOW.withAlpha(0.5),
    }
});
```

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #3748.

The depth plane should only be rendered in 3D. This is probably a copy-paste error that went unnoticed during on of the Scene was refactors.

### CODE REVIEW

**Comment by bagnell** [comment]
Thanks for looking into this @santilland! Your comment narrowed down the search for this bug.

**Comment by pjcozzi** [comment]
Update CHANGES.md.

**Comment by bagnell** [comment]
@pjcozzi CHANGEs.md is updated.

**Comment by pjcozzi** [comment]
Looks good.  Thanks again for the research, @santilland!

**Pull request merged**
