### PR TITLE
Add ion Assets Sandcastle tab and new assets to BaseLayerPicker

### PR DESCRIPTION
**Pull request by mramato**
1. Add `Sentinel-2`, `Blue Marble`, and `Earth at night` to BaseLayerPicker
2. Removed old Black Marble from the BaseLayerPicker.
3. Add new `ion Assets` tab to Sandcastle to showcase initial assets available to Cesium users.
4. Update ArcticDEM example to use ion version instead of deprecated assets.agi.com.
5. Rename `PATerrain` example to the more accurate `PAMAP Terrain` and have it use ion version instead of deprecated assets.agi.com.
6. Add bare bones `Blue Marble`, `Cesium World Terrain`, `Earth at Night`, `Natural Earth II`, `Sentinel-2`, and `Washington DC 2017` examples.
7. Update examples using deprecated cesiumjs.org version of Black Marble to use the newer Earth at Night ion asset.
8. Resize some overly-large gallery images.

CC @pjcozzi

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@mramato, thanks for the pull request! Maintainers, we have a signed CLA from @mramato, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
At quick glance, all sounds good. :rocket: 

Can someone please do a quick review of the examples?

**Comment by hpinkos** [comment]
- Add a view picker to the Cesium World Terrain example
- It might be helpful to add some in-line comments explaining about the data sets.  I saw you populated the info dropdown, but I don't think many people know it exists.
- `ArcticDEM` -> `ArcticDEM Terrain`?  It might help distinguish between imagery and terrain examples.
- Replace the Washington DC thumbnail with a picture of some landmark in DC
- Change the thumbnail for 'Earth at Night' to something that is a more recognizable land form.  Like zoomed out on the US.
- Turn off the base layer picker for all these examples

**Comment by hpinkos** [comment]
Should we link to a terms of use or a blog post about ion from the examples?

**Comment by mramato** [comment]
> Add a view picker to the Cesium World Terrain example

The larger `Terrain` example already covers several views.  Already discussed this offline with @pjcozzi These examples are intentionally sparse and temporary.  There current purposes is to show how to access the available assets.  Most will actually go away in a couple of months.  

> It might be helpful to add some in-line comments explaining about the data sets. I saw you populated the info dropdown, but I don't think many people know it exists.

This I'll do.

> ArcticDEM -> ArcticDEM Terrain? It might help distinguish between imagery and terrain examples.

DEM implies it's a terrain example, we don't add "Imagery" to the imagery examples, so I'm not sure this makes sense.  I think we'll be fine once I add additional comments.

> Turn off the base layer picker for all these examples

I see no reason to do this.  Our examples always do too much.  The point of this example is to show how to load the layer.  Disabling the base layer picker adds nothing to the example.

**Comment by hpinkos** [comment]
> Disabling the base layer picker adds nothing to the example.

I don't like that the base layer picker has no icon for the imagery examples

**Comment by mramato** [comment]
> I don't like that the base layer picker has no icon for the imagery examples

You were the one that request we show nothing when an item wasn't selected, and the lack of an icon has nothing to do with the example.  I stand by my comment.

**Comment by mramato** [comment]
This is ready.

**Comment by hpinkos** [comment]
Thanks

**Pull request merged**
