### PR TITLE
skyBox, skyAtmosphere, globe

### PR DESCRIPTION
**Pull request by emackey**
Three new/updated options for CesiumWidget & Viewer.  `skyBox` was already an option, but it was impossible to specify the absence of a skyBox with `false`, so that has been added.  `skyAtmosphere` is a new option, for those that don't want the Earth's glow.   `globe` is a new option for those who are currently specifying `imageryProvider=false`, to disable rendering of the globe.  This last one allows users to place the camera inside of the Earth, looking out, with code like this:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    globe: false,
    imageryProvider: false,
    baseLayerPicker: false,
    skyAtmosphere: false,
    mapProjection : new Cesium.GeographicProjection(new Cesium.Ellipsoid(1,1,1))
});
viewer.dataSources.add(Cesium.CzmlDataSource.load('../../SampleData/simple.czml'));
```

I haven't written tests for this branch yet as there was some debate over its usefulness.  I'll concede that this is not the "right" way for a particular use-case I had in mind, however, I still think there are other cases where these options are needed.  Several users have asked on the mailing list how to turn off `skyBox` and the answer is to destroy the default one after construction.  Same answer for `skyAtmosphere`.  Turning off the globe is a valid case for those wishing to place the camera inside (for example, the projection dome that we currently power with a special build of STK, might be replaced by this someday).

Let me know if this might get merged, I'll write the tests.

### CODE REVIEW

**Comment by pjcozzi** [comment]
```javascript
    skyAtmosphere: false,
    skyBox: false
```
These are good with me.
```javascript
    globe: false,
```
I'm fine with this too, but agree it is not ideal.

I'd write tests and merge if @mramato it is OK with it.

**Comment by pjcozzi** [comment]
What is the plan here?  If we want this for 1.8, please merge this week.

**Comment by emackey** [comment]
I'll write the tests.  If I don't get to it in time, it can go in 1.9.

**Comment by emackey** [comment]
This is finally ready!

**Comment by pjcozzi** [comment]
Thanks @emackey

**Comment by mramato** [comment]
As we discussed offline, I was originally against this change mainly because I think it will be really hard to maintain (anywhere that uses scene.globe now has to verify that the globe exists and that's an easy mistake to make).  Is there a reason we chose to not create the globe rather than simply hide it with `globe.show = false`?  You aren't really losing out on anything memory wise and that function already exists.  It also removes my main issue (that the making scene.globe unavailable).

I also think that our rats nests of incompatible Viewer options arguments needs to be dealt with, this isn't this PRs fault, but I think the better solution is to allow people to specify whatever values they want and we only actually throw if there's a direct incompability.  For instances, BaseLayerPicker without a globe should be no problem if we go with my suggestion above.  I tried to shut the globe off and had to play "add the property" until it stopped throwing exceptions.  This will frustrate users as well.

Thoughts?

**Comment by emackey** [comment]
I agree the options are getting a bit out of control.  I do want the user to have the option of supplying a non-Earth globe, if they desire.  Also, `Scene` is not guaranteed to have a globe, and most of its unit tests take place without a globe, so no code should assume that scene.globe is defined.  The ellipsoid can be had from `scene.mapProjection.ellipsoid` regardless if a globe is available.  I believe it saves some ellipsoid terrain generation work when the globe is off.

I do like the idea of auto-setting the options that need to be set false.  I'll open a separate PR.

**Comment by pjcozzi** [comment]
Whatever you guys want to do is fine, but if something is being added to or removed from 1.8, please do it ASAP.

**Comment by mramato** [comment]
I'm still not sold on the idea of the globe going away, but since @pjcozzi was okay with it, I'll deal.  I just think Viewer has way too many constructor options at this point.

**Comment by mramato** [comment]
I think one solution (definitely not for tomorrow) is to deprecate a bunch of the top-level options and make them sub-objects, I'm not sure why we didn't do that before.  I don't want to start making changes until we are sure though because this is a high-level area of the code and I'd like to avoid churn.

**Pull request merged**
