### PR TITLE
Use https://

### LINKED ISSUE #3650: Use https instead of `//` everywhere by default
Traditionally, using `//` was standard practice because it would use the protocol of the existing page, i.e. `http` on http pages, `https` on https pages. With the pending transition to https everywhere, it makes sense for us to replace `//` everywhere we currently use it with `https` instead.

Furthermore, using `//` in offline apps (such as cordova or webviews) causes `//` to become `file://` which means Cesium is broken by default in those situations.  This will save developers writing those apps the initial headaches they've had in the past.

### PR DESCRIPTION
**Pull request by TomPed**
Fixes #3650

### CODE REVIEW

**Comment by mramato** [comment]
Please update changes and mention that all external urls are now `https` by default and that this will make Cesium work better our of the box for non-server-based applications.

**Comment by mramato** [comment]
`KmlDataSource` still has a `//maps.google.com` link that should be https.  You will also need to update a test that checks for it in `KmlDataSourceSpec`

**Comment by mramato** [comment]
Just those 2 comments, other than that this looks good.  Thanks @TomPed!

**Comment by TomPed** [comment]
Updated.

**Comment by mramato** [comment]
Thanks @TomPed!

**Pull request merged**
