### PR TITLE
work around webpack build warning with earcut

### PR DESCRIPTION
**Pull request by chris-cooper**
Pulling in Cesium via webpack produces the following warning...
```
WARNING in ./~/cesium/Source/ThirdParty/earcut-2.1.1.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/cesium/Source/ThirdParty/earcut-2.1.1.js 1:479-486
```
This PR strips the boilerplate from earcut so it can be loaded directly like other Cesium modules.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for the fix, @chris-cooper!

@bagnell instead, is it possible to just use the unminified version of earcut?

**Comment by mramato** [comment]
While we should always use the unminified version of libraries, if I recall correctly, there was no unminified version of earcut that did not include a bunch of debug code.  @bagnell can you please confirm.

**Comment by mramato** [comment]
Rather than modify the minified version, I'd rather see us modify an unminified version to not include it's debug code (or use pragmas) if possible.

**Comment by chris-cooper** [comment]
Thanks @mramato.  A couple of things I forgot to mention:
* This was more than just a build warning as it caused an earcut error at runtime
* The full source code is [in a single CommonJS module](https://github.com/mapbox/earcut/blob/master/src/earcut.js).  Has anyone looked into if it's feasible for Cesium to pull in CommonJS third party dependencies directly from source code in node_modules (i.e. the reverse of how [Terria pulls in AMD cesium dependencies using a require()](https://github.com/TerriaJS/terriajs/blob/4.0.1/lib/Core/DataUri.js#L3)?

**Comment by kring** [comment]
@chris-cooper I'm seeing the warningin 1.23, too, but I'm not seeing any runtime errors.  When do you see that?  My test case it is admittedly pretty simple: I'm loading a GeoJSON with a polygon.  I would expect that to trigger it, though.

**Comment by chris-cooper** [comment]
It was working OK locally, but intermittently gives the following error when running from a remote server...
```
earcut.js:645 An error occurred while rendering.  Rendering has stopped.
undefined
Error: importScripts failed for Workers/createPolylineGeometry at https://(url-changed)/cesium/Workers/createPolylineGeometry.js
http://requirejs.org/docs/errors.html#importscripts
Error: importScripts failed for Workers/createPolylineGeometry at https://(url-changed)/cesium/Workers/createPolylineGeometry.js
http://requirejs.org/docs/errors.html#importscripts
    at makeError (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:1191)
    at Function.req.load (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:16165)
    at Object.load (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:12786)
    at Object.load (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:6357)
    at Object.fetch (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:6296)
    at Object.check (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:7362)
    at Object.enable (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:9429)
    at Object.enable (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:11891)
    at Object.<anonymous> (https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:9286)
    at https://(url-changed)/cesium/Workers/cesiumWorkerBootstrapper.js:29:938
```

**Comment by mramato** [comment]
I looked into this some more and I think the easiest thing to do is just remove the source map directive from the submitted file.  The "build" we are using is nothing more than the commonjs source file that @chris-cooper mentioned but with a UMD wrapper, so removing the source map should fix the issue without introducing any problems (or making it hard to maintain).  I'll open a PR for people to try out.

**Comment by mramato** [comment]
@chris-cooper can you give #4169 a try and confirm it fixes the issue?  Thanks.

**Comment by mramato** [comment]
There was additional discussion of this in #4169, ultimately it is a webpack issue but there's no reason we can't work around it since we know Cesium sues AMD and there's significant maintenance overhead here.

**Comment by mramato** [comment]
Thanks @chris-cooper

**Pull request merged**
