### PR TITLE
Fix rotation for a GroundPrimitive with an EllipseGeometry

### PR DESCRIPTION
**Pull request by jedfong**
This code fixes an issue with [EllipseGeometry.createShadowVolume](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/EllipseGeometry.js#LC855) where the rotation was not used when creating the EllipseGeometry.

### CODE REVIEW

**Comment by jedfong** [comment]
It would be nice to have a test for these types of options, but I didn't see anything similar being tested in [EllipseGeometrySpec](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Core/EllipseGeometrySpec.js).  Does anyone have thoughts on this?

**Comment by hpinkos** [comment]
Thanks @jedfong! 
Yeah, I think we're missing tests for many of our createShadowVolume functions.  It would be great if you wouldn't mind adding that =)

**Comment by jedfong** [comment]
I added a test for EllipseGeometry.createShadowVolume

**Comment by jedfong** [comment]
This is ready

**Comment by hpinkos** [comment]
Great, thanks @jedfong!

**Pull request merged**
