### PR TITLE
Initial KML support

### PR DESCRIPTION
**Pull request by mramato**
1. The changes to the public API are extremely minor, it simply adds a new object, `KmlDataSource`, which is the same as other data sources but for KML. It only has 3 functions. (`fromUrl`, `load`, `loadUrl`).
2. Also adds KML and KMZ support to `viewerDragDropMixin` and the Cesium Viewer app `source` parameter.
3. I've been keeping #873 up to date with what's done and what's not for overall KML support, check that out if you want to see what we support/don't support yet.
4. Do not look at `SurfacePositionProperty` at yet, I still have a lot of work to do on this class (including renaming it).  I'll update this PR when it's ready.  No matter what, it will be private for 1.7 since we still need to figure out the exact details of height reference support.  This is more about laying ground work.

Also, just a reminder that you'll want to either set `InfoBoxViewModel.defaultSanitizer` to `undefined` or comment out line 161 of `InfoBoxViewModel` when you're playing with this in order to avoid balloon descriptions getting neutered. I plan on addressing this in an unrelated pull (hopefully before 1.7).  You'll also want to use the proxy if you play with public Network Links.

ToDo before Merge
- [x] Rename `SurfacePositionProperty` to `ScaledPositionProperty` and finish initial height reference support
- [x] Verify how styles are applied and write tests for each type of Entity that gets created.
- [x] Test DataSource clock and changed/error/loading events
- [x] Replace Sandcastle example and sample KML data, also snap new gallery image.
- [x] Update CHANGES
- [x] Improve ref doc and explain the `Entity.kml` property that gets added.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Unrelated to this PR, but the speed indicator is off-the-charts (literally) for the States example.  Do we have an issue for this?

image

**Comment by pjcozzi** [comment]
Outside the scope of this PR and already known I suppose, but the profile for the Facilities example is...not good.

image

**Comment by mramato** [comment]
> Unrelated to this PR, but the speed indicator is off-the-charts (literally) for the States example. Do we have an issue for this?

Yes, #1072 It only happens data sets with huge time spans so it's never been a priority.

**Comment by mramato** [comment]
> Outside the scope of this PR and already known I suppose, but the profile for the Facilities example is...not good.

5% of that is definitely new code in this branch that hasn't been optimized yet (the height reference stuff), the rest is a known issue that I just need time to fix (for all non-static-geometry visualizers).  I already know how to fix it, and it's not even that much work.  Just need to find the time.

**Comment by pjcozzi** [comment]
Other than the known caveats, this looks pretty good to me.  2,500 lines of tests for 1,700 lines of code is wonderful.  Coverage is reasonable too.

I only tried a handful of KML files outside of the ones in the branch.  I'd like to try more this week.

**Comment by mramato** [comment]
Okay, this branch is ready for more eyeballs. I still want to do another full review myself, but I don't plan on making any additional changes outside of review comments (or any issues I find myself).

**Comment by pjcozzi** [comment]
@mramato I can merge this over the weekend or wait until early Monday if you prefer to get more time for reviews...

**Comment by pjcozzi** [comment]
Do we have to update the bottom of LICENSE.md for any of the example or test data?

**Comment by mramato** [comment]
We're had the us_states (as KML) on on the website forever, but I'm not sure where it came from.  I'll have to dig around.

The GDP example was created with http://www.kmlfactbook.org/ and uses Public Domain data, so I think we are in the clear there.

Everything else originated from AGI (facilities) or is of my own creation. (bikeRide and test data).

**Comment by pjcozzi** [comment]
We can file a separate bug on this if @mramato and @bagnell want: in the KML Sandcastle example, open the bike ride KML.  Switch to 2D and zoom in.  Switch to Columbus View and it freezes the tab.

**Comment by mramato** [comment]
There seems to be two bugs here. 1) a bug introduced in 1.6 that is triggered by morphing while tracking something and 2) Another manifestation of #2401, which still only happens in Chrome.

I fixed 1 in this branch.  2 still happens in Chrome., I'll reopen #2401.

**Comment by pjcozzi** [comment]
@mramato can we merge or are you still tweaking this?

**Comment by mramato** [comment]
As we discussed offline, I removed the us_states KML and example, since usage rights are no clearly defined.  We can add back a similar example in the future if we ever find (or make) one.

This is ready to be merged.

**Comment by pjcozzi** [comment]
IE 11 performance is really bad.  The GDP per capita example takes about a minute to load on my machine.  Perhaps it is their Web Worker implementation.

**Comment by mramato** [comment]
That's weird.  It only takes 10 seconds on my laptop, which is running Windows 8.1 and IE `Version: 11.0.9600.17631` and `Update Versions: 11.0.16 (KB3021952)`

**Comment by mramato** [comment]
For reference, my laptop is a 2 year old i5-3320 running at 2.60GHz (dual core).  It was also using the HD 4000 at the time (now that it should matter for load).

**Pull request merged**
