### PR TITLE
Fix Billboard.computeScreenSpacePosition

### LINKED ISSUE #3920: Billboard.prototype.computeScreenSpacePosition returning wrong y position
The behavior of computeScreenSpacePosition seems to have changed recently (there seem to be a few new commits changing Billboard.js). It looks like the y screen coordinate is the inverse of what it used to be. According to the API docs, the y coordinate increases from top to bottom.

The attached Billboards sandcastle example prints the screen positions and the computed screen positions of the clicked billboard.

Am I possibly missing something here?
[sandcastle_compute_screenposition.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/266055/sandcastle_compute_screenposition.txt)

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #3920.

Swap screen space position y coordinate so it increases from top to bottom. Also fix the calculation in 2D for labels.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@e-andersson can you please test this? We would like to include this in Cesium 1.22 in a few days on June 1?  The branch is hosted here: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/billboard-screen-space-position/

**Comment by pjcozzi** [comment]
@bagnell update CHANGES.md

**Comment by e-andersson** [comment]
@pjcozzi Did some quick testing (Sandcastle + our application) and it appears to work now.

**Comment by pjcozzi** [comment]
Thanks for testing @e-andersson!

**Pull request merged**
