### PR TITLE
Add a demo showing how a single entity can be split across CZML files.

### PR DESCRIPTION
**Pull request by emackey**
This demo adds a copy of the existing Vehicle.czml file, split across 3 new files.  The demo loads only the first part, and watches the clock to see when other parts are needed.

Of course, for such a small vehicle path, this extra work isn't required.  It's just here to show how the parts would fit together in a larger application that needed to split up CZML files.

TODO:
- [x] Need to add thumbnail
- [x] CHANGES.md

@shunter Any chance you can review?

/cc @pjcozzi @mramato

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@emackey, thanks for the pull request! Maintainers, we have a signed CLA from @emackey, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by emackey** [comment]
Demoing off a branch always seems slow, but, here's the link:  [Multi-part CZML Demo](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/multipart-czml-demo/Apps/Sandcastle/index.html?src=Multi-part%20CZML.html&label=Showcases)

**Comment by mramato** [comment]
@emackey, use the built Sandcastle instead

http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/multipart-czml-demo/Build/Apps/Sandcastle/index.html?src=Multi-part%20CZML.html&label=Showcases

**Comment by emackey** [comment]
Thanks, that seems faster.

**Comment by pjcozzi** [comment]
Awesome @emackey, thanks for adding this so quickly.  To make this a more complete example for the folks requesting it, could you please swap out the billboard with the milktruck or another model.  Just do whatever is reasonable for orientation even if it is export something quick from STK.

Would also love to see the latest way to use a custom property and display it as an overlay.

**Comment by emackey** [comment]
OK, branch is still building but demo link will be the same when it's done.

The 3D model is used now with auto-orientation from Cesium.

A multi-part custom property "fuel remaining" has been added, split across all 3 parts of the CZML.  Cesium automatically interpolates the value smoothly, even between values that came from different CZML files.

**Comment by pjcozzi** [comment]
@emackey this is perfect, thanks. 👏 

@mramato @shunter any suggestions before we merge?

**Comment by pjcozzi** [comment]
Awesome, thanks again!

**Pull request merged**
