### PR TITLE
Workaround for Safari bug #1804

### PR DESCRIPTION
**Pull request by speigg**
Workaround for Safari bug #1804

### CODE REVIEW

**Comment by mramato** [comment]
Thanks @speigg I'll give this is a try tomorrow (when I have access to an OS X machine).  Even with a simple change like this, we need you to fill out a copy of our Contributor License Agreement (CLA) and email it to us at cla@agi.com, as [defined in CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).  Most likely you want the [individual agreement](http://www.agi.com/licenses/individual-cla-agi-v1.0.txt).  It's a one time process for all first-time contributors.

If you are not interested or unable to sign the CLA, I can vouch for this change and re-make it myself manually, no big deal.  I know it's silly, but for legal reasons every commit that goes into Cesium must have a signed CLA attached to it.  Thanks.

**Comment by mramato** [comment]
Also, do you have any thoughts as to why this fixes problems in Safari?  I originally tracked the issue to what looked like scoping problems in the JavaScript engine, but I'm not sure why this particular change would fix it (unless the bug isn't in scoping and is instead something else).

**Comment by speigg** [comment]
Feel free to go ahead and make the change yourself  :)

**Comment by speigg** [comment]
Oh, and no, I have no idea why this actually works. My reasoning was simply that Safari was confusing these parameters in part because both parameters were based on the same string... so I figured that if I make the strings "different enough" Safari would treat them as two separate values... not a very technical explanation, but it apparently it works!

**Comment by mramato** [comment]
Thanks again.

**Pull request closed without merging**
