### PR TITLE
fixed inverseTransposeModel typos

### PR DESCRIPTION
**Pull request by andyfry01**
Hello, 

I corrected the typo from [Issue #3942](https://github.com/AnalyticalGraphicsInc/cesium/issues/3942). The issue only referenced the typo in [Model.js line 2132](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2132), although there was also a typo (inverseTranposeModel) in [UniformState.js line 264](https://github.com/AnalyticalGraphicsInc/cesium/blob/bd3ddefcc1f38a8444d3bddfd0d093867a979454/Source/Renderer/UniformState.js#L264). The same typo is also in [BuiltinFunctionsSpec lines 28, 39 and 50](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Renderer/BuiltinFunctionsSpec.js), should these be corrected?

Thanks,
Andy

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @andyfry01!  I know it's a small change, but can you please send in a [CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can merge this?

And yes, I think this typo should be corrected throughout

**Comment by andyfry01** [comment]
Sure thing @hpinkos, I'll fill out a CLA and will also push another commit to change the other typos.

**Comment by andyfry01** [comment]
Hi again @hpinkos,

I removed the MapQuest imagery provider from [createDefaultImageryProviderViewModels.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/BaseLayerPicker/createDefaultImageryProviderViewModels.js) as per [issue #4019](https://github.com/AnalyticalGraphicsInc/cesium/issues/4109#issuecomment-232470451).

I also corrected the remaining "tranpose" typos in:

- [Documentation/Contributors/README.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/03191f3c7558d8ab6b3fe6fb002261501a2d9eb6/Documentation/Contributors/README.md)
- [Source/Shaders/Builtin/Functions/transpose.glsl](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/transpose.glsl)
- [Specs/Renderer/BuiltinFunctionsSpec.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Renderer/BuiltinFunctionsSpec.js). 

Also just emailed my CLA form to the email indicated. 

Thanks!
Andy

**Comment by pjcozzi** [comment]
We now have a CLA from @andyfry01.  Thanks again for these contributions!

**Comment by lilleyse** [comment]
This looks good to me.

**Comment by pjcozzi** [comment]
Thanks again @andyfry01.  I also added you to the list of contributors: https://github.com/AnalyticalGraphicsInc/cesium/commit/126ac75d2d0f53a8769a982c45d6bb8af498a5eb#diff-f0eaedffe49f98e11072394a678af7cc

**Pull request merged**
