### PR TITLE
Update node modules

### PR DESCRIPTION
**Pull request by hpinkos**
- Update eslint: 
  - Turned off the `no-prototype-builtins` rule which was erroring our use of `foo.hasOwnProperty`
  - Removed a bunch of unnecessary gloabal defines
- Updated `rimraf` (no changes required)
- Updated `gulp-tap` (no changes required)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/update-node-modules/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Could someone review this? @tfili @mramato?

**Comment by mramato** [comment]
I'm surprised `no-prototype-builtins` is on by default.  Weird.

**Comment by mramato** [comment]
Thanks @hpinkos!  We'll need to publish a new version of `eslint-config-cesium` at some point, but that can happen separately.

**Pull request merged**
