### PR TITLE
KML imports lookAt data.

### PR DESCRIPTION
**Pull request by Hoverbear**
Helps with #873.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@mramato Ping, Is there anything else I should add to this PR?

**Comment by mramato** [comment]
@Hoverbear I apologize for the delay.  As I mentioned in our previous conversation, since Cesium already has a method for expressing an entity view (the `Entity.viewFrom` property), I would rather translate the `lookAt` data into that property instead of exposing it directly.  The Entity API is all about making data interaction generic, so a user shouldn't need to know if something came from KML/CZML/GeoJSON/etc... in order to zoom to it.

That being said, `viewFrom` itself may need some changes to better accommodate KML and has, itself, been scheduled to be refactored for a while.  I'll try and figure out what that's going to take soon so that we can get this feature into master.

In order to accept any of your contributions into Cesium, we need you to fill out and email us a copy of the CLA, as defined in [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md)  The [individual CLA](http://www.agi.com/licenses/individual-cla-agi-v1.0.txt) is probably what you want.

**Comment by Hoverbear** [comment]
@mramato Yes, I worked on trying to get `viewFrom` to work for several hours but was unable to because there is no clear way to take a `Cartesian3` and modify it with a `HeadingPitchRoll` type. Did I perhaps miss something?

**Comment by Hoverbear** [comment]
@mramato Ping. :)

**Pull request closed without merging**
