### PR TITLE
Billboard clamping requires tweak to pixel offset

### LINKED ISSUE #4082: KML billboard alignment problem introduced in 1.23
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/U6Q74ewtnQM
See the forum post for the example kmz file

In 1.22, the billboard is aligned center to it stays in line with the polyline

In 1.23, it doesn't match up anymore

### PR DESCRIPTION
**Pull request by tfili**
Fixes #4082 

Modify `pixelOffset` to account for clamped billboards being aligned to BOTTOM.

The following appeared to be wrong too
* The `hotSpot` in the Y direction didn't take scale into account.
* `insetPixels` in Y seemed to also be incorrect (see test `IconStyle: Sets billboard image with hotSpot insetPixels`)

Still need
* [x] Tests
* [x] Verify this works with combinations of labels, scales, hot spots, etc.

CC @mramato

### CODE REVIEW

**Comment by mramato** [comment]
Why does RELATIVE_TO_GROUND in Cesium force a bottom origin to begin with?  That seems odd to me.

**Comment by tfili** [comment]
> Why does RELATIVE_TO_GROUND in Cesium force a bottom origin to begin with? That seems odd to me.

@mramato that was how it was when I inherited the branch. Never really thought about it. Do we want to change it? In practice it probably wouldn't break anyone.

**Comment by mramato** [comment]
> that was how it was when I inherited the branch.

I thought this was happening at the primitive level, you're saying it's not?  Either way, I think it should be changed.  I don't see why we would force bottom alignment for anything other than clamp to ground.  Even then, why wouldn't the primitive do the pixel offset trick you're doing here internally?

**Comment by tfili** [comment]
@mramato The more I think about it, why enforce bottom origin anywhere? Why not just use the verticalOrigin they specify? In datasources we can just handle it correctly.

**Comment by mramato** [comment]
@tfili that makes sense to me, but @pjcozzi and @bagnell may have had other reasons for changing it in the first place.

**Comment by pjcozzi** [comment]
@bagnell can confirm, but I believe we intentionally use bottom origin when clamping to terrain so half the billboard/label is not under terrain.  Is this happening in other cases?

**Comment by mramato** [comment]
> Is this happening in other cases?

It's happening for relative to ground, not just clamp to ground.  But I'm still not sure why we would override the user setting to begin with.  While I agree most users will want bottom origin when clamping, it's kind of odd to ignore the explicit setting.

**Comment by pjcozzi** [comment]
> It's happening for relative to ground, not just clamp to ground.

I agree this should not happen.

> But I'm still not sure why we would override the user setting to begin with. While I agree most users will want bottom origin when clamping, it's kind of odd to ignore the explicit setting.

I think its a good choice for the Cesium API; no one has complained in several releases, but not for the KML data source.

**Comment by tfili** [comment]
I don't think it makes sense for the API or KML.

With a `heightReference` of `NONE` or `RELATIVE_TO_GROUND` and an altitude of `0`, we default to `CENTER` and make the user change it to `BOTTOM`.

For `CLAMP_TO_GROUND` we now make the `verticalOrigin` property not matter at all, but still allows you to set it. It also changes how the `pixelOffset` property works since it's relative to the origin they specify except for this case. Then if they happen to change `heightReference` then the `verticalOrigin` magically changes and 'pixelOffset' is now wrong and needs to be reset.

I think it just introduces a lot more weird behavior just so a user doesn't have to set `verticalOrigin`, which they had no problem specifying before when the marker was on the ground.

**Comment by pjcozzi** [comment]
It would be a breaking change, but I would be fine I suppose with changing the Primitive API to not do this, and then just changing the Sandcastle example to set the origin to bottom.  Discuss with @bagnell and pick a direction.

**Comment by bagnell** [comment]
>I believe we intentionally use bottom origin when clamping to terrain so half the billboard/label is not under terrain

That is what we decided. Any other vertical origin will cause the billboard to be occluded by terrain. Why would a user want that? Now they need to remember to set it to bottom. I agree it shouldn't happen by default for relative to ground.

**Comment by tfili** [comment]
@bagnell I get the fact that almost all users would want it to be `BOTTOM`, but forcing that breaks `heightReference` and `pixelOffset`. Any user that put billboards on the ellipsoid before (which I'm assuming would be the majority), always had to set the it to `BOTTOM`.

**Comment by mramato** [comment]
For what it's worth, I agree with @tfili here; but I'll go along with whatever the team decides.

**Comment by pjcozzi** [comment]
Leave labeled `next release`, but push for 1.24.

**Comment by tfili** [comment]
@mramato @pjcozzi @bagnell What do we want to do here?

I think we should always set `verticalOrigin` to `CENTER` so we don't introduce a lot of weirdness into the API and break a bunch of other properties.

If we want to keep it  so that `verticalOrigin` to `CENTER` unless it's clamped, then it's set to `BOTTOM`, then this is ready.

**Comment by mramato** [comment]
I was on your side, so whatever you wanted is fine with me.

**Comment by bagnell** [comment]
>@mramato @pjcozzi @bagnell What do we want to do here?

You've convinced me that `verticalOrigin` should be `CENTER`.

**Comment by pjcozzi** [comment]
I have too many fish to fry so I am going with the majority here.

Does this need a review by anyone?

**Comment by tfili** [comment]
I updated it to not force it to `BOTTOM`. Should be ready for final review.

**Comment by pjcozzi** [comment]
@mramato do you want to do the final review and merge?

**Comment by mramato** [comment]
Update Changes.

**Comment by tfili** [comment]
@mramato Updated.

**Comment by mramato** [comment]
Something went screwy here and there are now a bunch of commits not part of this PR.  Can you squash your changes to fix it?

**Comment by tfili** [comment]
@mramato That's weird. Not sure what happened. I squashed it.

**Comment by mramato** [comment]
Thanks.

**Pull request merged**
