### PR TITLE
Fix draco model in Edge

### LINKED ISSUE #7079: Draco Compressed Model doesn't work in Edge.
localhost:8080/Apps/Sandcastle/index.html?src=3D%20Models.html

The Draco Compressed Model doesn't work in Edge.  The model doesn't appear in the scene, and I see this message in the console: `WEBGL11025: INVALID_VALUE: drawElements: Negative count or offset.`

Surprisingly it works in IE.  And also Firefox and Chrome.

This works in 1.49, so this is a recent regression and needs to be fixed before the release on Monday.

@lilleyse @OmarShehata @ggetz

### PR DESCRIPTION
**Pull request by ggetz**
Fixes #7079

@hpinkos can you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by OmarShehata** [comment]
Since this only happens in master, and not any released version, should we remove the mention from `CHANGES.md` ?

**Comment by lilleyse** [comment]
Looks good to me!

**Comment by lilleyse** [comment]
Travis is failing because of https://github.com/AnalyticalGraphicsInc/cesium/issues/7076, but tests are passing here and locally.

**Pull request merged**
