### PR TITLE
MapboxImageryProvider credit option

### LINKED ISSUE #3009: Ability to pass credit string to MapboxImageryProvider
Also, is this called often?  If so, can we avoid the allocation?
```javascript
MapboxImageryProvider.prototype.getTileCredits = function(x, y, level) {
    return [defaultCredit2];
};
```

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #3009

If a credit is passed in, I add it after the other two credits that Mapbox requires to use their imagery.  Should I replace the default credits instead?

### CODE REVIEW

**Comment by pjcozzi** [comment]
> Should I replace the default credits instead?

Yes.

**Comment by hpinkos** [comment]
@pjcozzi ready

**Comment by pjcozzi** [comment]
Thanks.  Update CHANGES.md.  Do we have tests for credit parameters?  I imagine we should.

**Comment by hpinkos** [comment]
@pjcozzi I added specs and updated changes.

**Comment by pjcozzi** [comment]
Looks good, thanks.

**Pull request merged**
