### PR TITLE
Events

### LINKED ISSUE #2435: Cesium prevents sliders from working
Try this Sandcastle example:
http://localhost:8080/Apps/Sandcastle/index.html?src=Imagery%20Adjustment.html&label=Showcases

The sliders can't be moved by dragging them.  Clicking works.  This is caused by Cesium canceling the document's mousemove event.  Some discussion here:
https://groups.google.com/d/topic/cesium-dev/Emt-CrGYulY/discussion

### PR DESCRIPTION
**Pull request by bagnell**
This reverts the changes in #2408 and #2417. It instead adds an option to listen for the mouse/pointer/touch up and move events on the document. Fixes #2435.

### CODE REVIEW

**Comment by mramato** [comment]
@emackey (and @kring) can you guys take point on reviewing/merging this?  Thanks.

**Comment by emackey** [comment]
After discussion with @bagnell and @mramato, we are going to completely back out #2408 and #2417, and just have the picking examples that needed these changes use native JS events instead of Cesium events.

**Comment by mramato** [comment]
To further clarify, it's my believe that we provide little to no benefit by providing our own API for this kind of stuff and we should encourage users to use the standard HTML events wherever possible.  We should seriously consider deprecating the public API we expose for these events with the next release and switching any Sandcastle examples over to use native events.

**Comment by bagnell** [comment]
I reverted the remaining changes, but I left the updated tests.

**Comment by pjcozzi** [comment]
> To further clarify, it's my believe that we provide little to no benefit by providing our own API for this kind of stuff and we should encourage users to use the standard HTML events wherever possible. We should seriously consider deprecating the public API we expose for these events with the next release and switching any Sandcastle examples over to use native events.

+1.  Can you write an issue with the specifics to deprecate?

**Comment by kring** [comment]
Code looks good, test pass, and the problems I originally found in National Map go away with this change.  Are there Sandcastle changes that need to happen too?  That can be a separate pull request in any case.  Merging.

**Pull request merged**
