### PR TITLE
Fix PolygonGeometry winding order with holes.

### LINKED ISSUE #2404: Winding order bug in extruded polygons with holes?
Are extruded polygons with holes considered opened or closed?  Right now the DataSource layer sets them to closed, (which I assume is correct) but this results in interior walls being culled as in the below image:

image

My assumption is that this a bug in the geometry; specifically I think [this line](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/PolygonGeometry.js#L505) is flipped and should be 
`if (windingOrder === WindingOrder.COUNTER_CLOCKWISE)`

If @pjcozzi or @bagnell can confirm either way, I'll open a fix (either in the Polygon code or the DataSource primitive batching code depending on the answer).

### PR DESCRIPTION
**Pull request by mramato**
Fixes #2404 

Is there an easy way to unit test this?  It's easy to test in Sandcastle, but obviously a unit test would be better.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Modify one of the unit tests for a polygon with holes and make sure it produces the same results with the inner positions both CW and CWW.

**Comment by mramato** [comment]
I tried that, but the test doesn't actually test the problem (and passes in master without this fix). The reason is that master still flips the winding order, it just does it incorrectly and both polygons end up incorrect (but equal to each other).  In this branch it flips the winding order correctly and both polygons end up correct (and still equal to each other).  As far as I can tell, there's no way to detect that the computed geometry is correct without doing some sort of rendering test (which would probably be hard to set up in this situation).

**Comment by pjcozzi** [comment]
When this didn't work, the indices for some triangles should have been backwards which is why backface culling removed them even when they were frontfacing from the viewer's perspective.  We should be able to test that.  I'm also OK merging this as is.

**Comment by mramato** [comment]
It's up to you. I agree a test would be good, but I'm not familiar enough with this are to be able to write one.  If you or @bagnell want to take a stab at it, go ahead (or you can just merge).  

For the record, here's the test I wrote but didn't submit because it passes in master.
```
    it('holes have correct winding order', function() {
        var clockwise = {
                positions : Cartesian3.fromDegreesArray([
                    -124.0, 35.0,
                    -124.0, 40.0,
                    -110.0, 40.0,
                    -110.0, 35.0
                ]),
                holes : [{
                    positions : Cartesian3.fromDegreesArray([
                        -122.0, 36.0,
                        -112.0, 36.0,
                        -112.0, 39.0,
                        -122.0, 39.0
                    ]),
                    holes : [{
                        positions : Cartesian3.fromDegreesArray([
                            -120.0, 36.5,
                            -120.0, 38.5,
                            -114.0, 38.5,
                            -114.0, 36.5
                        ])
                    }]
                }]
            };

        var counterClockwise = {
            positions : clockwise.positions,
            holes : [{
                positions : clockwise.holes[0].positions.slice(0).reverse(),
                holes : [{
                    positions : clockwise.holes[0].holes[0].positions.slice(0).reverse()
                }]
            }]
        };

        CesiumMath.setRandomNumberSeed(0);
        var clockwiseGeometry = PolygonGeometry.createGeometry(new PolygonGeometry({
            vertexformat : VertexFormat.POSITION_ONLY,
            polygonHierarchy : clockwise,
            granularity : CesiumMath.PI_OVER_THREE,
            extrudedHeight : 10
        }));

        CesiumMath.setRandomNumberSeed(0);
        var counterClockwiseGeometry = PolygonGeometry.createGeometry(new PolygonGeometry({
            vertexformat : VertexFormat.POSITION_ONLY,
            polygonHierarchy : counterClockwise,
            granularity : CesiumMath.PI_OVER_THREE,
            extrudedHeight : 10
        }));

        expect(clockwiseGeometry.indices).toEqual(counterClockwiseGeometry.indices);
    });
```

**Pull request merged**
