### PR TITLE
removing outline not supported error

### LINKED ISSUE #5266: Clean up CZML geometry examples
A bunch of our CZML Sandcastle examples trigger the "outlines not supported for Ground primitives" warnings in the console.  This is confusing for new users.  We should either remove the outlines from these examples (since they don't show up anyway) or explicitly set the height to 0 so that ground primitives aren't used and the outline is shown.

@rahwang this might be a good low-hanging issue to work on.

### PR DESCRIPTION
**Pull request by rahwang**
Fixes #5266.

Part of #5270 too!

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @rahwang! Just found one demo where this is still a problem:
- [ ] CZML Reference Properties

**Comment by rahwang** [comment]
Good catch, @hpinkos  -- I actually got that one in #5277 

Thanks!

**Comment by hpinkos** [comment]
:+1:

**Comment by mramato** [comment]
So did we just remove outlines from all examples?  What if someone wants an outline?

**Comment by pjcozzi** [comment]
> So did we just remove outlines from all examples? What if someone wants an outline?

@rahwang what is the plan here?

**Comment by rahwang** [comment]
@pjcozzi I can go back and add outlines to all the geometry not on the terrain. I think a maximum or 2-3 pieces of reference geometry per sandcastle example is appropriate. Trying demo all the styling options for every geometry type feels redundant. Any objections?

**Comment by pjcozzi** [comment]
Sounds good, thanks!

**Pull request merged**
