### PR TITLE
Fixes time issue in particle tails example

### PR DESCRIPTION
**Pull request by hanbollar**
Fixes [#6521](https://github.com/AnalyticalGraphicsInc/cesium/issues/6521)

Sort of a hacky fix for the issue - just added included dt and added in an if statement. The reason this example had the weird time issue but the other particle system examples dont is because the update function here updates the position itself instead of the velocity of the particle - gives reaaaally bad visual output with it based on velocity based on how the math is done.

Also if we include this fix - there should be an update added to the blog post to explain why the if statement was added and that it was actually added to remove the time change issue.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hanbollar, thanks for the pull request! Maintainers, we have a signed CLA from @hanbollar, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hanbollar** [comment]
@ggetz is this a better fix? it incorporates dt so it stops when appropriate (in the vertical and horizontal directions) however i had to clamp the overall max dt so that when the environment was loading / etc you wouldnt get too much of a disturbance in the visual for the rocket example - otherwise it looked super wonky

lmk what u think

**Comment by pjcozzi** [comment]
hello again, @hanbollar, thanks for getting these over the finish line even _after_ your internship!  Could you please also send in an [individual CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) and add your name again to CONTRIBUTORS.md as you are no longer covered by AGI's CLA?  You will be one of the few and prestigious to have your name more than once in CONTRIBUTORS.md! 🏅

**Comment by hanbollar** [comment]
@pjcozzi just sent in the cla and updated contributors.md 👍

**Comment by pjcozzi** [comment]
Received, thank you!

**Comment by ggetz** [comment]
Thanks @hanbollar ! I just tweaked a variable name, but looks good otherwise.

**Comment by ggetz** [comment]
(No need to update CHANGES.md, this tutorial hasn't gone out yet)

**Pull request merged**
