### PR TITLE
Update Cesium to ES6 modules

### PR DESCRIPTION
**Pull request by mramato**
This is a draft pull request that will bring native ES6 modules to Cesium's code base.  The general plan and roadmap are in #8122 and I'll be PRing into this branch as things progress.

I don't expect anyone to ever review this PR directly (until maybe the very end), it's just open to track the overall progress of the refactor.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/es6-staging/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
This PR now contains both ES6 boilerplate and the new Sandcastle example boilerplate, all of which would just be noise if it were included in the main PR.

**Comment by OmarShehata** [comment]
This should now be ready right @mramato ? I can do a final test and merge.

**Comment by mramato** [comment]
As discussed offline, I'm going to squash everything down into a single commit so that it's trivial to go back to "pre-ES6" in case we need to bisect/triage anything.

**Comment by mramato** [comment]
Okay, I force pushed the single commit.  I also pushed the old branch to `old-es6-staging` just in case anything comes up that warrants me needing it (I'll delete it at some point).

@OmarShehata this is ready for merge.

**Comment by mramato** [comment]
Just realized I never updated CHANGES.md :rofl: but we have a blog and other info in the works, so I would prefer to wait until those are ready and then update CHANGES separately, since there's no way we could explain any useful information in a one line bullet.

**Comment by mramato** [comment]
@OmarShehata bump.

**Comment by OmarShehata** [comment]
@mramato I'm just doing a final test on IE11/Edge. I'm seeing some unexpected behavior. The built Sandcastle/Viewer do work in both IE11 and Edge. But unbuilt Sandcastle seems to work in IE11 (I guess it will automatically use the built version then?) but does not work in Edge. It fails with:

```
Error loading http://localhost:8080/Apps/Sandcastle/load-cesium-es6.js
```

Is this expected?

**Comment by mramato** [comment]
* IE11 requires the built version of CesiumJS (but not the built version of Sandcastle)
* I guess Edge currently requires both the built version of CesiumJS and Sandcastle because Edge does not support dynamic ES6 modules.  I may be able to fix this in a follow-up PR, but for now Edge does work with built Sandcastle.  Edge is supposed to switch over to Chromium "any day now" but I'll see what we can do.  I would not let the "Edge case" (see what I did there?) hold this up.

**Comment by OmarShehata** [comment]
Sounds good, I think it's fine as well since it does work with the built Sandcastle. Feel free to just write up an issue that explains that IE11 & Edge now require built Cesium that we could point people to (although this just one of several things I assume the big ES6 blog will cover that we'll link to from CHANGES.md).

**Pull request merged**
