### PR TITLE
Fix translucent flickering after a pick

### LINKED ISSUE #5307: Transparent objects flicker when using scene.pick
When moving the mouse around in an app that uses scene.pick, translucent objects flicker. The gif capture is not best, the flickering is much faster.

flickery

Sample code:

http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=eaae1407cd39601a2c3ba62b30f00a1f

### PR DESCRIPTION
**Pull request by bagnell**
Fix an issue with clearing the OIT buffers after a pick. Removes an
optimization where the OIT buffers weren't cleared when there was no
translucent commands being rendered. The issue occurred after rearranging
the scene for multiple viewports so the buffers are now only cleared once
at the beginning of the frame instead of per viewport.

Fixes #5307.

### CODE REVIEW

**Comment by bagnell** [comment]
@mramato, can you test if this fixed the issue you were seeing where picking stopped working?

**Comment by pjcozzi** [comment]
Code LGTM

**Comment by mramato** [comment]
> @mramato, can you test if this fixed the issue you were seeing where picking stopped working?

Unfortunately the issue is completely random (as far as I can tell anyway), but I'll keep an eye out and let you know if it's still happening after this change.

**Comment by mramato** [comment]
I can confirm the issue is fixed.  Since @pjcozzi already approved the code, I'll merge this as soon as it goes green.

**Comment by mramato** [comment]
Thanks @bagnell!

**Pull request merged**
