### PR TITLE
Added Terrain Snow Shading Feature

### PR DESCRIPTION
**Pull request by HuYuxin**
* This pull request is to fix issue #6070. This feature is completed by @akhabbaz, @VElysianP, and @HuYuxin as the final project of University of Pennsylvania Fall 2017 CIS 565 taught by @pjcozzi. [Here is the original project repository](https://github.com/HuYuxin/CIS565FinalProjectCesiumSnow)
* We added our changes in CHANGES.md. They are:
  * Updated GlobalFS.glsl to only apply material over non-ocean areas. Added 4 new local variables: normalWithNoise, shiness, specular, isOcean in main() funcion. Updated #ifdef APPLY_MATERIAL section and #ifdef ENABLE_VERTEX_LIGHTING section to enable normal maps and blinn-phong shading on snow material.
  * Updated Source/Scene/Material.js to include snow material.
  * Added New Shader SnowMaterial.glsl under Source/Shaders/Materials for snow material.
  * Added example page Apps/Sandcastle/SnowRendering.html, as well as corresponding normal maps snowNormalMapLevel*.jpg under Apps/Sandcastle/images/.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @HuYuxin!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Thanks and congrats @akhabbaz, @VElysianP, and @HuYuxin!

@likangning93 could you please do an initial review in the next few weeks?

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the pull request @akhabbaz, @VElysianP, and @HuYuxin!  I'm going to merge this into the `terrain-snow-shading` branch so we can pick this back up when we have more time to look at it.  Thanks again for the contribution!

**Pull request merged**
