### PR TITLE
Shadow map shaders

### PR DESCRIPTION
**Pull request by bagnell**
Removes some of the procedural shaders in favor of conditional compilation.

### CODE REVIEW

**Comment by pjcozzi** [comment]
+1.  Just add tests, https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Renderer/BuiltinFunctionsSpec.js

**Comment by bagnell** [comment]
@pjcozzi This is ready. I only added unit tests for 2 new built-in functions. The others rely on automatic uniforms and that is changing in another branch. I'll add them there.

**Comment by pjcozzi** [comment]
Sounds good.  @lilleyse merge when ready.

**Comment by lilleyse** [comment]
Made some fixes. Merging now.

**Pull request merged**
