### PR TITLE
Fix morphing from 2D to 3D

### LINKED ISSUE #4383: Morphing from 2D while tracking a model entity is broken
Found by @mramato in #4309: 
1. Run the 3D Models Sandcastle example.
2. Switch to 2D
3. Double click the model to track it.
4. Switch to 3D. (The morph is all screwy)

This can only be seen after the crash is fixed in #4382.

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #4383. 

Not just when tracking models. It also happens for any of the geometry Sandcastle examples. For example, double click one of the boxes in the box example to track it. When morphing to 3D from 2D, the camera position will remain the same when switching from an orthographic projection to a perspective projection. It was much more noticeable in the model example. This change adds back the flight to the home view.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Update CHANGES.md.

Does this need unit tests?  I'm not sure how well the original code was covered.

**Comment by bagnell** [comment]
>Does this need unit tests? I'm not sure how well the original code was covered.

There are no tests for `SceneTransitioner` but the morph functions are called all over the tests to change the mode.

**Comment by pjcozzi** [comment]
From #4383:

> 1. Run the 3D Models Sandcastle example.
2. Switch to 2D
3. Double click the model to track it.
4. Switch to 3D. (The morph is all screwy)

The final morph from 2D to 3D freezes for me.

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look. I fixed the freeze by not updating imagery or terrain during the morph, but there might be a deeper problem. The freeze was caused by the loops here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ImageryLayer.js#L539

**Comment by pjcozzi** [comment]
Looks good.

> I fixed the freeze by not updating imagery or terrain during the morph, but there might be a deeper problem.

Submit an issue if there is a real problem.

**Pull request merged**
