### PR TITLE
Improve CoplanarPolygonGeometry normal calculation

### LINKED ISSUE #7185: perPositionHeight reversed material
In [this Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVNRb9QwDP4r0fGwm1Tau20I1N1OjDFpSJNADCEhilDaem1YGhcnvVuH9t9x096uuwnelofK/mznsz83K0lipWANJE6EgbU4A6uaKvzqsele5t0zNE4qA7QXiD+JEXxsievPYHKgS8T6nAjJilhcS20heEhpdH5qVCUdcMxRA4m53z9OTGJWnjgHPNdQgXFMn2PWdGZYgBvQd+2HfLrnSCrN5NtKDinXck3fe+h9BTaUeT4dOqxRtwWaeNNxd0oFJCkr23gz6Jkkx5Y0h+E1YfUeCgKwp0SyvQBVlM5Ov2/ruzOfz4LDWTCf8QnE09jRv2IH/49t7vyxH4wa9j3Eoq/a4p2kpKSOH4k4SqiBPqFlUdBcDHd0+g8Z98MeOttr2st4h1h9wemOqPvHk2CysK7VsOxL3qqqRnKiIT0Nw8hBVWtuyEZpk92ACzNr+111yS+G9Y33UA+txUKmFnXj4HgbTNE5rGLx+lV9O4Kpn2I2gtYqd2UsDg9mjzIfRHuzxXniRbSZge1crYTKT5LJzh+eTESmpbUcuW60vlJ3kEyWi4jzl+MyjTJXpvi4AtKy7VLK+fKyB8MwXETsPq1yiDqVNLqRo36DQ7yXipuoWJMOYVM2Dlnftvc0P7feygitRZZFmQHgIQi19d6wqoXFhjIQljKGS+dqG0dRP/QvGyIVkee30ZU0eSat0xClqnjZrZI/xrQ/h67CNaQV07i2Br7Ll0U99gxkVX20y+Wh56DC1S7V70ZlN05V8ED4jflESri2/CvnCFYYdMI2tX8JrgSxyDCHpa9fRN4W0L/LsPv5fIAv+ws), you can see the video is reversed. If you set `perPositionHeight` to false, it's correct. 

I'm not sure why. Came up [on the forum](https://groups.google.com/d/msg/cesium-dev/CSQeUtcSj_4/_ridnkKxCAAJ).

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #7185

Flips the normal of the polygon if it is pointing roughly towards the center of the earth instead of away from it.  (Also flip the tangent so it points towards the right instead of the left).  This then fixes the texture coordinate calculation so images don't appear mirrored in some cases.

```js
var positions = new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArrayHeights([
            110,30,0, 
            110,40,0, 
            120,40,0, 
            120,30,0]));

var primitive = scene.primitives.add(new Cesium.Primitive({
    geometryInstances : [new Cesium.GeometryInstance({
        geometry : new Cesium.CoplanarPolygonGeometry({
            polygonHierarchy : positions,
            vertexFormat : Cesium.MaterialAppearance.MaterialSupport.TEXTURED.vertexFormat
        })
    })],
    appearance : new Cesium.MaterialAppearance({
        material : Cesium.Material.fromType('Image', {
            image: '../images/Cesium_Logo_Color.jpg'
        }),
        closed : false,
        translucent : false
    })
}));
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@OmarShehata can you review?

**Comment by OmarShehata** [comment]
If using winding order to compute normal is going to cause problems, I think this could work. Can we add a flag that says something like `flipNormal` ? Then the doc can say that the polygon will always face away from the ellipsoid, unless you set that. 

That way it resolves the use case Scott brought up here https://github.com/AnalyticalGraphicsInc/cesium/issues/7185#issuecomment-432829840 , and still gives the user explicit control over this without either them or us having to worry about winding order. 

What do you think @hpinkos ?

**Comment by mramato** [comment]
I don't think a `flipNormal` makes sense here, since we don't do it for other geometry. Cesium can certainly do better in this area, but I think staying consistent with other geometry is the best short-term approach and we can revisit if it becomes a problem.

**Comment by OmarShehata** [comment]
@mramato isn't this the only flat geometry that won't always be on the surface? That's why I thought this would make sense. If not, then I agree doing this as a separate issue for all relevant geometry types is better.

**Comment by hpinkos** [comment]
@OmarShehata yeah, we can consider adding something like that in the future if people ask for it.  It's just not really necessary for this PR.

**Comment by hpinkos** [comment]
This is ready for review

**Comment by mramato** [comment]
> @mramato isn't this the only flat geometry that won't always be on the surface?

No, rectangle, polygon, ellipse, etc... all have height properties and can be in the air.

@OmarShehata please bump for @bagnell to give a final lookover and merge once you're happy.

**Comment by OmarShehata** [comment]
Code looks good! It resolves the original issue as well as the issue here https://groups.google.com/d/msg/cesium-dev/aTbKq5Kn8Tc/R3RDMvd_BwAJ.

For `CHANGES.md`:

> Fixed texture coordinate calculation for polygon entities with `perPositionHeight` [#7187](https://github.com/AnalyticalGraphicsInc/cesium/pull/7187)

This links to the wrong PR. Shouldn't it be more like "Fixed inconsistent normal calculation for polygon entities with `perPositionHeight`" ?

**Comment by hpinkos** [comment]
@OmarShehata the normal was the underlying problem, but the incorrect texture was the bug that someone saw and reported.

**Comment by OmarShehata** [comment]
I'm fine with that description, but just wanted to clarify that the link still goes to a different PR than this one.

**Comment by hpinkos** [comment]
Thanks @OmarShehata!

@bagnell please review and merge

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/aTbKq5Kn8Tc/R3RDMvd_BwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/7188 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Pull request merged**
