### PR TITLE
KML tours: processing KMLTourFlyTo

### PR DESCRIPTION
**Pull request by jaforom**
Hi all,

I recorded a tour with Google Earth and then I tried to load it in my Cesium viewer. It went fine, but I noted that the pitch was wrong (the camera was always vertical). In my tour, I used several pitches.

When I found the code where the `KMLTourFlyTo` is processed, I found this code line, inside `processLookAt` function:
    
`var hpr = new HeadingPitchRange(heading, tilt - 90.0, range);`

This is wrong, because tilt must be in radians, so the correct line code will be:

`var hpr = new HeadingPitchRange(heading, tilt - Cesium.Math.PI / 2, range);`

The Cesium version is 1.39 and the bug is in line 156365.

I modified the line in CesiumUnminified/Cesium.js and then I loaded the KML again: the tour was right, using the different pitches I recorded in the tour.

Regards

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @jaforom!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
We now have a CLA from @jaforom.  Thanks again for the contribution!

**Comment by ggetz** [comment]
Hi @jaforom, are you should your PR is using the right branch? It looks like you're attempting to merge the `cesiumjs.org` branch with `master`. `cesiumjs.org` should be your branch of Cesium where you made your changes,

**Comment by jaforom** [comment]
Dear Gabby,

You’re right. When I initiate the pull request I did it wrong, because it was my first PR and I didn’t know how to do it correctly.

Could you help me about changing the branch to set the right one? I don’t know how to do that. Or may I close it and create a new one by using a fork?


Regards

De: Gabby Getz [mailto:notifications@github.com]
Enviado el: miércoles, 22 de noviembre de 2017 15:00
Para: AnalyticalGraphicsInc/cesium
CC: Juan Carlos Afonso; Mention
Asunto: Re: [AnalyticalGraphicsInc/cesium] KML tours: processing KMLTourFlyTo (#5997)


Hi @jaforom<https://github.com/jaforom>, are you should your PR is using the right branch? It looks like you're attempting to merge the cesiumjs.org branch with master. cesiumjs.org should be your branch of Cesium where you made your changes,

**Comment by jaforom** [comment]
Maybe I must close this PR and leave #5998 as the right PR.

**Comment by ggetz** [comment]
@jaforom Yes, it looks like you set up the PR correctly in #5998, thanks! You can go ahead and close this PR.

**Comment by jaforom** [comment]
The right one is #5998.

**Pull request closed without merging**
