### PR TITLE
Presenter's Guide

### PR DESCRIPTION
**Pull request by pjcozzi**
A guide for giving Cesium presentations (or any type of talk really):

* [Presenter's Guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/presenters-guide/Documentation/Contributors/PresentersGuide/README.md)

@slchow can you please copyedit?

Everyone - feel free to add more tips.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Now duplicate with #3332, which targets master.

**Comment by slchow** [comment]
Oh, sorry! Let me try recommitting to this branch.

**Comment by slchow** [comment]
Is #3333  correct?

**Comment by pjcozzi** [comment]
Yes, thanks.

**Comment by pjcozzi** [comment]
This is ready.  Can someone merge this?

**Comment by hpinkos** [comment]
@pjcozzi looks good!

**Pull request merged**
