### PR TITLE
Camera.flyHome in 2D uses Rectangle.MAX_VALUE instead of Camera.DEFAULT_VIEW_RECTANGLE

### LINKED ISSUE #4933: Camera.flyHome in 2D uses Rectangle.MAX_VALUE instead of Camera.DEFAULT_VIEW_RECTANGLE
Brought up on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/elr1j2jHlbg

Should we change the home button to use the `Camera.DEFAULT_VIEW_RECTANGLE` in 2D and Columbus View?

### PR DESCRIPTION
**Pull request by PratyushTalreja**
Fixes #4933

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @PratyushTalreja!  It looks like there is a test failure.  Please update the CameraSpec.js

**Comment by PratyushTalreja** [comment]
Hi @hpinkos . I have made the changes in the file CameraSpec.js

**Comment by pjcozzi** [comment]
@hpinkos or @bagnell do you want to finish reviewing this?

**Comment by hpinkos** [comment]
@PratyushTalreja it looks like some of the unit tests are still failing: 

```
  Scene/Camera
    ✗ flyHome works in 2D
	Expected (-9183857.990445068, 3896182.1777645755, 1) to equal epsilon (0, 0, 1), 1e-8.
	    at Specs/Scene/CameraSpec.js:2229:33
	    at Object.<anonymous> (Specs/customizeJasmine.js:75:30)
    ✗ computeViewRectangle when zoomed out
	Expected Rectangle({ west: -3.141592653589793, south: -1.5707963267948966, east: 3.141592653589793, north: 1.5707963267948966 }) to equal Rectangle({ west: -1.6580627893946132, south: -0.3490658503988659, east: -1.2217304763960306, north: 1.5707963267948966 }).
	    at Specs/Scene/CameraSpec.js:2431:22
	    at Object.<anonymous> (Specs/customizeJasmine.js:75:30)
```

**Comment by hpinkos** [comment]
@PratyushTalreja also, do we have a Contributor's License Agreement (CLA) from you?  If not, please send one over so we can merge this change.  You can find instructions for doing so here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

Thanks!

**Comment by PratyushTalreja** [comment]
I have signed the CLA. I am not sure why it is showing some errors?

**Comment by hpinkos** [comment]
Thanks @PratyushTalreja, I believe we did receive your CLA.

Have you tried to run the tests locally?  You can see information about how to run the tests in our testing guide: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide

**Comment by hpinkos** [comment]
Thanks for the pull request @PratyushTalreja! I'm going to close this because someone fixed it in another branch: #5561

**Pull request closed without merging**
