### PR TITLE
We weren't allowing primitive materials to have an image be a Resource

### LINKED ISSUE #6199: CZML Image Material Broken?
Greetings Cesium Folks!

As of CesiumJS 1.42, I am seeing some strange behavior with previously working Image Material rendered via CZML. I have also noticed this is occurring in the Cesium Sandcastle example below:

[Sandcastle with missing Cesium logo](https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=CZML%20Rectangle.html&label=CZML)

The polygon renders correctly and the default white texture appears. However, previous versions would asynchronously load the referenced "uri" element and overlay the image. This seems to have stopped with 1.42 based on my tests (1.41 behavior not apparent).

Here is my CZML for reference, which I believe is correct and has not changed between the previous releases of Cesium since Fall 2017:

`[{"id":"document","version":"1.0"}, {"name":"data-Base_Reflectivity_L2","position":{"cartographicDegrees":[-86.5625,36.2472229004,1.0]},"ellipse":{"semiMinorAxis":299875.0,"semiMajorAxis":299875.0,"height":10.0,"outline":true,"material":{"image":{"transparent":true,"image":{"uri":"http://data.horizonwx.com/kohx/Base_Reflectivity_L2/1508163444.png"}}}}}]`

I've attached screen grabs from my development environment and the sandcastle.

If I'm missing something, or if there is now a new syntax to follow for overlaying materials on polygons in CZML I'm happy to adjust. 

Thanks!

screen shot 2018-02-08 at 17 22 56

screen shot 2018-02-08 at 17 23 21

### PR DESCRIPTION
**Pull request by tfili**
Fixes #6199 

This needs fixes in #6211, so that will need to be merged first.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@tfili, thanks for the pull request! Maintainers, we have a signed CLA from @tfili, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Update CHANGES and I'll merge.

**Comment by tfili** [comment]
@mramato Done!

**Comment by mramato** [comment]
👍

**Pull request merged**
