### PR TITLE
Fix loading pnts tile with uint32 batch ids

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/316

Needed to cast the Uint32Array to a Float32Array since unsigned ints are not a valid WebGL vertex attribute type.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@lilleyse, thanks for the pull request! Maintainers, we have a signed CLA from @lilleyse, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by PissedCapslock** [comment]
Any change that this fix will make the 1.47 release ?

**Comment by lilleyse** [comment]
Yes it should make it for 1.47.

@ggetz would you be able to review?

**Comment by PissedCapslock** [comment]
Thanks !

**Pull request merged**
