### PR TITLE
Correct bounding sphere transform for glTF 2.0.

### LINKED ISSUE #6784: Model bounding sphere wrong after forward axis conversion change
Compare "Milk Truck" ( a 1.0 model) and "Draco Compressed Model" (a 2.0 model) in the 3D Models sandcastle. [1.47](http://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Models.html) vs [1.46](http://cesiumjs.org/releases/1.46/Apps/Sandcastle/index.html?src=3D%20Models.html)

In 1.47 the pivot point is slightly off.

Removing these lines fixes it, but I haven't looked around enough to know why. Similarly placing them above the other axis conversions works. @emackey would you be able to check this out?

```
if (model._forwardAxis === Axis.Z) {
    // glTF 2.0 has a Z-forward convention that must be adapted here to X-forward.
    BoundingSphere.transformWithoutScale(boundingSphere, Axis.Z_UP_TO_X_UP, boundingSphere);
}
```

Noticed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6559

### PR DESCRIPTION
**Pull request by emackey**
Fixes #6784.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/bounding-gltf-2.0/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
The pivot point is a bit off center in CV and 2D, but only for OffsetCube. It seems worse in 1.46 though, so maybe not relevant to this PR.

Also it would be good to get to the bottom of why the transform is applied first for computing the bounding sphere but last for the model matrix.

**Comment by lilleyse** [comment]
Besides that, this does fix the problem.

**Comment by emackey** [comment]
> Also it would be good to get to the bottom of why the transform is applied first for computing the bounding sphere but last for the model matrix.

The (non-bounding-sphere) model matrix is being transformed by another matrix.  The original model matrix is oriented for Cesium (+X forward, +Z up), then transformed to Y-up (still +X forward), and finally to +Z forward, +Y up.  The resulting transformation matrix takes vertices expressed in that system and gets them into Cesium's preferred orientation.

The BoundingSphere calculations are taking a single point, the sphere's center point, and getting it into Cesium's coordinate system.  So we're transforming a point by two different matrices, not stacking up the matrix multiplications into a single transform matrix.

For example, in the case of OffsetCube, the glTF mesh data is centered around `[2, 4, 6]`, with `4` being "up" (glTF +Y) and `6` being "forward" (glTF +Z).  We first transform +Z to +X, and get `[6, 4, -2]` as an intermediate center point.  Then we transform +Y to +Z, and get `[6, 2, 4]`.  Previously, `4` had been "up", and this is now +Z where Cesium expects.  Previously `6` had been "forward", and this is now +X where Cesium expects.

**Comment by lilleyse** [comment]
Ah yeah that makes sense. In both cases the `Z_UP_TO_X_UP` transform is still applied first, but it just appears different because the model matrix stacks it last. Thanks!

**Pull request merged**
