### PR TITLE
CZML and Entity articulations API

### PR DESCRIPTION
**Pull request by emackey**
Support for articulations was added at the graphics primitive level in the 1.58 release (in #7835).

This PR adds support at the entity and CZML layers.  The implementation is very similar to how the existing `nodeTransformations` work at those layers.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/entity-articulations/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by emackey** [comment]
Some sample articulations CZML is used in the new [Sandcastle Demo](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/entity-articulations/Apps/Sandcastle/index.html?src=CZML%20Model%20Articulations.html&label=CZML).

```
    "model": {
        "gltf" : "https://assets.agi.com/models/launchvehicle.glb",
        "scale" : 2.0,
        "minimumPixelSize" : 128,
        "runAnimations" : false,
        "articulations" : {
            "Fairing Open" : {
                "epoch" : "2019-06-01T16:00:00Z",
                "number" : [
                    0, 0,
                    600, 120
                ]
            },
            "Fairing Separate" : {
                "epoch" : "2019-06-01T16:00:00Z",
                "number" : [
                    0, 0,
                    400, -50
                ]
            },
            "Fairing Drop" : {
                "epoch" : "2019-06-01T16:00:00Z",
                "interpolationAlgorithm" : "LAGRANGE",
                "interpolationDegree" : 2,
                "number" : [
                    0, 0,
                    80, 0,
                    100, 0,
                    120, -1,
                    600, -120
                ]
            }
        }
    }
```

**Comment by emackey** [comment]
Apparently Travis never got the message to GitHub about completion of the most recent build.

**Comment by shunter** [comment]
Could use some tests in CzmlDataSourceSpec (patterned off the tests for nodeTransformations)  Otherwise this all looks good.  I'll double check that this syntax works out for czml-writer.

**Comment by shunter** [comment]
I was able to get the writer working with a value directly under a property bag rather than the nodeTransformations which had an extra level.

Syntax in C# looks like:

```C#
using (var articulationsWriter = modelWriter.OpenArticulationsProperty())
using (var articulationWriter = articulationsWriter.OpenArticulationProperty("articulation1 stage1"))
{
	articulationWriter.WriteNumber(3.5);
}
```

So this all should work out.

**Comment by emackey** [comment]
@shunter I added some tests to CzmlDataSourceSpec.  I didn't attempt to regenerate the CZML ValidationDocument, can you do that?

**Comment by shunter** [comment]
Yeah I can update the validation document separately.  My local czml-writer changes are dependent on the changes made for #7899 so once that's merged I can add articulations on top of that.

**Pull request merged**
