### PR TITLE
Made imagerySplitPosition use absolute coordinates

### LINKED ISSUE #5106: Imagery Layers Split has IDL issues in 2D
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Imagery%20Layers%20Split.html&label=Showcases

If you scroll the 2D map so the IDL is in the center of the screen, the split imagery no longer lines up with the screen divider

### PR DESCRIPTION
**Pull request by jasonbeverage**
This should fix #5106 by making the imagerySplitPosition option use absolute coordinates instead of relative coordinates so that the multiple viewport rendering of the 2D view won't cause issues.

I've also updated the sandcastle example to use absolute coordinates and put a prerender listener in there to make sure the split position is correct when the window is resized.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @jasonbeverage!  Looks good at quick glance.  Can you please update CHANGES.md, including a link to #5106?

@rahwang can you please review and test this?

**Comment by pjcozzi** [comment]
Ah, this is a breaking change, right?  Can you please make a new property name and deprecate the old one? See https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#deprecation-and-breaking-changes

**Comment by jasonbeverage** [comment]
Hey @pjcozzi , I opened up another PR at #5151 that still uses the relative coordinates publicly and computes the absolute coordinates in UniformState.update.  This avoids having to deprecate the property and also makes it easier for users to deal with the canvas resizing.  I'm going to close this PR in favor of the other one if that is ok with you.

**Comment by pjcozzi** [comment]
Sounds good, thanks @jasonbeverage!

**Pull request closed without merging**
