### PR TITLE
Share textures across models in a limited but useful case

### PR DESCRIPTION
**Pull request by kring**
This PR shares textures across models in the limited case of textures that come from regular old images.  Textures that come from arraybuffers (e.g. compressed textures. textures embedded in a binary glTF) or from images with really long URLs (e,g, data URIs) are not supported here because determining a suitable cache key would be tricky.

My use case is a 3D Tiles tileset with lots of overlap in the textures used by different tiles.  The images are all external to the b3dm files.  Before this PR, heaps of duplicate textures would be created and eventually WebGL context would be lost after exceeding GPU memory.  After this PR, it works great.

It's safe to say we'll want to support sharing textures (and probably other resources) in more scenarios eventually, but this incremental improvement is pretty useful.

One possible criticism of this PR is that `loadImage` is still called even for textures that do not need to be created because they're already in the cache.  I didn't think it was worth the extra complexity that would be necessary in `parseTextures` to fix this, since the browser should already do a pretty good job of making this fast.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Yes, I would like to review.  Please give me a week or two.

**Comment by hpinkos** [comment]
@lilleyse @pjcozzi do we want these changes?

**Comment by pjcozzi** [comment]
@hpinkos we'll want something like this.  We could start with this and get it over the finish line when it is a priority.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @kring! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@cesium-concierge stop

**Comment by hpinkos** [comment]
I'm going to close this PR due to inactivity, but keep the branch around for when we want to revisit this.

**Pull request closed without merging**
