### PR TITLE
Fix for camera getting stuck in orbit bug

### PR DESCRIPTION
**Pull request by moodragon46**
This is a fix for a bug that can be replicated using the following steps:

1. Use the middle mouse button to orbit
2. While holding the middle mouse button down, click the left mouse button
3. Release the middle mouse button.

The camera will be stuck in orbiting until the middle mouse button is pressed and released. The expected behaviour is that the camera will stop orbiting when the middle mouse button is released for the first time.

mousefix

### CODE REVIEW

**Comment by mramato** [comment]
Thanks @moodragon46!  I've ran into this issue before and it drives me crazy.  In order for us to review and merge you're code, you'll need to follow the above instructions to full out a CLA.  @pjcozzi will bump this issue once we receive it and then someone else will come along to do the review.

Thanks again!

**Comment by moodragon46** [comment]
Do you know how I can get my name added to the Propeller CLA's list of contributors?

**Comment by mramato** [comment]
Ahh, sorry I didn't notice that you were listed under the Propeller section. I suppose all we need is for someone else from Propeller to vouch for you, @chris-cooper?

CC @pjcozzi just in case there's something else we need to do

**Comment by chris-cooper** [comment]
Thanks @mramato , yes @moodragon46 is doing some intern work at Propeller.

**Comment by pjcozzi** [comment]
@moodragon46 thanks for the contribution, please let me know your last name and I will add you to the automated CLA.  You can email me at pcozzi@agi.com

**Comment by pjcozzi** [comment]
Added @moodragon46, thanks!

**Comment by hpinkos** [comment]
@bagnell can you please review?

**Comment by bagnell** [comment]
I can confirm this fixes the issue, but I see one failing test locally and ~70 failing on Travis.

**Comment by moodragon46** [comment]
The specs now pass locally.

**Comment by moodragon46** [comment]
@hpinkos I'm using Windows and I'm unable to start Firefox headless. I'll see if i can work it out when I have time.

**Comment by moodragon46** [comment]
It should be fixed now.

**Comment by hpinkos** [comment]
Great, thanks @moodragon46!  @bagnell please review and merge when ready

**Comment by bagnell** [comment]
Looks good. Thanks @moodragon46!

**Comment by lilleyse** [comment]
I had to revert this change for now since it introduced an issue that was blocking the 1.51 release. All mouse click events were being treated as left click, right click, and middle click events. See https://github.com/AnalyticalGraphicsInc/cesium/pull/7218.

We are still definitely interested in this fix, so lets plan to open the same PR right after the release is out and look closer into fixing that bug.

**Pull request merged**
