### PR TITLE
Better rotation

### PR DESCRIPTION
**Pull request by mramato**
This completes the work started by @Relfos and replaces #2666. (Thanks @Relfos!)

To recap:

1. Add a new `Rotation` object, which is a `Packable` number that causes interpolation to always take the shortest angle.  So halfway from 0 -> 350 will be 355 instead of 170.  This should provide much more realistic interpolation when using time-dynamic rotations.  It's not used directly, but instead passed to the `SampledProperty` constructor when the value will represent a rotation.
2. Improved specs and doc for all PackableForInterpolation objects (in addition to adding the new stuff for Rotation).
3. Makes all CZML rotations use the new capability. (That's the only place we, ourselves, create time-dynamic angles).

[Original form thread](https://groups.google.com/d/msg/cesium-dev/2ZrxVg9PLbg/9xrHi9YSVrIJ)

### CODE REVIEW

**Comment by pjcozzi** [comment]
I have some test failures:

image

I may have caused them when I just merged in master.

**Comment by mramato** [comment]
I'll take a look, it's probably something I did right before submitting and then forgot to re-run them.

**Comment by mramato** [comment]
Okay, this is ready.  It turns out there was a missing unit test for `billboard.rotation`, so the tests didn't start failing until I changed all CZML rotations to use it.  I fixed the problem and also added a test for `billboard.rotation`.

**Comment by pjcozzi** [comment]
Tests pass, thanks.

**Pull request merged**
