### PR TITLE
added zoom algorithm that better maintains target point in 3D

### PR DESCRIPTION
**Pull request by e-andersson**
Submitting PR against `master` instead of `3d-tiles` as per request from @bagnell in #3924.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks again, @e-andersson!  Can you please update CHANGES.md?  This will be released in Cesium 1.23 on July 1.

> The test coverage isn't great because there are code paths that only run when terrain is picked.

@bagnell can we programmatically pick terrain?  Or extract or mock something to test this block?

**Comment by e-andersson** [comment]
@pjcozzi CHANGES.md updated now!

**Comment by pjcozzi** [comment]
@e-andersson can you also merge in master?  There is probably a minor conflict in CHANGES.md.

**Comment by pjcozzi** [comment]
@bagnell is anything else needed here?

> @bagnell can we programmatically pick terrain? Or extract or mock something to test this block?

**Comment by e-andersson** [comment]
@pjcozzi Ah, I intended to but forgot it.

**Comment by pjcozzi** [comment]
@e-andersson can you please merge in master?  Sorry, there is another conflict.

@bagnell is this ready to merge?  Is it possible to better test this?  I would like to get this into 1.23.

**Comment by e-andersson** [comment]
Will have a look at it this evening.

**Comment by bagnell** [comment]
@pjcozzi This is ready to merge. I'm not sure of a good way to test where the terrain is picked. We should create an issue to add tests everywhere `Camera` and `ScreenSpaceCameraController` picks terrain.

**Comment by e-andersson** [comment]
@pjcozzi merged in master, sorry I couldn't do it sooner.

**Comment by pjcozzi** [comment]
New functionality looks great, thanks again @e-andersson!

**Pull request merged**
