### PR TITLE
Add UrlTemplateImageryProvider

### PR DESCRIPTION
**Pull request by kaktus40**
Hello,
in response to this [question] (https://groups.google.com/forum/#!topic/cesium-dev/f7c29TO3XMM), I made some modifications on TileMapServiceImageryProvider. Now this provider accepts schema in his options that will be used to request a server.

For example if the file server structure to request is "revX/Y/Z" and the extension is gif where:
 - revX is the reverse abscissa of tiles ("tilingScheme.getNumberOfXTilesAtLevel(level) - x - 1" in code),
 - Y is the ordinate of tiles,
 - Z is the level of tiles;

then the code to access to the tiles of the server is
```javascript
var tms = new Cesium.TileMapServiceImageryProvider({
        url : 'URL/of/TMS',
        fileExtension: 'gif',
        schema: '{revX}/{Y}/{Z}'
     });
```
then tms.requestImage(3, 1, 2) should request the url "URL/of/TMS/0/1/2.gif" instead of "URL/of/TMS/2/3/2.gif"

### CODE REVIEW

**Comment by kring** [comment]
Thanks @kaktus40.  This is very useful.  I think it's a bit odd to give `TileMapServiceImageryProvider` this capability, though.  It would be better to create a new imagery provider, maybe called `UrlTemplateImageryProvider`, that takes a URL template much like the `schema` you've implemented here.  The `fileExtension` property can go away, too, because the extension can be part of the template.  Would you be willing to work on something like that?

**Comment by kring** [comment]
So basically, your example above would instead look like:
```
var provider = new Cesium.UrlTemplateImageryProvider({
    url: 'URL/of/TMS/{reverseX}/{Y}/{Z}.gif',
    
});
```
(In my example of always renamed `revX` to `reverseX` because we try to avoid abbreviations in Cesium.)

**Comment by kaktus40** [comment]
Hello,
I can work on it. Do you think there could be a work to do with OGCHelper?

**Comment by kring** [comment]
Sorry, I've been putting off a thorough review of your `OGCHelper` for too long.  I'll at least add some initial thoughts over there (#2362).

**Comment by pjcozzi** [comment]
+1 for the new design.  Users will definitionally want this.  Thanks for the contribution, @kaktus40.

**Comment by kaktus40** [comment]
Hello I follow your prescriptions and create a new ImageryProvider based on url template.

**Comment by kring** [comment]
Thanks @kaktus40, this looks great!  I'm going to pull it into a separate branch and tweak a few things before merging it.  Do we already have a CLA for you?  Can you add yourself to `CONTRIBUTORS.md` in this pull request?

**Comment by kaktus40** [comment]
Hello, I have send a CLA in december 2014 or january 2015 and I made a pull with adding myself in the CONTRIBUTORS.md

**Comment by kring** [comment]
Great, thanks!

**Comment by pjcozzi** [comment]
Moving this discussion to #2795.

**Pull request closed without merging**
