### PR TITLE
Fix typo when cloning ShaderSource.

### PR DESCRIPTION
**Pull request by bagnell**
This might fix any bugs with picking translucent geometry. I quickly looked at existing issues but didn't find anything.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@bagnell, thanks for the pull request! Maintainers, we have a signed CLA from @bagnell, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
I think someone on the forum recently had translucent picking issues @hpinkos or @ggetz may know for sure.

**Comment by ggetz** [comment]
@mramato Were you talking about this post? https://groups.google.com/forum/#!searchin/cesium-dev/pick%7Csort:date/cesium-dev/C-yXSf6-8aQ/LW5ZZIMHBwAJ

**Comment by mramato** [comment]
Possibly, I just remember hearing something about a translucent picking bug recently.

**Comment by hpinkos** [comment]
Good catch @bagnell!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!searchin/cesium-dev/pick%7Csort

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/6234 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Pull request merged**
