### PR TITLE
Revert "Fix blinking polyline"

### LINKED ISSUE #7365: Sample line positions and draw with depth test disabled broken
Run http://localhost:8080/Apps/Sandcastle/index.html?src=Clamp%20to%20Terrain.html&label=All and select `Sample line positions and draw with depth test`  It will crash with `normalized result is not a number`

### LINKED ISSUE #7368: Sample Height from 3D Tiles broken
CC @lilleyse 

http://localhost:8080/Apps/Sandcastle/index.html?src=Sample%20Height%20from%203D%20Tiles.html&label=All

Maybe be the same root cause as #7365?

### PR DESCRIPTION
**Pull request by hpinkos**
Reverts #6955 

Fixes #7365
Fixes #7368

Never merge a PR right before the release

@lilleyse please open whatever issues necessary since we're reverting #6955

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Thanks, please re-open any of the issues that PR closed and we'll revert the revert ASAP and keep the PR open for @bagnell to finish up.

**Comment by hpinkos** [comment]
#6741 was the issue we globbed a bunch of random polyline artifact problems onto.  In the initial comment I asked @lilleyse to open a new issue for the specific problem since he created some other separate issues from #6741

**Comment by lilleyse** [comment]
Opened https://github.com/AnalyticalGraphicsInc/cesium/issues/7374

**Pull request merged**
