### PR TITLE
fix bug with unpickable Models and shader modification

### PR DESCRIPTION
**Pull request by likangning93**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/6442

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@likangning93, thanks for the pull request! Maintainers, we have a signed CLA from @likangning93, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by lilleyse** [comment]
Thanks @likangning93, confirmed that it is now fixed.

**Comment by AkshayGore** [comment]
How to run Cesium 3D offline (Localhost)?
What are the requirement for running ?
Please help me..
Akshaygore@live.com

**Comment by likangning93** [comment]
Hi @AkshayGore, generally the forum is the best place for questions like this: https://groups.google.com/forum/#!forum/cesium-dev

But for getting started in general please take a look at our build guide and contributing guides: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md.

**Pull request merged**
