### PR TITLE
Remove ClippingPlaneCollection.clone

### PR DESCRIPTION
**Pull request by hpinkos**
The presence of `ClippingPlaneCollection.clone` was causing a new `ClippingPlaneCollection` to be created every frame when it was the `value` of a `ConstantProperty` for a `ModelGraphics`.
This is also why we had to do this crazy `CallbackProperty` thing in the model clipping planes Sandcastle example.

None of our other collections like `BillboardCollection` and `PrimitiveCollection` have a clone method, and we weren't using it anywhere in our code, so I thought the best thing to do is remove it.  I made it a breaking change instead of deprecating it because I don't think many (if any) of our users were using this function either.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@mramato can you review please?

**Comment by mramato** [comment]
@ggetz or @likangning93 are more familiar with this code, so they should probably be the ones to review.  We should make sure there wasn't a good reason as to why this was added in the first place.

**Comment by hpinkos** [comment]
@ggetz can you review?

**Comment by hpinkos** [comment]
@ggetz The model thing is already a bug in master, the bug of creating an new clipping plane collection every frame in `ModelVisualizer` just happened to make it work for model entities.  I wrote up this issue: #6878 
I can start looking at it, but if you have any suggestions for how to fix it that would be appreciated.

I'm not sure what problem you found related to tile content, but I really don't think that's related to this PR since `clone` wasn't being used anywhere for the 3d tiles clipping stuff.  Can you check to see if that exists in master as well?

**Comment by hpinkos** [comment]
Nevermind, I had a typo.  I'll figure out what's going on with the model

**Comment by hpinkos** [comment]
Oh good, it's just a bug in the sandcastle example

**Comment by hpinkos** [comment]
@ggetz anything else?

**Comment by ggetz** [comment]
Thanks @hpinkos The model edge clipping is resolved! 

However, there's still a problem with tilesets. If I chose the BIM model and use `maximumScreenSpaceError : 2`, I can see the smoke stacks aren't getting clipped correctly, however the edges are still highlighted in the correct places. Maybe this is an issue with `discard` in the shader? Are you seeing the same?

**Comment by hpinkos** [comment]
@ggetz opened #6879

Anything else?

**Comment by ggetz** [comment]
Other than that, this looks good. Thanks @hpinkos !

**Pull request merged**
