### PR TITLE
Revert #5939

### PR DESCRIPTION
**Pull request by hpinkos**
#5939 broke the water mask

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hpinkos, thanks for the pull request! Maintainers, we have a signed CLA from @hpinkos, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
@lilleyse please review and merge.

@bagnell please open a new PR with these changes after you fix the watermask issue.

**Comment by lilleyse** [comment]
The indentation of the includes is off. Otherwise seems fine.

**Comment by lilleyse** [comment]
The issue seems so obvious in retrospect, but areas of the code like water mask expects `flipY` to happen automatically but it no longer does for `arrayBuffer` uploads. We will have to either ignore those warning or flip the buffers ourselves.

**Comment by hpinkos** [comment]
@lilleyse fixed

**Comment by hpinkos** [comment]
Thanks @lilleyse!

Just to re-iterate, we almost never want to merge a non-trivial change like this right before the release.  It's better to wait.

**Pull request merged**
