### PR TITLE
Fix RectangleGeometry texture rotation

### LINKED ISSUE #2737: Texture rotation incorrect
When rotating a rectangle the texture is zooming in and out, even when using the default cesium materials.

I've attached some sample html to quickly reproduce.

```
<div id="cesiumContainer"></div>
<div id="buttons">
    <button onclick="this.disabled=true; addBillboard();">Add Billboard</button>
</div>

<script>
    var viewer          = new Cesium.Viewer('cesiumContainer');
    var entity          = new Cesium.Entity();
    var image           = new Image(300, 300);
    var canvas          = document.createElement('canvas');

    canvas.width    = 300;
    canvas.height   = 300;

    var context         = canvas.getContext('2d');

    var rot             = 0.0;
    var doRotation      = false;

    function addBillboard() {
        image.src = 'red.png';

        //Need to wait for image to load before proceeding to draw
        image.onload = function () {
            canvas.getContext('2d').drawImage(image, 0, 0);

            entity.rectangle = new Cesium.RectangleGraphics(
                {
                    coordinates: Cesium.Rectangle.fromDegrees(-86.69777, 30.03883, -76.69777, 40.03883),
                    material: new Cesium.ImageMaterialProperty( {image: canvas} ),
//                    material: new Cesium.StripeMaterialProperty({repeat: 4}),
                    rotation: new Cesium.CallbackProperty(getRotationValue, false),
                    stRotation: new Cesium.CallbackProperty(getRotationValue, false)
                }
            );

            viewer.entities.add(entity);
            viewer.flyTo(viewer.entities)
                .then(function() {
                    setInterval(rotateRect, 50);
                });
        };
    }

    function getRotationValue() {
        return rot;
    }

    function rotateRect() {
        rot = (rot + 0.015) % Cesium.Math.TWO_PI;
    }

</script>
```

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #2737

Before the texture was being rotated using a texture rotation matrix.  This wasn't working because the `RectangleGeometry` is rotated in Cartographic space (so it remains a rectangle in 2D) and using the matrix to rotate the texture coordinates made them no longer line up with the positions.

To fix this, I compute the rotated texture coordinates based on the angle difference between the texture coordinate rotation and the rectangle rotation.

rotatingrectangle2

### CODE REVIEW

**Comment by dwhipps** [comment]
@hpinkos One thing I checked (and want to stress) is that this bug was more/most obvious when the aspect ratio of the rect was bigger (i.e more rectangular, less square.) I did that test and it looks great. Thanks!

**Comment by pjcozzi** [comment]
Amazing!

@hpinkos please update all the issues and/or forum posts about this, thanks!

**Comment by jburr-nc** [comment]
Thank you!! This was extremely helpful.  It works great when I point to master.  Will this be part of release 1.29 at the very beginning of January?

**Comment by hpinkos** [comment]
@jburr-nc yep!  This will be included in 1.29 released on January 2

**Pull request merged**
