### PR TITLE
Removed "@returned {undefined}"

### PR DESCRIPTION
**Pull request by gabriel-macario**
Issue #6265

Apologies for the previous two pull requests; I had not yet read the "Contributing" and "Code of Conduct" documents.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @gabriel-macario!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
Thanks @gabriel-macario!  Congrats on your first Cesium PR.  We received your CLA, thanks.

**Comment by hpinkos** [comment]
Thanks @gabriel-macario!  This looks great.
Can you revert the changes in `protobuf-minimal.js` though?  Since that's a third party library we don't want to make alterations to that file.

**Comment by gabriel-macario** [comment]
Hello, I believe I've undone the changes to protobuf-minimal.js

Sorry for all the extra commits, not quite used to github yet.

**Comment by hpinkos** [comment]
Great @gabriel-macario, thanks for fixing this!

**Pull request merged**
