### PR TITLE
Fix Fog minimumBrightness default value

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @fredj!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/default_val/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Thanks @fredj 

@lilleyse Just to be extra cautious, can you confirm that the doc is what's wrong here and not the value?

**Comment by fredj** [comment]
This value was updated in 8cf28a6041c115c254a65c129a074036325a2718 and 8b1ac520933d9fffce7d3ae2e9823c68a927a840

**Comment by mramato** [comment]
Good enough for me, thanks again @fredj!

**Pull request merged**
