### PR TITLE
Solve struct ellipsoid caused the model to dark

### PR DESCRIPTION
**Pull request by verybigzhouhai**
Solved the problem that struct ellipsoid caused the model to darken on Qualcomm platform.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @verybigzhouhai! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/verybigzhouhai/cesium/blob/master/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by verybigzhouhai** [comment]
@OmarShehata Hi，Now I am modifying the relevant code of the ellipsoid struct. Do you think it is acceptable? I will continue to modify other structures.

**Comment by verybigzhouhai** [comment]
Fixes #7651

**Comment by OmarShehata** [comment]
Awesome, thanks so much for putting this together @verybigzhouhai ! I'll give this a review in the next couple of days. I'd definitely be curious if this also fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/7871.

**Comment by verybigzhouhai** [comment]
ok,hope to pass the review

**Comment by pjcozzi** [comment]
Thanks again for contributing, @verybigzhouhai, we received your CLA.

**Comment by verybigzhouhai** [comment]
This is ready!

**Comment by verybigzhouhai** [comment]
Because of some setup reasons, I need to turn off this PR first, and I'll turn on the same one later.

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @verybigzhouhai! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Comment by OmarShehata** [comment]
Just let me know when it's ready @verybigzhouhai . Ignore the concierge message there, it's something I have to fix.

**Pull request closed without merging**
