### PR TITLE
Added a unit vector to the cartesian3 class

### PR DESCRIPTION
**Pull request by hanbollar**
added (1.0, 1.0, 1.0) as a constant unit vector just like UNIT_X, UNIT_Y, UNIT_Z.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hanbollar, thanks for the pull request! Maintainers, we have a signed CLA from @hanbollar, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@hanbollar what is this useful for?  Also, I wouldn't call this a unit vector.  A unit vector has a magnitude of 1

**Comment by hanbollar** [comment]
@hpinkos I personally have had a lot of times where i needed a vector of (1.0, 1.0, 1.0) either for initialization or for debugging, etc and its a fundamental vector that can be very useful. just the same way we already have IDENTITY and ZERO for matrices. i can rename it to ONE for usage purposes.

lmk what you think

**Comment by hpinkos** [comment]
Sorry, I just don't think this is super useful in a general sense.  Especially since it's frozen, if you need a vector that will be mutated later you'll have to do `var v = Cartesian3.clone(Cartesian3.ONE));` and at that point it's just easier to do `var v = new Cartesian3(1.0, 1.0, 1.0)`

**Pull request closed without merging**
