### PR TITLE
Add Rectangle.equalsEpsilon

### PR DESCRIPTION
**Pull request by hpinkos**
For API consistency.  We never added a static `Rectangle.equalsEpsilon`, we just had `Rectangle.prototype.equalsEpsilon`

Don't merge until after the release is finished

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@hpinkos, thanks for the pull request! Maintainers, we have a signed CLA from @hpinkos, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@ggetz can you review?

**Comment by hpinkos** [comment]
@ggetz fixed

**Comment by ggetz** [comment]
Thanks @hpinkos

**Pull request merged**
