### PR TITLE
Polyline Crash on Undefined Globe Fix

### PR DESCRIPTION
**Pull request by WilliamKHo**
For #5146. Ellipsoid assignment moved to `update` and check added for globe. Without the globe the polyline is drawn as a straight line segment. Hopefully this is appropriate behavior?

### CODE REVIEW

**Comment by hpinkos** [comment]
Looks good @WilliamKHo, thanks!  Can you update CHANGES.md and add a unit test?  The user who reported the issue posted a link to a sandcastle example that reproduces the crash in this post: https://groups.google.com/forum/#!msg/cesium-dev/UboMKwwn8Xk/noMUrTS7CQAJ

**Comment by WilliamKHo** [comment]
Hey please look over this?

**Comment by hpinkos** [comment]
Looks good!  You have a merge conflict though, so merge in master and we'll get this in

**Comment by WilliamKHo** [comment]
Ok should be good now!

**Comment by hpinkos** [comment]
:+1: thanks!

**Pull request merged**
