### PR TITLE
Initial work on issue#2369

### PR DESCRIPTION
**Pull request by ayk115**
#2369. This is not the entire work. This commit enables pasting (crl+v) Czml directly into the cesium inspector without the need to create a temporary file.

### CODE REVIEW

**Comment by GatorScott** [comment]
Your KML and CZML tests look good.

My reading of the GeoJSON spec, specifically section 2, suggests that you need to test for any of the possible GeoJSON object types: Feature, FeatureCollection, GeometryCollection, or any of the geometry types.

You included a check for a object type of "Topology" in the GeoJSON test.  I haven't seen the rest of your code, but is it your intention to also support TopoJSON geometries?

**Comment by ayk115** [comment]
Yes, I intended to support TopoJson also. Cesium doesn't has a separate loader for TopoJson. Its the same for GeoJson and TopoJson (GeoJsonDataSource). Therefore, I created only one validator function for GeoJson and TopoJson. If we need separate validators for GeoJson and TopoJson, I will make the required changes. 

I also added support for all object types in GeoJson.

**Comment by pjcozzi** [comment]
What's the plan with this?

**Comment by mramato** [comment]
There hasn't been any movement here and implementing this properly is probably more trouble than it's worth.

**Pull request closed without merging**
