### PR TITLE
Document options.convert param on setView and flyTo methods of Camera

### PR DESCRIPTION
**Pull request by mwijngaard**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @mwijngaard! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/mwijngaard/cesium/blob/camera-convert-param/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/camera-convert-param/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mwijngaard** [comment]
CLA sent

**Comment by OmarShehata** [comment]
Thanks a lot @mwijngaard ! I didn't even know this was an option. We'll take a look at this sometime next week.

Are you using this option to be able to easily center the camera in your 2D scene, or something like that?

**Comment by pjcozzi** [comment]
Thanks again for contributing, @mwijngaard!  We received your CLA.

**Comment by hpinkos** [comment]
Yes @mwijngaard, I believe this option was intentionally left private because we expected that it would only be used internally by some of our other functions.  Do you have a use case where you need to use this parameter?

**Comment by OmarShehata** [comment]
> I believe this option was intentionally left private because we expected that it would only be used internally by some of our other functions.

I considered this too, but then realized it still needs to be documented and labelled as `@private` so either way this must have been forgotten.

**Comment by mwijngaard** [comment]
I'm building some custom camera controls which use flyTo to orbit a certain target point. Since I'm only using columbus view, it's much easier for me to reason about the required transforms in the 2d coordinate system, than in 3d. Or do you suggest another way to achieve this? @OmarShehata I found this option precisely by looking into how flyHome was implemented in columbus view, if that's where you were headed? :-)

**Comment by hpinkos** [comment]
Fair enough.  Thanks for the contribution @mwijngaard!

**Comment by mwijngaard** [comment]
Thank you!

**Pull request merged**
