### PR TITLE
Added several texture assets, including a high-contrast skybox altern…

### PR DESCRIPTION
**Pull request by Tythos**
…ative and a higher-resolution lunar texture based off of NASA Clementine data.

High-contrast skybox is less distracting, significantly preferable under more strenuous lighting conditions on displays (projection, etc.), and mitigates issues with non-star entities (Milky Way, etc.) experiencing distortion in the rasterization process.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @Tythos! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Tythos/cesium/blob/master/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks @Tythos!  Do you know where the images came from or how they're licensed?

**Comment by Tythos** [comment]
- Lunar texture is downsampled and filtered from the Public Domain 4k texture pack at http://www.celestiamotherlode.net/catalog/show_addon_details.php?addon_id=980

- Skybox textures are filtered versions of existing skybox used within Cesium

**Comment by hpinkos** [comment]
Thanks @Tythos, were you the ones that filtered the existing skybox images?

We'll need to make and update to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md to include the lunar texture.

And before we merge this, we'll also need to you submit a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

**Comment by Tythos** [comment]
Sounds good. Is there a better branch you would suggest so the PR isn't going straight to Master once that's done?

**Comment by hpinkos** [comment]
I'm sorry @Tythos, I don't understand your question.  Why wouldn't this go into master?

**Comment by Tythos** [comment]
Master is fine with me if it's fine with you. There are, by my count, 109 branches right now and I thought, in hindsight, you might prefer a separate workflow for something like graphical assets (as in this case), as opposed to code for specific features, bug fixes, issues, etc. It wasn't super-clear to me where this would fall in the work flow outlined by https://cesium.com/blog/2013/10/08/github-pull-request-workflows/; that's all.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Tythos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@Tythos did we ever get a CLA from you?  We'll need a CLA before merging.  You can find instructions here: [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Tythos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by Tythos** [comment]
Hello, Hannah! Yes, you should have CLA on file. Let me know if it doesn't show up and I can resubmit it.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Tythos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Tythos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Tythos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
@Tythos I can confirm we have your CLA on file, thanks for making this contribution! You can definitely see a much more detailed star map with this version:

NewStartMap


<details><summary>Comparison Sandcastle code</summary>
<p>

```
var clockViewModel = new Cesium.ClockViewModel();
var options1 = {
    clockViewModel : clockViewModel
};
var options2 = {
    clockViewModel : clockViewModel
};

var view1 = new Cesium.Viewer('view3D', options1);
var view2 = new Cesium.Viewer('view2D', options2);

function skyBoxUrl(suffix) {
    return Cesium.buildModuleUrl('Assets/Textures/SkyBoxHC/tycho2t3_80_' + suffix + '.png');
}

view2.scene.skyBox = new Cesium.SkyBox({
  sources : {
    positiveX : skyBoxUrl('px'),
    negativeX : skyBoxUrl('mx'),
    positiveY : skyBoxUrl('py'),
    negativeY : skyBoxUrl('my'),
    positiveZ : skyBoxUrl('pz'),
    negativeZ : skyBoxUrl('mz')
  }
});

var worldPosition;
var distance;

function syncView() {
    var camera1 = view1.scene.camera;
    var camera2 = view2.scene.camera;

    camera2.setView({
        destination : camera1.position, 
        orientation : {
            heading : camera1.heading,
            pitch : camera1.pitch,
            roll : camera1.roll,
        }
    });
}

view1.camera.changed.addEventListener(syncView);
view1.camera.percentageChanged = 0.01;

view2.scene.screenSpaceCameraController.enableRotate = false;
view2.scene.screenSpaceCameraController.enableTranslate = false;
view2.scene.screenSpaceCameraController.enableZoom = false;
view2.scene.screenSpaceCameraController.enableTilt = false;
view2.scene.screenSpaceCameraController.enableLook = false;
```
</p>
</details>

I'm surprised that the higher resolution one is actually smaller in file-size here. If we're going to ship it with the library, should we just make it the default and replace the old one? Otherwise it'll just be one more sample folder no one knows about, and without a code example like the above you'd have to do some digging to figure out how to replace the default one.

**Comment by mramato** [comment]
I agree, I'm not sure shipping multiple start maps justifies the zip size and effort.  We also have to make sure any change is properly reflected in licensing.  File size is also super important here for loading purposes.  @emackey any thoughts here?

**Comment by emackey** [comment]
Agreed with shipping only one, not multiple.

One important caveat: "High contrast" is not an advantage for a background image.  We deliberately darkened the old starmap to reduce the contrast, to make Cesium's entities and other foreground objects stand out from the stars.  This was particularly important when the foreground objects may themselves be dots in space.

That said, the starmap that ships with Cesium is basically garbage.  It looks like a dusty monitor.  I would love to replace it with one that actually showed a bit of the Milky Way and some nebulas, but maybe darkened a bit to keep them in  the background.  Actually I've been looking at the [ESA/Gaia star map](http://sci.esa.int/gaia/60196-gaia-s-sky-in-colour-equirectangular-projection/), which has some nice Milky Way things going on, but lacks distinctive dots for the brighter stars.  I guess astronomers don't like the glow/blooming effects that fascinate 3D graphics folks.  Maybe with some post-processing, the bright stars could be superimposed?  Priorities, priorities...

**Comment by Tythos** [comment]
Inclusion or exclusion is fine with me. The file size is a good point and not something I had checked, but it does like you're earning 90% in image size (part of that is contrast, part of that is just PNG compression algorithms).

A note on HC, though: The original motivation for the alternate sky box came from conferences and other projector-in-light-room scenarios where the old sky box looked worse than a dusty monitor--it was indistinguishable from a gray matte, and made it harder to distinguish in-space objects and to appreciate the improved atmospheric shaders. This set of textures are useful for those kind of situations where you need clear points of light to shine in from the background.

As for the Clementine texture, that might be harder to justify, especially with the drastic increase in file size.

**Comment by hpinkos** [comment]
Thanks for the time you put into this @Tythos. I'm going to close this PR since it sounds like we don't want to add a second skybox to the package.  @emackey if you disagree and think we should replace our star map with this one, please reopen this PR.

**Comment by cesium-concierge** [comment]
Thanks for the awesome work @Tythos! Your contribution is about to launch to millions of users with the next release. :rocket:

Do you mind if we tweet about it? CC @OmarShehata @Slchow.

**Pull request closed without merging**
