### PR TITLE
Add camera#flying property

### PR DESCRIPTION
**Pull request by gberaudo**
This read-only property allows the flying information to be easily accessed from everywhere.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@gberaudo, thanks for the pull request! Maintainers, we have a signed CLA from @gberaudo, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by gberaudo** [comment]
I added 2 more commits to fix issues with the current_flight property not beeing updated in some cases.

**Comment by hpinkos** [comment]
Thanks for the PR @gberaudo!  Can you briefly explain why this change is helpful?

**Comment by ggetz** [comment]
There are `moveStart` and `moveEnd` events, so it's possibly, albeit a little clumsier, to check this already.

**Comment by gberaudo** [comment]
Thanks for the quick reply and advice.

I prevent the user for moving too far away from a sphere. When it is the case, I fly it back to home.
However I do not want that mechanism to triggers when the user is already flying.

You are right @ggetz, these events looks great to me. I will have a try to use them and will reopen the PR if needed.

**Comment by gberaudo** [comment]
I looked at it @ggetz. Unfortunately I can not use these events because they are too broad, including any movement of the camera, not just flying.

My mechanism triggers when the user moves too far from the sphere using mouse control, not when flying.

This PR simply fixes how Cesium tracks in progress flights, and export the value. There may be better way to do it though, and I am opened to your suggestions.

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Hi @gberaudo, thanks for opening this pull request, but I don't think this is something we want to add to our API.  As always, we're happy to look at any PRs you want to submit in the future!

**Pull request closed without merging**
