### PR TITLE
Add width and height parameters to Scene.drillPick

### PR DESCRIPTION
**Pull request by sir-chaos**
On https://github.com/AnalyticalGraphicsInc/cesium/issues/6361

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @sir-chaos!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Thanks for the pull request @sir-chaos!  When you have a moment, can you send over a CLA?  We need that in order to review and merge your changes.  Instructions are in the cesium-concierge post above.

Also, we'll probably want some unit tests before merging this.  Thanks!

**Comment by sir-chaos** [comment]
@hpinkos sure, just did it.

**Comment by pjcozzi** [comment]
Thanks again @sir-chaos, we received your CLA, sorry for the slow response.

**Comment by hpinkos** [comment]
Hi @sir-chaos, did you add unit tests?  If you did you may have forgotten to push them up, I don't see it in this pull request

**Comment by sir-chaos** [comment]
Hi @hpinkos, probably I misunderstood your last comment, so no tests added yet, but I can try and do that.

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by chris-cooper** [comment]
Hi, what is the status of this PR @sir-chaos ?

**Comment by hpinkos** [comment]
Thanks for the PR @sir-chaos!  @chris-cooper went ahead and finished up these changes in #6922.  These changes will be included in Cesium 1.49 available on September 3rd.
Hope to see more contributions from you in the future! =)

**Comment by sir-chaos** [comment]
Glad to hear that.
Unfortunately I wasn't able to provide the unit tests as was suggested, but it's good the features are now in trunk.

**Pull request closed without merging**
