### PR TITLE
More ion cleanup

### PR DESCRIPTION
**Pull request by mramato**
This is ready for a full review.

1. Rename `CesiumIon` -> `Ion`
2. Rename `CesiumIonResource` -> `IonResource`.
3. `Ion` now only has API settings, similar to `BingMapApi` and others.
4. `Ion.defaultServerUrl` -> `Ion.defaultServer` and is now a `Resource`.
5. Moved `CesiumIon.createResource` -> `IonResource.fromAssetId`
6. Removed the now unneeded `CesiumIonResource.create`
7. `IonResource` is now public.
8. `IonResource` instances are also handle external assets, which removes the monkey patching to `Resource.clone` we were previously doing.
9. Properly documented everything
10. Updated Sandcastle examples.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@mramato, thanks for the pull request! Maintainers, we have a signed CLA from @mramato, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
There's an error when I switch to the point cloud model in the `3D Tiles Clipping Planes.html` demo

**Comment by hpinkos** [comment]
Just that one comment @mramato, everything else looks great

**Comment by mramato** [comment]
I never noticed you could actually change models, I think I broke it with an earlier PR but I'll fix it here.

**Comment by hpinkos** [comment]
Great, thanks @mramato!

**Pull request merged**
