### PR TITLE
Added WebStorm Plugin to Docs

### LINKED ISSUE #3817: Source/test WebStorm plugin
It would be cool to have a simple WebStorm plugin that provides a hotkey to swap between a source file and its test, e.g., (`/Source/path/file.js <-> /Specs/path/fileSpec.js`).

Good code sprint project.

### PR DESCRIPTION
**Pull request by TomPed**
Fixes #3817.

Added WebStorm plugin documentation to the WebStorm and Testing guides.

### CODE REVIEW

**Comment by pjcozzi** [comment]
The link to download the plugin is 404: https://plugins.jetbrains.com/plugin/8388?pr=

**Comment by TomPed** [comment]
Ahh, did not push the changes yet.

**Comment by TomPed** [comment]
All set.

**Comment by pjcozzi** [comment]
Open a PR in the cesium-webstorm-plugin repo please so I can comment there.

**Comment by TomPed** [comment]
[Here](https://github.com/AnalyticalGraphicsInc/cesium-webstorm-plugin/pull/1).

**Comment by TomPed** [comment]
This is ready.

**Comment by pjcozzi** [comment]
Thansk @TomPed!

**Pull request merged**
