### PR TITLE
Fix incorrect camera computation in southern hemisphere.

### LINKED ISSUE #2434: Setting the camera's heading doesn't work in the southern hemisphere
Here's a simple Sandcastle example to show the problem:

```
var viewer = new Cesium.Viewer('cesiumContainer');
var toolbar = document.getElementById('toolbar');
var heading = document.createElement('input');
toolbar.appendChild(heading);
heading.addEventListener('focusout', function() {
    viewer.camera.heading = Number.parseFloat(heading.value);
}, false);
```

Enter 0 in the input box and tab out of it, and the camera doesn't move (north is still up, as expected).  Now pan the camera so that it's located anywhere in the southern hemisphere and do the same thing.  The globe flips upside-down so that south is up.

### PR DESCRIPTION
**Pull request by kring**
Fixes #2434.

As usual, I don't really know what I'm doing.  But I tracked the bad heading-setter in the southern hemisphere to a flipped `roll` property.  Instead of roughly zero, it would be roughly pi.  There was some logic in the `roll` getter that was flipping the roll if the z component of the camera's `right` vector was less than zero, which it ends up being in the southern hemisphere.  I can't really explain why that would be necessary, and removing it fixed my problem and caused no test failures.

### CODE REVIEW

**Comment by bagnell** [comment]
It was flipping the roll if the z component of the up vector was less than zero. That was because we use `acos` to get the angle and its range is only [-pi / 2, pi / 2]. The roll getter would then only return the right angle if it was in [0, 90] or [270, 360] degrees.

So I don't think this is the right fix. I'll think about what else can be done. Let me know if you have any ideas.

**Comment by kring** [comment]
Yeah that's not too surprising; I didn't think through the math very deeply.  If you could write a quick test showing where that flip results in the correct answer I might have a better chance at coming up with a better solution.  Is it when the roll has the camera completely upside-down?

**Comment by bagnell** [comment]
> Is it when the roll has the camera completely upside-down?

Yup. You can test it with this:
```javascript
        var roll = CesiumMath.toRadians(110.0);
        camera.setView({
            position : Cartesian3.fromDegrees(-72.0, 40.0, 20.0),
            heading : 0.0,
            pitch : 0.0,
            roll : roll
        });

        expect(camera.roll).toEqualEpsilon(roll, CesiumMath.EPSILON14);
```

**Comment by kring** [comment]
Let me see if I understand what's going on here...

The up vector in this code is expressed in the ENU frame, so when the camera is looking straight down at the Earth, the z component of the up vector should be zero.  That's if "down" means "along the ellipsoid surface normal".  But `CameraFlightPath.createTween` doesn't look down along the surface normal, it looks down toward the center of the Earth.  I'd argue that this is wrong, but maybe there's a good reason for it.  In any case, that means that `up.z` isn't going to be zero, it's going to be slightly positive in the northern hemisphere, and slightly negative in the southern hemisphere.  Or, another way to think of it is that the camera is actually upside down (relative to the ENU frame) when in the southern hemisphere!

So I can see two ways to fix this:
* change `createTween` to look down along the geodetic normal instead of the geocentric one, and probably also stick a tolerance on that `up.z < 0` because we're basically testing for exact equality to zero in a bunch of really common cases.
* change the pitch and roll computation to use a geocentric frame instead of ENU.  Probably need a tolerance here, too, because mathematically up.z will exactly equal zero all the time but numerically who knows.

Does any of this make sense?

**Comment by bagnell** [comment]
> Does any of this make sense?

Makes perfect sense. I added a tolerance to `up.z < 0`. I added a test that fails in master and both of the new tests added here pass.

I tested this by moving all over the globe with different heading/pitch/roll angles. Everything seems to work as expected. Let me know if you find something that's broken.

**Comment by bagnell** [comment]
FYI, I'm make some more improvements based on #2446 and #2451 that I'll submit soon.

**Comment by kring** [comment]
Thanks, Dan.  I'm a little worried that large-ish tolerance will come back to bite us (they usually do in my experience), but it's definitely a huge improvement over the current situation.  Any problems that do crop up will probably be in the uncommon situation where the camera is upside-down, anyway.  So I'm happy to merge when you're ready.

**Comment by bagnell** [comment]
@kring This is ready for another review.

The original problem is fixed and I also fixed a few other problems mentioned in #2446 and #2451. I added a few more tests. 4 should fail in master and they should all pass in this branch.

I pushed the changes to the `roll-test-app` branch which is the same as this but has some code in the Hello World Sandcastle example that outputs the heading/pitch/roll. It has the text input that changes the heading in degrees when it goes out of focus. The 'a' and 'd' keys increase/decrease the roll angle.

>I'm a little worried that large-ish tolerance will come back to bite us

I agree. There is still a large-ish tolerance that checks if the camera is looking straight down, but I think in that case the camera is actually upside down so it should be fine.

**Comment by kring** [comment]
Looks good, thanks Dan!

**Pull request merged**
