### PR TITLE
Cardboard demo

### PR DESCRIPTION
**Pull request by bagnell**
Partly for #3524, though I would keep that open. I like the idea to add more randomly placed hot air balloons, but it would required model instancing.

### CODE REVIEW

**Comment by emackey** [comment]
One suggestion I have is to enable the full DPI rendering, which is hard on mobile but is so badly needed for a device like Cardboard.  I think you can use the workaround code from the 1.18 CHANGES.md.

**Comment by mramato** [comment]
> One suggestion I have is to enable the full DPI rendering, which is hard on mobile but is so badly needed for a device like Cardboard. I think you can use the workaround code from the 1.18 CHANGES.md.

@bagnell and I had a conversation about that this morning.  I'm in disagreement.  At full resolution, Cesium runs at about 15fps on most phones (that I've tried) and terrain takes forever to load (because of the number of tiles).  A high frame rate and minimal terrain pop-in is much more important than the total resolution.  I believe low frame rate is the number one cause of nausea in VR.

**Comment by emackey** [comment]
Good points.  I didn't get a chance to try high-dpi mode yet, but I've also heard of the perils of low frame rate VR.

**Comment by emackey** [comment]
I wonder if the frame rate is OK if you tell the terrain system to have high pixel error at high DPI?

**Comment by mramato** [comment]
It's worth a try, but I believe that mobile gpus are fill-rate limited so fps on a mostly blank globe is mostly a matter of resolution.

**Comment by pjcozzi** [comment]
> I like the idea to add more randomly placed hot air balloons, but it would required model instancing

We could do something simple without instancing...just do half a dozen or a dozen balloons (the models are not that heavy and the WebGL resources are cached, instancing will just save on draw commands).

**Comment by bagnell** [comment]
I added multiple balloons floating around with the viewer. Is there anything else that needs to be done here?

**Comment by pjcozzi** [comment]
Add the balloon to the Models Sandcastle examples (entity and primitive)

**Comment by pjcozzi** [comment]
Update CHANGES.md.  Mention both the new Sandcastle example and new model.

**Comment by pjcozzi** [comment]
Looks great!

@tfili this could be one of the demos for the Khronos table at SIGGRAPH.

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look.

**Comment by bellengj** [comment]
Will this demo work on Oculus and Vive?

**Pull request merged**
