### PR TITLE
Fix artifacts in BIM demo

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/AnalyticalGraphicsInc/cesium/issues/5722

Updates the tileset used in the BIM demo. [Live Demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xVdbb9s2FP4rXF4irw59j+M6CZaLtxpwEKN2WwxNMTASbRGhSYGknLlF/vsOKUqWHLvdsAHzCy2e23cuPIdsNNBUPlOFppwIgyKq2VKglYwoR4mSaxbRCD1u0DUVhtMNmm20oSv9INZEoTWjVvQCCfqMbkA0XeGPbi84Dt3njRSGMEHVcW2YyeiQCgoimSx2n55kGKeaGiC6XZwotmKGranGJIqCB4HgVzKVLZ3beSYXfMs47C9V/G3ONpbiPdUyVSHFCyVXVxqYx1Fw1jvt1jKRF1gtQI8AK0qizRR4mabYxFQEi1SEhkkReJYa8ta8H1+lXM1lTq2XYb4DZUwsp8yE8XsiljRo4l4dnTRxu577jB9lKizXLImpoliBSKrRz6iLmzWL7KWGJQBRz4BoC4YqJVUBJZRCS04xl0tPcYIlv0LJpbrmVER3kGEI9J5I3lR48PvRdHJ1M/IpSlj4BChBckG4tombERGFRENx2CTN5XLJ6XVqDKA7nlJ1sqDEpIoiTTl1oI/rmSwsuRthTMMnGhWObK14Su6HKyCniEa/ZophN9fjSZ4QeMvbTIEwMKygki3+jIqX1ECiE6rMJjj2ZFesVgRiNsq2XFQCT68XcbO7+PfRZHL/aStTwbc1ZZ0ogU3F/wT307vxfJSLsAXKLaOLi4td9AWa/Z5BzdIFHO/Ia3txLlrkMZQF3+0Ns1BRKmYJCeloDcDeZUxBdtxDApLaAvPC2J5TkaTmKiuTol5Wcu0cK9BZL37yVVOBrCggFVt0eWALl/NWA7KFWgy1P5WaWVvlOHkvvMvBbqgqhnezu8tchVTOAhPaEBFSudh3Og/nZbeOSimpH0rAfJNQfHf/YTb64+7+oyuKRgONBTIx00U/pmuqNkXIYqIREejhyFfXw5EdFK4i0XPMwhiBKEFLLh8JR+Nb7HTOrcKCD/6nGgaLkYhoLUNGDM0NgHCopNYoYosF9EIofwcEjEZocn+rM4WfpHoiynZNiDUwoM4tcoPAAYRWadthSBODIJAezCMxFl6k36LYmES/bTSWzMTpIzTGVeNKEL4xLCT8N0US8ESPRdjoRCfOfINpncLSPu1lFe7dvyMJVNG3lyECUNcp4xE4v4JNMOtZtPUz9w7788GiiIpRznCBPrda7WazVUetVqd11oS1A/9Os+/Tfh31W53mAD6bg9Ne2263Wv2zjNzzbH0r1u6edd13t9k/zdS0254+cPudds+r73r1fu11SnzWjtcz6PkV6J1B24rDYkFZ7q7T2mn2HXhwwnMNvPJm9tl3izc5OMt0dJpeppsxdb6U+/my6GevumN2sFFClKbjLf1Af7Tu1Hb678Fm6YZkpQ3nuZtLxwrZ2ib/s//7Zbjlh+G5NPG2a+eCOCN4zgVoCiw7A87mEJZzLzlEb96wyhGv9qwdtZ9Zbtyp9ZEIPdRK7w+5FDRwpHqVs1Zp4aUpxSWJDs2oQzNsuG+E7cnm8HWMfxhcBjPnz1IQsNu4X+wqtT01471EJ61KNAtRnXAW0owNauRADL4Xgf/cRTfKdiZNLljb64VtHuUC2KO7FK7q4CkikaQ63hfBap8qYu0V1w7GFutYPpeuiXvCCtMAHgnaPhFAlQ+whuJ033AOCeePJHzaexQn+RHz7LhK+M4R22H8wVHL1UNm8xJgtVKwc5D7xu5rX0sTXLu3wgEvvVWwb5mw/6wcAnhT+cjpEszK/uGrS4Wt9sr9on9V+Krd6592MHev35/xihVoZqWglIz5in2B+ta0rPlv11ElNfmTyK4TOOD29eLuRBMGL1wAVH3ybd8mBzNZahOvHl52/eBa6b+3U2nJhaWj+tG5NhtOLzP5X9gqkcrYl3CAcQMe7QmHW5ZuPKbwooKnoHZX7fNGLnQesTXcjS4ejnae7nDBCzlc04CySDmfsa/04ejyvAH8FTGLCu7f93Bb5GRjWeLW5STbxBifN+DztZSRErKjShr/Ag).

* No more line flicker artifacts
* Tried to remove as much z-fighting as possible
    * Ideally this would be fixed in the tileset rather than patched in the example.
* Updated glTFs so that the REPLACE blend mode works.
* Upgraded to glTF 2

Also adds hover-over picking to the demo. Because we don't have [global batch ids](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/265) there is a bit of boilerplate in there to get it to work.

I wanted to add silhouetting but I felt like there were too many artifacts. [Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=xVjrc9o4EP9XdPkSuFJhXknIo3NpQhMyENJAkj7S6QhbYCW25FoyKXTyv9/Klo1NoO3N3cz5i5D29dvValeiWkVX4omG6MojXCGHSjblyBcO9VAQihlzqIPGc/SWcuXRORrOpaK+vOczEqIZo1r0CHH6hE5ANPLxbbxW2rbj6YngijBOw+3yQSIjbcopiCSyOJ4CKSEq5lFJFZDjdRyEzGeKzajExHFK9xzBlzOWDI3TUSJX+pFw6C8Kvf2UrSv4NZUiCm2KJ6HwjyUwd53SXrPdrKCckP6IDdDlSDxSvo+26fzCHZ/ZbMAuujeLbu2SdWWXX7fsk+5O9zH4cHty0cbA9M05e9RMD4OR618urh/6rOZ9Gl2w3uj9YnDaVYO7S3Y5rz32z95/v1z0nz7e9b9f+n3WO7kIPoGywfCJ2fXLmX12u+g+BOOu/25ha2O+89D1LBg91wG+/ujG6p/2a/3T4/rg3MJ7N9dnjW+XZ4uP1yKa3J4rOrV9QsZf3+8+qJbryIi0rQv6xD+I7aWjz+Xktx7LcfhN6HFIiTO/giAxSbFyKS9NIm4rJnjJsJTTiJktXAjhj0RKreT35xyUMT69Ysp2rwmf0pKFWxX02sL1SrrZeCwirrmGgUtDikMQiST6EzWxVdbYnstYAJDwCRAtwdAwFGEGxRZcCo9iT0wNJRYseGYLT4RvPcqdPqQ35NiaJDop8ODrzlXv+KST5adknisiqlRO/EpIBfHSSTNUZEp7bByScI5tiKSiHWdKT6miMeiYXtKolopwxNlEhL5M8OVg6Sn+2On1BncbJADnVLkgYmGrVuSR1AObcHaP0OcvmpScpxWsybH6LUeGme7Ei89LY1/K5WWEjN13IBOFyclO98wQDak0ScZlOoE4MPhQaQC1oeIp1aACGqp5aduQ42KiRWBbO8lSHK2SoVfWxXApU0C4NKUzpgA34v8T4Lvz7qiTirAJSi2jo6OjVfzlfP166RscLTqBAuwYbc/GSY3dJdzxVuv3ELab8mFAbNqZAbTzhKmUJJBNQFJqaEYY60rKg0gdJ8cyO5++mMWuFaKV+ZHWd2Y/ZpwYTh3kINPiSUKl7htoxpPSagQKIVjdtFXmZRxehpdxqQi3qZisqw2bA76aILlYVzbFdTQPKO4Pboadr/3BbSdxuFpFXY6Uy2TWCumMhvMscC6RiHB0v2US535Ld+k42dCTy2wXgShBU0+MiYe6pzjWOdIKMz74HUmoDEogIqWwGZzu1AAI26GQEjlsMoFqDJkdAwGjDuoNTmWi8E6EjyTUdRviDQyocYriHhwDhGKtC7JNA4UglAbMmCgNz5H7yFUqkPvV6pQpNxpD4fOrx5x4c8Vs4p2FJABPoMva1YbzOjZfZVJGMNR3WknqGvf7JIBc+vF8gADU24h5DjjvwyKYNSxS+5l6h03iM8ehvJMyQIms1eqWVaugWq1R27NgbMCvnWS+s1tBu7WG1Yap1d5p1fVyrba7l5Bbhm1Xi9Wbe8143rR2dxI19bqht+P1Rr1l1DeNejO2Gjk+bcfoabfMCPRGu67FYdCgNHcz1tqwdmPw4IThahvlVjLdjQdjsr2X6GhYRqaZMDW+FMv1NCtWL0pfSGHKUUBCSbtL+obipx0qvyivG2th3AjX1Q24lZ2YJrlMgM/m55eDJX/WGFcETcc0nNBEUUmzM91CD2A4NJIH6NUrVjjoxeq1ovYzS43Hak0s1vZz2xOclmJSpciZqxpxZVnby1cMr2lZniDOpoa1qaEdrOtna3b/4OWO/HIrGDSg7znkOF4YTFaV6jqc8L5Br2uF2GeiMvCYTRM2yKnySk/LovCzGPznTmrgf6x0qFSwvNaP9E6Wrq/RnQtYMS2yWASRdPOYl2CK1S2Lt1Fd3hhfLF3xpA0TT9JNoQ2SC6J+14EyE2QJCR3P4ewSzxsT+3Ht8e2lx9Kw4yLhJ8dyhfEXxzNVD7ubpgEr5wKeglzXsNd5m+v+Mn7nbPDT2AUEmgmbaeEwwFPYxE7mgBbWDzZefAps5RcByKpega9Y8/5p3dPfhj0vWIESmAtKzpjJ22fIcknzmn87k1Y2J33O6bEHB10/YeIbVY9JkISrauHBmnmzeS9z5WLNs1GPN3FZ/feWCuU5s7VV2TqUau7RN4n8X8wPRKj0XxgljKuK+oEHdzRZHUf2o37IyvgGflhNhQ4dNoOb1dH91sq/LnA9tD245AFlEnnekC3o/dabwyrwF8Q0KniBD+Cu6ZG5ZnFrb3rJIsb4sArTl1JKCNihMKfxbw)

To do:
* [x] Don't use tileset out of my personal ion account
* [x] Update other demos to use the new asset

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/update-bim-demo/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by pjcozzi** [comment]
> Also adds hover-over picking to the demo

Please make this a check box that defaults to `false`; it is too distracting for initial navigation.

**Comment by pjcozzi** [comment]
>Tried to remove as much z-fighting as possible
> Ideally this would be fixed in the tileset rather than patched in the example.

Where is the code doing the patching?  I don't see it at glance.

**Comment by pjcozzi** [comment]
> I wanted to add silhouetting but I felt like there were too many artifacts. Example

Not too bad but just depends on the view; agree to stay with just highlight for now.

**Comment by pjcozzi** [comment]
> Also adds hover-over picking to the demo. Because we don't have global batch ids there is a bit of boilerplate in there to get it to work.

Not ideal but OK for now.

**Comment by pjcozzi** [comment]
Update CHANGES.md mainly to just build awareness of BIM in Cesium and per-feature selection.

**Comment by pjcozzi** [comment]
Thanks for upgrading this, bump when ready.

**Comment by lilleyse** [comment]
> Where is the code doing the patching? I don't see it at glance.

[Here](https://github.com/AnalyticalGraphicsInc/cesium/pull/7181/files#diff-f3294321d31947d9808cc747c0686f11R92) and [here](https://github.com/AnalyticalGraphicsInc/cesium/pull/7181/files#diff-f3294321d31947d9808cc747c0686f11R126)

**Comment by lilleyse** [comment]
@pjcozzi Ready

**Comment by pjcozzi** [comment]
> Here and here

ah, lol

**Comment by pjcozzi** [comment]
@lilleyse please submit a separate cleanup issue for this model so we can remove the workarounds.  The workarounds are fine for demoing BIM / interiors, but not a useful code example.

**Comment by pjcozzi** [comment]
Should we move the near plane up?

image

**Comment by pjcozzi** [comment]
Minor, but show unchecking remove the highlight?  Perhaps a good idea if it is only a line or code or two

image

**Comment by lilleyse** [comment]
> Should we move the near plane up?

I believe that is a log-depth problem rather than the near plane being too far - https://github.com/AnalyticalGraphicsInc/cesium/issues/6573#issuecomment-433163104

**Comment by lilleyse** [comment]
@pjcozzi Updated. Opened https://github.com/AnalyticalGraphicsInc/cesium/issues/7191 to address the z-fighting.

**Comment by pjcozzi** [comment]
Thanks!!!

**Pull request merged**
