### PR TITLE
Fix czml follow surface

### PR DESCRIPTION
**Pull request by hpinkos**
From https://github.com/AnalyticalGraphicsInc/cesium/pull/7582#issuecomment-468415808

@shunter thank you so much for catching this before the release tomorrow.  Does this fix look right?

I also added specs.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-czml/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Wait, just saw your message about `followSurface` being time varying.  I'll rework this in a second.

**Comment by shunter** [comment]
I'm mostly finished making the fixes as well.  Up to you if you want to continue or use my changes.

**Comment by hpinkos** [comment]
@shunter if you have a fix ready, go ahead and submit a pull request.  Thanks =)

**Pull request closed without merging**
