### PR TITLE
Convert Kml log()s to oneTimeWarning

### PR DESCRIPTION
**Pull request by denverpierce**
This changes all the console.log()s in `KmlDataSource` to `oneTimeWarning` in order to reduce console clutter when loading warning-provoking KML files.

### CODE REVIEW

**Comment by hpinkos** [comment]
Great idea @denverpierce, thanks!
Can you update the specs?  Some of them are failing because they expect console.log to be called.

**Comment by denverpierce** [comment]
Yes, I'll adjust things.

**Comment by denverpierce** [comment]
This is ready for another look.

I changed the `oneTimeWarning()` for `processUnsupportedFeature` from `localName` to `nodeName`.  This makes it so that `<gx:Tour>` and `<Tour>` trigger the unsupported call separately.

**Comment by hpinkos** [comment]
Thanks @denverpierce! This looks good.  I just pushed a change to fix some of the formatting.

**Pull request merged**
