### PR TITLE
Fix for reading certain CRN textures

### PR DESCRIPTION
**Pull request by lilleyse**
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/0Io8gRRHIgs

In some cases `dxtData` will exceed `length` which throws an exception with `set`. This creates a view of the exact size needed before the `set` call.

### CODE REVIEW

**Comment by bagnell** [comment]
`dxtData` will exceed `length` when there are mimaps. Perhaps add a comment?

Update CHANGES.md.

**Comment by lilleyse** [comment]
Updated

**Comment by bagnell** [comment]
Also, can you add a test?

**Comment by bagnell** [comment]
Like we discussed offline, loading KTX has the same problem.

**Comment by lilleyse** [comment]
Updated.

For KTX I just replaced `.slice` with `new Uint8Array`. Is the deep copy in `transcodeCRNToDXT` there because it's in a web worker?

**Comment by bagnell** [comment]
> Is the deep copy in `transcodeCRNToDXT` there because it's in a web worker?

Yes. We need to transfer the buffer back to the main thread; otherwise, we would need to transfer the whole buffer used by the transcoder.

**Pull request merged**
