### PR TITLE
Fixed labels don't show for individual entities in datasources when c…

### PR DESCRIPTION
**Pull request by emstrabala**
…lustering is enabled #6087

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emstrabala!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for the pull request @emstrabala!  We'll try to look at this in the next week or so.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emstrabala! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emstrabala! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emstrabala! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emstrabala! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@OmarShehata please review

**Comment by hpinkos** [comment]
Nevermind @OmarShehata, I got this one

**Comment by hpinkos** [comment]
Thank you so much for the PR @emstrabala!  I'm sorry it took so long for us to review this, but this fix looks good to me!  I was worried this one was going to be much more complicated to fix.  I'm glad you found this solution =)

**Pull request merged**
