### PR TITLE
Merge master to 3d-tiles

### PR DESCRIPTION
**Pull request by bagnell**
- [x] Test instanced models
- [x] Test point clouds

### CODE REVIEW

**Comment by bagnell** [comment]
This may also affect the GC. See [here](https://github.com/AnalyticalGraphicsInc/cesium/commit/f7607de69008ebd3314f738d5f4e9704b3f4f4e1#diff-48617a8be782e09aa150c0f8b277d27dL347) and [here](https://github.com/AnalyticalGraphicsInc/cesium/commit/f7607de69008ebd3314f738d5f4e9704b3f4f4e1#diff-c9a487b91ae648635e2f8cd14391b12cL786)

**Comment by pjcozzi** [comment]
> This may also affect the GC. See here and here

Ah!  Good catch!

**Comment by pjcozzi** [comment]
As part of this pull request, could you alsou pdate the Sandcastle example to avoid this warning: https://github.com/AnalyticalGraphicsInc/cesium/blob/595bb4e9f426e85c0bd682f24f323b3877af9050/Source/Scene/Camera.js#L1047

**Comment by pjcozzi** [comment]
@bagnell what commits need review here?  Just f7607de69008ebd3314f738d5f4e9704b3f4f4e1.

**Comment by lilleyse** [comment]
I don't think that code in `ModelInstanceCollection` will affect GC. I use an `ignoreCommands` variable so `Model` commands are never added to the command list. We don't need `emptyCommandList` after all. Model can get the `frameState` as is.

**Comment by bagnell** [comment]
@pjcozzi I finished testing and this is ready for review.

>what commits need review here? Just f7607de.

Yes.

**Comment by pjcozzi** [comment]
@bagnell can you merge in master so I can test and merge this?

**Comment by bagnell** [comment]
@pjcozzi I merged both master ad 3d-tiles. It is ready for review.

**Comment by pjcozzi** [comment]
Thanks!

**Pull request merged**
