### PR TITLE
Don't require individual source classes in sandcastle app

### PR DESCRIPTION
**Pull request by hpinkos**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/no-source-in-sandcastle/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@OmarShehata please review

**Comment by OmarShehata** [comment]
It would have been helpful to link to https://github.com/AnalyticalGraphicsInc/cesium/issues/7523 for context in the PR description.

While I think the way Sandcastle is structured now is still incredibly confusing (the built version relies on the `require`'d Cesium failing to load, and loading it from `window.Cesium`, which comes from somewhere else?) this looks like an improvement if the built Sandcastle doesn't break when it can't access `Source/`.

**Comment by hpinkos** [comment]
Oh, i didn't realize we had that issue written up.  thanks @OmarShehata

**Comment by mramato** [comment]
@OmarShehata if you ever really wanted an awesome side project, rewriting Sandcastle is probably number 2 on the list of longstanding giant undertakings (ES6 is number 1).

I'm actually a little concerned about how easily we'll be able to update Sandcastle for ES6 Cesium, so the issues are slightly related.  Might be a good discussion to have at our code sprint, even if we can't take on the challenge this time around, preparing a roadmap issue with a full breakdown of doing it would be a big help.

**Pull request merged**
