### PR TITLE
add depthTestAgainstTerrain

### PR DESCRIPTION
**Pull request by PrasannaNatarajan**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for the fix, @PrasannaNatarajan!  Can you please send in a [CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can review this?

Fixes #4945.

**Comment by pjcozzi** [comment]
@rahwang do you want to review this?

**Comment by rahwang** [comment]
This looks good to me! Thanks, @PrasannaNatarajan !

**Comment by pjcozzi** [comment]
Thanks @PrasannaNatarajan @rahwang!

@PrasannaNatarajan I'll also add you to [CONTRIBUTORS.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTORS.md).

**Pull request merged**
