### PR TITLE
Fix string->number conversion in 3D Tiles inspector

### PR DESCRIPTION
**Pull request by lilleyse**
Values were being sent as strings rather than numbers, causing the sliders not to work.

@hpinkos could you look at this? I'm not sure if this is the correct thing to do.

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @lilleyse!  This looks like the right thing to do

**Comment by mramato** [comment]
Shouldn't this use `Number(value)` instead of `parsefloat`?  Number makes sure the number is really a number, `parseFloat` ignores invalid data (for example "123qwe" will return 123 with parseFloat).

**Comment by hpinkos** [comment]
@mramato Yeah, you're right.  I didn't think it would make a difference because it will always be a number value coming from the slider.  I forgot that you can add invalid characters into the input textbox though.

@lilleyse make sure to add an `isNaN` check after casting the value to a number.  I'm sure we only want to apply it to the tileset if it's a valid number.

**Comment by lilleyse** [comment]
Updated.

Is there a way to tell the slider to always return a number? That would also fix this.

**Comment by mramato** [comment]
There is not, but even if there was you need to handle the case where a user enters a value manually in the text box above the slider.

**Comment by mramato** [comment]
Thanks @lilleyse.

**Pull request merged**
