### PR TITLE
Fixed process terrain data's bug.

### PR DESCRIPTION
**Pull request by icgp**
Some terrain data have addition data, must limit subtile's count.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @icgp!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by tfili** [comment]
@icgp Thanks for the PR.

Do you know what this additional data is? Do we want to use it?

Also, can you write a test for this? We have a sample tile here `Specs/Data/GoogleEarthEnterprise/gee.terrain`. If the data is useless, at a minimum you can probably just add some junk data to this tile for the test. If you have a sample tile that we have the right to use, you can use that as well.

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
Hi @icgp, thanks for the pull request.  I'm going to close this for now because we don't have enough information to review it.  If you are interested in working on it in the future, feel free to re-open it.  Thanks again!

**Pull request closed without merging**
